// ReSharper disable All

namespace Rdatasets.mosaicData
{
    using System.Collections.Generic;

    /// <summary>
    /// Countries
    /// </summary>

    public class Countries
    {
        public readonly int κ;
        public readonly string maptools;
        public readonly string maps;
        public readonly string gapminder;

        public Countries(int κ, string maptools, string maps, string gapminder)
        {
            this.κ = κ;
            this.maptools = maptools;
            this.maps = maps;
            this.gapminder = gapminder;
        }

        public static IEnumerable<Countries> Data
        {
            get
            {
                yield return new Countries(1, "Afghanistan", "Afghanistan", "Afghanistan");
                yield return new Countries(2, "Åland Islands", null, null);
                yield return new Countries(3, "Albania", "Albania", "Albania");
                yield return new Countries(4, "Algeria", "Algeria", "Algeria");
                yield return new Countries(5, "American Samoa", "American Samoa", "Samoa");
                yield return new Countries(6, null, "Andaman Islands", null);
                yield return new Countries(7, "Andorra", "Andorra", "Andorra");
                yield return new Countries(8, "Angola", "Angola", "Angola");
                yield return new Countries(9, "Anguilla", "Anguilla", null);
                yield return new Countries(10, "Antarctica", "Antarctica", null);
                yield return new Countries(11, "Antigua and Barbuda", "Antigua", "Antigua and Barbuda");
                yield return new Countries(12, null, "Aral Sea", null);
                yield return new Countries(13, "Argentina", "Argentina", "Argentina");
                yield return new Countries(14, "Armenia", null, "Armenia");
                yield return new Countries(15, "Aruba", "Aruba", null);
                yield return new Countries(16, "Australia", "Australia", "Australia");
                yield return new Countries(17, "Austria", "Austria", "Austria");
                yield return new Countries(18, "Azerbaijan", null, "Azerbaijan");
                yield return new Countries(19, null, "Azores", null);
                yield return new Countries(20, "Bahamas", "Bahamas", "Bahamas");
                yield return new Countries(21, "Bahrain", "Bahrain", "Bahrain");
                yield return new Countries(22, "Bangladesh", "Bangladesh", "Bangladesh");
                yield return new Countries(23, "Barbados", "Barbados", "Barbados");
                yield return new Countries(24, "Antigua and Barbuda", "Barbuda", "Antigua and Barbuda");
                yield return new Countries(25, "Belarus", " ", "Belarus");
                yield return new Countries(26, "Belgium", "Belgium", "Belgium");
                yield return new Countries(27, "Belize", "Belize", "Belize");
                yield return new Countries(28, "Benin", "Benin", "Benin");
                yield return new Countries(29, "Bhutan", "Bhutan", "Bhutan");
                yield return new Countries(30, null, "Black Sea", null);
                yield return new Countries(31, "Bolivia", "Bolivia", "Bolivia");
                yield return new Countries(32, null, "Bonaire", null);
                yield return new Countries(33, "Bosnia and Herzegovina", "Yugoslavia", "Bosnia and Herzegovina");
                yield return new Countries(34, "Botswana", "Botswana", "Botswana");
                yield return new Countries(35, "Bouvet Island", null, null);
                yield return new Countries(36, "Brazil", "Brazil", "Brazil");
                yield return new Countries(37, "British Indian Ocean Territory", null, null);
                yield return new Countries(38, "Brunei Darussalam", "Brunei", "Brunei");
                yield return new Countries(39, "Bulgaria", "Bulgaria", "Bulgaria");
                yield return new Countries(40, "Burkina Faso", "Burkina Faso", "Burkina Faso");
                yield return new Countries(41, "Bermuda", null, null);
                yield return new Countries(42, "Burundi", "Burundi", "Burundi");
                yield return new Countries(43, "United States", "California", "United States");
                yield return new Countries(44, "Cambodia", "Cambodia", "Cambodia");
                yield return new Countries(45, "Cameroon", "Cameroon", "Cameroon");
                yield return new Countries(46, "Canada", "Canada", "Canada");
                yield return new Countries(47, null, "Canary Islands", null);
                yield return new Countries(48, "Cape Verde", "Cape Verde", "Cape Verde");
                yield return new Countries(49, null, "Caspian Sea", null);
                yield return new Countries(50, "Cayman Islands", "Cayman Islands", null);
                yield return new Countries(51, "Central African Republic", "Central African Republic", "Central African Republic");
                yield return new Countries(52, "Chad", "Chad", "Chad");
                yield return new Countries(53, null, "Chagos Archipelago", null);
                yield return new Countries(54, "Chile", "Chile", "Chile");
                yield return new Countries(55, "China", "China", "China");
                yield return new Countries(56, "Christmas Island", null, null);
                yield return new Countries(57, "Cocos (Keeling) Islands", null, null);
                yield return new Countries(58, "Colombia", "Colombia", "Colombia");
                yield return new Countries(59, "Comoros", "Comoros", "Comoros");
                yield return new Countries(60, "Congo", "Congo", "Congo [Republic]");
                yield return new Countries(61, "Democratic Republic of the Congo", "Zaire", "Congo [DRC]");
                yield return new Countries(62, "Cook Islands", "Cook Islands", "Cook Islands");
                yield return new Countries(63, "Costa Rica", "Costa Rica", "Costa Rica");
                yield return new Countries(64, "Croatia", "Yugoslavia", "Croatia");
                yield return new Countries(65, "Cuba", "Cuba", "Cuba");
                yield return new Countries(66, null, "Curacao", null);
                yield return new Countries(67, "Cyprus", "Cyprus", "Cyprus");
                yield return new Countries(68, "Czech Republic", "Czechoslovakia", "Czech Republic");
                yield return new Countries(69, "Denmark", "Denmark", "Denmark");
                yield return new Countries(70, "Djibouti", "Djibouti", "Djibouti");
                yield return new Countries(71, "Dominica", "Dominica", "Dominica");
                yield return new Countries(72, "Dominican Republic", "Dominican Republic", "Dominican Republic");
                yield return new Countries(73, "Ecuador", "Ecuador", "Ecuador");
                yield return new Countries(74, "Egypt", "Egypt", "Egypt");
                yield return new Countries(75, "El Salvador", "El Salvador", "El Salvador");
                yield return new Countries(76, "Eritrea", null, "Eritrea");
                yield return new Countries(77, "Equatorial Guinea", "Equatorial Guinea", "Equatorial Guinea");
                yield return new Countries(78, "Estonia", null, "Estonia");
                yield return new Countries(79, "Ethiopia", "Ethiopia", "Ethiopia");
                yield return new Countries(80, "Falkland Islands (Malvinas)", "Falkland Islands", null);
                yield return new Countries(81, "Faroe Islands", null, null);
                yield return new Countries(82, "Fiji", "Fiji", "Fiji");
                yield return new Countries(83, "Finland", "Finland", "Finland");
                yield return new Countries(84, "France", "France", "France");
                yield return new Countries(85, "French Guiana", "French Guiana", null);
                yield return new Countries(86, "French Polynesia", "French Polynesia", null);
                yield return new Countries(87, "French Southern and Antarctic Lands", null, null);
                yield return new Countries(88, "Gabon", "Gabon", "Gabon");
                yield return new Countries(89, "Gambia", "Gambia", "Gambia");
                yield return new Countries(90, null, "Gaza Strip", null);
                yield return new Countries(91, "Georgia", null, "Georgia");
                yield return new Countries(92, "South Georgia South Sandwich Islands", null, null);
                yield return new Countries(93, "Germany", "Germany", "Germany");
                yield return new Countries(94, "Ghana", "Ghana", "Ghana");
                yield return new Countries(95, "Gibraltar", null, null);
                yield return new Countries(96, null, "Great Bitter Lake", null);
                yield return new Countries(97, null, "Great Lakes", null);
                yield return new Countries(98, "Greece", "Greece", "Greece");
                yield return new Countries(99, "Greenland", "Greenland", null);
                yield return new Countries(100, "Grenada", "Grenada", "Grenada");
                yield return new Countries(101, "Guadeloupe", "Guadeloupe", null);
                yield return new Countries(102, "Guam", null, null);
                yield return new Countries(103, "Guatemala", "Guatemala", "Guatemala");
                yield return new Countries(104, "Guinea", "Guinea", "Guinea");
                yield return new Countries(105, "Guinea-Bissau", "Guinea-Bissau", "Guinea-Bissau");
                yield return new Countries(106, "Guyana", "Guyana", "Guyana");
                yield return new Countries(107, "Haiti", "Haiti", "Haiti");
                yield return new Countries(108, "United States", "Hawaii", "United States");
                yield return new Countries(109, "Heard Island and McDonald Islands", null, null);
                yield return new Countries(110, "Honduras", "Honduras", "Honduras");
                yield return new Countries(111, "Holy See (Vatican City)", null, null);
                yield return new Countries(112, "Hong Kong", null, null);
                yield return new Countries(113, "Hungary", "Hungary", "Hungary");
                yield return new Countries(114, "Iceland", "Iceland", "Iceland");
                yield return new Countries(115, "India", "India", "India");
                yield return new Countries(116, "Indonesia", "Indonesia", "Indonesia");
                yield return new Countries(117, "Iran (Islamic Republic of)", "Iran", "Iran");
                yield return new Countries(118, "Iraq", "Iraq", "Iraq");
                yield return new Countries(119, "Ireland", "Ireland", "Ireland");
                yield return new Countries(120, null, "Irian Jaya", null);
                yield return new Countries(121, "Isle of Man", "Isle of Man", null);
                yield return new Countries(122, null, "Isle of Wight", null);
                yield return new Countries(123, "Israel", "Israel", "Israel");
                yield return new Countries(124, "Italy", "Italy", "Italy");
                yield return new Countries(125, "Cote d'Ivoire", "Ivory Coast", "Côte d'Ivoire");
                yield return new Countries(126, "Jamaica", "Jamaica", "Jamaica");
                yield return new Countries(127, "Japan", "Japan", "Japan");
                yield return new Countries(128, "Jordan", "Jordan", "Jordan");
                yield return new Countries(129, "Kazakhstan", null, "Kazakhstan");
                yield return new Countries(130, "Kenya", "Kenya", "Kenya");
                yield return new Countries(131, "Kiribati", "Kiribati", "Kiribati");
                yield return new Countries(132, "Kyrgyzstan", null, "Kyrgyzstan");
                yield return new Countries(133, "Kuwait", "Kuwait", "Kuwait");
                yield return new Countries(134, null, "Lacul Greaca", null);
                yield return new Countries(135, null, "Lake Albert", null);
                yield return new Countries(136, null, "Lake Fjerritslev", null);
                yield return new Countries(137, null, "Lake Kariba", null);
                yield return new Countries(138, null, "Lake Malawi", null);
                yield return new Countries(139, null, "Lake Pasvikelv", null);
                yield return new Countries(140, null, "Lake Tanganyika", null);
                yield return new Countries(141, null, "Lake Titicaca", null);
                yield return new Countries(142, null, "Lake Victoria", null);
                yield return new Countries(143, "Lao People's Democratic Republic", "Laos", "Laos");
                yield return new Countries(144, "Latvia", null, "Latvia");
                yield return new Countries(145, "Lebanon", "Lebanon", "Lebanon");
                yield return new Countries(146, "Lesotho", "Lesotho", "Lesotho");
                yield return new Countries(147, "Libyan Arab Jamahiriya", "Liberia", "Liberia");
                yield return new Countries(148, "Libya", "Libya", "Libya");
                yield return new Countries(149, "Liechtenstein", "Liechtenstein", null);
                yield return new Countries(150, "Lithuania", null, "Lithuania");
                yield return new Countries(151, "Luxembourg", "Luxembourg", "Luxembourg");
                yield return new Countries(152, "The former Yugoslav Republic of Macedonia", "Yogoslavia", "Macedonia [FYROM]");
                yield return new Countries(153, "Macau", null, null);
                yield return new Countries(154, "Madagascar", "Madagascar", "Madagascar");
                yield return new Countries(155, null, "Madeira Islands", null);
                yield return new Countries(156, "Malawi", "Malawi", "Malawi");
                yield return new Countries(157, "Malaysia", "Malaysia", "Malaysia");
                yield return new Countries(158, "Maldives", "Maldives", null);
                yield return new Countries(159, "Republic of Moldova", null, "Moldova");
                yield return new Countries(160, "Mali", "Mali", "Mali");
                yield return new Countries(161, "Malta", "Malta", "Malta");
                yield return new Countries(162, "Marshall Islands", "Marshall Islands", null);
                yield return new Countries(163, "Martinique", "Martinique", null);
                yield return new Countries(164, null, "Maug Island", null);
                yield return new Countries(165, "Mauritania", "Mauritania", "Mauritania");
                yield return new Countries(166, "Mauritius", "Mauritius", "Mauritius");
                yield return new Countries(167, "Mayotte", null, null);
                yield return new Countries(168, "Mexico", "Mexico", "Mexico");
                yield return new Countries(169, "Micronesia", " Federated States of", "Micronesia");
                yield return new Countries(170, "Micronesia", "", "");
                yield return new Countries(171, "Monaco", "Monaco", null);
                yield return new Countries(172, "Mongolia", "Mongolia", "Mongolia");
                yield return new Countries(173, "Montenegro", null, null);
                yield return new Countries(174, "Montserrat", "Montserrat", null);
                yield return new Countries(175, "Morocco", "Morocco", "Morocco");
                yield return new Countries(176, "Mozambique", "Mozambique", "Mozambique");
                yield return new Countries(177, "Burma", "Myanmar", "Myanmar [Burma]");
                yield return new Countries(178, "Namibia", "Namibia", "Namibia");
                yield return new Countries(179, "Nauru", "Nauru", "Nauru");
                yield return new Countries(180, "Nepal", "Nepal", "Nepal");
                yield return new Countries(181, "Netherlands", "Netherlands", "Netherlands");
                yield return new Countries(182, "Netherlands Antilles", null, null);
                yield return new Countries(183, null, "Neutral Zone", null);
                yield return new Countries(184, null, "Nevis", null);
                yield return new Countries(185, "New Caledonia", "New Caledonia", null);
                yield return new Countries(186, "New Zealand", "New Zealand", "New Zealand");
                yield return new Countries(187, "Nicaragua", "Nicaragua", "Nicaragua");
                yield return new Countries(188, "Niger", "Niger", "Niger");
                yield return new Countries(189, "Nigeria", "Nigeria", "Nigeria");
                yield return new Countries(190, "Niue", null, "Niue");
                yield return new Countries(191, "Korea", " Democratic People's Republic of", "North Korea");
                yield return new Countries(192, "North Korea", "", "");
                yield return new Countries(193, "Norfolk Island", null, null);
                yield return new Countries(194, "Northern Mariana Islands", "Northern Mariana Islands", null);
                yield return new Countries(195, "Norway", "Norway", "Norway");
                yield return new Countries(196, "Oman", "Oman", "Oman");
                yield return new Countries(197, "Pakistan", "Pakistan", "Pakistan");
                yield return new Countries(198, "Panama", "Panama", "Panama");
                yield return new Countries(199, "Palau", null, "Palau");
                yield return new Countries(200, "Palestine", null, null);
                yield return new Countries(201, "Papua New Guinea", "Papua New Guinea", "Papua New Guinea");
                yield return new Countries(202, null, "Paracel Islands", null);
                yield return new Countries(203, "Paraguay", "Paraguay", "Paraguay");
                yield return new Countries(204, "Peru", "Peru", "Peru");
                yield return new Countries(205, "Philippines", "Philippines", "Philippines");
                yield return new Countries(206, "Pitcairn Islands", "Pitcairn Islands", null);
                yield return new Countries(207, "Poland", "Poland", "Poland");
                yield return new Countries(208, "Portugal", "Portugal", "Portugal");
                yield return new Countries(209, "Puerto Rico", "Puerto Rico", "Puerto Rico");
                yield return new Countries(210, "Qatar", "Qatar", "Qatar");
                yield return new Countries(211, "Reunion", null, null);
                yield return new Countries(212, "Romania", "Romania", "Romania");
                yield return new Countries(213, "Rwanda", "Rwanda", "Rwanda");
                yield return new Countries(214, null, "Saint Eustatius", null);
                yield return new Countries(215, "Saint Helena", null, null);
                yield return new Countries(216, "Saint Kitts and Nevis", "Saint Kitts", "Saint Kitts and Nevis");
                yield return new Countries(217, "Saint Lucia", "Saint Lucia", "Saint Lucia");
                yield return new Countries(218, "Saint Vincent and the Grenadines", "Saint Vincent", "Saint Vincent and the Grenadines");
                yield return new Countries(219, "Saint Barthelemy", "Saint-Barthelemy", null);
                yield return new Countries(220, "Saint Pierre and Miquelon", null, null);
                yield return new Countries(221, "Saint Martin", "Saint-Martin", null);
                yield return new Countries(222, "San Marino", "San Marino", "San Marino");
                yield return new Countries(223, "Sao Tome and Principe", "Sao Tome and Principe", "São Tomé and Príncipe");
                yield return new Countries(224, null, "Sardinia", null);
                yield return new Countries(225, "Saudi Arabia", "Saudi Arabia", "Saudi Arabia");
                yield return new Countries(226, "Senegal", "Senegal", "Senegal");
                yield return new Countries(227, "Serbia", "Yugoslavia", "Serbia");
                yield return new Countries(228, "Seychelles", "Seychelles", "Seychelles");
                yield return new Countries(229, null, "Sicily", null);
                yield return new Countries(230, "Sierra Leone", "Sierra Leone", "Sierra Leone");
                yield return new Countries(231, null, "Sin Cowe Island", null);
                yield return new Countries(232, "Singapore", null, "Singapore");
                yield return new Countries(233, "Slovakia", "Czechoslovakia", "Slovakia");
                yield return new Countries(234, "Slovenia", "Yugoslavia", "Slovenia");
                yield return new Countries(235, "Solomon Islands", "Solomon Islands", "Solomon Islands");
                yield return new Countries(236, "Somalia", "Somalia", "Somalia");
                yield return new Countries(237, null, "Sonsorol Island", null);
                yield return new Countries(238, "South Africa", "South Africa", "South Africa");
                yield return new Countries(239, "Korea", " Republic of", "South Korea");
                yield return new Countries(240, "South Korea", "", "");
                yield return new Countries(241, null, "South Sandwich Islands", null);
                yield return new Countries(242, "Spain", "Spain", "Spain");
                yield return new Countries(243, null, "Spratly Island", null);
                yield return new Countries(244, "Sri Lanka", "Sri Lanka", "Sri Lanka");
                yield return new Countries(245, "Sudan", "Sudan", "Sudan");
                yield return new Countries(246, "Suriname", "Suriname", "Suriname");
                yield return new Countries(247, "Svalbard", null, null);
                yield return new Countries(248, "Swaziland", "Swaziland", "Swaziland");
                yield return new Countries(249, "Sweden", "Sweden", "Sweden");
                yield return new Countries(250, "Switzerland", "Switzerland", "Switzerland");
                yield return new Countries(251, "Syrian Arab Republic", "Syria", "Syria");
                yield return new Countries(252, "Taiwan", null, null);
                yield return new Countries(253, "Tajikistan", null, "Tajikistan");
                yield return new Countries(254, "United Republic of Tanzania", "Tanzania", "Tanzania");
                yield return new Countries(255, "Thailand", "Thailand", "Thailand");
                yield return new Countries(256, "Timor-Leste", null, "Timor-Leste");
                yield return new Countries(257, "Trinidad and Tobago", "Tobago", "Trinidad and Tobago");
                yield return new Countries(258, "Togo", "Togo", "Togo");
                yield return new Countries(259, "Tokelau", "Tokelau", null);
                yield return new Countries(260, "Tonga", "Tonga", "Tonga");
                yield return new Countries(261, "Trinidad and Tobago", "Trinidad", "Trinidad and Tobago");
                yield return new Countries(262, "Tunisia", "Tunisia", "Tunisia");
                yield return new Countries(263, "Turkey", "Turkey", "Turkey");
                yield return new Countries(264, "Turkmenistan", null, "Turkmenistan");
                yield return new Countries(265, "Turks and Caicos Islands", "Turks and Caicos", null);
                yield return new Countries(266, "Tuvalu", "Tuvalu", "Tuvalu");
                yield return new Countries(267, "Uganda", "Uganda", "Uganda");
                yield return new Countries(268, "United Kingdom", "UK", "United Kingdom");
                yield return new Countries(269, "Ukraine", null, "Ukraine");
                yield return new Countries(270, "Untied Arab Emirates", "United Arab Emirates", "United Arab Emirates");
                yield return new Countries(271, "Uruguay", "Uruguay", "Uruguay");
                yield return new Countries(272, "United States", "USA", "United States");
                yield return new Countries(273, "United States Minor Outlying Islands", null, null);
                yield return new Countries(274, "Uzbekistan", null, "Uzbekistan");
                yield return new Countries(275, "Russia", "USSR", "Russia");
                yield return new Countries(276, "Vanuatu", "Vanuatu", "Vanuatu");
                yield return new Countries(277, "Venezuela", "Venezuela", "Venezuela");
                yield return new Countries(278, "Viet Nam", "Vietnam", "Vietnam");
                yield return new Countries(279, "British Virgin Islands", "Virgin Islands", null);
                yield return new Countries(280, "United States Virgin Islands", "Virgin Islands", null);
                yield return new Countries(281, null, "Vislinskiy Zaliv", null);
                yield return new Countries(282, "United Kingdom", "Wales", "United Kingdom");
                yield return new Countries(283, "Wallis and Futuna Islands", null, null);
                yield return new Countries(284, null, "West Bank", "West Bank");
                yield return new Countries(285, "Western Sahara", "Western Sahara", null);
                yield return new Countries(286, "Yemen", "Yemen", "Yemen");
                yield return new Countries(287, "Zambia", "Zambia", "Zambia");
                yield return new Countries(288, "Zimbabwe", "Zimbabwe", "Zimbabwe");
            }
        }
    }
}
