// ReSharper disable All

namespace Rdatasets.mosaicData
{
    using System.Collections.Generic;

    /// <summary>
    /// Countries
    /// </summary>

    public class Countries
    {
        public readonly string maptools;
        public readonly string maps;
        public readonly string gapminder;

        public Countries(string maptools, string maps, string gapminder)
        {
            this.maptools = maptools;
            this.maps = maps;
            this.gapminder = gapminder;
        }

        public static IEnumerable<Countries> Data
        {
            get
            {
                yield return new Countries("Afghanistan", "Afghanistan", "Afghanistan");
                yield return new Countries("Åland Islands", null, null);
                yield return new Countries("Albania", "Albania", "Albania");
                yield return new Countries("Algeria", "Algeria", "Algeria");
                yield return new Countries("American Samoa", "American Samoa", "Samoa");
                yield return new Countries(null, "Andaman Islands", null);
                yield return new Countries("Andorra", "Andorra", "Andorra");
                yield return new Countries("Angola", "Angola", "Angola");
                yield return new Countries("Anguilla", "Anguilla", null);
                yield return new Countries("Antarctica", "Antarctica", null);
                yield return new Countries("Antigua and Barbuda", "Antigua", "Antigua and Barbuda");
                yield return new Countries(null, "Aral Sea", null);
                yield return new Countries("Argentina", "Argentina", "Argentina");
                yield return new Countries("Armenia", null, "Armenia");
                yield return new Countries("Aruba", "Aruba", null);
                yield return new Countries("Australia", "Australia", "Australia");
                yield return new Countries("Austria", "Austria", "Austria");
                yield return new Countries("Azerbaijan", null, "Azerbaijan");
                yield return new Countries(null, "Azores", null);
                yield return new Countries("Bahamas", "Bahamas", "Bahamas");
                yield return new Countries("Bahrain", "Bahrain", "Bahrain");
                yield return new Countries("Bangladesh", "Bangladesh", "Bangladesh");
                yield return new Countries("Barbados", "Barbados", "Barbados");
                yield return new Countries("Antigua and Barbuda", "Barbuda", "Antigua and Barbuda");
                yield return new Countries("Belarus", " ", "Belarus");
                yield return new Countries("Belgium", "Belgium", "Belgium");
                yield return new Countries("Belize", "Belize", "Belize");
                yield return new Countries("Benin", "Benin", "Benin");
                yield return new Countries("Bhutan", "Bhutan", "Bhutan");
                yield return new Countries(null, "Black Sea", null);
                yield return new Countries("Bolivia", "Bolivia", "Bolivia");
                yield return new Countries(null, "Bonaire", null);
                yield return new Countries("Bosnia and Herzegovina", "Yugoslavia", "Bosnia and Herzegovina");
                yield return new Countries("Botswana", "Botswana", "Botswana");
                yield return new Countries("Bouvet Island", null, null);
                yield return new Countries("Brazil", "Brazil", "Brazil");
                yield return new Countries("British Indian Ocean Territory", null, null);
                yield return new Countries("Brunei Darussalam", "Brunei", "Brunei");
                yield return new Countries("Bulgaria", "Bulgaria", "Bulgaria");
                yield return new Countries("Burkina Faso", "Burkina Faso", "Burkina Faso");
                yield return new Countries("Bermuda", null, null);
                yield return new Countries("Burundi", "Burundi", "Burundi");
                yield return new Countries("United States", "California", "United States");
                yield return new Countries("Cambodia", "Cambodia", "Cambodia");
                yield return new Countries("Cameroon", "Cameroon", "Cameroon");
                yield return new Countries("Canada", "Canada", "Canada");
                yield return new Countries(null, "Canary Islands", null);
                yield return new Countries("Cape Verde", "Cape Verde", "Cape Verde");
                yield return new Countries(null, "Caspian Sea", null);
                yield return new Countries("Cayman Islands", "Cayman Islands", null);
                yield return new Countries("Central African Republic", "Central African Republic", "Central African Republic");
                yield return new Countries("Chad", "Chad", "Chad");
                yield return new Countries(null, "Chagos Archipelago", null);
                yield return new Countries("Chile", "Chile", "Chile");
                yield return new Countries("China", "China", "China");
                yield return new Countries("Christmas Island", null, null);
                yield return new Countries("Cocos (Keeling) Islands", null, null);
                yield return new Countries("Colombia", "Colombia", "Colombia");
                yield return new Countries("Comoros", "Comoros", "Comoros");
                yield return new Countries("Congo", "Congo", "Congo [Republic]");
                yield return new Countries("Democratic Republic of the Congo", "Zaire", "Congo [DRC]");
                yield return new Countries("Cook Islands", "Cook Islands", "Cook Islands");
                yield return new Countries("Costa Rica", "Costa Rica", "Costa Rica");
                yield return new Countries("Croatia", "Yugoslavia", "Croatia");
                yield return new Countries("Cuba", "Cuba", "Cuba");
                yield return new Countries(null, "Curacao", null);
                yield return new Countries("Cyprus", "Cyprus", "Cyprus");
                yield return new Countries("Czech Republic", "Czechoslovakia", "Czech Republic");
                yield return new Countries("Denmark", "Denmark", "Denmark");
                yield return new Countries("Djibouti", "Djibouti", "Djibouti");
                yield return new Countries("Dominica", "Dominica", "Dominica");
                yield return new Countries("Dominican Republic", "Dominican Republic", "Dominican Republic");
                yield return new Countries("Ecuador", "Ecuador", "Ecuador");
                yield return new Countries("Egypt", "Egypt", "Egypt");
                yield return new Countries("El Salvador", "El Salvador", "El Salvador");
                yield return new Countries("Eritrea", null, "Eritrea");
                yield return new Countries("Equatorial Guinea", "Equatorial Guinea", "Equatorial Guinea");
                yield return new Countries("Estonia", null, "Estonia");
                yield return new Countries("Ethiopia", "Ethiopia", "Ethiopia");
                yield return new Countries("Falkland Islands (Malvinas)", "Falkland Islands", null);
                yield return new Countries("Faroe Islands", null, null);
                yield return new Countries("Fiji", "Fiji", "Fiji");
                yield return new Countries("Finland", "Finland", "Finland");
                yield return new Countries("France", "France", "France");
                yield return new Countries("French Guiana", "French Guiana", null);
                yield return new Countries("French Polynesia", "French Polynesia", null);
                yield return new Countries("French Southern and Antarctic Lands", null, null);
                yield return new Countries("Gabon", "Gabon", "Gabon");
                yield return new Countries("Gambia", "Gambia", "Gambia");
                yield return new Countries(null, "Gaza Strip", null);
                yield return new Countries("Georgia", null, "Georgia");
                yield return new Countries("South Georgia South Sandwich Islands", null, null);
                yield return new Countries("Germany", "Germany", "Germany");
                yield return new Countries("Ghana", "Ghana", "Ghana");
                yield return new Countries("Gibraltar", null, null);
                yield return new Countries(null, "Great Bitter Lake", null);
                yield return new Countries(null, "Great Lakes", null);
                yield return new Countries("Greece", "Greece", "Greece");
                yield return new Countries("Greenland", "Greenland", null);
                yield return new Countries("Grenada", "Grenada", "Grenada");
                yield return new Countries("Guadeloupe", "Guadeloupe", null);
                yield return new Countries("Guam", null, null);
                yield return new Countries("Guatemala", "Guatemala", "Guatemala");
                yield return new Countries("Guinea", "Guinea", "Guinea");
                yield return new Countries("Guinea-Bissau", "Guinea-Bissau", "Guinea-Bissau");
                yield return new Countries("Guyana", "Guyana", "Guyana");
                yield return new Countries("Haiti", "Haiti", "Haiti");
                yield return new Countries("United States", "Hawaii", "United States");
                yield return new Countries("Heard Island and McDonald Islands", null, null);
                yield return new Countries("Honduras", "Honduras", "Honduras");
                yield return new Countries("Holy See (Vatican City)", null, null);
                yield return new Countries("Hong Kong", null, null);
                yield return new Countries("Hungary", "Hungary", "Hungary");
                yield return new Countries("Iceland", "Iceland", "Iceland");
                yield return new Countries("India", "India", "India");
                yield return new Countries("Indonesia", "Indonesia", "Indonesia");
                yield return new Countries("Iran (Islamic Republic of)", "Iran", "Iran");
                yield return new Countries("Iraq", "Iraq", "Iraq");
                yield return new Countries("Ireland", "Ireland", "Ireland");
                yield return new Countries(null, "Irian Jaya", null);
                yield return new Countries("Isle of Man", "Isle of Man", null);
                yield return new Countries(null, "Isle of Wight", null);
                yield return new Countries("Israel", "Israel", "Israel");
                yield return new Countries("Italy", "Italy", "Italy");
                yield return new Countries("Cote d'Ivoire", "Ivory Coast", "Côte d'Ivoire");
                yield return new Countries("Jamaica", "Jamaica", "Jamaica");
                yield return new Countries("Japan", "Japan", "Japan");
                yield return new Countries("Jordan", "Jordan", "Jordan");
                yield return new Countries("Kazakhstan", null, "Kazakhstan");
                yield return new Countries("Kenya", "Kenya", "Kenya");
                yield return new Countries("Kiribati", "Kiribati", "Kiribati");
                yield return new Countries("Kyrgyzstan", null, "Kyrgyzstan");
                yield return new Countries("Kuwait", "Kuwait", "Kuwait");
                yield return new Countries(null, "Lacul Greaca", null);
                yield return new Countries(null, "Lake Albert", null);
                yield return new Countries(null, "Lake Fjerritslev", null);
                yield return new Countries(null, "Lake Kariba", null);
                yield return new Countries(null, "Lake Malawi", null);
                yield return new Countries(null, "Lake Pasvikelv", null);
                yield return new Countries(null, "Lake Tanganyika", null);
                yield return new Countries(null, "Lake Titicaca", null);
                yield return new Countries(null, "Lake Victoria", null);
                yield return new Countries("Lao People's Democratic Republic", "Laos", "Laos");
                yield return new Countries("Latvia", null, "Latvia");
                yield return new Countries("Lebanon", "Lebanon", "Lebanon");
                yield return new Countries("Lesotho", "Lesotho", "Lesotho");
                yield return new Countries("Libyan Arab Jamahiriya", "Liberia", "Liberia");
                yield return new Countries("Libya", "Libya", "Libya");
                yield return new Countries("Liechtenstein", "Liechtenstein", null);
                yield return new Countries("Lithuania", null, "Lithuania");
                yield return new Countries("Luxembourg", "Luxembourg", "Luxembourg");
                yield return new Countries("The former Yugoslav Republic of Macedonia", "Yogoslavia", "Macedonia [FYROM]");
                yield return new Countries("Macau", null, null);
                yield return new Countries("Madagascar", "Madagascar", "Madagascar");
                yield return new Countries(null, "Madeira Islands", null);
                yield return new Countries("Malawi", "Malawi", "Malawi");
                yield return new Countries("Malaysia", "Malaysia", "Malaysia");
                yield return new Countries("Maldives", "Maldives", null);
                yield return new Countries("Republic of Moldova", null, "Moldova");
                yield return new Countries("Mali", "Mali", "Mali");
                yield return new Countries("Malta", "Malta", "Malta");
                yield return new Countries("Marshall Islands", "Marshall Islands", null);
                yield return new Countries("Martinique", "Martinique", null);
                yield return new Countries(null, "Maug Island", null);
                yield return new Countries("Mauritania", "Mauritania", "Mauritania");
                yield return new Countries("Mauritius", "Mauritius", "Mauritius");
                yield return new Countries("Mayotte", null, null);
                yield return new Countries("Mexico", "Mexico", "Mexico");
                yield return new Countries("Micronesia", " Federated States of", "Micronesia");
                yield return new Countries("Micronesia", "", "");
                yield return new Countries("Monaco", "Monaco", null);
                yield return new Countries("Mongolia", "Mongolia", "Mongolia");
                yield return new Countries("Montenegro", null, null);
                yield return new Countries("Montserrat", "Montserrat", null);
                yield return new Countries("Morocco", "Morocco", "Morocco");
                yield return new Countries("Mozambique", "Mozambique", "Mozambique");
                yield return new Countries("Burma", "Myanmar", "Myanmar [Burma]");
                yield return new Countries("Namibia", "Namibia", "Namibia");
                yield return new Countries("Nauru", "Nauru", "Nauru");
                yield return new Countries("Nepal", "Nepal", "Nepal");
                yield return new Countries("Netherlands", "Netherlands", "Netherlands");
                yield return new Countries("Netherlands Antilles", null, null);
                yield return new Countries(null, "Neutral Zone", null);
                yield return new Countries(null, "Nevis", null);
                yield return new Countries("New Caledonia", "New Caledonia", null);
                yield return new Countries("New Zealand", "New Zealand", "New Zealand");
                yield return new Countries("Nicaragua", "Nicaragua", "Nicaragua");
                yield return new Countries("Niger", "Niger", "Niger");
                yield return new Countries("Nigeria", "Nigeria", "Nigeria");
                yield return new Countries("Niue", null, "Niue");
                yield return new Countries("Korea", " Democratic People's Republic of", "North Korea");
                yield return new Countries("North Korea", "", "");
                yield return new Countries("Norfolk Island", null, null);
                yield return new Countries("Northern Mariana Islands", "Northern Mariana Islands", null);
                yield return new Countries("Norway", "Norway", "Norway");
                yield return new Countries("Oman", "Oman", "Oman");
                yield return new Countries("Pakistan", "Pakistan", "Pakistan");
                yield return new Countries("Panama", "Panama", "Panama");
                yield return new Countries("Palau", null, "Palau");
                yield return new Countries("Palestine", null, null);
                yield return new Countries("Papua New Guinea", "Papua New Guinea", "Papua New Guinea");
                yield return new Countries(null, "Paracel Islands", null);
                yield return new Countries("Paraguay", "Paraguay", "Paraguay");
                yield return new Countries("Peru", "Peru", "Peru");
                yield return new Countries("Philippines", "Philippines", "Philippines");
                yield return new Countries("Pitcairn Islands", "Pitcairn Islands", null);
                yield return new Countries("Poland", "Poland", "Poland");
                yield return new Countries("Portugal", "Portugal", "Portugal");
                yield return new Countries("Puerto Rico", "Puerto Rico", "Puerto Rico");
                yield return new Countries("Qatar", "Qatar", "Qatar");
                yield return new Countries("Reunion", null, null);
                yield return new Countries("Romania", "Romania", "Romania");
                yield return new Countries("Rwanda", "Rwanda", "Rwanda");
                yield return new Countries(null, "Saint Eustatius", null);
                yield return new Countries("Saint Helena", null, null);
                yield return new Countries("Saint Kitts and Nevis", "Saint Kitts", "Saint Kitts and Nevis");
                yield return new Countries("Saint Lucia", "Saint Lucia", "Saint Lucia");
                yield return new Countries("Saint Vincent and the Grenadines", "Saint Vincent", "Saint Vincent and the Grenadines");
                yield return new Countries("Saint Barthelemy", "Saint-Barthelemy", null);
                yield return new Countries("Saint Pierre and Miquelon", null, null);
                yield return new Countries("Saint Martin", "Saint-Martin", null);
                yield return new Countries("San Marino", "San Marino", "San Marino");
                yield return new Countries("Sao Tome and Principe", "Sao Tome and Principe", "São Tomé and Príncipe");
                yield return new Countries(null, "Sardinia", null);
                yield return new Countries("Saudi Arabia", "Saudi Arabia", "Saudi Arabia");
                yield return new Countries("Senegal", "Senegal", "Senegal");
                yield return new Countries("Serbia", "Yugoslavia", "Serbia");
                yield return new Countries("Seychelles", "Seychelles", "Seychelles");
                yield return new Countries(null, "Sicily", null);
                yield return new Countries("Sierra Leone", "Sierra Leone", "Sierra Leone");
                yield return new Countries(null, "Sin Cowe Island", null);
                yield return new Countries("Singapore", null, "Singapore");
                yield return new Countries("Slovakia", "Czechoslovakia", "Slovakia");
                yield return new Countries("Slovenia", "Yugoslavia", "Slovenia");
                yield return new Countries("Solomon Islands", "Solomon Islands", "Solomon Islands");
                yield return new Countries("Somalia", "Somalia", "Somalia");
                yield return new Countries(null, "Sonsorol Island", null);
                yield return new Countries("South Africa", "South Africa", "South Africa");
                yield return new Countries("Korea", " Republic of", "South Korea");
                yield return new Countries("South Korea", "", "");
                yield return new Countries(null, "South Sandwich Islands", null);
                yield return new Countries("Spain", "Spain", "Spain");
                yield return new Countries(null, "Spratly Island", null);
                yield return new Countries("Sri Lanka", "Sri Lanka", "Sri Lanka");
                yield return new Countries("Sudan", "Sudan", "Sudan");
                yield return new Countries("Suriname", "Suriname", "Suriname");
                yield return new Countries("Svalbard", null, null);
                yield return new Countries("Swaziland", "Swaziland", "Swaziland");
                yield return new Countries("Sweden", "Sweden", "Sweden");
                yield return new Countries("Switzerland", "Switzerland", "Switzerland");
                yield return new Countries("Syrian Arab Republic", "Syria", "Syria");
                yield return new Countries("Taiwan", null, null);
                yield return new Countries("Tajikistan", null, "Tajikistan");
                yield return new Countries("United Republic of Tanzania", "Tanzania", "Tanzania");
                yield return new Countries("Thailand", "Thailand", "Thailand");
                yield return new Countries("Timor-Leste", null, "Timor-Leste");
                yield return new Countries("Trinidad and Tobago", "Tobago", "Trinidad and Tobago");
                yield return new Countries("Togo", "Togo", "Togo");
                yield return new Countries("Tokelau", "Tokelau", null);
                yield return new Countries("Tonga", "Tonga", "Tonga");
                yield return new Countries("Trinidad and Tobago", "Trinidad", "Trinidad and Tobago");
                yield return new Countries("Tunisia", "Tunisia", "Tunisia");
                yield return new Countries("Turkey", "Turkey", "Turkey");
                yield return new Countries("Turkmenistan", null, "Turkmenistan");
                yield return new Countries("Turks and Caicos Islands", "Turks and Caicos", null);
                yield return new Countries("Tuvalu", "Tuvalu", "Tuvalu");
                yield return new Countries("Uganda", "Uganda", "Uganda");
                yield return new Countries("United Kingdom", "UK", "United Kingdom");
                yield return new Countries("Ukraine", null, "Ukraine");
                yield return new Countries("Untied Arab Emirates", "United Arab Emirates", "United Arab Emirates");
                yield return new Countries("Uruguay", "Uruguay", "Uruguay");
                yield return new Countries("United States", "USA", "United States");
                yield return new Countries("United States Minor Outlying Islands", null, null);
                yield return new Countries("Uzbekistan", null, "Uzbekistan");
                yield return new Countries("Russia", "USSR", "Russia");
                yield return new Countries("Vanuatu", "Vanuatu", "Vanuatu");
                yield return new Countries("Venezuela", "Venezuela", "Venezuela");
                yield return new Countries("Viet Nam", "Vietnam", "Vietnam");
                yield return new Countries("British Virgin Islands", "Virgin Islands", null);
                yield return new Countries("United States Virgin Islands", "Virgin Islands", null);
                yield return new Countries(null, "Vislinskiy Zaliv", null);
                yield return new Countries("United Kingdom", "Wales", "United Kingdom");
                yield return new Countries("Wallis and Futuna Islands", null, null);
                yield return new Countries(null, "West Bank", "West Bank");
                yield return new Countries("Western Sahara", "Western Sahara", null);
                yield return new Countries("Yemen", "Yemen", "Yemen");
                yield return new Countries("Zambia", "Zambia", "Zambia");
                yield return new Countries("Zimbabwe", "Zimbabwe", "Zimbabwe");
            }
        }
    }
}
