// ReSharper disable All

namespace Rdatasets.pscl
{
    using System.Collections.Generic;

    /// <summary>
    /// Prussian army horse kick data
    /// </summary>

    public class prussian
    {
        public readonly int κ;
        public readonly int y;
        public readonly int year;
        public readonly string corp;

        public prussian(int κ, int y, int year, string corp)
        {
            this.κ = κ;
            this.y = y;
            this.year = year;
            this.corp = corp;
        }

        public static IEnumerable<prussian> Data
        {
            get
            {
                yield return new prussian(1, 0, 75, "G");
                yield return new prussian(2, 2, 76, "G");
                yield return new prussian(3, 2, 77, "G");
                yield return new prussian(4, 1, 78, "G");
                yield return new prussian(5, 0, 79, "G");
                yield return new prussian(6, 0, 80, "G");
                yield return new prussian(7, 1, 81, "G");
                yield return new prussian(8, 1, 82, "G");
                yield return new prussian(9, 0, 83, "G");
                yield return new prussian(10, 3, 84, "G");
                yield return new prussian(11, 0, 85, "G");
                yield return new prussian(12, 2, 86, "G");
                yield return new prussian(13, 1, 87, "G");
                yield return new prussian(14, 0, 88, "G");
                yield return new prussian(15, 0, 89, "G");
                yield return new prussian(16, 1, 90, "G");
                yield return new prussian(17, 0, 91, "G");
                yield return new prussian(18, 1, 92, "G");
                yield return new prussian(19, 0, 93, "G");
                yield return new prussian(20, 1, 94, "G");
                yield return new prussian(21, 0, 75, "I");
                yield return new prussian(22, 0, 76, "I");
                yield return new prussian(23, 0, 77, "I");
                yield return new prussian(24, 2, 78, "I");
                yield return new prussian(25, 0, 79, "I");
                yield return new prussian(26, 3, 80, "I");
                yield return new prussian(27, 0, 81, "I");
                yield return new prussian(28, 2, 82, "I");
                yield return new prussian(29, 0, 83, "I");
                yield return new prussian(30, 0, 84, "I");
                yield return new prussian(31, 0, 85, "I");
                yield return new prussian(32, 1, 86, "I");
                yield return new prussian(33, 1, 87, "I");
                yield return new prussian(34, 1, 88, "I");
                yield return new prussian(35, 0, 89, "I");
                yield return new prussian(36, 2, 90, "I");
                yield return new prussian(37, 0, 91, "I");
                yield return new prussian(38, 3, 92, "I");
                yield return new prussian(39, 1, 93, "I");
                yield return new prussian(40, 0, 94, "I");
                yield return new prussian(41, 0, 75, "II");
                yield return new prussian(42, 0, 76, "II");
                yield return new prussian(43, 0, 77, "II");
                yield return new prussian(44, 2, 78, "II");
                yield return new prussian(45, 0, 79, "II");
                yield return new prussian(46, 2, 80, "II");
                yield return new prussian(47, 0, 81, "II");
                yield return new prussian(48, 0, 82, "II");
                yield return new prussian(49, 1, 83, "II");
                yield return new prussian(50, 1, 84, "II");
                yield return new prussian(51, 0, 85, "II");
                yield return new prussian(52, 0, 86, "II");
                yield return new prussian(53, 2, 87, "II");
                yield return new prussian(54, 1, 88, "II");
                yield return new prussian(55, 1, 89, "II");
                yield return new prussian(56, 0, 90, "II");
                yield return new prussian(57, 0, 91, "II");
                yield return new prussian(58, 2, 92, "II");
                yield return new prussian(59, 0, 93, "II");
                yield return new prussian(60, 0, 94, "II");
                yield return new prussian(61, 0, 75, "III");
                yield return new prussian(62, 0, 76, "III");
                yield return new prussian(63, 0, 77, "III");
                yield return new prussian(64, 1, 78, "III");
                yield return new prussian(65, 1, 79, "III");
                yield return new prussian(66, 1, 80, "III");
                yield return new prussian(67, 2, 81, "III");
                yield return new prussian(68, 0, 82, "III");
                yield return new prussian(69, 2, 83, "III");
                yield return new prussian(70, 0, 84, "III");
                yield return new prussian(71, 0, 85, "III");
                yield return new prussian(72, 0, 86, "III");
                yield return new prussian(73, 1, 87, "III");
                yield return new prussian(74, 0, 88, "III");
                yield return new prussian(75, 1, 89, "III");
                yield return new prussian(76, 2, 90, "III");
                yield return new prussian(77, 1, 91, "III");
                yield return new prussian(78, 0, 92, "III");
                yield return new prussian(79, 0, 93, "III");
                yield return new prussian(80, 0, 94, "III");
                yield return new prussian(81, 0, 75, "IV");
                yield return new prussian(82, 1, 76, "IV");
                yield return new prussian(83, 0, 77, "IV");
                yield return new prussian(84, 1, 78, "IV");
                yield return new prussian(85, 1, 79, "IV");
                yield return new prussian(86, 1, 80, "IV");
                yield return new prussian(87, 1, 81, "IV");
                yield return new prussian(88, 0, 82, "IV");
                yield return new prussian(89, 0, 83, "IV");
                yield return new prussian(90, 0, 84, "IV");
                yield return new prussian(91, 0, 85, "IV");
                yield return new prussian(92, 1, 86, "IV");
                yield return new prussian(93, 0, 87, "IV");
                yield return new prussian(94, 0, 88, "IV");
                yield return new prussian(95, 0, 89, "IV");
                yield return new prussian(96, 0, 90, "IV");
                yield return new prussian(97, 1, 91, "IV");
                yield return new prussian(98, 1, 92, "IV");
                yield return new prussian(99, 0, 93, "IV");
                yield return new prussian(100, 0, 94, "IV");
                yield return new prussian(101, 0, 75, "V");
                yield return new prussian(102, 0, 76, "V");
                yield return new prussian(103, 0, 77, "V");
                yield return new prussian(104, 0, 78, "V");
                yield return new prussian(105, 2, 79, "V");
                yield return new prussian(106, 1, 80, "V");
                yield return new prussian(107, 0, 81, "V");
                yield return new prussian(108, 0, 82, "V");
                yield return new prussian(109, 1, 83, "V");
                yield return new prussian(110, 0, 84, "V");
                yield return new prussian(111, 0, 85, "V");
                yield return new prussian(112, 1, 86, "V");
                yield return new prussian(113, 0, 87, "V");
                yield return new prussian(114, 1, 88, "V");
                yield return new prussian(115, 1, 89, "V");
                yield return new prussian(116, 1, 90, "V");
                yield return new prussian(117, 1, 91, "V");
                yield return new prussian(118, 1, 92, "V");
                yield return new prussian(119, 1, 93, "V");
                yield return new prussian(120, 0, 94, "V");
                yield return new prussian(121, 0, 75, "VI");
                yield return new prussian(122, 0, 76, "VI");
                yield return new prussian(123, 1, 77, "VI");
                yield return new prussian(124, 0, 78, "VI");
                yield return new prussian(125, 2, 79, "VI");
                yield return new prussian(126, 0, 80, "VI");
                yield return new prussian(127, 0, 81, "VI");
                yield return new prussian(128, 1, 82, "VI");
                yield return new prussian(129, 2, 83, "VI");
                yield return new prussian(130, 0, 84, "VI");
                yield return new prussian(131, 1, 85, "VI");
                yield return new prussian(132, 1, 86, "VI");
                yield return new prussian(133, 3, 87, "VI");
                yield return new prussian(134, 1, 88, "VI");
                yield return new prussian(135, 1, 89, "VI");
                yield return new prussian(136, 1, 90, "VI");
                yield return new prussian(137, 0, 91, "VI");
                yield return new prussian(138, 3, 92, "VI");
                yield return new prussian(139, 0, 93, "VI");
                yield return new prussian(140, 0, 94, "VI");
                yield return new prussian(141, 1, 75, "VII");
                yield return new prussian(142, 0, 76, "VII");
                yield return new prussian(143, 1, 77, "VII");
                yield return new prussian(144, 0, 78, "VII");
                yield return new prussian(145, 0, 79, "VII");
                yield return new prussian(146, 0, 80, "VII");
                yield return new prussian(147, 1, 81, "VII");
                yield return new prussian(148, 0, 82, "VII");
                yield return new prussian(149, 1, 83, "VII");
                yield return new prussian(150, 1, 84, "VII");
                yield return new prussian(151, 0, 85, "VII");
                yield return new prussian(152, 0, 86, "VII");
                yield return new prussian(153, 2, 87, "VII");
                yield return new prussian(154, 0, 88, "VII");
                yield return new prussian(155, 0, 89, "VII");
                yield return new prussian(156, 2, 90, "VII");
                yield return new prussian(157, 1, 91, "VII");
                yield return new prussian(158, 0, 92, "VII");
                yield return new prussian(159, 2, 93, "VII");
                yield return new prussian(160, 0, 94, "VII");
                yield return new prussian(161, 1, 75, "VIII");
                yield return new prussian(162, 0, 76, "VIII");
                yield return new prussian(163, 0, 77, "VIII");
                yield return new prussian(164, 0, 78, "VIII");
                yield return new prussian(165, 1, 79, "VIII");
                yield return new prussian(166, 0, 80, "VIII");
                yield return new prussian(167, 0, 81, "VIII");
                yield return new prussian(168, 1, 82, "VIII");
                yield return new prussian(169, 0, 83, "VIII");
                yield return new prussian(170, 0, 84, "VIII");
                yield return new prussian(171, 0, 85, "VIII");
                yield return new prussian(172, 0, 86, "VIII");
                yield return new prussian(173, 1, 87, "VIII");
                yield return new prussian(174, 0, 88, "VIII");
                yield return new prussian(175, 0, 89, "VIII");
                yield return new prussian(176, 0, 90, "VIII");
                yield return new prussian(177, 1, 91, "VIII");
                yield return new prussian(178, 1, 92, "VIII");
                yield return new prussian(179, 0, 93, "VIII");
                yield return new prussian(180, 1, 94, "VIII");
                yield return new prussian(181, 0, 75, "IX");
                yield return new prussian(182, 0, 76, "IX");
                yield return new prussian(183, 0, 77, "IX");
                yield return new prussian(184, 0, 78, "IX");
                yield return new prussian(185, 0, 79, "IX");
                yield return new prussian(186, 2, 80, "IX");
                yield return new prussian(187, 1, 81, "IX");
                yield return new prussian(188, 1, 82, "IX");
                yield return new prussian(189, 1, 83, "IX");
                yield return new prussian(190, 0, 84, "IX");
                yield return new prussian(191, 2, 85, "IX");
                yield return new prussian(192, 1, 86, "IX");
                yield return new prussian(193, 1, 87, "IX");
                yield return new prussian(194, 0, 88, "IX");
                yield return new prussian(195, 1, 89, "IX");
                yield return new prussian(196, 2, 90, "IX");
                yield return new prussian(197, 0, 91, "IX");
                yield return new prussian(198, 1, 92, "IX");
                yield return new prussian(199, 0, 93, "IX");
                yield return new prussian(200, 0, 94, "IX");
                yield return new prussian(201, 0, 75, "X");
                yield return new prussian(202, 0, 76, "X");
                yield return new prussian(203, 1, 77, "X");
                yield return new prussian(204, 1, 78, "X");
                yield return new prussian(205, 0, 79, "X");
                yield return new prussian(206, 1, 80, "X");
                yield return new prussian(207, 0, 81, "X");
                yield return new prussian(208, 2, 82, "X");
                yield return new prussian(209, 0, 83, "X");
                yield return new prussian(210, 2, 84, "X");
                yield return new prussian(211, 0, 85, "X");
                yield return new prussian(212, 0, 86, "X");
                yield return new prussian(213, 0, 87, "X");
                yield return new prussian(214, 0, 88, "X");
                yield return new prussian(215, 2, 89, "X");
                yield return new prussian(216, 1, 90, "X");
                yield return new prussian(217, 3, 91, "X");
                yield return new prussian(218, 0, 92, "X");
                yield return new prussian(219, 1, 93, "X");
                yield return new prussian(220, 1, 94, "X");
                yield return new prussian(221, 0, 75, "XI");
                yield return new prussian(222, 0, 76, "XI");
                yield return new prussian(223, 0, 77, "XI");
                yield return new prussian(224, 0, 78, "XI");
                yield return new prussian(225, 2, 79, "XI");
                yield return new prussian(226, 4, 80, "XI");
                yield return new prussian(227, 0, 81, "XI");
                yield return new prussian(228, 1, 82, "XI");
                yield return new prussian(229, 3, 83, "XI");
                yield return new prussian(230, 0, 84, "XI");
                yield return new prussian(231, 1, 85, "XI");
                yield return new prussian(232, 1, 86, "XI");
                yield return new prussian(233, 1, 87, "XI");
                yield return new prussian(234, 1, 88, "XI");
                yield return new prussian(235, 2, 89, "XI");
                yield return new prussian(236, 1, 90, "XI");
                yield return new prussian(237, 3, 91, "XI");
                yield return new prussian(238, 1, 92, "XI");
                yield return new prussian(239, 3, 93, "XI");
                yield return new prussian(240, 1, 94, "XI");
                yield return new prussian(241, 1, 75, "XIV");
                yield return new prussian(242, 1, 76, "XIV");
                yield return new prussian(243, 2, 77, "XIV");
                yield return new prussian(244, 1, 78, "XIV");
                yield return new prussian(245, 1, 79, "XIV");
                yield return new prussian(246, 3, 80, "XIV");
                yield return new prussian(247, 0, 81, "XIV");
                yield return new prussian(248, 4, 82, "XIV");
                yield return new prussian(249, 0, 83, "XIV");
                yield return new prussian(250, 1, 84, "XIV");
                yield return new prussian(251, 0, 85, "XIV");
                yield return new prussian(252, 3, 86, "XIV");
                yield return new prussian(253, 2, 87, "XIV");
                yield return new prussian(254, 1, 88, "XIV");
                yield return new prussian(255, 0, 89, "XIV");
                yield return new prussian(256, 2, 90, "XIV");
                yield return new prussian(257, 1, 91, "XIV");
                yield return new prussian(258, 1, 92, "XIV");
                yield return new prussian(259, 0, 93, "XIV");
                yield return new prussian(260, 0, 94, "XIV");
                yield return new prussian(261, 0, 75, "XV");
                yield return new prussian(262, 1, 76, "XV");
                yield return new prussian(263, 0, 77, "XV");
                yield return new prussian(264, 0, 78, "XV");
                yield return new prussian(265, 0, 79, "XV");
                yield return new prussian(266, 0, 80, "XV");
                yield return new prussian(267, 0, 81, "XV");
                yield return new prussian(268, 1, 82, "XV");
                yield return new prussian(269, 0, 83, "XV");
                yield return new prussian(270, 1, 84, "XV");
                yield return new prussian(271, 1, 85, "XV");
                yield return new prussian(272, 0, 86, "XV");
                yield return new prussian(273, 0, 87, "XV");
                yield return new prussian(274, 0, 88, "XV");
                yield return new prussian(275, 2, 89, "XV");
                yield return new prussian(276, 2, 90, "XV");
                yield return new prussian(277, 0, 91, "XV");
                yield return new prussian(278, 0, 92, "XV");
                yield return new prussian(279, 0, 93, "XV");
                yield return new prussian(280, 0, 94, "XV");
            }
        }
    }
}
