// ReSharper disable All

namespace Rdatasets.geepack
{
    using System.Collections.Generic;

    /// <summary>
    /// Ordinal Data from Koch
    /// </summary>

    public class koch
    {
        public readonly int trt;
        public readonly int day;
        public readonly int y;
        public readonly int id;

        public koch(int trt, int day, int y, int id)
        {
            this.trt = trt;
            this.day = day;
            this.y = y;
            this.id = id;
        }

        public static IEnumerable<koch> Data
        {
            get
            {
                yield return new koch(1, 3, 3, 1);
                yield return new koch(1, 7, 2, 1);
                yield return new koch(1, 10, 2, 1);
                yield return new koch(1, 14, 2, 1);
                yield return new koch(1, 3, 2, 2);
                yield return new koch(1, 7, 2, 2);
                yield return new koch(1, 10, 2, 2);
                yield return new koch(1, 14, 1, 2);
                yield return new koch(1, 3, 2, 3);
                yield return new koch(1, 7, 2, 3);
                yield return new koch(1, 10, 2, 3);
                yield return new koch(1, 14, 2, 3);
                yield return new koch(1, 3, 1, 4);
                yield return new koch(1, 7, 2, 4);
                yield return new koch(1, 10, 1, 4);
                yield return new koch(1, 14, 2, 4);
                yield return new koch(1, 3, 3, 5);
                yield return new koch(1, 7, 2, 5);
                yield return new koch(1, 10, 2, 5);
                yield return new koch(1, 14, 1, 5);
                yield return new koch(1, 3, 2, 6);
                yield return new koch(1, 7, 2, 6);
                yield return new koch(1, 10, 1, 6);
                yield return new koch(1, 14, 3, 6);
                yield return new koch(1, 3, 3, 7);
                yield return new koch(1, 7, 2, 7);
                yield return new koch(1, 10, 2, 7);
                yield return new koch(1, 14, 1, 7);
                yield return new koch(1, 3, 2, 8);
                yield return new koch(1, 7, 1, 8);
                yield return new koch(1, 10, 2, 8);
                yield return new koch(1, 14, 1, 8);
                yield return new koch(1, 3, 2, 9);
                yield return new koch(1, 7, 2, 9);
                yield return new koch(1, 10, 2, 9);
                yield return new koch(1, 14, 1, 9);
                yield return new koch(1, 3, 2, 10);
                yield return new koch(1, 7, 1, 10);
                yield return new koch(1, 10, 2, 10);
                yield return new koch(1, 14, 1, 10);
                yield return new koch(1, 3, 2, 11);
                yield return new koch(1, 7, 1, 11);
                yield return new koch(1, 10, 2, 11);
                yield return new koch(1, 14, 2, 11);
                yield return new koch(1, 3, 2, 12);
                yield return new koch(1, 7, 2, 12);
                yield return new koch(1, 10, 1, 12);
                yield return new koch(1, 14, 2, 12);
                yield return new koch(1, 3, 3, 13);
                yield return new koch(1, 7, 2, 13);
                yield return new koch(1, 10, 2, 13);
                yield return new koch(1, 14, 2, 13);
                yield return new koch(1, 3, 2, 14);
                yield return new koch(1, 7, 1, 14);
                yield return new koch(1, 10, 1, 14);
                yield return new koch(1, 14, 1, 14);
                yield return new koch(1, 3, 3, 15);
                yield return new koch(1, 7, 2, 15);
                yield return new koch(1, 10, 3, 15);
                yield return new koch(1, 14, 2, 15);
                yield return new koch(1, 3, 3, 16);
                yield return new koch(1, 7, 2, 16);
                yield return new koch(1, 10, 1, 16);
                yield return new koch(1, 14, 1, 16);
                yield return new koch(1, 3, 2, 17);
                yield return new koch(1, 7, 3, 17);
                yield return new koch(1, 10, 2, 17);
                yield return new koch(1, 14, 2, 17);
                yield return new koch(1, 3, 3, 18);
                yield return new koch(1, 7, 3, 18);
                yield return new koch(1, 10, 3, 18);
                yield return new koch(1, 14, 2, 18);
                yield return new koch(1, 3, 1, 19);
                yield return new koch(1, 7, 1, 19);
                yield return new koch(1, 10, 1, 19);
                yield return new koch(1, 14, 1, 19);
                yield return new koch(1, 3, 2, 20);
                yield return new koch(1, 7, 2, 20);
                yield return new koch(1, 10, 2, 20);
                yield return new koch(1, 14, 1, 20);
                yield return new koch(1, 3, 3, 21);
                yield return new koch(1, 7, 1, 21);
                yield return new koch(1, 10, 2, 21);
                yield return new koch(1, 14, 2, 21);
                yield return new koch(1, 3, 2, 22);
                yield return new koch(1, 7, 2, 22);
                yield return new koch(1, 10, 3, 22);
                yield return new koch(1, 14, 1, 22);
                yield return new koch(1, 3, 2, 23);
                yield return new koch(1, 7, 1, 23);
                yield return new koch(1, 10, 1, 23);
                yield return new koch(1, 14, 1, 23);
                yield return new koch(1, 3, 2, 24);
                yield return new koch(1, 7, 1, 24);
                yield return new koch(1, 10, 1, 24);
                yield return new koch(1, 14, 1, 24);
                yield return new koch(1, 3, 2, 25);
                yield return new koch(1, 7, 1, 25);
                yield return new koch(1, 10, 2, 25);
                yield return new koch(1, 14, 1, 25);
                yield return new koch(1, 3, 2, 26);
                yield return new koch(1, 7, 2, 26);
                yield return new koch(1, 10, 2, 26);
                yield return new koch(1, 14, 2, 26);
                yield return new koch(1, 3, 3, 27);
                yield return new koch(1, 7, 2, 27);
                yield return new koch(1, 10, 3, 27);
                yield return new koch(1, 14, 2, 27);
                yield return new koch(1, 3, 3, 28);
                yield return new koch(1, 7, 2, 28);
                yield return new koch(1, 10, 2, 28);
                yield return new koch(1, 14, 2, 28);
                yield return new koch(1, 3, 2, 29);
                yield return new koch(1, 7, 3, 29);
                yield return new koch(1, 10, 2, 29);
                yield return new koch(1, 14, 2, 29);
                yield return new koch(1, 3, 1, 30);
                yield return new koch(1, 7, 1, 30);
                yield return new koch(1, 10, 1, 30);
                yield return new koch(1, 14, 1, 30);
                yield return new koch(1, 3, 1, 31);
                yield return new koch(1, 7, 2, 31);
                yield return new koch(1, 10, 1, 31);
                yield return new koch(1, 14, 2, 31);
                yield return new koch(1, 3, 2, 32);
                yield return new koch(1, 7, 2, 32);
                yield return new koch(1, 10, 2, 32);
                yield return new koch(1, 14, 1, 32);
                yield return new koch(1, 3, 2, 33);
                yield return new koch(1, 7, 1, 33);
                yield return new koch(1, 10, 1, 33);
                yield return new koch(1, 14, 1, 33);
                yield return new koch(1, 3, 1, 34);
                yield return new koch(1, 7, 1, 34);
                yield return new koch(1, 10, 1, 34);
                yield return new koch(1, 14, 1, 34);
                yield return new koch(1, 3, 2, 35);
                yield return new koch(1, 7, 1, 35);
                yield return new koch(1, 10, 1, 35);
                yield return new koch(1, 14, 1, 35);
                yield return new koch(1, 3, 2, 36);
                yield return new koch(1, 7, 3, 36);
                yield return new koch(1, 10, 2, 36);
                yield return new koch(1, 14, 2, 36);
                yield return new koch(0, 3, 3, 37);
                yield return new koch(0, 7, 2, 37);
                yield return new koch(0, 10, 2, 37);
                yield return new koch(0, 14, 2, 37);
                yield return new koch(0, 3, 2, 38);
                yield return new koch(0, 7, 2, 38);
                yield return new koch(0, 10, 1, 38);
                yield return new koch(0, 14, 1, 38);
                yield return new koch(0, 3, 3, 39);
                yield return new koch(0, 7, 3, 39);
                yield return new koch(0, 10, 3, 39);
                yield return new koch(0, 14, 2, 39);
                yield return new koch(0, 3, 2, 40);
                yield return new koch(0, 7, 2, 40);
                yield return new koch(0, 10, 1, 40);
                yield return new koch(0, 14, 2, 40);
                yield return new koch(0, 3, 3, 41);
                yield return new koch(0, 7, 2, 41);
                yield return new koch(0, 10, 2, 41);
                yield return new koch(0, 14, 1, 41);
                yield return new koch(0, 3, 2, 42);
                yield return new koch(0, 7, 2, 42);
                yield return new koch(0, 10, 2, 42);
                yield return new koch(0, 14, 1, 42);
                yield return new koch(0, 3, 2, 43);
                yield return new koch(0, 7, 2, 43);
                yield return new koch(0, 10, 2, 43);
                yield return new koch(0, 14, 2, 43);
                yield return new koch(0, 3, 3, 44);
                yield return new koch(0, 7, 3, 44);
                yield return new koch(0, 10, 3, 44);
                yield return new koch(0, 14, 2, 44);
                yield return new koch(0, 3, 3, 45);
                yield return new koch(0, 7, 2, 45);
                yield return new koch(0, 10, 3, 45);
                yield return new koch(0, 14, 2, 45);
                yield return new koch(0, 3, 2, 46);
                yield return new koch(0, 7, 2, 46);
                yield return new koch(0, 10, 1, 46);
                yield return new koch(0, 14, 2, 46);
                yield return new koch(0, 3, 1, 47);
                yield return new koch(0, 7, 2, 47);
                yield return new koch(0, 10, 1, 47);
                yield return new koch(0, 14, 2, 47);
                yield return new koch(0, 3, 3, 48);
                yield return new koch(0, 7, 2, 48);
                yield return new koch(0, 10, 2, 48);
                yield return new koch(0, 14, 2, 48);
                yield return new koch(0, 3, 2, 49);
                yield return new koch(0, 7, 1, 49);
                yield return new koch(0, 10, 1, 49);
                yield return new koch(0, 14, 1, 49);
                yield return new koch(0, 3, 2, 50);
                yield return new koch(0, 7, 2, 50);
                yield return new koch(0, 10, 3, 50);
                yield return new koch(0, 14, 2, 50);
                yield return new koch(0, 3, 3, 51);
                yield return new koch(0, 7, 2, 51);
                yield return new koch(0, 10, 2, 51);
                yield return new koch(0, 14, 2, 51);
                yield return new koch(0, 3, 2, 52);
                yield return new koch(0, 7, 1, 52);
                yield return new koch(0, 10, 2, 52);
                yield return new koch(0, 14, 2, 52);
                yield return new koch(0, 3, 3, 53);
                yield return new koch(0, 7, 3, 53);
                yield return new koch(0, 10, 3, 53);
                yield return new koch(0, 14, 2, 53);
                yield return new koch(0, 3, 2, 54);
                yield return new koch(0, 7, 2, 54);
                yield return new koch(0, 10, 2, 54);
                yield return new koch(0, 14, 1, 54);
                yield return new koch(0, 3, 3, 55);
                yield return new koch(0, 7, 2, 55);
                yield return new koch(0, 10, 3, 55);
                yield return new koch(0, 14, 2, 55);
                yield return new koch(0, 3, 3, 56);
                yield return new koch(0, 7, 3, 56);
                yield return new koch(0, 10, 3, 56);
                yield return new koch(0, 14, 2, 56);
                yield return new koch(0, 3, 3, 57);
                yield return new koch(0, 7, 2, 57);
                yield return new koch(0, 10, 3, 57);
                yield return new koch(0, 14, 2, 57);
                yield return new koch(0, 3, 2, 58);
                yield return new koch(0, 7, 2, 58);
                yield return new koch(0, 10, 1, 58);
                yield return new koch(0, 14, 1, 58);
                yield return new koch(0, 3, 3, 59);
                yield return new koch(0, 7, 3, 59);
                yield return new koch(0, 10, 3, 59);
                yield return new koch(0, 14, 1, 59);
                yield return new koch(0, 3, 2, 60);
                yield return new koch(0, 7, 2, 60);
                yield return new koch(0, 10, 1, 60);
                yield return new koch(0, 14, 1, 60);
                yield return new koch(0, 3, 3, 61);
                yield return new koch(0, 7, 3, 61);
                yield return new koch(0, 10, 2, 61);
                yield return new koch(0, 14, 2, 61);
                yield return new koch(0, 3, 3, 62);
                yield return new koch(0, 7, 2, 62);
                yield return new koch(0, 10, 3, 62);
                yield return new koch(0, 14, 1, 62);
                yield return new koch(0, 3, 3, 63);
                yield return new koch(0, 7, 3, 63);
                yield return new koch(0, 10, 3, 63);
                yield return new koch(0, 14, 2, 63);
                yield return new koch(0, 3, 3, 64);
                yield return new koch(0, 7, 1, 64);
                yield return new koch(0, 10, 2, 64);
                yield return new koch(0, 14, 3, 64);
                yield return new koch(0, 3, 3, 65);
                yield return new koch(0, 7, 2, 65);
                yield return new koch(0, 10, 2, 65);
                yield return new koch(0, 14, 2, 65);
                yield return new koch(0, 3, 3, 66);
                yield return new koch(0, 7, 1, 66);
                yield return new koch(0, 10, 3, 66);
                yield return new koch(0, 14, 1, 66);
                yield return new koch(0, 3, 3, 67);
                yield return new koch(0, 7, 2, 67);
                yield return new koch(0, 10, 2, 67);
                yield return new koch(0, 14, 1, 67);
                yield return new koch(0, 3, 2, 68);
                yield return new koch(0, 7, 2, 68);
                yield return new koch(0, 10, 1, 68);
                yield return new koch(0, 14, 2, 68);
                yield return new koch(0, 3, 3, 69);
                yield return new koch(0, 7, 2, 69);
                yield return new koch(0, 10, 2, 69);
                yield return new koch(0, 14, 2, 69);
                yield return new koch(0, 3, 3, 70);
                yield return new koch(0, 7, 3, 70);
                yield return new koch(0, 10, 3, 70);
                yield return new koch(0, 14, 2, 70);
                yield return new koch(0, 3, 3, 71);
                yield return new koch(0, 7, 3, 71);
                yield return new koch(0, 10, 2, 71);
                yield return new koch(0, 14, 2, 71);
                yield return new koch(0, 3, 3, 72);
                yield return new koch(0, 7, 2, 72);
                yield return new koch(0, 10, 2, 72);
                yield return new koch(0, 14, 2, 72);
            }
        }
    }
}
