language: csharp
os:
  - linux
dist: trusty
sudo: required
dotnet: 2.1.300
env:
  - CONFIGURATION=Debug
  - CONFIGURATION=Release

if: tag IS blank

before_install:
  - dotnet --info

install:
  - dotnet restore

script:
  - dotnet run --no-restore -c Release -p src/RdatasetsGenerator/RdatasetsGenerator.csproj -- data src/Rdatasets
  - dotnet build --no-restore -c $CONFIGURATION
