// ReSharper disable All

namespace Rdatasets.mediation
{
    using System.Collections.Generic;

    /// <summary>
    /// Brader, Valentino and Suhay (2008) Framing Experiment Data
    /// </summary>

    public class framing
    {
        public readonly int cond;
        public readonly string anx;
        public readonly int age;
        public readonly string educ;
        public readonly string gender;
        public readonly int income;
        public readonly int emo;
        public readonly int p_harm;
        public readonly int tone;
        public readonly int eth;
        public readonly int treat;
        public readonly string english;
        public readonly int immigr;
        public readonly int anti_info;
        public readonly int cong_mesg;

        public framing(int cond, string anx, int age, string educ, string gender, int income, int emo, int p_harm, int tone, int eth, int treat, string english, int immigr, int anti_info, int cong_mesg)
        {
            this.cond = cond;
            this.anx = anx;
            this.age = age;
            this.educ = educ;
            this.gender = gender;
            this.income = income;
            this.emo = emo;
            this.p_harm = p_harm;
            this.tone = tone;
            this.eth = eth;
            this.treat = treat;
            this.english = english;
            this.immigr = immigr;
            this.anti_info = anti_info;
            this.cong_mesg = cong_mesg;
        }

        public static IEnumerable<framing> Data
        {
            get
            {
                yield return new framing(3, "a little anxious", 45, "high school", "male", 13, 7, 6, 0, 1, 0, "Oppose", 4, 0, 1);
                yield return new framing(4, "somewhat anxious", 73, "bachelor's degree or higher", "male", 16, 6, 3, 0, 0, 0, "Favor", 3, 0, 0);
                yield return new framing(2, "a little anxious", 53, "some college", "female", 3, 8, 7, 1, 0, 0, "Strongly Oppose", 3, 0, 0);
                yield return new framing(1, "not anxious at all", 45, "high school", "male", 14, 9, 8, 1, 1, 1, "Strongly Oppose", 4, 0, 1);
                yield return new framing(3, "somewhat anxious", 55, "some college", "female", 12, 5, 5, 0, 1, 0, "Strongly Oppose", 2, 0, 0);
                yield return new framing(1, "a little anxious", 85, "high school", "female", 3, 5, 6, 1, 1, 1, "Strongly Oppose", 4, 0, 0);
                yield return new framing(1, "a little anxious", 58, "high school", "female", 10, 10, 8, 1, 1, 1, "Oppose", 4, 0, 0);
                yield return new framing(2, "a little anxious", 53, "some college", "male", 9, 8, 7, 1, 0, 0, "Favor", 4, 1, 1);
                yield return new framing(1, "a little anxious", 52, "some college", "female", 14, 8, 5, 1, 1, 1, "Strongly Oppose", 3, 0, 0);
                yield return new framing(4, "very anxious", 42, "some college", "male", 15, 3, 2, 0, 0, 0, "Oppose", 2, 0, 0);
                yield return new framing(4, "a little anxious", 38, "bachelor's degree or higher", "female", 9, 11, 8, 0, 0, 0, "Strongly Oppose", 4, 1, 1);
                yield return new framing(4, "very anxious", 38, "high school", "male", 6, 9, 8, 0, 0, 0, "Strongly Oppose", 4, 1, 1);
                yield return new framing(4, "a little anxious", 26, "bachelor's degree or higher", "female", 10, 8, 6, 0, 0, 0, "Oppose", 3, 0, 1);
                yield return new framing(1, "not anxious at all", 52, "some college", "male", 11, 10, 8, 1, 1, 1, "Strongly Oppose", 4, 0, 1);
                yield return new framing(1, "very anxious", 48, "some college", "male", 19, 3, 3, 1, 1, 1, "Oppose", 2, 0, 0);
                yield return new framing(2, "not anxious at all", 62, "high school", "female", 10, 12, 8, 1, 0, 0, "Strongly Oppose", 4, 1, 1);
                yield return new framing(1, "not anxious at all", 41, "less than high school", "female", 7, 9, 8, 1, 1, 1, "Oppose", 4, 0, 0);
                yield return new framing(3, "somewhat anxious", 54, "high school", "male", 11, 6, 6, 0, 1, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(1, "a little anxious", 69, "high school", "female", 9, 8, 7, 1, 1, 1, "Strongly Oppose", 4, 0, 0);
                yield return new framing(1, "somewhat anxious", 71, "less than high school", "male", 6, 6, 6, 1, 1, 1, "Strongly Oppose", 1, 0, 0);
                yield return new framing(3, "somewhat anxious", 62, "some college", "male", 14, 4, 5, 0, 1, 0, "Oppose", 2, 0, 0);
                yield return new framing(2, "very anxious", 41, "some college", "male", 13, 3, 6, 1, 0, 0, "Strongly Oppose", 3, 0, 0);
                yield return new framing(3, "a little anxious", 60, "high school", "female", 11, 7, 7, 0, 1, 0, "Strongly Oppose", 4, 0, 1);
                yield return new framing(4, "somewhat anxious", 62, "some college", "male", 17, 6, 8, 0, 0, 0, "Oppose", 4, 0, 1);
                yield return new framing(4, "somewhat anxious", 31, "bachelor's degree or higher", "male", 13, 7, 5, 0, 0, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(3, "somewhat anxious", 50, "some college", "female", 13, 4, 2, 0, 1, 0, "Strongly Oppose", 2, 0, 0);
                yield return new framing(3, "a little anxious", 48, "high school", "male", 7, 9, 5, 0, 1, 0, "Strongly Oppose", 4, 0, 1);
                yield return new framing(2, "somewhat anxious", 29, "some college", "male", 10, 6, 4, 1, 0, 0, "Strongly Favor", 2, 0, 0);
                yield return new framing(3, "a little anxious", 64, "high school", "female", 5, 9, 5, 0, 1, 0, "Oppose", 4, 0, 0);
                yield return new framing(3, "very anxious", 65, "high school", "female", 12, 4, 6, 0, 1, 0, "Strongly Oppose", 4, 0, 1);
                yield return new framing(4, "not anxious at all", 66, "less than high school", "female", 4, 12, 8, 0, 0, 0, "Oppose", 4, 0, 0);
                yield return new framing(1, "not anxious at all", 68, "high school", "female", 9, 11, 8, 1, 1, 1, "Strongly Oppose", 4, 0, 1);
                yield return new framing(4, "somewhat anxious", 43, "high school", "female", 15, 6, 6, 0, 0, 0, "Favor", 3, 0, 0);
                yield return new framing(3, "a little anxious", 57, "bachelor's degree or higher", "female", 12, 7, 5, 0, 1, 0, "Oppose", 3, 0, 0);
                yield return new framing(3, "somewhat anxious", 41, "high school", "male", 11, 9, 4, 0, 1, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(2, "somewhat anxious", 85, "bachelor's degree or higher", "male", 13, 7, 7, 1, 0, 0, "Strongly Oppose", 3, 0, 1);
                yield return new framing(4, "a little anxious", 70, "bachelor's degree or higher", "male", 15, 8, 8, 0, 0, 0, "Strongly Oppose", 4, 0, 1);
                yield return new framing(3, "a little anxious", 65, "bachelor's degree or higher", "male", 14, 8, 6, 0, 1, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(2, "a little anxious", 67, "less than high school", "female", 11, 11, 8, 1, 0, 0, "Strongly Oppose", 4, 1, 1);
                yield return new framing(1, "a little anxious", 68, "some college", "female", 9, 6, 5, 1, 1, 1, "Favor", 2, 0, 0);
                yield return new framing(2, "somewhat anxious", 64, "some college", "male", 13, 5, 5, 1, 0, 0, "Strongly Oppose", 2, 0, 0);
                yield return new framing(1, "a little anxious", 37, "some college", "male", 13, 10, 8, 1, 1, 1, "Strongly Oppose", 4, 0, 1);
                yield return new framing(3, "not anxious at all", 45, "high school", "female", 7, 10, 7, 0, 1, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(3, "a little anxious", 81, "less than high school", "female", 14, 9, 7, 0, 1, 0, "Oppose", 4, 0, 1);
                yield return new framing(2, "somewhat anxious", 51, "high school", "female", 10, 6, 6, 1, 0, 0, "Strongly Oppose", 3, 0, 0);
                yield return new framing(1, "a little anxious", 53, "some college", "male", 12, 10, 8, 1, 1, 1, "Strongly Oppose", 4, 0, 1);
                yield return new framing(4, "somewhat anxious", 62, "high school", "female", 9, 6, 5, 0, 0, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(2, "a little anxious", 42, "less than high school", "male", 8, 9, 8, 1, 0, 0, "Oppose", 4, 0, 1);
                yield return new framing(1, "a little anxious", 71, "some college", "female", 12, 8, 8, 1, 1, 1, "Strongly Oppose", 4, 0, 0);
                yield return new framing(1, "a little anxious", 56, "high school", "male", 11, 11, 8, 1, 1, 1, "Strongly Oppose", 4, 0, 1);
                yield return new framing(1, "a little anxious", 67, "less than high school", "female", 8, 10, 5, 1, 1, 1, "Oppose", 4, 0, 1);
                yield return new framing(4, "a little anxious", 77, "some college", "female", 6, 7, 6, 0, 0, 0, "Strongly Oppose", 2, 1, 0);
                yield return new framing(1, "not anxious at all", 24, "some college", "female", 15, 11, 7, 1, 1, 1, "Strongly Oppose", 4, 1, 1);
                yield return new framing(4, "a little anxious", 42, "high school", "male", 3, 7, 5, 0, 0, 0, "Oppose", 2, 0, 0);
                yield return new framing(3, "very anxious", 25, "bachelor's degree or higher", "female", 11, 3, 4, 0, 1, 0, "Oppose", 2, 0, 0);
                yield return new framing(1, "a little anxious", 60, "high school", "female", 12, 8, 6, 1, 1, 1, "Oppose", 4, 0, 0);
                yield return new framing(1, "somewhat anxious", 43, "some college", "male", 14, 10, 8, 1, 1, 1, "Strongly Oppose", 1, 0, 1);
                yield return new framing(1, "a little anxious", 60, "some college", "male", 6, 9, 6, 1, 1, 1, "Strongly Oppose", 3, 0, 0);
                yield return new framing(4, "not anxious at all", 31, "high school", "male", 11, 11, 7, 0, 0, 0, "Strongly Oppose", 4, 1, 0);
                yield return new framing(2, "somewhat anxious", 47, "some college", "female", 13, 7, 6, 1, 0, 0, "Favor", 3, 0, 0);
                yield return new framing(1, "very anxious", 32, "bachelor's degree or higher", "female", 10, 3, 2, 1, 1, 1, "Favor", 2, 0, 0);
                yield return new framing(2, "somewhat anxious", 66, "some college", "male", 8, 8, 7, 1, 0, 0, "Strongly Oppose", 3, 0, 0);
                yield return new framing(2, "very anxious", 44, "high school", "female", 15, 6, 8, 1, 0, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(2, "somewhat anxious", 46, "high school", "male", 17, 6, 4, 1, 0, 0, "Strongly Oppose", 3, 0, 0);
                yield return new framing(4, "very anxious", 41, "high school", "female", 10, 3, 3, 0, 0, 0, "Strongly Oppose", 2, 0, 0);
                yield return new framing(2, "a little anxious", 75, "high school", "female", 9, 7, 4, 1, 0, 0, "Strongly Oppose", 3, 0, 0);
                yield return new framing(1, "not anxious at all", 53, "bachelor's degree or higher", "male", 10, 12, 8, 1, 1, 1, "Strongly Oppose", 4, 0, 1);
                yield return new framing(3, "very anxious", 60, "bachelor's degree or higher", "male", 12, 3, 4, 0, 1, 0, "Favor", 2, 0, 0);
                yield return new framing(3, "very anxious", 75, "high school", "female", 2, 4, 6, 0, 1, 0, "Favor", 2, 0, 0);
                yield return new framing(2, "not anxious at all", 45, "high school", "male", 9, 12, 8, 1, 0, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(2, "not anxious at all", 69, "less than high school", "female", 5, 12, 8, 1, 0, 0, "Strongly Oppose", 4, 0, 1);
                yield return new framing(4, "somewhat anxious", 67, "high school", "female", 15, 6, 4, 0, 0, 0, "Strongly Oppose", 3, 0, 0);
                yield return new framing(4, "somewhat anxious", 20, "high school", "male", 9, 5, 5, 0, 0, 0, "Oppose", 2, 0, 0);
                yield return new framing(1, "somewhat anxious", 43, "bachelor's degree or higher", "male", 16, 6, 4, 1, 1, 1, "Strongly Oppose", 2, 0, 0);
                yield return new framing(4, "a little anxious", 32, "some college", "male", 10, 9, 8, 0, 0, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(3, "somewhat anxious", 39, "high school", "male", 12, 5, 4, 0, 1, 0, "Favor", 3, 0, 0);
                yield return new framing(3, "very anxious", 53, "bachelor's degree or higher", "female", 13, 4, 3, 0, 1, 0, "Favor", 2, 0, 0);
                yield return new framing(2, "not anxious at all", 57, "some college", "female", 2, 12, 8, 1, 0, 0, "Strongly Oppose", 4, 1, 0);
                yield return new framing(4, "a little anxious", 62, "high school", "female", 7, 8, 7, 0, 0, 0, "Strongly Oppose", 3, 1, 1);
                yield return new framing(2, "a little anxious", 69, "high school", "female", 7, 9, 8, 1, 0, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(2, "somewhat anxious", 44, "high school", "female", 13, 7, 6, 1, 0, 0, "Oppose", 4, 0, 0);
                yield return new framing(1, "not anxious at all", 57, "high school", "male", 11, 12, 8, 1, 1, 1, "Strongly Oppose", 4, 0, 0);
                yield return new framing(4, "a little anxious", 27, "some college", "female", 15, 7, 4, 0, 0, 0, "Strongly Oppose", 2, 0, 0);
                yield return new framing(3, "somewhat anxious", 82, "bachelor's degree or higher", "female", 17, 7, 5, 0, 1, 0, "Oppose", 2, 0, 0);
                yield return new framing(4, "somewhat anxious", 84, "high school", "male", 12, 6, 6, 0, 0, 0, "Strongly Oppose", 3, 1, 1);
                yield return new framing(3, "somewhat anxious", 54, "some college", "female", 13, 5, 6, 0, 1, 0, "Oppose", 2, 0, 0);
                yield return new framing(2, "very anxious", 36, "less than high school", "male", 11, 4, 6, 1, 0, 0, "Oppose", 4, 0, 0);
                yield return new framing(1, "not anxious at all", 47, "some college", "male", 13, 12, 8, 1, 1, 1, "Strongly Oppose", 4, 1, 1);
                yield return new framing(1, "very anxious", 28, "bachelor's degree or higher", "female", 12, 3, 6, 1, 1, 1, "Strongly Oppose", 4, 0, 0);
                yield return new framing(2, "very anxious", 42, "high school", "female", 14, 4, 8, 1, 0, 0, "Strongly Oppose", 4, 0, 1);
                yield return new framing(3, "very anxious", 60, "high school", "male", 6, 7, 8, 0, 1, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(1, "very anxious", 55, "bachelor's degree or higher", "male", 15, 3, 4, 1, 1, 1, "Strongly Oppose", 3, 0, 0);
                yield return new framing(2, "a little anxious", 55, "high school", "female", 6, 9, 7, 1, 0, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(4, "not anxious at all", 61, "some college", "male", 12, 12, 8, 0, 0, 0, "Strongly Oppose", 4, 1, 1);
                yield return new framing(3, "somewhat anxious", 84, "high school", "female", 11, 5, 2, 0, 1, 0, "Favor", 2, 0, 0);
                yield return new framing(4, "not anxious at all", 45, "high school", "female", 3, 10, 8, 0, 0, 0, "Oppose", 1, 0, 1);
                yield return new framing(1, "a little anxious", 67, "some college", "male", 7, 8, 8, 1, 1, 1, "Oppose", 3, 0, 0);
                yield return new framing(2, "not anxious at all", 24, "some college", "male", 12, 11, 8, 1, 0, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(2, "not anxious at all", 64, "less than high school", "male", 11, 10, 7, 1, 0, 0, "Strongly Oppose", 4, 1, 1);
                yield return new framing(1, "a little anxious", 72, "high school", "female", 7, 10, 3, 1, 1, 1, "Strongly Oppose", 4, 0, 0);
                yield return new framing(2, "not anxious at all", 40, "high school", "female", 4, 12, 8, 1, 0, 0, "Strongly Favor", 1, 0, 1);
                yield return new framing(4, "not anxious at all", 35, "bachelor's degree or higher", "female", 11, 9, 8, 0, 0, 0, "Strongly Oppose", 4, 1, 1);
                yield return new framing(1, "not anxious at all", 69, "high school", "female", 8, 12, 8, 1, 1, 1, "Oppose", 4, 0, 1);
                yield return new framing(1, "a little anxious", 30, "less than high school", "female", 6, 11, 7, 1, 1, 1, "Oppose", 4, 0, 0);
                yield return new framing(2, "a little anxious", 45, "high school", "female", 7, 8, 8, 1, 0, 0, "Strongly Oppose", 3, 0, 0);
                yield return new framing(4, "very anxious", 35, "some college", "male", 9, 3, 4, 0, 0, 0, "Oppose", 2, 0, 0);
                yield return new framing(4, "not anxious at all", 47, "high school", "male", 11, 10, 8, 0, 0, 0, "Oppose", 3, 1, 1);
                yield return new framing(4, "a little anxious", 53, "some college", "male", 11, 5, 4, 0, 0, 0, "Strongly Oppose", 2, 0, 0);
                yield return new framing(3, "a little anxious", 75, "high school", "male", 4, 9, 6, 0, 1, 0, "Oppose", 2, 0, 0);
                yield return new framing(1, "somewhat anxious", 70, "high school", "female", 13, 8, 6, 1, 1, 1, "Favor", 3, 0, 0);
                yield return new framing(1, "somewhat anxious", 56, "high school", "female", 8, 7, 8, 1, 1, 1, "Strongly Oppose", 4, 0, 1);
                yield return new framing(3, "a little anxious", 70, "less than high school", "female", 7, 8, 8, 0, 1, 0, "Strongly Oppose", 3, 0, 0);
                yield return new framing(4, "somewhat anxious", 35, "bachelor's degree or higher", "male", 11, 4, 3, 0, 0, 0, "Strongly Oppose", 2, 0, 0);
                yield return new framing(1, "not anxious at all", 54, "bachelor's degree or higher", "female", 11, 12, 6, 1, 1, 1, "Strongly Oppose", 4, 0, 0);
                yield return new framing(2, "somewhat anxious", 76, "bachelor's degree or higher", "male", 12, 5, 6, 1, 0, 0, "Strongly Oppose", 2, 0, 0);
                yield return new framing(1, "a little anxious", 65, "high school", "female", 13, 9, 6, 1, 1, 1, "Strongly Oppose", 4, 1, 1);
                yield return new framing(2, "somewhat anxious", 22, "high school", "male", 12, 5, 4, 1, 0, 0, "Oppose", 2, 0, 0);
                yield return new framing(3, "somewhat anxious", 28, "high school", "male", 13, 8, 8, 0, 1, 0, "Strongly Oppose", 4, 0, 1);
                yield return new framing(4, "very anxious", 26, "bachelor's degree or higher", "male", 11, 3, 5, 0, 0, 0, "Favor", 3, 0, 0);
                yield return new framing(1, "somewhat anxious", 67, "high school", "male", 13, 5, 6, 1, 1, 1, "Strongly Oppose", 4, 0, 0);
                yield return new framing(4, "very anxious", 58, "high school", "male", 13, 5, 4, 0, 0, 0, "Strongly Oppose", 3, 0, 1);
                yield return new framing(3, "somewhat anxious", 34, "some college", "female", 16, 6, 3, 0, 1, 0, "Strongly Oppose", 3, 0, 0);
                yield return new framing(2, "very anxious", 29, "bachelor's degree or higher", "female", 1, 5, 6, 1, 0, 0, "Oppose", 2, 0, 0);
                yield return new framing(3, "a little anxious", 61, "less than high school", "male", 13, 10, 6, 0, 1, 0, "Oppose", 4, 0, 1);
                yield return new framing(4, "not anxious at all", 58, "some college", "female", 6, 11, 8, 0, 0, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(1, "very anxious", 46, "some college", "female", 10, 5, 4, 1, 1, 1, "Oppose", 2, 0, 0);
                yield return new framing(3, "not anxious at all", 73, "less than high school", "female", 6, 8, 6, 0, 1, 0, "Strongly Oppose", 4, 0, 1);
                yield return new framing(4, "very anxious", 23, "bachelor's degree or higher", "male", 1, 3, 3, 0, 0, 0, "Strongly Oppose", 1, 0, 0);
                yield return new framing(3, "very anxious", 19, "high school", "male", 15, 4, 6, 0, 1, 0, "Strongly Oppose", 3, 0, 0);
                yield return new framing(2, "somewhat anxious", 35, "some college", "male", 8, 4, 4, 1, 0, 0, "Strongly Oppose", 2, 0, 0);
                yield return new framing(2, "very anxious", 29, "bachelor's degree or higher", "male", 19, 4, 5, 1, 0, 0, "Strongly Oppose", 3, 0, 0);
                yield return new framing(2, "very anxious", 53, "bachelor's degree or higher", "male", 8, 3, 3, 1, 0, 0, "Strongly Oppose", 3, 0, 0);
                yield return new framing(3, "a little anxious", 72, "bachelor's degree or higher", "male", 12, 7, 6, 0, 1, 0, "Oppose", 3, 0, 1);
                yield return new framing(3, "somewhat anxious", 36, "bachelor's degree or higher", "male", 14, 5, 4, 0, 1, 0, "Favor", 1, 0, 0);
                yield return new framing(1, "not anxious at all", 26, "less than high school", "male", 5, 11, 8, 1, 1, 1, "Strongly Oppose", 3, 0, 0);
                yield return new framing(2, "a little anxious", 46, "bachelor's degree or higher", "female", 13, 7, 8, 1, 0, 0, "Strongly Oppose", 4, 0, 1);
                yield return new framing(3, "a little anxious", 31, "high school", "male", 6, 9, 8, 0, 1, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(2, "a little anxious", 70, "high school", "female", 1, 8, 7, 1, 0, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(4, "a little anxious", 65, "bachelor's degree or higher", "male", 13, 7, 6, 0, 0, 0, "Strongly Oppose", 3, 0, 1);
                yield return new framing(4, "very anxious", 69, "less than high school", "female", 1, 4, 4, 0, 0, 0, "Oppose", 2, 0, 0);
                yield return new framing(4, "very anxious", 72, "bachelor's degree or higher", "male", 11, 4, 4, 0, 0, 0, "Oppose", 2, 0, 0);
                yield return new framing(1, "not anxious at all", 71, "less than high school", "female", 13, 12, 8, 1, 1, 1, "Strongly Oppose", 4, 1, 1);
                yield return new framing(2, "very anxious", 62, "some college", "male", 12, 4, 6, 1, 0, 0, "Oppose", 3, 0, 0);
                yield return new framing(3, "a little anxious", 37, "bachelor's degree or higher", "male", 13, 7, 5, 0, 1, 0, "Oppose", 3, 0, 0);
                yield return new framing(2, "very anxious", 36, "high school", "female", 5, 3, 6, 1, 0, 0, "Oppose", 3, 0, 0);
                yield return new framing(4, "somewhat anxious", 47, "some college", "female", 9, 4, 4, 0, 0, 0, "Favor", 3, 0, 0);
                yield return new framing(3, "somewhat anxious", 47, "bachelor's degree or higher", "male", 16, 5, 4, 0, 1, 0, "Oppose", 3, 0, 0);
                yield return new framing(1, "very anxious", 28, "bachelor's degree or higher", "male", 4, 3, 3, 1, 1, 1, "Oppose", 3, 0, 0);
                yield return new framing(2, "somewhat anxious", 34, "bachelor's degree or higher", "female", 11, 5, 6, 1, 0, 0, "Oppose", 2, 0, 0);
                yield return new framing(2, "very anxious", 69, "bachelor's degree or higher", "male", 10, 3, 4, 1, 0, 0, "Favor", 2, 0, 0);
                yield return new framing(3, "a little anxious", 47, "high school", "male", 12, 10, 8, 0, 1, 0, "Oppose", 3, 0, 1);
                yield return new framing(1, "not anxious at all", 73, "high school", "male", 11, 11, 8, 1, 1, 1, "Strongly Oppose", 4, 0, 1);
                yield return new framing(3, "very anxious", 63, "high school", "female", 10, 3, 3, 0, 1, 0, "Strongly Oppose", 2, 0, 0);
                yield return new framing(2, "somewhat anxious", 33, "less than high school", "male", 1, 7, 4, 1, 0, 0, "Strongly Oppose", 2, 0, 0);
                yield return new framing(1, "somewhat anxious", 42, "high school", "female", 6, 7, 4, 1, 1, 1, "Oppose", 2, 0, 0);
                yield return new framing(3, "somewhat anxious", 43, "high school", "female", 7, 5, 6, 0, 1, 0, "Strongly Oppose", 4, 1, 1);
                yield return new framing(4, "very anxious", 50, "bachelor's degree or higher", "female", 16, 3, 4, 0, 0, 0, "Oppose", 2, 0, 0);
                yield return new framing(2, "somewhat anxious", 56, "bachelor's degree or higher", "male", 10, 6, 7, 1, 0, 0, "Strongly Oppose", 3, 0, 1);
                yield return new framing(3, "somewhat anxious", 28, "some college", "female", 11, 6, 6, 0, 1, 0, "Strongly Oppose", 2, 0, 0);
                yield return new framing(1, "somewhat anxious", 44, "some college", "female", 13, 8, 8, 1, 1, 1, "Oppose", 4, 0, 0);
                yield return new framing(3, "somewhat anxious", 38, "bachelor's degree or higher", "female", 9, 5, 6, 0, 1, 0, "Oppose", 1, 0, 0);
                yield return new framing(1, "not anxious at all", 34, "bachelor's degree or higher", "female", 14, 11, 7, 1, 1, 1, "Strongly Oppose", 2, 0, 0);
                yield return new framing(2, "very anxious", 56, "some college", "male", 16, 3, 3, 1, 0, 0, "Strongly Oppose", 2, 0, 0);
                yield return new framing(3, "somewhat anxious", 47, "bachelor's degree or higher", "male", 11, 4, 6, 0, 1, 0, "Oppose", 2, 0, 0);
                yield return new framing(4, "somewhat anxious", 42, "bachelor's degree or higher", "male", 7, 7, 6, 0, 0, 0, "Strongly Oppose", 4, 0, 1);
                yield return new framing(3, "somewhat anxious", 53, "some college", "female", 16, 4, 5, 0, 1, 0, "Strongly Oppose", 2, 0, 0);
                yield return new framing(3, "very anxious", 38, "bachelor's degree or higher", "female", 11, 4, 4, 0, 1, 0, "Strongly Favor", 1, 0, 0);
                yield return new framing(2, "somewhat anxious", 50, "bachelor's degree or higher", "female", 11, 6, 4, 1, 0, 0, "Favor", 3, 0, 0);
                yield return new framing(3, "a little anxious", 21, "high school", "male", 15, 8, 7, 0, 1, 0, "Strongly Oppose", 3, 0, 1);
                yield return new framing(4, "somewhat anxious", 25, "some college", "male", 18, 5, 6, 0, 0, 0, "Strongly Oppose", 3, 0, 0);
                yield return new framing(3, "very anxious", 58, "high school", "female", 16, 5, 8, 0, 1, 0, "Oppose", 4, 0, 1);
                yield return new framing(4, "somewhat anxious", 39, "some college", "male", 10, 5, 7, 0, 0, 0, "Strongly Oppose", 3, 1, 0);
                yield return new framing(4, "not anxious at all", 26, "some college", "female", 7, 12, 8, 0, 0, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(4, "somewhat anxious", 61, "some college", "female", 8, 8, 6, 0, 0, 0, "Strongly Oppose", 4, 0, 1);
                yield return new framing(1, "somewhat anxious", 29, "some college", "female", 11, 5, 4, 1, 1, 1, "Oppose", 1, 0, 0);
                yield return new framing(3, "not anxious at all", 39, "some college", "female", 12, 12, 7, 0, 1, 0, "Strongly Oppose", 4, 0, 1);
                yield return new framing(2, "somewhat anxious", 40, "bachelor's degree or higher", "male", 11, 7, 6, 1, 0, 0, "Strongly Oppose", 4, 0, 1);
                yield return new framing(1, "somewhat anxious", 30, "bachelor's degree or higher", "female", 11, 4, 4, 1, 1, 1, "Strongly Favor", 2, 0, 0);
                yield return new framing(2, "very anxious", 64, "bachelor's degree or higher", "female", 10, 3, 5, 1, 0, 0, "Oppose", 1, 0, 0);
                yield return new framing(2, "a little anxious", 50, "less than high school", "male", 5, 10, 7, 1, 0, 0, "Strongly Oppose", 3, 0, 1);
                yield return new framing(2, "somewhat anxious", 33, "bachelor's degree or higher", "female", 12, 9, 8, 1, 0, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(3, "somewhat anxious", 35, "high school", "male", 9, 6, 6, 0, 1, 0, "Oppose", 4, 0, 1);
                yield return new framing(1, "somewhat anxious", 26, "bachelor's degree or higher", "female", 16, 6, 5, 1, 1, 1, "Oppose", 3, 0, 0);
                yield return new framing(1, "not anxious at all", 44, "some college", "male", 16, 10, 8, 1, 1, 1, "Strongly Oppose", 4, 0, 0);
                yield return new framing(1, "somewhat anxious", 44, "some college", "male", 13, 6, 6, 1, 1, 1, "Oppose", 4, 0, 1);
                yield return new framing(1, "not anxious at all", 25, "some college", "male", 11, 12, 8, 1, 1, 1, "Strongly Oppose", 4, 1, 1);
                yield return new framing(3, "very anxious", 44, "bachelor's degree or higher", "male", 17, 3, 4, 0, 1, 0, "Oppose", 1, 0, 0);
                yield return new framing(2, "a little anxious", 51, "bachelor's degree or higher", "female", 17, 9, 8, 1, 0, 0, "Strongly Oppose", 4, 1, 1);
                yield return new framing(2, "very anxious", 62, "bachelor's degree or higher", "female", 14, 5, 6, 1, 0, 0, "Strongly Oppose", 3, 0, 0);
                yield return new framing(4, "very anxious", 55, "bachelor's degree or higher", "female", 18, 3, 8, 0, 0, 0, "Strongly Oppose", 4, 0, 1);
                yield return new framing(3, "somewhat anxious", 43, "bachelor's degree or higher", "male", 13, 5, 6, 0, 1, 0, "Strongly Oppose", 3, 0, 1);
                yield return new framing(4, "very anxious", 53, "bachelor's degree or higher", "male", 12, 3, 3, 0, 0, 0, "Strongly Oppose", 3, 1, 1);
                yield return new framing(3, "a little anxious", 49, "some college", "female", 10, 6, 4, 0, 1, 0, "Oppose", 3, 0, 1);
                yield return new framing(3, "somewhat anxious", 34, "some college", "male", 11, 5, 4, 0, 1, 0, "Favor", 2, 0, 0);
                yield return new framing(4, "not anxious at all", 36, "high school", "male", 11, 9, 7, 0, 0, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(2, "very anxious", 31, "bachelor's degree or higher", "male", 11, 3, 3, 1, 0, 0, "Strongly Oppose", 3, 0, 1);
                yield return new framing(4, "somewhat anxious", 57, "bachelor's degree or higher", "female", 15, 5, 5, 0, 0, 0, "Strongly Oppose", 2, 0, 0);
                yield return new framing(2, "somewhat anxious", 18, "less than high school", "female", 16, 6, 6, 1, 0, 0, "Oppose", 1, 0, 0);
                yield return new framing(3, "somewhat anxious", 37, "bachelor's degree or higher", "female", 12, 5, 6, 0, 1, 0, "Strongly Oppose", 3, 0, 0);
                yield return new framing(3, "very anxious", 63, "bachelor's degree or higher", "male", 16, 3, 4, 0, 1, 0, "Strongly Oppose", 1, 0, 0);
                yield return new framing(2, "a little anxious", 48, "bachelor's degree or higher", "female", 16, 8, 8, 1, 0, 0, "Oppose", 3, 0, 0);
                yield return new framing(4, "not anxious at all", 32, "high school", "male", 13, 12, 8, 0, 0, 0, "Strongly Oppose", 4, 0, 1);
                yield return new framing(2, "a little anxious", 28, "some college", "female", 9, 7, 5, 1, 0, 0, "Oppose", 2, 0, 0);
                yield return new framing(4, "somewhat anxious", 45, "high school", "female", 13, 6, 5, 0, 0, 0, "Favor", 3, 0, 0);
                yield return new framing(1, "a little anxious", 59, "some college", "male", 13, 7, 8, 1, 1, 1, "Oppose", 4, 1, 1);
                yield return new framing(4, "not anxious at all", 82, "high school", "female", 10, 11, 8, 0, 0, 0, "Strongly Oppose", 3, 1, 0);
                yield return new framing(2, "very anxious", 62, "bachelor's degree or higher", "female", 2, 4, 4, 1, 0, 0, "Favor", 2, 0, 0);
                yield return new framing(1, "very anxious", 35, "bachelor's degree or higher", "female", 19, 4, 5, 1, 1, 1, "Oppose", 3, 0, 0);
                yield return new framing(4, "very anxious", 47, "some college", "female", 15, 4, 5, 0, 0, 0, "Oppose", 1, 0, 1);
                yield return new framing(3, "not anxious at all", 65, "some college", "male", 15, 11, 8, 0, 1, 0, "Strongly Oppose", 2, 0, 0);
                yield return new framing(1, "a little anxious", 62, "high school", "male", 13, 8, 8, 1, 1, 1, "Strongly Oppose", 4, 0, 0);
                yield return new framing(4, "a little anxious", 59, "bachelor's degree or higher", "female", 18, 7, 7, 0, 0, 0, "Strongly Oppose", 4, 0, 1);
                yield return new framing(4, "somewhat anxious", 51, "bachelor's degree or higher", "female", 9, 6, 6, 0, 0, 0, "Oppose", 2, 0, 0);
                yield return new framing(1, "somewhat anxious", 33, "high school", "female", 12, 8, 6, 1, 1, 1, "Strongly Oppose", 4, 0, 0);
                yield return new framing(1, "a little anxious", 27, "some college", "female", 8, 9, 6, 1, 1, 1, "Oppose", 3, 0, 0);
                yield return new framing(2, "somewhat anxious", 54, "bachelor's degree or higher", "female", 10, 5, 3, 1, 0, 0, "Strongly Oppose", 2, 1, 0);
                yield return new framing(3, "very anxious", 58, "bachelor's degree or higher", "male", 5, 3, 2, 0, 1, 0, "Favor", 1, 0, 0);
                yield return new framing(2, "very anxious", 20, "some college", "male", 3, 3, 3, 1, 0, 0, "Strongly Favor", 2, 0, 0);
                yield return new framing(3, "very anxious", 47, "bachelor's degree or higher", "male", 5, 3, 3, 0, 1, 0, "Oppose", 3, 0, 0);
                yield return new framing(2, "a little anxious", 29, "high school", "male", 12, 10, 7, 1, 0, 0, "Oppose", 4, 1, 1);
                yield return new framing(3, "not anxious at all", 54, "high school", "female", 4, 12, 8, 0, 1, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(1, "a little anxious", 24, "bachelor's degree or higher", "female", 7, 7, 6, 1, 1, 1, "Oppose", 3, 0, 0);
                yield return new framing(2, "not anxious at all", 47, "high school", "female", 10, 12, 8, 1, 0, 0, "Strongly Oppose", 4, 1, 1);
                yield return new framing(3, "a little anxious", 25, "some college", "female", 11, 7, 3, 0, 1, 0, "Oppose", 2, 0, 0);
                yield return new framing(4, "somewhat anxious", 28, "high school", "male", 10, 5, 6, 0, 0, 0, "Oppose", 3, 0, 0);
                yield return new framing(2, "somewhat anxious", 57, "bachelor's degree or higher", "male", 16, 7, 6, 1, 0, 0, "Strongly Favor", 3, 0, 1);
                yield return new framing(4, "a little anxious", 26, "high school", "male", 8, 10, 6, 0, 0, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(1, "a little anxious", 43, "high school", "male", 7, 7, 7, 1, 1, 1, "Strongly Favor", 3, 0, 1);
                yield return new framing(4, "somewhat anxious", 35, "high school", "male", 12, 6, 6, 0, 0, 0, "Strongly Oppose", 4, 0, 1);
                yield return new framing(4, "a little anxious", 29, "bachelor's degree or higher", "female", 11, 7, 5, 0, 0, 0, "Oppose", 2, 0, 0);
                yield return new framing(2, "very anxious", 26, "some college", "female", 14, 5, 4, 1, 0, 0, "Oppose", 3, 0, 0);
                yield return new framing(3, "not anxious at all", 18, "high school", "female", 15, 12, 8, 0, 1, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(4, "very anxious", 60, "bachelor's degree or higher", "female", 12, 3, 2, 0, 0, 0, "Oppose", 1, 0, 0);
                yield return new framing(4, "very anxious", 42, "bachelor's degree or higher", "female", 15, 3, 3, 0, 0, 0, "Strongly Oppose", 2, 0, 0);
                yield return new framing(1, "a little anxious", 29, "high school", "female", 15, 10, 8, 1, 1, 1, "Strongly Oppose", 4, 0, 1);
                yield return new framing(3, "somewhat anxious", 57, "bachelor's degree or higher", "female", 10, 5, 4, 0, 1, 0, "Favor", 1, 0, 0);
                yield return new framing(2, "not anxious at all", 53, "high school", "female", 14, 10, 8, 1, 0, 0, "Strongly Oppose", 4, 0, 1);
                yield return new framing(3, "very anxious", 27, "some college", "male", 6, 3, 6, 0, 1, 0, "Strongly Oppose", 3, 0, 0);
                yield return new framing(1, "a little anxious", 25, "bachelor's degree or higher", "male", 8, 9, 7, 1, 1, 1, "Strongly Oppose", 4, 0, 1);
                yield return new framing(3, "somewhat anxious", 37, "some college", "female", 7, 7, 4, 0, 1, 0, "Strongly Oppose", 2, 0, 0);
                yield return new framing(1, "a little anxious", 25, "some college", "female", 12, 7, 7, 1, 1, 1, "Oppose", 3, 0, 1);
                yield return new framing(1, "very anxious", 38, "bachelor's degree or higher", "female", 13, 4, 3, 1, 1, 1, "Strongly Oppose", 3, 0, 0);
                yield return new framing(1, "somewhat anxious", 39, "bachelor's degree or higher", "female", 15, 5, 5, 1, 1, 1, "Strongly Oppose", 3, 0, 0);
                yield return new framing(1, "somewhat anxious", 26, "some college", "male", 7, 7, 6, 1, 1, 1, "Strongly Oppose", 4, 0, 1);
                yield return new framing(4, "very anxious", 45, "bachelor's degree or higher", "female", 18, 5, 3, 0, 0, 0, "Strongly Oppose", 3, 0, 0);
                yield return new framing(2, "somewhat anxious", 27, "some college", "male", 13, 5, 7, 1, 0, 0, "Favor", 4, 0, 0);
                yield return new framing(3, "very anxious", 46, "high school", "male", 12, 3, 5, 0, 1, 0, "Oppose", 2, 0, 0);
                yield return new framing(1, "somewhat anxious", 62, "high school", "male", 3, 5, 2, 1, 1, 1, "Strongly Oppose", 3, 0, 0);
                yield return new framing(3, "somewhat anxious", 44, "high school", "female", 12, 6, 5, 0, 1, 0, "Oppose", 2, 0, 0);
                yield return new framing(3, "somewhat anxious", 65, "bachelor's degree or higher", "male", 9, 6, 8, 0, 1, 0, "Strongly Oppose", 3, 0, 0);
                yield return new framing(2, "not anxious at all", 34, "bachelor's degree or higher", "male", 8, 12, 7, 1, 0, 0, "Oppose", 3, 0, 0);
                yield return new framing(4, "somewhat anxious", 66, "high school", "female", 11, 7, 8, 0, 0, 0, "Oppose", 3, 1, 1);
                yield return new framing(3, "very anxious", 44, "high school", "female", 14, 3, 4, 0, 1, 0, "Favor", 2, 0, 0);
                yield return new framing(1, "a little anxious", 34, "high school", "male", 13, 7, 5, 1, 1, 1, "Oppose", 3, 0, 1);
                yield return new framing(4, "a little anxious", 43, "some college", "male", 10, 11, 8, 0, 0, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(2, "a little anxious", 30, "high school", "male", 9, 8, 7, 1, 0, 0, "Strongly Oppose", 4, 0, 0);
                yield return new framing(1, "not anxious at all", 27, "some college", "female", 17, 12, 7, 1, 1, 1, "Strongly Oppose", 4, 0, 1);
                yield return new framing(1, "a little anxious", 20, "high school", "female", 17, 8, 4, 1, 1, 1, "Oppose", 2, 0, 1);
                yield return new framing(2, "a little anxious", 56, "high school", "female", 10, 10, 8, 1, 0, 0, "Strongly Oppose", 3, 0, 0);
                yield return new framing(2, "not anxious at all", 42, "high school", "male", 12, 10, 7, 1, 0, 0, "Oppose", 4, 0, 1);
                yield return new framing(3, "somewhat anxious", 44, "bachelor's degree or higher", "male", 17, 7, 6, 0, 1, 0, "Oppose", 1, 0, 0);
                yield return new framing(4, "somewhat anxious", 28, "bachelor's degree or higher", "female", 14, 6, 6, 0, 0, 0, "Strongly Oppose", 1, 0, 1);
                yield return new framing(2, "very anxious", 38, "bachelor's degree or higher", "female", 14, 3, 6, 1, 0, 0, "Favor", 2, 0, 0);
                yield return new framing(1, "somewhat anxious", 29, "bachelor's degree or higher", "male", 10, 9, 7, 1, 1, 1, "Strongly Oppose", 4, 0, 1);
                yield return new framing(4, "very anxious", 52, "some college", "female", 1, 3, 2, 0, 0, 0, "Oppose", 2, 0, 0);
            }
        }
    }
}
