// ReSharper disable All

namespace Rdatasets.lattice
{
    using System.Collections.Generic;

    /// <summary>
    /// Heights of New York Choral Society singers
    /// </summary>

    public class singer
    {
        public readonly int κ;
        public readonly int height;
        public readonly string voice_part;

        public singer(int κ, int height, string voice_part)
        {
            this.κ = κ;
            this.height = height;
            this.voice_part = voice_part;
        }

        public static IEnumerable<singer> Data
        {
            get
            {
                yield return new singer(1, 64, "Soprano 1");
                yield return new singer(2, 62, "Soprano 1");
                yield return new singer(3, 66, "Soprano 1");
                yield return new singer(4, 65, "Soprano 1");
                yield return new singer(5, 60, "Soprano 1");
                yield return new singer(6, 61, "Soprano 1");
                yield return new singer(7, 65, "Soprano 1");
                yield return new singer(8, 66, "Soprano 1");
                yield return new singer(9, 65, "Soprano 1");
                yield return new singer(10, 63, "Soprano 1");
                yield return new singer(11, 67, "Soprano 1");
                yield return new singer(12, 65, "Soprano 1");
                yield return new singer(13, 62, "Soprano 1");
                yield return new singer(14, 65, "Soprano 1");
                yield return new singer(15, 68, "Soprano 1");
                yield return new singer(16, 65, "Soprano 1");
                yield return new singer(17, 63, "Soprano 1");
                yield return new singer(18, 65, "Soprano 1");
                yield return new singer(19, 62, "Soprano 1");
                yield return new singer(20, 65, "Soprano 1");
                yield return new singer(21, 66, "Soprano 1");
                yield return new singer(22, 62, "Soprano 1");
                yield return new singer(23, 65, "Soprano 1");
                yield return new singer(24, 63, "Soprano 1");
                yield return new singer(25, 65, "Soprano 1");
                yield return new singer(26, 66, "Soprano 1");
                yield return new singer(27, 65, "Soprano 1");
                yield return new singer(28, 62, "Soprano 1");
                yield return new singer(29, 65, "Soprano 1");
                yield return new singer(30, 66, "Soprano 1");
                yield return new singer(31, 65, "Soprano 1");
                yield return new singer(32, 61, "Soprano 1");
                yield return new singer(33, 65, "Soprano 1");
                yield return new singer(34, 66, "Soprano 1");
                yield return new singer(35, 65, "Soprano 1");
                yield return new singer(36, 62, "Soprano 1");
                yield return new singer(37, 63, "Soprano 2");
                yield return new singer(38, 67, "Soprano 2");
                yield return new singer(39, 60, "Soprano 2");
                yield return new singer(40, 67, "Soprano 2");
                yield return new singer(41, 66, "Soprano 2");
                yield return new singer(42, 62, "Soprano 2");
                yield return new singer(43, 65, "Soprano 2");
                yield return new singer(44, 62, "Soprano 2");
                yield return new singer(45, 61, "Soprano 2");
                yield return new singer(46, 62, "Soprano 2");
                yield return new singer(47, 66, "Soprano 2");
                yield return new singer(48, 60, "Soprano 2");
                yield return new singer(49, 65, "Soprano 2");
                yield return new singer(50, 65, "Soprano 2");
                yield return new singer(51, 61, "Soprano 2");
                yield return new singer(52, 64, "Soprano 2");
                yield return new singer(53, 68, "Soprano 2");
                yield return new singer(54, 64, "Soprano 2");
                yield return new singer(55, 63, "Soprano 2");
                yield return new singer(56, 62, "Soprano 2");
                yield return new singer(57, 64, "Soprano 2");
                yield return new singer(58, 62, "Soprano 2");
                yield return new singer(59, 64, "Soprano 2");
                yield return new singer(60, 65, "Soprano 2");
                yield return new singer(61, 60, "Soprano 2");
                yield return new singer(62, 65, "Soprano 2");
                yield return new singer(63, 70, "Soprano 2");
                yield return new singer(64, 63, "Soprano 2");
                yield return new singer(65, 67, "Soprano 2");
                yield return new singer(66, 66, "Soprano 2");
                yield return new singer(67, 65, "Alto 1");
                yield return new singer(68, 62, "Alto 1");
                yield return new singer(69, 68, "Alto 1");
                yield return new singer(70, 67, "Alto 1");
                yield return new singer(71, 67, "Alto 1");
                yield return new singer(72, 63, "Alto 1");
                yield return new singer(73, 67, "Alto 1");
                yield return new singer(74, 66, "Alto 1");
                yield return new singer(75, 63, "Alto 1");
                yield return new singer(76, 72, "Alto 1");
                yield return new singer(77, 62, "Alto 1");
                yield return new singer(78, 61, "Alto 1");
                yield return new singer(79, 66, "Alto 1");
                yield return new singer(80, 64, "Alto 1");
                yield return new singer(81, 60, "Alto 1");
                yield return new singer(82, 61, "Alto 1");
                yield return new singer(83, 66, "Alto 1");
                yield return new singer(84, 66, "Alto 1");
                yield return new singer(85, 66, "Alto 1");
                yield return new singer(86, 62, "Alto 1");
                yield return new singer(87, 70, "Alto 1");
                yield return new singer(88, 65, "Alto 1");
                yield return new singer(89, 64, "Alto 1");
                yield return new singer(90, 63, "Alto 1");
                yield return new singer(91, 65, "Alto 1");
                yield return new singer(92, 69, "Alto 1");
                yield return new singer(93, 61, "Alto 1");
                yield return new singer(94, 66, "Alto 1");
                yield return new singer(95, 65, "Alto 1");
                yield return new singer(96, 61, "Alto 1");
                yield return new singer(97, 63, "Alto 1");
                yield return new singer(98, 64, "Alto 1");
                yield return new singer(99, 67, "Alto 1");
                yield return new singer(100, 66, "Alto 1");
                yield return new singer(101, 68, "Alto 1");
                yield return new singer(102, 70, "Alto 2");
                yield return new singer(103, 65, "Alto 2");
                yield return new singer(104, 65, "Alto 2");
                yield return new singer(105, 65, "Alto 2");
                yield return new singer(106, 64, "Alto 2");
                yield return new singer(107, 66, "Alto 2");
                yield return new singer(108, 64, "Alto 2");
                yield return new singer(109, 70, "Alto 2");
                yield return new singer(110, 63, "Alto 2");
                yield return new singer(111, 70, "Alto 2");
                yield return new singer(112, 64, "Alto 2");
                yield return new singer(113, 63, "Alto 2");
                yield return new singer(114, 67, "Alto 2");
                yield return new singer(115, 65, "Alto 2");
                yield return new singer(116, 63, "Alto 2");
                yield return new singer(117, 66, "Alto 2");
                yield return new singer(118, 66, "Alto 2");
                yield return new singer(119, 64, "Alto 2");
                yield return new singer(120, 64, "Alto 2");
                yield return new singer(121, 70, "Alto 2");
                yield return new singer(122, 70, "Alto 2");
                yield return new singer(123, 66, "Alto 2");
                yield return new singer(124, 66, "Alto 2");
                yield return new singer(125, 66, "Alto 2");
                yield return new singer(126, 69, "Alto 2");
                yield return new singer(127, 67, "Alto 2");
                yield return new singer(128, 65, "Alto 2");
                yield return new singer(129, 69, "Tenor 1");
                yield return new singer(130, 72, "Tenor 1");
                yield return new singer(131, 71, "Tenor 1");
                yield return new singer(132, 66, "Tenor 1");
                yield return new singer(133, 76, "Tenor 1");
                yield return new singer(134, 74, "Tenor 1");
                yield return new singer(135, 71, "Tenor 1");
                yield return new singer(136, 66, "Tenor 1");
                yield return new singer(137, 68, "Tenor 1");
                yield return new singer(138, 67, "Tenor 1");
                yield return new singer(139, 70, "Tenor 1");
                yield return new singer(140, 65, "Tenor 1");
                yield return new singer(141, 72, "Tenor 1");
                yield return new singer(142, 70, "Tenor 1");
                yield return new singer(143, 68, "Tenor 1");
                yield return new singer(144, 64, "Tenor 1");
                yield return new singer(145, 73, "Tenor 1");
                yield return new singer(146, 66, "Tenor 1");
                yield return new singer(147, 68, "Tenor 1");
                yield return new singer(148, 67, "Tenor 1");
                yield return new singer(149, 64, "Tenor 1");
                yield return new singer(150, 68, "Tenor 2");
                yield return new singer(151, 73, "Tenor 2");
                yield return new singer(152, 69, "Tenor 2");
                yield return new singer(153, 71, "Tenor 2");
                yield return new singer(154, 69, "Tenor 2");
                yield return new singer(155, 76, "Tenor 2");
                yield return new singer(156, 71, "Tenor 2");
                yield return new singer(157, 69, "Tenor 2");
                yield return new singer(158, 71, "Tenor 2");
                yield return new singer(159, 66, "Tenor 2");
                yield return new singer(160, 69, "Tenor 2");
                yield return new singer(161, 71, "Tenor 2");
                yield return new singer(162, 71, "Tenor 2");
                yield return new singer(163, 71, "Tenor 2");
                yield return new singer(164, 69, "Tenor 2");
                yield return new singer(165, 70, "Tenor 2");
                yield return new singer(166, 69, "Tenor 2");
                yield return new singer(167, 68, "Tenor 2");
                yield return new singer(168, 70, "Tenor 2");
                yield return new singer(169, 68, "Tenor 2");
                yield return new singer(170, 69, "Tenor 2");
                yield return new singer(171, 72, "Bass 1");
                yield return new singer(172, 70, "Bass 1");
                yield return new singer(173, 72, "Bass 1");
                yield return new singer(174, 69, "Bass 1");
                yield return new singer(175, 73, "Bass 1");
                yield return new singer(176, 71, "Bass 1");
                yield return new singer(177, 72, "Bass 1");
                yield return new singer(178, 68, "Bass 1");
                yield return new singer(179, 68, "Bass 1");
                yield return new singer(180, 71, "Bass 1");
                yield return new singer(181, 66, "Bass 1");
                yield return new singer(182, 68, "Bass 1");
                yield return new singer(183, 71, "Bass 1");
                yield return new singer(184, 73, "Bass 1");
                yield return new singer(185, 73, "Bass 1");
                yield return new singer(186, 70, "Bass 1");
                yield return new singer(187, 68, "Bass 1");
                yield return new singer(188, 70, "Bass 1");
                yield return new singer(189, 75, "Bass 1");
                yield return new singer(190, 68, "Bass 1");
                yield return new singer(191, 71, "Bass 1");
                yield return new singer(192, 70, "Bass 1");
                yield return new singer(193, 74, "Bass 1");
                yield return new singer(194, 70, "Bass 1");
                yield return new singer(195, 75, "Bass 1");
                yield return new singer(196, 75, "Bass 1");
                yield return new singer(197, 69, "Bass 1");
                yield return new singer(198, 72, "Bass 1");
                yield return new singer(199, 71, "Bass 1");
                yield return new singer(200, 70, "Bass 1");
                yield return new singer(201, 71, "Bass 1");
                yield return new singer(202, 68, "Bass 1");
                yield return new singer(203, 70, "Bass 1");
                yield return new singer(204, 75, "Bass 1");
                yield return new singer(205, 72, "Bass 1");
                yield return new singer(206, 66, "Bass 1");
                yield return new singer(207, 72, "Bass 1");
                yield return new singer(208, 70, "Bass 1");
                yield return new singer(209, 69, "Bass 1");
                yield return new singer(210, 72, "Bass 2");
                yield return new singer(211, 75, "Bass 2");
                yield return new singer(212, 67, "Bass 2");
                yield return new singer(213, 75, "Bass 2");
                yield return new singer(214, 74, "Bass 2");
                yield return new singer(215, 72, "Bass 2");
                yield return new singer(216, 72, "Bass 2");
                yield return new singer(217, 74, "Bass 2");
                yield return new singer(218, 72, "Bass 2");
                yield return new singer(219, 72, "Bass 2");
                yield return new singer(220, 74, "Bass 2");
                yield return new singer(221, 70, "Bass 2");
                yield return new singer(222, 66, "Bass 2");
                yield return new singer(223, 68, "Bass 2");
                yield return new singer(224, 75, "Bass 2");
                yield return new singer(225, 68, "Bass 2");
                yield return new singer(226, 70, "Bass 2");
                yield return new singer(227, 72, "Bass 2");
                yield return new singer(228, 67, "Bass 2");
                yield return new singer(229, 70, "Bass 2");
                yield return new singer(230, 70, "Bass 2");
                yield return new singer(231, 69, "Bass 2");
                yield return new singer(232, 72, "Bass 2");
                yield return new singer(233, 71, "Bass 2");
                yield return new singer(234, 74, "Bass 2");
                yield return new singer(235, 75, "Bass 2");
            }
        }
    }
}
