// ReSharper disable All

namespace Rdatasets.lattice
{
    using System.Collections.Generic;

    /// <summary>
    /// Mortality Rates in US by Cause and Gender
    /// </summary>

    public class USRegionalMortality
    {
        public readonly string Region;
        public readonly string Status;
        public readonly string Sex;
        public readonly string Cause;
        public readonly double Rate;
        public readonly double SE;

        public USRegionalMortality(string Region, string Status, string Sex, string Cause, double Rate, double SE)
        {
            this.Region = Region;
            this.Status = Status;
            this.Sex = Sex;
            this.Cause = Cause;
            this.Rate = Rate;
            this.SE = SE;
        }

        public static IEnumerable<USRegionalMortality> Data
        {
            get
            {
                yield return new USRegionalMortality("HHS Region 01", "Urban", "Male", "Heart disease", 188.2, 1);
                yield return new USRegionalMortality("HHS Region 01", "Rural", "Male", "Heart disease", 199.1, 2.6);
                yield return new USRegionalMortality("HHS Region 01", "Urban", "Female", "Heart disease", 115.1, 0.6);
                yield return new USRegionalMortality("HHS Region 01", "Rural", "Female", "Heart disease", 124.5, 1.7);
                yield return new USRegionalMortality("HHS Region 02", "Urban", "Male", "Heart disease", 226.8, 0.8);
                yield return new USRegionalMortality("HHS Region 02", "Rural", "Male", "Heart disease", 248.8, 3.3);
                yield return new USRegionalMortality("HHS Region 02", "Urban", "Female", "Heart disease", 148.6, 0.5);
                yield return new USRegionalMortality("HHS Region 02", "Rural", "Female", "Heart disease", 165.6, 2.3);
                yield return new USRegionalMortality("HHS Region 03", "Urban", "Male", "Heart disease", 218.2, 0.8);
                yield return new USRegionalMortality("HHS Region 03", "Rural", "Male", "Heart disease", 246, 2);
                yield return new USRegionalMortality("HHS Region 03", "Urban", "Female", "Heart disease", 138.1, 0.5);
                yield return new USRegionalMortality("HHS Region 03", "Rural", "Female", "Heart disease", 162.5, 1.4);
                yield return new USRegionalMortality("HHS Region 04", "Urban", "Male", "Heart disease", 212.8, 0.5);
                yield return new USRegionalMortality("HHS Region 04", "Rural", "Male", "Heart disease", 276.4, 1.3);
                yield return new USRegionalMortality("HHS Region 04", "Urban", "Female", "Heart disease", 132.2, 0.4);
                yield return new USRegionalMortality("HHS Region 04", "Rural", "Female", "Heart disease", 176.8, 0.9);
                yield return new USRegionalMortality("HHS Region 05", "Urban", "Male", "Heart disease", 222.5, 0.6);
                yield return new USRegionalMortality("HHS Region 05", "Rural", "Male", "Heart disease", 229, 1.2);
                yield return new USRegionalMortality("HHS Region 05", "Urban", "Female", "Heart disease", 139.6, 0.4);
                yield return new USRegionalMortality("HHS Region 05", "Rural", "Female", "Heart disease", 140.8, 0.8);
                yield return new USRegionalMortality("HHS Region 06", "Urban", "Male", "Heart disease", 219.9, 0.8);
                yield return new USRegionalMortality("HHS Region 06", "Rural", "Male", "Heart disease", 266.4, 1.6);
                yield return new USRegionalMortality("HHS Region 06", "Urban", "Female", "Heart disease", 140.7, 0.5);
                yield return new USRegionalMortality("HHS Region 06", "Rural", "Female", "Heart disease", 175.7, 1.1);
                yield return new USRegionalMortality("HHS Region 07", "Urban", "Male", "Heart disease", 210, 1.3);
                yield return new USRegionalMortality("HHS Region 07", "Rural", "Male", "Heart disease", 237.7, 1.7);
                yield return new USRegionalMortality("HHS Region 07", "Urban", "Female", "Heart disease", 131.1, 0.9);
                yield return new USRegionalMortality("HHS Region 07", "Rural", "Female", "Heart disease", 152.3, 1.2);
                yield return new USRegionalMortality("HHS Region 08", "Urban", "Male", "Heart disease", 166.5, 1.4);
                yield return new USRegionalMortality("HHS Region 08", "Rural", "Male", "Heart disease", 191.2, 2.1);
                yield return new USRegionalMortality("HHS Region 08", "Urban", "Female", "Heart disease", 106.7, 0.9);
                yield return new USRegionalMortality("HHS Region 08", "Rural", "Female", "Heart disease", 119.8, 1.4);
                yield return new USRegionalMortality("HHS Region 09", "Urban", "Male", "Heart disease", 195.8, 0.6);
                yield return new USRegionalMortality("HHS Region 09", "Rural", "Male", "Heart disease", 205.8, 2.7);
                yield return new USRegionalMortality("HHS Region 09", "Urban", "Female", "Heart disease", 121, 0.4);
                yield return new USRegionalMortality("HHS Region 09", "Rural", "Female", "Heart disease", 125.2, 1.9);
                yield return new USRegionalMortality("HHS Region 10", "Urban", "Male", "Heart disease", 176, 1.1);
                yield return new USRegionalMortality("HHS Region 10", "Rural", "Male", "Heart disease", 194.9, 2.3);
                yield return new USRegionalMortality("HHS Region 10", "Urban", "Female", "Heart disease", 106, 0.7);
                yield return new USRegionalMortality("HHS Region 10", "Rural", "Female", "Heart disease", 114.3, 1.6);
                yield return new USRegionalMortality("HHS Region 01", "Urban", "Male", "Cancer", 194.5, 1);
                yield return new USRegionalMortality("HHS Region 01", "Rural", "Male", "Cancer", 202.7, 2.5);
                yield return new USRegionalMortality("HHS Region 01", "Urban", "Female", "Cancer", 140.3, 0.8);
                yield return new USRegionalMortality("HHS Region 01", "Rural", "Female", "Cancer", 144.7, 2);
                yield return new USRegionalMortality("HHS Region 02", "Urban", "Male", "Cancer", 187.5, 0.7);
                yield return new USRegionalMortality("HHS Region 02", "Rural", "Male", "Cancer", 204.9, 2.9);
                yield return new USRegionalMortality("HHS Region 02", "Urban", "Female", "Cancer", 139.2, 0.5);
                yield return new USRegionalMortality("HHS Region 02", "Rural", "Female", "Cancer", 151.7, 2.3);
                yield return new USRegionalMortality("HHS Region 03", "Urban", "Male", "Cancer", 204.3, 0.7);
                yield return new USRegionalMortality("HHS Region 03", "Rural", "Male", "Cancer", 224.7, 1.9);
                yield return new USRegionalMortality("HHS Region 03", "Urban", "Female", "Cancer", 146.7, 0.5);
                yield return new USRegionalMortality("HHS Region 03", "Rural", "Female", "Cancer", 156.7, 1.4);
                yield return new USRegionalMortality("HHS Region 04", "Urban", "Male", "Cancer", 204.7, 0.5);
                yield return new USRegionalMortality("HHS Region 04", "Rural", "Male", "Cancer", 245.2, 1.2);
                yield return new USRegionalMortality("HHS Region 04", "Urban", "Female", "Cancer", 139.9, 0.4);
                yield return new USRegionalMortality("HHS Region 04", "Rural", "Female", "Cancer", 156.2, 0.8);
                yield return new USRegionalMortality("HHS Region 05", "Urban", "Male", "Cancer", 207.3, 0.6);
                yield return new USRegionalMortality("HHS Region 05", "Rural", "Male", "Cancer", 217.2, 1.1);
                yield return new USRegionalMortality("HHS Region 05", "Urban", "Female", "Cancer", 149.9, 0.4);
                yield return new USRegionalMortality("HHS Region 05", "Rural", "Female", "Cancer", 152, 0.9);
                yield return new USRegionalMortality("HHS Region 06", "Urban", "Male", "Cancer", 201.6, 0.7);
                yield return new USRegionalMortality("HHS Region 06", "Rural", "Male", "Cancer", 223.8, 1.4);
                yield return new USRegionalMortality("HHS Region 06", "Urban", "Female", "Cancer", 137.8, 0.5);
                yield return new USRegionalMortality("HHS Region 06", "Rural", "Female", "Cancer", 151.8, 1.1);
                yield return new USRegionalMortality("HHS Region 07", "Urban", "Male", "Cancer", 204.3, 1.3);
                yield return new USRegionalMortality("HHS Region 07", "Rural", "Male", "Cancer", 214.1, 1.6);
                yield return new USRegionalMortality("HHS Region 07", "Urban", "Female", "Cancer", 148, 1);
                yield return new USRegionalMortality("HHS Region 07", "Rural", "Female", "Cancer", 149.7, 1.3);
                yield return new USRegionalMortality("HHS Region 08", "Urban", "Male", "Cancer", 167, 1.3);
                yield return new USRegionalMortality("HHS Region 08", "Rural", "Male", "Cancer", 173.7, 1.9);
                yield return new USRegionalMortality("HHS Region 08", "Urban", "Female", "Cancer", 122.5, 1);
                yield return new USRegionalMortality("HHS Region 08", "Rural", "Female", "Cancer", 132.6, 1.6);
                yield return new USRegionalMortality("HHS Region 09", "Urban", "Male", "Cancer", 176.1, 0.5);
                yield return new USRegionalMortality("HHS Region 09", "Rural", "Male", "Cancer", 186.7, 2.5);
                yield return new USRegionalMortality("HHS Region 09", "Urban", "Female", "Cancer", 130.1, 0.4);
                yield return new USRegionalMortality("HHS Region 09", "Rural", "Female", "Cancer", 135.7, 2);
                yield return new USRegionalMortality("HHS Region 10", "Urban", "Male", "Cancer", 190.6, 1.1);
                yield return new USRegionalMortality("HHS Region 10", "Rural", "Male", "Cancer", 197.1, 2.3);
                yield return new USRegionalMortality("HHS Region 10", "Urban", "Female", "Cancer", 140.9, 0.9);
                yield return new USRegionalMortality("HHS Region 10", "Rural", "Female", "Cancer", 143.8, 1.9);
                yield return new USRegionalMortality("HHS Region 01", "Urban", "Male", "Lower respiratory", 36.7, 0.5);
                yield return new USRegionalMortality("HHS Region 01", "Rural", "Male", "Lower respiratory", 51.7, 1.3);
                yield return new USRegionalMortality("HHS Region 01", "Urban", "Female", "Lower respiratory", 32.2, 0.4);
                yield return new USRegionalMortality("HHS Region 01", "Rural", "Female", "Lower respiratory", 41.3, 1);
                yield return new USRegionalMortality("HHS Region 02", "Urban", "Male", "Lower respiratory", 33, 0.3);
                yield return new USRegionalMortality("HHS Region 02", "Rural", "Male", "Lower respiratory", 59.3, 1.6);
                yield return new USRegionalMortality("HHS Region 02", "Urban", "Female", "Lower respiratory", 28, 0.2);
                yield return new USRegionalMortality("HHS Region 02", "Rural", "Female", "Lower respiratory", 46.3, 1.2);
                yield return new USRegionalMortality("HHS Region 03", "Urban", "Male", "Lower respiratory", 41.7, 0.3);
                yield return new USRegionalMortality("HHS Region 03", "Rural", "Male", "Lower respiratory", 62.1, 1);
                yield return new USRegionalMortality("HHS Region 03", "Urban", "Female", "Lower respiratory", 34.4, 0.3);
                yield return new USRegionalMortality("HHS Region 03", "Rural", "Female", "Lower respiratory", 46.4, 0.8);
                yield return new USRegionalMortality("HHS Region 04", "Urban", "Male", "Lower respiratory", 48.5, 0.3);
                yield return new USRegionalMortality("HHS Region 04", "Rural", "Male", "Lower respiratory", 70.7, 0.6);
                yield return new USRegionalMortality("HHS Region 04", "Urban", "Female", "Lower respiratory", 39.9, 0.2);
                yield return new USRegionalMortality("HHS Region 04", "Rural", "Female", "Lower respiratory", 51.1, 0.5);
                yield return new USRegionalMortality("HHS Region 05", "Urban", "Male", "Lower respiratory", 48.7, 0.3);
                yield return new USRegionalMortality("HHS Region 05", "Rural", "Male", "Lower respiratory", 59.9, 0.6);
                yield return new USRegionalMortality("HHS Region 05", "Urban", "Female", "Lower respiratory", 40.1, 0.2);
                yield return new USRegionalMortality("HHS Region 05", "Rural", "Female", "Lower respiratory", 44.7, 0.4);
                yield return new USRegionalMortality("HHS Region 06", "Urban", "Male", "Lower respiratory", 49.5, 0.4);
                yield return new USRegionalMortality("HHS Region 06", "Rural", "Male", "Lower respiratory", 65.8, 0.8);
                yield return new USRegionalMortality("HHS Region 06", "Urban", "Female", "Lower respiratory", 39.4, 0.3);
                yield return new USRegionalMortality("HHS Region 06", "Rural", "Female", "Lower respiratory", 50.5, 0.6);
                yield return new USRegionalMortality("HHS Region 07", "Urban", "Male", "Lower respiratory", 54.8, 0.7);
                yield return new USRegionalMortality("HHS Region 07", "Rural", "Male", "Lower respiratory", 65.9, 0.9);
                yield return new USRegionalMortality("HHS Region 07", "Urban", "Female", "Lower respiratory", 44, 0.5);
                yield return new USRegionalMortality("HHS Region 07", "Rural", "Female", "Lower respiratory", 45.6, 0.7);
                yield return new USRegionalMortality("HHS Region 08", "Urban", "Male", "Lower respiratory", 48.9, 0.7);
                yield return new USRegionalMortality("HHS Region 08", "Rural", "Male", "Lower respiratory", 56.1, 1.1);
                yield return new USRegionalMortality("HHS Region 08", "Urban", "Female", "Lower respiratory", 37.1, 0.6);
                yield return new USRegionalMortality("HHS Region 08", "Rural", "Female", "Lower respiratory", 40.2, 0.9);
                yield return new USRegionalMortality("HHS Region 09", "Urban", "Male", "Lower respiratory", 40.6, 0.3);
                yield return new USRegionalMortality("HHS Region 09", "Rural", "Male", "Lower respiratory", 50.7, 1.3);
                yield return new USRegionalMortality("HHS Region 09", "Urban", "Female", "Lower respiratory", 33.7, 0.2);
                yield return new USRegionalMortality("HHS Region 09", "Rural", "Female", "Lower respiratory", 43.6, 1.1);
                yield return new USRegionalMortality("HHS Region 10", "Urban", "Male", "Lower respiratory", 46.3, 0.6);
                yield return new USRegionalMortality("HHS Region 10", "Rural", "Male", "Lower respiratory", 52.3, 1.2);
                yield return new USRegionalMortality("HHS Region 10", "Urban", "Female", "Lower respiratory", 38.4, 0.5);
                yield return new USRegionalMortality("HHS Region 10", "Rural", "Female", "Lower respiratory", 45.3, 1);
                yield return new USRegionalMortality("HHS Region 01", "Urban", "Male", "Unintentional injuries", 47.4, 0.5);
                yield return new USRegionalMortality("HHS Region 01", "Rural", "Male", "Unintentional injuries", 60.5, 1.5);
                yield return new USRegionalMortality("HHS Region 01", "Urban", "Female", "Unintentional injuries", 22.5, 0.3);
                yield return new USRegionalMortality("HHS Region 01", "Rural", "Female", "Unintentional injuries", 28.8, 1);
                yield return new USRegionalMortality("HHS Region 02", "Urban", "Male", "Unintentional injuries", 39.7, 0.3);
                yield return new USRegionalMortality("HHS Region 02", "Rural", "Male", "Unintentional injuries", 49.6, 1.5);
                yield return new USRegionalMortality("HHS Region 02", "Urban", "Female", "Unintentional injuries", 17, 0.2);
                yield return new USRegionalMortality("HHS Region 02", "Rural", "Female", "Unintentional injuries", 23.4, 1);
                yield return new USRegionalMortality("HHS Region 03", "Urban", "Male", "Unintentional injuries", 51.8, 0.4);
                yield return new USRegionalMortality("HHS Region 03", "Rural", "Male", "Unintentional injuries", 77.6, 1.2);
                yield return new USRegionalMortality("HHS Region 03", "Urban", "Female", "Unintentional injuries", 24.3, 0.2);
                yield return new USRegionalMortality("HHS Region 03", "Rural", "Female", "Unintentional injuries", 39.8, 0.9);
                yield return new USRegionalMortality("HHS Region 04", "Urban", "Male", "Unintentional injuries", 56.2, 0.3);
                yield return new USRegionalMortality("HHS Region 04", "Rural", "Male", "Unintentional injuries", 79.1, 0.7);
                yield return new USRegionalMortality("HHS Region 04", "Urban", "Female", "Unintentional injuries", 28.6, 0.2);
                yield return new USRegionalMortality("HHS Region 04", "Rural", "Female", "Unintentional injuries", 41.3, 0.5);
                yield return new USRegionalMortality("HHS Region 05", "Urban", "Male", "Unintentional injuries", 50.9, 0.3);
                yield return new USRegionalMortality("HHS Region 05", "Rural", "Male", "Unintentional injuries", 62.3, 0.7);
                yield return new USRegionalMortality("HHS Region 05", "Urban", "Female", "Unintentional injuries", 25.9, 0.2);
                yield return new USRegionalMortality("HHS Region 05", "Rural", "Female", "Unintentional injuries", 32.3, 0.4);
                yield return new USRegionalMortality("HHS Region 06", "Urban", "Male", "Unintentional injuries", 54.6, 0.4);
                yield return new USRegionalMortality("HHS Region 06", "Rural", "Male", "Unintentional injuries", 77.2, 0.9);
                yield return new USRegionalMortality("HHS Region 06", "Urban", "Female", "Unintentional injuries", 27, 0.2);
                yield return new USRegionalMortality("HHS Region 06", "Rural", "Female", "Unintentional injuries", 39.9, 0.6);
                yield return new USRegionalMortality("HHS Region 07", "Urban", "Male", "Unintentional injuries", 53.4, 0.6);
                yield return new USRegionalMortality("HHS Region 07", "Rural", "Male", "Unintentional injuries", 68.1, 1);
                yield return new USRegionalMortality("HHS Region 07", "Urban", "Female", "Unintentional injuries", 28.7, 0.4);
                yield return new USRegionalMortality("HHS Region 07", "Rural", "Female", "Unintentional injuries", 35.4, 0.7);
                yield return new USRegionalMortality("HHS Region 08", "Urban", "Male", "Unintentional injuries", 55.3, 0.7);
                yield return new USRegionalMortality("HHS Region 08", "Rural", "Male", "Unintentional injuries", 71, 1.3);
                yield return new USRegionalMortality("HHS Region 08", "Urban", "Female", "Unintentional injuries", 32.7, 0.5);
                yield return new USRegionalMortality("HHS Region 08", "Rural", "Female", "Unintentional injuries", 39.2, 0.9);
                yield return new USRegionalMortality("HHS Region 09", "Urban", "Male", "Unintentional injuries", 41.8, 0.2);
                yield return new USRegionalMortality("HHS Region 09", "Rural", "Male", "Unintentional injuries", 79.1, 1.8);
                yield return new USRegionalMortality("HHS Region 09", "Urban", "Female", "Unintentional injuries", 20.5, 0.2);
                yield return new USRegionalMortality("HHS Region 09", "Rural", "Female", "Unintentional injuries", 40.9, 1.3);
                yield return new USRegionalMortality("HHS Region 10", "Urban", "Male", "Unintentional injuries", 49.8, 0.6);
                yield return new USRegionalMortality("HHS Region 10", "Rural", "Male", "Unintentional injuries", 66.2, 1.5);
                yield return new USRegionalMortality("HHS Region 10", "Urban", "Female", "Unintentional injuries", 28.4, 0.4);
                yield return new USRegionalMortality("HHS Region 10", "Rural", "Female", "Unintentional injuries", 37.2, 1.1);
                yield return new USRegionalMortality("HHS Region 01", "Urban", "Male", "Cerebrovascular diseases", 28.4, 0.4);
                yield return new USRegionalMortality("HHS Region 01", "Rural", "Male", "Cerebrovascular diseases", 31.2, 1);
                yield return new USRegionalMortality("HHS Region 01", "Urban", "Female", "Cerebrovascular diseases", 28.5, 0.3);
                yield return new USRegionalMortality("HHS Region 01", "Rural", "Female", "Cerebrovascular diseases", 33.6, 0.9);
                yield return new USRegionalMortality("HHS Region 02", "Urban", "Male", "Cerebrovascular diseases", 29.2, 0.3);
                yield return new USRegionalMortality("HHS Region 02", "Rural", "Male", "Cerebrovascular diseases", 32.9, 1.2);
                yield return new USRegionalMortality("HHS Region 02", "Urban", "Female", "Cerebrovascular diseases", 27.2, 0.2);
                yield return new USRegionalMortality("HHS Region 02", "Rural", "Female", "Cerebrovascular diseases", 32.2, 1);
                yield return new USRegionalMortality("HHS Region 03", "Urban", "Male", "Cerebrovascular diseases", 38.2, 0.3);
                yield return new USRegionalMortality("HHS Region 03", "Rural", "Male", "Cerebrovascular diseases", 42.5, 0.8);
                yield return new USRegionalMortality("HHS Region 03", "Urban", "Female", "Cerebrovascular diseases", 37.4, 0.3);
                yield return new USRegionalMortality("HHS Region 03", "Rural", "Female", "Cerebrovascular diseases", 42.1, 0.7);
                yield return new USRegionalMortality("HHS Region 04", "Urban", "Male", "Cerebrovascular diseases", 37.5, 0.2);
                yield return new USRegionalMortality("HHS Region 04", "Rural", "Male", "Cerebrovascular diseases", 49.1, 0.5);
                yield return new USRegionalMortality("HHS Region 04", "Urban", "Female", "Cerebrovascular diseases", 36.4, 0.2);
                yield return new USRegionalMortality("HHS Region 04", "Rural", "Female", "Cerebrovascular diseases", 46.6, 0.4);
                yield return new USRegionalMortality("HHS Region 05", "Urban", "Male", "Cerebrovascular diseases", 38.3, 0.3);
                yield return new USRegionalMortality("HHS Region 05", "Rural", "Male", "Cerebrovascular diseases", 40.6, 0.5);
                yield return new USRegionalMortality("HHS Region 05", "Urban", "Female", "Cerebrovascular diseases", 36.5, 0.2);
                yield return new USRegionalMortality("HHS Region 05", "Rural", "Female", "Cerebrovascular diseases", 40.1, 0.4);
                yield return new USRegionalMortality("HHS Region 06", "Urban", "Male", "Cerebrovascular diseases", 41.4, 0.4);
                yield return new USRegionalMortality("HHS Region 06", "Rural", "Male", "Cerebrovascular diseases", 45.9, 0.7);
                yield return new USRegionalMortality("HHS Region 06", "Urban", "Female", "Cerebrovascular diseases", 39.6, 0.3);
                yield return new USRegionalMortality("HHS Region 06", "Rural", "Female", "Cerebrovascular diseases", 47.2, 0.6);
                yield return new USRegionalMortality("HHS Region 07", "Urban", "Male", "Cerebrovascular diseases", 38, 0.6);
                yield return new USRegionalMortality("HHS Region 07", "Rural", "Male", "Cerebrovascular diseases", 39.2, 0.7);
                yield return new USRegionalMortality("HHS Region 07", "Urban", "Female", "Cerebrovascular diseases", 37.3, 0.5);
                yield return new USRegionalMortality("HHS Region 07", "Rural", "Female", "Cerebrovascular diseases", 40.1, 0.6);
                yield return new USRegionalMortality("HHS Region 08", "Urban", "Male", "Cerebrovascular diseases", 33.7, 0.6);
                yield return new USRegionalMortality("HHS Region 08", "Rural", "Male", "Cerebrovascular diseases", 36.2, 0.9);
                yield return new USRegionalMortality("HHS Region 08", "Urban", "Female", "Cerebrovascular diseases", 34.3, 0.5);
                yield return new USRegionalMortality("HHS Region 08", "Rural", "Female", "Cerebrovascular diseases", 38, 0.8);
                yield return new USRegionalMortality("HHS Region 09", "Urban", "Male", "Cerebrovascular diseases", 34.5, 0.2);
                yield return new USRegionalMortality("HHS Region 09", "Rural", "Male", "Cerebrovascular diseases", 36.6, 1.1);
                yield return new USRegionalMortality("HHS Region 09", "Urban", "Female", "Cerebrovascular diseases", 34, 0.2);
                yield return new USRegionalMortality("HHS Region 09", "Rural", "Female", "Cerebrovascular diseases", 37.5, 1);
                yield return new USRegionalMortality("HHS Region 10", "Urban", "Male", "Cerebrovascular diseases", 36.8, 0.5);
                yield return new USRegionalMortality("HHS Region 10", "Rural", "Male", "Cerebrovascular diseases", 37.1, 1);
                yield return new USRegionalMortality("HHS Region 10", "Urban", "Female", "Cerebrovascular diseases", 35.2, 0.4);
                yield return new USRegionalMortality("HHS Region 10", "Rural", "Female", "Cerebrovascular diseases", 40.3, 1);
                yield return new USRegionalMortality("HHS Region 01", "Urban", "Male", "Alzheimers", 16.4, 0.3);
                yield return new USRegionalMortality("HHS Region 01", "Rural", "Male", "Alzheimers", 18.1, 0.8);
                yield return new USRegionalMortality("HHS Region 01", "Urban", "Female", "Alzheimers", 21.8, 0.3);
                yield return new USRegionalMortality("HHS Region 01", "Rural", "Female", "Alzheimers", 27.9, 0.8);
                yield return new USRegionalMortality("HHS Region 02", "Urban", "Male", "Alzheimers", 10.5, 0.2);
                yield return new USRegionalMortality("HHS Region 02", "Rural", "Male", "Alzheimers", 12.3, 0.7);
                yield return new USRegionalMortality("HHS Region 02", "Urban", "Female", "Alzheimers", 13.6, 0.1);
                yield return new USRegionalMortality("HHS Region 02", "Rural", "Female", "Alzheimers", 17.9, 0.7);
                yield return new USRegionalMortality("HHS Region 03", "Urban", "Male", "Alzheimers", 15.2, 0.2);
                yield return new USRegionalMortality("HHS Region 03", "Rural", "Male", "Alzheimers", 17.9, 0.6);
                yield return new USRegionalMortality("HHS Region 03", "Urban", "Female", "Alzheimers", 19.9, 0.2);
                yield return new USRegionalMortality("HHS Region 03", "Rural", "Female", "Alzheimers", 26.2, 0.5);
                yield return new USRegionalMortality("HHS Region 04", "Urban", "Male", "Alzheimers", 18.3, 0.2);
                yield return new USRegionalMortality("HHS Region 04", "Rural", "Male", "Alzheimers", 25.3, 0.4);
                yield return new USRegionalMortality("HHS Region 04", "Urban", "Female", "Alzheimers", 25.8, 0.2);
                yield return new USRegionalMortality("HHS Region 04", "Rural", "Female", "Alzheimers", 35.2, 0.4);
                yield return new USRegionalMortality("HHS Region 05", "Urban", "Male", "Alzheimers", 20, 0.2);
                yield return new USRegionalMortality("HHS Region 05", "Rural", "Male", "Alzheimers", 20.9, 0.4);
                yield return new USRegionalMortality("HHS Region 05", "Urban", "Female", "Alzheimers", 26, 0.2);
                yield return new USRegionalMortality("HHS Region 05", "Rural", "Female", "Alzheimers", 29.2, 0.3);
                yield return new USRegionalMortality("HHS Region 06", "Urban", "Male", "Alzheimers", 20.7, 0.3);
                yield return new USRegionalMortality("HHS Region 06", "Rural", "Male", "Alzheimers", 22.5, 0.5);
                yield return new USRegionalMortality("HHS Region 06", "Urban", "Female", "Alzheimers", 27.7, 0.2);
                yield return new USRegionalMortality("HHS Region 06", "Rural", "Female", "Alzheimers", 33, 0.5);
                yield return new USRegionalMortality("HHS Region 07", "Urban", "Male", "Alzheimers", 21, 0.4);
                yield return new USRegionalMortality("HHS Region 07", "Rural", "Male", "Alzheimers", 23.8, 0.5);
                yield return new USRegionalMortality("HHS Region 07", "Urban", "Female", "Alzheimers", 27.8, 0.4);
                yield return new USRegionalMortality("HHS Region 07", "Rural", "Female", "Alzheimers", 30.3, 0.5);
                yield return new USRegionalMortality("HHS Region 08", "Urban", "Male", "Alzheimers", 23.7, 0.5);
                yield return new USRegionalMortality("HHS Region 08", "Rural", "Male", "Alzheimers", 21.2, 0.7);
                yield return new USRegionalMortality("HHS Region 08", "Urban", "Female", "Alzheimers", 30.9, 0.5);
                yield return new USRegionalMortality("HHS Region 08", "Rural", "Female", "Alzheimers", 28.3, 0.7);
                yield return new USRegionalMortality("HHS Region 09", "Urban", "Male", "Alzheimers", 24.9, 0.2);
                yield return new USRegionalMortality("HHS Region 09", "Rural", "Male", "Alzheimers", 18.9, 0.8);
                yield return new USRegionalMortality("HHS Region 09", "Urban", "Female", "Alzheimers", 32.1, 0.2);
                yield return new USRegionalMortality("HHS Region 09", "Rural", "Female", "Alzheimers", 24, 0.8);
                yield return new USRegionalMortality("HHS Region 10", "Urban", "Male", "Alzheimers", 29.9, 0.5);
                yield return new USRegionalMortality("HHS Region 10", "Rural", "Male", "Alzheimers", 22.9, 0.8);
                yield return new USRegionalMortality("HHS Region 10", "Urban", "Female", "Alzheimers", 40.8, 0.4);
                yield return new USRegionalMortality("HHS Region 10", "Rural", "Female", "Alzheimers", 33.9, 0.9);
                yield return new USRegionalMortality("HHS Region 01", "Urban", "Male", "Diabetes", 19.2, 0.3);
                yield return new USRegionalMortality("HHS Region 01", "Rural", "Male", "Diabetes", 23.8, 0.9);
                yield return new USRegionalMortality("HHS Region 01", "Urban", "Female", "Diabetes", 12.1, 0.2);
                yield return new USRegionalMortality("HHS Region 01", "Rural", "Female", "Diabetes", 15, 0.6);
                yield return new USRegionalMortality("HHS Region 02", "Urban", "Male", "Diabetes", 22.7, 0.2);
                yield return new USRegionalMortality("HHS Region 02", "Rural", "Male", "Diabetes", 24.5, 1);
                yield return new USRegionalMortality("HHS Region 02", "Urban", "Female", "Diabetes", 15.2, 0.2);
                yield return new USRegionalMortality("HHS Region 02", "Rural", "Female", "Diabetes", 17.6, 0.8);
                yield return new USRegionalMortality("HHS Region 03", "Urban", "Male", "Diabetes", 25, 0.3);
                yield return new USRegionalMortality("HHS Region 03", "Rural", "Male", "Diabetes", 32.5, 0.7);
                yield return new USRegionalMortality("HHS Region 03", "Urban", "Female", "Diabetes", 17.2, 0.2);
                yield return new USRegionalMortality("HHS Region 03", "Rural", "Female", "Diabetes", 24.1, 0.6);
                yield return new USRegionalMortality("HHS Region 04", "Urban", "Male", "Diabetes", 25.2, 0.2);
                yield return new USRegionalMortality("HHS Region 04", "Rural", "Male", "Diabetes", 32, 0.4);
                yield return new USRegionalMortality("HHS Region 04", "Urban", "Female", "Diabetes", 17.4, 0.1);
                yield return new USRegionalMortality("HHS Region 04", "Rural", "Female", "Diabetes", 25, 0.3);
                yield return new USRegionalMortality("HHS Region 05", "Urban", "Male", "Diabetes", 26.6, 0.2);
                yield return new USRegionalMortality("HHS Region 05", "Rural", "Male", "Diabetes", 28.5, 0.4);
                yield return new USRegionalMortality("HHS Region 05", "Urban", "Female", "Diabetes", 18.6, 0.2);
                yield return new USRegionalMortality("HHS Region 05", "Rural", "Female", "Diabetes", 20.3, 0.3);
                yield return new USRegionalMortality("HHS Region 06", "Urban", "Male", "Diabetes", 26.2, 0.3);
                yield return new USRegionalMortality("HHS Region 06", "Rural", "Male", "Diabetes", 32.8, 0.5);
                yield return new USRegionalMortality("HHS Region 06", "Urban", "Female", "Diabetes", 19.9, 0.2);
                yield return new USRegionalMortality("HHS Region 06", "Rural", "Female", "Diabetes", 25.1, 0.4);
                yield return new USRegionalMortality("HHS Region 07", "Urban", "Male", "Diabetes", 22.6, 0.4);
                yield return new USRegionalMortality("HHS Region 07", "Rural", "Male", "Diabetes", 25.9, 0.6);
                yield return new USRegionalMortality("HHS Region 07", "Urban", "Female", "Diabetes", 16, 0.3);
                yield return new USRegionalMortality("HHS Region 07", "Rural", "Female", "Diabetes", 19.1, 0.4);
                yield return new USRegionalMortality("HHS Region 08", "Urban", "Male", "Diabetes", 23.2, 0.5);
                yield return new USRegionalMortality("HHS Region 08", "Rural", "Male", "Diabetes", 24.7, 0.7);
                yield return new USRegionalMortality("HHS Region 08", "Urban", "Female", "Diabetes", 15, 0.4);
                yield return new USRegionalMortality("HHS Region 08", "Rural", "Female", "Diabetes", 18, 0.6);
                yield return new USRegionalMortality("HHS Region 09", "Urban", "Male", "Diabetes", 25.3, 0.2);
                yield return new USRegionalMortality("HHS Region 09", "Rural", "Male", "Diabetes", 24.9, 0.9);
                yield return new USRegionalMortality("HHS Region 09", "Urban", "Female", "Diabetes", 16.7, 0.1);
                yield return new USRegionalMortality("HHS Region 09", "Rural", "Female", "Diabetes", 17.8, 0.7);
                yield return new USRegionalMortality("HHS Region 10", "Urban", "Male", "Diabetes", 28.2, 0.4);
                yield return new USRegionalMortality("HHS Region 10", "Rural", "Male", "Diabetes", 29.8, 0.9);
                yield return new USRegionalMortality("HHS Region 10", "Urban", "Female", "Diabetes", 17.7, 0.3);
                yield return new USRegionalMortality("HHS Region 10", "Rural", "Female", "Diabetes", 20.1, 0.7);
                yield return new USRegionalMortality("HHS Region 01", "Urban", "Male", "Flu and pneumonia", 18.5, 0.3);
                yield return new USRegionalMortality("HHS Region 01", "Rural", "Male", "Flu and pneumonia", 15.6, 0.7);
                yield return new USRegionalMortality("HHS Region 01", "Urban", "Female", "Flu and pneumonia", 12.8, 0.2);
                yield return new USRegionalMortality("HHS Region 01", "Rural", "Female", "Flu and pneumonia", 11.9, 0.5);
                yield return new USRegionalMortality("HHS Region 02", "Urban", "Male", "Flu and pneumonia", 22.4, 0.2);
                yield return new USRegionalMortality("HHS Region 02", "Rural", "Male", "Flu and pneumonia", 19.6, 0.9);
                yield return new USRegionalMortality("HHS Region 02", "Urban", "Female", "Flu and pneumonia", 14.5, 0.2);
                yield return new USRegionalMortality("HHS Region 02", "Rural", "Female", "Flu and pneumonia", 14.9, 0.7);
                yield return new USRegionalMortality("HHS Region 03", "Urban", "Male", "Flu and pneumonia", 18.9, 0.2);
                yield return new USRegionalMortality("HHS Region 03", "Rural", "Male", "Flu and pneumonia", 22.8, 0.6);
                yield return new USRegionalMortality("HHS Region 03", "Urban", "Female", "Flu and pneumonia", 13.3, 0.2);
                yield return new USRegionalMortality("HHS Region 03", "Rural", "Female", "Flu and pneumonia", 17.1, 0.5);
                yield return new USRegionalMortality("HHS Region 04", "Urban", "Male", "Flu and pneumonia", 15.5, 0.1);
                yield return new USRegionalMortality("HHS Region 04", "Rural", "Male", "Flu and pneumonia", 24.1, 0.4);
                yield return new USRegionalMortality("HHS Region 04", "Urban", "Female", "Flu and pneumonia", 11.6, 0.1);
                yield return new USRegionalMortality("HHS Region 04", "Rural", "Female", "Flu and pneumonia", 19, 0.3);
                yield return new USRegionalMortality("HHS Region 05", "Urban", "Male", "Flu and pneumonia", 17.8, 0.2);
                yield return new USRegionalMortality("HHS Region 05", "Rural", "Male", "Flu and pneumonia", 18.8, 0.3);
                yield return new USRegionalMortality("HHS Region 05", "Urban", "Female", "Flu and pneumonia", 12.9, 0.1);
                yield return new USRegionalMortality("HHS Region 05", "Rural", "Female", "Flu and pneumonia", 14.1, 0.2);
                yield return new USRegionalMortality("HHS Region 06", "Urban", "Male", "Flu and pneumonia", 16.6, 0.2);
                yield return new USRegionalMortality("HHS Region 06", "Rural", "Male", "Flu and pneumonia", 23.1, 0.5);
                yield return new USRegionalMortality("HHS Region 06", "Urban", "Female", "Flu and pneumonia", 12.8, 0.2);
                yield return new USRegionalMortality("HHS Region 06", "Rural", "Female", "Flu and pneumonia", 18.1, 0.4);
                yield return new USRegionalMortality("HHS Region 07", "Urban", "Male", "Flu and pneumonia", 18.6, 0.4);
                yield return new USRegionalMortality("HHS Region 07", "Rural", "Male", "Flu and pneumonia", 21.1, 0.5);
                yield return new USRegionalMortality("HHS Region 07", "Urban", "Female", "Flu and pneumonia", 14.4, 0.3);
                yield return new USRegionalMortality("HHS Region 07", "Rural", "Female", "Flu and pneumonia", 17.3, 0.4);
                yield return new USRegionalMortality("HHS Region 08", "Urban", "Male", "Flu and pneumonia", 15.3, 0.4);
                yield return new USRegionalMortality("HHS Region 08", "Rural", "Male", "Flu and pneumonia", 18.1, 0.7);
                yield return new USRegionalMortality("HHS Region 08", "Urban", "Female", "Flu and pneumonia", 11.6, 0.3);
                yield return new USRegionalMortality("HHS Region 08", "Rural", "Female", "Flu and pneumonia", 14.6, 0.5);
                yield return new USRegionalMortality("HHS Region 09", "Urban", "Male", "Flu and pneumonia", 18.5, 0.2);
                yield return new USRegionalMortality("HHS Region 09", "Rural", "Male", "Flu and pneumonia", 19.1, 0.8);
                yield return new USRegionalMortality("HHS Region 09", "Urban", "Female", "Flu and pneumonia", 13.4, 0.1);
                yield return new USRegionalMortality("HHS Region 09", "Rural", "Female", "Flu and pneumonia", 14.9, 0.7);
                yield return new USRegionalMortality("HHS Region 10", "Urban", "Male", "Flu and pneumonia", 11.6, 0.3);
                yield return new USRegionalMortality("HHS Region 10", "Rural", "Male", "Flu and pneumonia", 12.7, 0.6);
                yield return new USRegionalMortality("HHS Region 10", "Urban", "Female", "Flu and pneumonia", 8.8, 0.2);
                yield return new USRegionalMortality("HHS Region 10", "Rural", "Female", "Flu and pneumonia", 10.5, 0.5);
                yield return new USRegionalMortality("HHS Region 01", "Urban", "Male", "Suicide", 15.2, 0.3);
                yield return new USRegionalMortality("HHS Region 01", "Rural", "Male", "Suicide", 25.6, 1);
                yield return new USRegionalMortality("HHS Region 01", "Urban", "Female", "Suicide", 4.5, 0.2);
                yield return new USRegionalMortality("HHS Region 01", "Rural", "Female", "Suicide", 5.8, 0.5);
                yield return new USRegionalMortality("HHS Region 02", "Urban", "Male", "Suicide", 12.6, 0.2);
                yield return new USRegionalMortality("HHS Region 02", "Rural", "Male", "Suicide", 20.3, 1);
                yield return new USRegionalMortality("HHS Region 02", "Urban", "Female", "Suicide", 3.4, 0.1);
                yield return new USRegionalMortality("HHS Region 02", "Rural", "Female", "Suicide", 3.9, 0.4);
                yield return new USRegionalMortality("HHS Region 03", "Urban", "Male", "Suicide", 19.1, 0.2);
                yield return new USRegionalMortality("HHS Region 03", "Rural", "Male", "Suicide", 26.9, 0.7);
                yield return new USRegionalMortality("HHS Region 03", "Urban", "Female", "Suicide", 4.8, 0.1);
                yield return new USRegionalMortality("HHS Region 03", "Rural", "Female", "Suicide", 6.6, 0.4);
                yield return new USRegionalMortality("HHS Region 04", "Urban", "Male", "Suicide", 21.5, 0.2);
                yield return new USRegionalMortality("HHS Region 04", "Rural", "Male", "Suicide", 24.6, 0.4);
                yield return new USRegionalMortality("HHS Region 04", "Urban", "Female", "Suicide", 5.9, 0.1);
                yield return new USRegionalMortality("HHS Region 04", "Rural", "Female", "Suicide", 6, 0.2);
                yield return new USRegionalMortality("HHS Region 05", "Urban", "Male", "Suicide", 18.8, 0.2);
                yield return new USRegionalMortality("HHS Region 05", "Rural", "Male", "Suicide", 23.4, 0.4);
                yield return new USRegionalMortality("HHS Region 05", "Urban", "Female", "Suicide", 4.9, 0.1);
                yield return new USRegionalMortality("HHS Region 05", "Rural", "Female", "Suicide", 5.1, 0.2);
                yield return new USRegionalMortality("HHS Region 06", "Urban", "Male", "Suicide", 20.2, 0.2);
                yield return new USRegionalMortality("HHS Region 06", "Rural", "Male", "Suicide", 27.2, 0.5);
                yield return new USRegionalMortality("HHS Region 06", "Urban", "Female", "Suicide", 5.3, 0.1);
                yield return new USRegionalMortality("HHS Region 06", "Rural", "Female", "Suicide", 6.4, 0.3);
                yield return new USRegionalMortality("HHS Region 07", "Urban", "Male", "Suicide", 22.5, 0.4);
                yield return new USRegionalMortality("HHS Region 07", "Rural", "Male", "Suicide", 26, 0.6);
                yield return new USRegionalMortality("HHS Region 07", "Urban", "Female", "Suicide", 5.8, 0.2);
                yield return new USRegionalMortality("HHS Region 07", "Rural", "Female", "Suicide", 5.8, 0.3);
                yield return new USRegionalMortality("HHS Region 08", "Urban", "Male", "Suicide", 29.1, 0.5);
                yield return new USRegionalMortality("HHS Region 08", "Rural", "Male", "Suicide", 34.3, 0.9);
                yield return new USRegionalMortality("HHS Region 08", "Urban", "Female", "Suicide", 8.7, 0.3);
                yield return new USRegionalMortality("HHS Region 08", "Rural", "Female", "Suicide", 8.4, 0.5);
                yield return new USRegionalMortality("HHS Region 09", "Urban", "Male", "Suicide", 17.9, 0.2);
                yield return new USRegionalMortality("HHS Region 09", "Rural", "Male", "Suicide", 35.4, 1.2);
                yield return new USRegionalMortality("HHS Region 09", "Urban", "Female", "Suicide", 5.2, 0.1);
                yield return new USRegionalMortality("HHS Region 09", "Rural", "Female", "Suicide", 9.7, 0.7);
                yield return new USRegionalMortality("HHS Region 10", "Urban", "Male", "Suicide", 24, 0.4);
                yield return new USRegionalMortality("HHS Region 10", "Rural", "Male", "Suicide", 32.2, 1);
                yield return new USRegionalMortality("HHS Region 10", "Urban", "Female", "Suicide", 7, 0.2);
                yield return new USRegionalMortality("HHS Region 10", "Rural", "Female", "Suicide", 8.6, 0.5);
                yield return new USRegionalMortality("HHS Region 01", "Urban", "Male", "Nephritis", 18.1, 0.3);
                yield return new USRegionalMortality("HHS Region 01", "Rural", "Male", "Nephritis", 13, 0.7);
                yield return new USRegionalMortality("HHS Region 01", "Urban", "Female", "Nephritis", 10.9, 0.2);
                yield return new USRegionalMortality("HHS Region 01", "Rural", "Female", "Nephritis", 8.8, 0.5);
                yield return new USRegionalMortality("HHS Region 02", "Urban", "Male", "Nephritis", 14.5, 0.2);
                yield return new USRegionalMortality("HHS Region 02", "Rural", "Male", "Nephritis", 14.4, 0.8);
                yield return new USRegionalMortality("HHS Region 02", "Urban", "Female", "Nephritis", 8.6, 0.1);
                yield return new USRegionalMortality("HHS Region 02", "Rural", "Female", "Nephritis", 11.6, 0.6);
                yield return new USRegionalMortality("HHS Region 03", "Urban", "Male", "Nephritis", 18.8, 0.2);
                yield return new USRegionalMortality("HHS Region 03", "Rural", "Male", "Nephritis", 22.4, 0.6);
                yield return new USRegionalMortality("HHS Region 03", "Urban", "Female", "Nephritis", 13, 0.2);
                yield return new USRegionalMortality("HHS Region 03", "Rural", "Female", "Nephritis", 17, 0.5);
                yield return new USRegionalMortality("HHS Region 04", "Urban", "Male", "Nephritis", 17.2, 0.2);
                yield return new USRegionalMortality("HHS Region 04", "Rural", "Male", "Nephritis", 22.6, 0.4);
                yield return new USRegionalMortality("HHS Region 04", "Urban", "Female", "Nephritis", 11.7, 0.1);
                yield return new USRegionalMortality("HHS Region 04", "Rural", "Female", "Nephritis", 17.3, 0.3);
                yield return new USRegionalMortality("HHS Region 05", "Urban", "Male", "Nephritis", 18.5, 0.2);
                yield return new USRegionalMortality("HHS Region 05", "Rural", "Male", "Nephritis", 17.9, 0.3);
                yield return new USRegionalMortality("HHS Region 05", "Urban", "Female", "Nephritis", 12.9, 0.1);
                yield return new USRegionalMortality("HHS Region 05", "Rural", "Female", "Nephritis", 12.8, 0.2);
                yield return new USRegionalMortality("HHS Region 06", "Urban", "Male", "Nephritis", 19.4, 0.2);
                yield return new USRegionalMortality("HHS Region 06", "Rural", "Male", "Nephritis", 21.5, 0.4);
                yield return new USRegionalMortality("HHS Region 06", "Urban", "Female", "Nephritis", 14.3, 0.2);
                yield return new USRegionalMortality("HHS Region 06", "Rural", "Female", "Nephritis", 16.7, 0.3);
                yield return new USRegionalMortality("HHS Region 07", "Urban", "Male", "Nephritis", 18.1, 0.4);
                yield return new USRegionalMortality("HHS Region 07", "Rural", "Male", "Nephritis", 16.5, 0.5);
                yield return new USRegionalMortality("HHS Region 07", "Urban", "Female", "Nephritis", 12.3, 0.3);
                yield return new USRegionalMortality("HHS Region 07", "Rural", "Female", "Nephritis", 12.5, 0.3);
                yield return new USRegionalMortality("HHS Region 08", "Urban", "Male", "Nephritis", 12.9, 0.4);
                yield return new USRegionalMortality("HHS Region 08", "Rural", "Male", "Nephritis", 10.8, 0.5);
                yield return new USRegionalMortality("HHS Region 08", "Urban", "Female", "Nephritis", 8.3, 0.3);
                yield return new USRegionalMortality("HHS Region 08", "Rural", "Female", "Nephritis", 8.5, 0.4);
                yield return new USRegionalMortality("HHS Region 09", "Urban", "Male", "Nephritis", 9, 0.1);
                yield return new USRegionalMortality("HHS Region 09", "Rural", "Male", "Nephritis", 12.6, 0.7);
                yield return new USRegionalMortality("HHS Region 09", "Urban", "Female", "Nephritis", 6.1, 0.1);
                yield return new USRegionalMortality("HHS Region 09", "Rural", "Female", "Nephritis", 8.4, 0.5);
                yield return new USRegionalMortality("HHS Region 10", "Urban", "Male", "Nephritis", 8.6, 0.3);
                yield return new USRegionalMortality("HHS Region 10", "Rural", "Male", "Nephritis", 8.6, 0.5);
                yield return new USRegionalMortality("HHS Region 10", "Urban", "Female", "Nephritis", 5.9, 0.2);
                yield return new USRegionalMortality("HHS Region 10", "Rural", "Female", "Nephritis", 6.7, 0.4);
            }
        }
    }
}
