// ReSharper disable All

namespace Rdatasets.HSAUR
{
    using System.Collections.Generic;

    /// <summary>
    /// Age of Onset of Schizophrenia Data
    /// </summary>

    public class schizophrenia
    {
        public readonly int κ;
        public readonly int age;
        public readonly string gender;

        public schizophrenia(int κ, int age, string gender)
        {
            this.κ = κ;
            this.age = age;
            this.gender = gender;
        }

        public static IEnumerable<schizophrenia> Data
        {
            get
            {
                yield return new schizophrenia(1, 20, "female");
                yield return new schizophrenia(2, 30, "female");
                yield return new schizophrenia(3, 21, "female");
                yield return new schizophrenia(4, 23, "female");
                yield return new schizophrenia(5, 30, "female");
                yield return new schizophrenia(6, 25, "female");
                yield return new schizophrenia(7, 13, "female");
                yield return new schizophrenia(8, 19, "female");
                yield return new schizophrenia(9, 16, "female");
                yield return new schizophrenia(10, 25, "female");
                yield return new schizophrenia(11, 20, "female");
                yield return new schizophrenia(12, 25, "female");
                yield return new schizophrenia(13, 27, "female");
                yield return new schizophrenia(14, 43, "female");
                yield return new schizophrenia(15, 6, "female");
                yield return new schizophrenia(16, 21, "female");
                yield return new schizophrenia(17, 15, "female");
                yield return new schizophrenia(18, 26, "female");
                yield return new schizophrenia(19, 23, "female");
                yield return new schizophrenia(20, 21, "female");
                yield return new schizophrenia(21, 23, "female");
                yield return new schizophrenia(22, 23, "female");
                yield return new schizophrenia(23, 34, "female");
                yield return new schizophrenia(24, 14, "female");
                yield return new schizophrenia(25, 17, "female");
                yield return new schizophrenia(26, 18, "female");
                yield return new schizophrenia(27, 21, "female");
                yield return new schizophrenia(28, 16, "female");
                yield return new schizophrenia(29, 35, "female");
                yield return new schizophrenia(30, 32, "female");
                yield return new schizophrenia(31, 48, "female");
                yield return new schizophrenia(32, 53, "female");
                yield return new schizophrenia(33, 51, "female");
                yield return new schizophrenia(34, 48, "female");
                yield return new schizophrenia(35, 29, "female");
                yield return new schizophrenia(36, 25, "female");
                yield return new schizophrenia(37, 44, "female");
                yield return new schizophrenia(38, 23, "female");
                yield return new schizophrenia(39, 36, "female");
                yield return new schizophrenia(40, 58, "female");
                yield return new schizophrenia(41, 28, "female");
                yield return new schizophrenia(42, 51, "female");
                yield return new schizophrenia(43, 40, "female");
                yield return new schizophrenia(44, 43, "female");
                yield return new schizophrenia(45, 21, "female");
                yield return new schizophrenia(46, 48, "female");
                yield return new schizophrenia(47, 17, "female");
                yield return new schizophrenia(48, 23, "female");
                yield return new schizophrenia(49, 28, "female");
                yield return new schizophrenia(50, 44, "female");
                yield return new schizophrenia(51, 28, "female");
                yield return new schizophrenia(52, 21, "female");
                yield return new schizophrenia(53, 31, "female");
                yield return new schizophrenia(54, 22, "female");
                yield return new schizophrenia(55, 56, "female");
                yield return new schizophrenia(56, 60, "female");
                yield return new schizophrenia(57, 15, "female");
                yield return new schizophrenia(58, 21, "female");
                yield return new schizophrenia(59, 30, "female");
                yield return new schizophrenia(60, 26, "female");
                yield return new schizophrenia(61, 28, "female");
                yield return new schizophrenia(62, 23, "female");
                yield return new schizophrenia(63, 21, "female");
                yield return new schizophrenia(64, 20, "female");
                yield return new schizophrenia(65, 43, "female");
                yield return new schizophrenia(66, 39, "female");
                yield return new schizophrenia(67, 40, "female");
                yield return new schizophrenia(68, 26, "female");
                yield return new schizophrenia(69, 50, "female");
                yield return new schizophrenia(70, 17, "female");
                yield return new schizophrenia(71, 17, "female");
                yield return new schizophrenia(72, 23, "female");
                yield return new schizophrenia(73, 44, "female");
                yield return new schizophrenia(74, 30, "female");
                yield return new schizophrenia(75, 35, "female");
                yield return new schizophrenia(76, 20, "female");
                yield return new schizophrenia(77, 41, "female");
                yield return new schizophrenia(78, 18, "female");
                yield return new schizophrenia(79, 39, "female");
                yield return new schizophrenia(80, 27, "female");
                yield return new schizophrenia(81, 28, "female");
                yield return new schizophrenia(82, 30, "female");
                yield return new schizophrenia(83, 34, "female");
                yield return new schizophrenia(84, 33, "female");
                yield return new schizophrenia(85, 30, "female");
                yield return new schizophrenia(86, 29, "female");
                yield return new schizophrenia(87, 46, "female");
                yield return new schizophrenia(88, 36, "female");
                yield return new schizophrenia(89, 58, "female");
                yield return new schizophrenia(90, 28, "female");
                yield return new schizophrenia(91, 30, "female");
                yield return new schizophrenia(92, 28, "female");
                yield return new schizophrenia(93, 37, "female");
                yield return new schizophrenia(94, 31, "female");
                yield return new schizophrenia(95, 29, "female");
                yield return new schizophrenia(96, 32, "female");
                yield return new schizophrenia(97, 48, "female");
                yield return new schizophrenia(98, 49, "female");
                yield return new schizophrenia(99, 30, "female");
                yield return new schizophrenia(100, 21, "male");
                yield return new schizophrenia(101, 18, "male");
                yield return new schizophrenia(102, 23, "male");
                yield return new schizophrenia(103, 21, "male");
                yield return new schizophrenia(104, 27, "male");
                yield return new schizophrenia(105, 24, "male");
                yield return new schizophrenia(106, 20, "male");
                yield return new schizophrenia(107, 12, "male");
                yield return new schizophrenia(108, 15, "male");
                yield return new schizophrenia(109, 19, "male");
                yield return new schizophrenia(110, 21, "male");
                yield return new schizophrenia(111, 22, "male");
                yield return new schizophrenia(112, 19, "male");
                yield return new schizophrenia(113, 24, "male");
                yield return new schizophrenia(114, 9, "male");
                yield return new schizophrenia(115, 19, "male");
                yield return new schizophrenia(116, 18, "male");
                yield return new schizophrenia(117, 17, "male");
                yield return new schizophrenia(118, 23, "male");
                yield return new schizophrenia(119, 17, "male");
                yield return new schizophrenia(120, 23, "male");
                yield return new schizophrenia(121, 19, "male");
                yield return new schizophrenia(122, 37, "male");
                yield return new schizophrenia(123, 26, "male");
                yield return new schizophrenia(124, 22, "male");
                yield return new schizophrenia(125, 24, "male");
                yield return new schizophrenia(126, 19, "male");
                yield return new schizophrenia(127, 22, "male");
                yield return new schizophrenia(128, 19, "male");
                yield return new schizophrenia(129, 16, "male");
                yield return new schizophrenia(130, 16, "male");
                yield return new schizophrenia(131, 18, "male");
                yield return new schizophrenia(132, 16, "male");
                yield return new schizophrenia(133, 33, "male");
                yield return new schizophrenia(134, 22, "male");
                yield return new schizophrenia(135, 23, "male");
                yield return new schizophrenia(136, 10, "male");
                yield return new schizophrenia(137, 14, "male");
                yield return new schizophrenia(138, 15, "male");
                yield return new schizophrenia(139, 20, "male");
                yield return new schizophrenia(140, 11, "male");
                yield return new schizophrenia(141, 25, "male");
                yield return new schizophrenia(142, 9, "male");
                yield return new schizophrenia(143, 22, "male");
                yield return new schizophrenia(144, 25, "male");
                yield return new schizophrenia(145, 20, "male");
                yield return new schizophrenia(146, 19, "male");
                yield return new schizophrenia(147, 22, "male");
                yield return new schizophrenia(148, 23, "male");
                yield return new schizophrenia(149, 24, "male");
                yield return new schizophrenia(150, 29, "male");
                yield return new schizophrenia(151, 24, "male");
                yield return new schizophrenia(152, 22, "male");
                yield return new schizophrenia(153, 26, "male");
                yield return new schizophrenia(154, 20, "male");
                yield return new schizophrenia(155, 25, "male");
                yield return new schizophrenia(156, 17, "male");
                yield return new schizophrenia(157, 25, "male");
                yield return new schizophrenia(158, 28, "male");
                yield return new schizophrenia(159, 22, "male");
                yield return new schizophrenia(160, 22, "male");
                yield return new schizophrenia(161, 23, "male");
                yield return new schizophrenia(162, 35, "male");
                yield return new schizophrenia(163, 16, "male");
                yield return new schizophrenia(164, 29, "male");
                yield return new schizophrenia(165, 33, "male");
                yield return new schizophrenia(166, 15, "male");
                yield return new schizophrenia(167, 29, "male");
                yield return new schizophrenia(168, 20, "male");
                yield return new schizophrenia(169, 29, "male");
                yield return new schizophrenia(170, 24, "male");
                yield return new schizophrenia(171, 39, "male");
                yield return new schizophrenia(172, 10, "male");
                yield return new schizophrenia(173, 20, "male");
                yield return new schizophrenia(174, 23, "male");
                yield return new schizophrenia(175, 15, "male");
                yield return new schizophrenia(176, 18, "male");
                yield return new schizophrenia(177, 20, "male");
                yield return new schizophrenia(178, 21, "male");
                yield return new schizophrenia(179, 30, "male");
                yield return new schizophrenia(180, 21, "male");
                yield return new schizophrenia(181, 18, "male");
                yield return new schizophrenia(182, 19, "male");
                yield return new schizophrenia(183, 15, "male");
                yield return new schizophrenia(184, 19, "male");
                yield return new schizophrenia(185, 18, "male");
                yield return new schizophrenia(186, 25, "male");
                yield return new schizophrenia(187, 17, "male");
                yield return new schizophrenia(188, 15, "male");
                yield return new schizophrenia(189, 42, "male");
                yield return new schizophrenia(190, 27, "male");
                yield return new schizophrenia(191, 18, "male");
                yield return new schizophrenia(192, 43, "male");
                yield return new schizophrenia(193, 20, "male");
                yield return new schizophrenia(194, 17, "male");
                yield return new schizophrenia(195, 21, "male");
                yield return new schizophrenia(196, 5, "male");
                yield return new schizophrenia(197, 27, "male");
                yield return new schizophrenia(198, 25, "male");
                yield return new schizophrenia(199, 18, "male");
                yield return new schizophrenia(200, 24, "male");
                yield return new schizophrenia(201, 33, "male");
                yield return new schizophrenia(202, 32, "male");
                yield return new schizophrenia(203, 29, "male");
                yield return new schizophrenia(204, 34, "male");
                yield return new schizophrenia(205, 20, "male");
                yield return new schizophrenia(206, 21, "male");
                yield return new schizophrenia(207, 31, "male");
                yield return new schizophrenia(208, 22, "male");
                yield return new schizophrenia(209, 15, "male");
                yield return new schizophrenia(210, 27, "male");
                yield return new schizophrenia(211, 26, "male");
                yield return new schizophrenia(212, 23, "male");
                yield return new schizophrenia(213, 47, "male");
                yield return new schizophrenia(214, 17, "male");
                yield return new schizophrenia(215, 21, "male");
                yield return new schizophrenia(216, 16, "male");
                yield return new schizophrenia(217, 21, "male");
                yield return new schizophrenia(218, 19, "male");
                yield return new schizophrenia(219, 31, "male");
                yield return new schizophrenia(220, 34, "male");
                yield return new schizophrenia(221, 23, "male");
                yield return new schizophrenia(222, 23, "male");
                yield return new schizophrenia(223, 20, "male");
                yield return new schizophrenia(224, 21, "male");
                yield return new schizophrenia(225, 18, "male");
                yield return new schizophrenia(226, 26, "male");
                yield return new schizophrenia(227, 30, "male");
                yield return new schizophrenia(228, 17, "male");
                yield return new schizophrenia(229, 21, "male");
                yield return new schizophrenia(230, 19, "male");
                yield return new schizophrenia(231, 22, "male");
                yield return new schizophrenia(232, 52, "male");
                yield return new schizophrenia(233, 19, "male");
                yield return new schizophrenia(234, 24, "male");
                yield return new schizophrenia(235, 19, "male");
                yield return new schizophrenia(236, 19, "male");
                yield return new schizophrenia(237, 33, "male");
                yield return new schizophrenia(238, 32, "male");
                yield return new schizophrenia(239, 29, "male");
                yield return new schizophrenia(240, 58, "male");
                yield return new schizophrenia(241, 39, "male");
                yield return new schizophrenia(242, 42, "male");
                yield return new schizophrenia(243, 32, "male");
                yield return new schizophrenia(244, 32, "male");
                yield return new schizophrenia(245, 46, "male");
                yield return new schizophrenia(246, 38, "male");
                yield return new schizophrenia(247, 44, "male");
                yield return new schizophrenia(248, 35, "male");
                yield return new schizophrenia(249, 45, "male");
                yield return new schizophrenia(250, 41, "male");
                yield return new schizophrenia(251, 31, "male");
            }
        }
    }
}
