// ReSharper disable All

namespace Rdatasets.HSAUR
{
    using System.Collections.Generic;

    /// <summary>
    /// Schizophrenia Data
    /// </summary>

    public class schizophrenia2
    {
        public readonly int κ;
        public readonly int subject;
        public readonly string onset;
        public readonly string disorder;
        public readonly int month;

        public schizophrenia2(int κ, int subject, string onset, string disorder, int month)
        {
            this.κ = κ;
            this.subject = subject;
            this.onset = onset;
            this.disorder = disorder;
            this.month = month;
        }

        public static IEnumerable<schizophrenia2> Data
        {
            get
            {
                yield return new schizophrenia2(1, 1, "< 20 yrs", "present", 0);
                yield return new schizophrenia2(45, 1, "< 20 yrs", "present", 2);
                yield return new schizophrenia2(89, 1, "< 20 yrs", "absent", 6);
                yield return new schizophrenia2(133, 1, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(177, 1, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(2, 2, "> 20 yrs", "absent", 0);
                yield return new schizophrenia2(46, 2, "> 20 yrs", "absent", 2);
                yield return new schizophrenia2(90, 2, "> 20 yrs", "absent", 6);
                yield return new schizophrenia2(134, 2, "> 20 yrs", "absent", 8);
                yield return new schizophrenia2(178, 2, "> 20 yrs", "absent", 10);
                yield return new schizophrenia2(3, 3, "< 20 yrs", "present", 0);
                yield return new schizophrenia2(47, 3, "< 20 yrs", "present", 2);
                yield return new schizophrenia2(91, 3, "< 20 yrs", "absent", 6);
                yield return new schizophrenia2(135, 3, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(179, 3, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(4, 4, "< 20 yrs", "absent", 0);
                yield return new schizophrenia2(48, 4, "< 20 yrs", "absent", 2);
                yield return new schizophrenia2(92, 4, "< 20 yrs", "absent", 6);
                yield return new schizophrenia2(136, 4, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(180, 4, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(5, 5, "< 20 yrs", "present", 0);
                yield return new schizophrenia2(49, 5, "< 20 yrs", "present", 2);
                yield return new schizophrenia2(93, 5, "< 20 yrs", "present", 6);
                yield return new schizophrenia2(137, 5, "< 20 yrs", "present", 8);
                yield return new schizophrenia2(181, 5, "< 20 yrs", "present", 10);
                yield return new schizophrenia2(6, 6, "< 20 yrs", "present", 0);
                yield return new schizophrenia2(50, 6, "< 20 yrs", "present", 2);
                yield return new schizophrenia2(94, 6, "< 20 yrs", "absent", 6);
                yield return new schizophrenia2(138, 6, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(182, 6, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(7, 7, "< 20 yrs", "present", 0);
                yield return new schizophrenia2(51, 7, "< 20 yrs", "absent", 2);
                yield return new schizophrenia2(95, 7, "< 20 yrs", "present", 6);
                yield return new schizophrenia2(139, 7, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(183, 7, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(8, 8, "< 20 yrs", "present", 0);
                yield return new schizophrenia2(52, 8, "< 20 yrs", "present", 2);
                yield return new schizophrenia2(96, 8, "< 20 yrs", "absent", 6);
                yield return new schizophrenia2(140, 8, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(184, 8, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(9, 9, "< 20 yrs", "absent", 0);
                yield return new schizophrenia2(53, 9, "< 20 yrs", "absent", 2);
                yield return new schizophrenia2(97, 9, "< 20 yrs", "present", 6);
                yield return new schizophrenia2(141, 9, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(185, 9, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(10, 10, "> 20 yrs", "absent", 0);
                yield return new schizophrenia2(54, 10, "> 20 yrs", "absent", 2);
                yield return new schizophrenia2(98, 10, "> 20 yrs", "absent", 6);
                yield return new schizophrenia2(142, 10, "> 20 yrs", "absent", 8);
                yield return new schizophrenia2(186, 10, "> 20 yrs", "absent", 10);
                yield return new schizophrenia2(11, 11, "> 20 yrs", "present", 0);
                yield return new schizophrenia2(55, 11, "> 20 yrs", "present", 2);
                yield return new schizophrenia2(99, 11, "> 20 yrs", "present", 6);
                yield return new schizophrenia2(143, 11, "> 20 yrs", "absent", 8);
                yield return new schizophrenia2(187, 11, "> 20 yrs", "present", 10);
                yield return new schizophrenia2(12, 12, "< 20 yrs", "absent", 0);
                yield return new schizophrenia2(56, 12, "< 20 yrs", "absent", 2);
                yield return new schizophrenia2(100, 12, "< 20 yrs", null, 6);
                yield return new schizophrenia2(144, 12, "< 20 yrs", null, 8);
                yield return new schizophrenia2(188, 12, "< 20 yrs", null, 10);
                yield return new schizophrenia2(13, 13, "> 20 yrs", "present", 0);
                yield return new schizophrenia2(57, 13, "> 20 yrs", "present", 2);
                yield return new schizophrenia2(101, 13, "> 20 yrs", "absent", 6);
                yield return new schizophrenia2(145, 13, "> 20 yrs", "absent", 8);
                yield return new schizophrenia2(189, 13, "> 20 yrs", "absent", 10);
                yield return new schizophrenia2(14, 14, "< 20 yrs", "present", 0);
                yield return new schizophrenia2(58, 14, "< 20 yrs", "present", 2);
                yield return new schizophrenia2(102, 14, "< 20 yrs", "absent", 6);
                yield return new schizophrenia2(146, 14, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(190, 14, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(15, 15, "> 20 yrs", "present", 0);
                yield return new schizophrenia2(59, 15, "> 20 yrs", "present", 2);
                yield return new schizophrenia2(103, 15, "> 20 yrs", "absent", 6);
                yield return new schizophrenia2(147, 15, "> 20 yrs", "absent", 8);
                yield return new schizophrenia2(191, 15, "> 20 yrs", "absent", 10);
                yield return new schizophrenia2(16, 16, "< 20 yrs", "present", 0);
                yield return new schizophrenia2(60, 16, "< 20 yrs", "present", 2);
                yield return new schizophrenia2(104, 16, "< 20 yrs", "present", 6);
                yield return new schizophrenia2(148, 16, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(192, 16, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(17, 17, "< 20 yrs", "absent", 0);
                yield return new schizophrenia2(61, 17, "< 20 yrs", "present", 2);
                yield return new schizophrenia2(105, 17, "< 20 yrs", "absent", 6);
                yield return new schizophrenia2(149, 17, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(193, 17, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(18, 18, "< 20 yrs", "present", 0);
                yield return new schizophrenia2(62, 18, "< 20 yrs", "present", 2);
                yield return new schizophrenia2(106, 18, "< 20 yrs", "absent", 6);
                yield return new schizophrenia2(150, 18, "< 20 yrs", "present", 8);
                yield return new schizophrenia2(194, 18, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(19, 19, "< 20 yrs", "present", 0);
                yield return new schizophrenia2(63, 19, "< 20 yrs", "present", 2);
                yield return new schizophrenia2(107, 19, "< 20 yrs", "present", 6);
                yield return new schizophrenia2(151, 19, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(195, 19, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(20, 20, "< 20 yrs", "absent", 0);
                yield return new schizophrenia2(64, 20, "< 20 yrs", "absent", 2);
                yield return new schizophrenia2(108, 20, "< 20 yrs", "absent", 6);
                yield return new schizophrenia2(152, 20, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(196, 20, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(21, 21, "< 20 yrs", "absent", 0);
                yield return new schizophrenia2(65, 21, "< 20 yrs", "absent", 2);
                yield return new schizophrenia2(109, 21, "< 20 yrs", "present", 6);
                yield return new schizophrenia2(153, 21, "< 20 yrs", "present", 8);
                yield return new schizophrenia2(197, 21, "< 20 yrs", "present", 10);
                yield return new schizophrenia2(22, 22, "> 20 yrs", "absent", 0);
                yield return new schizophrenia2(66, 22, "> 20 yrs", "present", 2);
                yield return new schizophrenia2(110, 22, "> 20 yrs", "present", 6);
                yield return new schizophrenia2(154, 22, "> 20 yrs", "absent", 8);
                yield return new schizophrenia2(198, 22, "> 20 yrs", "absent", 10);
                yield return new schizophrenia2(23, 23, "< 20 yrs", "present", 0);
                yield return new schizophrenia2(67, 23, "< 20 yrs", "present", 2);
                yield return new schizophrenia2(111, 23, "< 20 yrs", "absent", 6);
                yield return new schizophrenia2(155, 23, "< 20 yrs", "present", 8);
                yield return new schizophrenia2(199, 23, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(24, 24, "< 20 yrs", "present", 0);
                yield return new schizophrenia2(68, 24, "< 20 yrs", "absent", 2);
                yield return new schizophrenia2(112, 24, "< 20 yrs", "absent", 6);
                yield return new schizophrenia2(156, 24, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(200, 24, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(25, 25, "> 20 yrs", "present", 0);
                yield return new schizophrenia2(69, 25, "> 20 yrs", "absent", 2);
                yield return new schizophrenia2(113, 25, "> 20 yrs", "absent", 6);
                yield return new schizophrenia2(157, 25, "> 20 yrs", "absent", 8);
                yield return new schizophrenia2(201, 25, "> 20 yrs", "absent", 10);
                yield return new schizophrenia2(26, 26, "< 20 yrs", "absent", 0);
                yield return new schizophrenia2(70, 26, "< 20 yrs", "absent", 2);
                yield return new schizophrenia2(114, 26, "< 20 yrs", "absent", 6);
                yield return new schizophrenia2(158, 26, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(202, 26, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(27, 27, "< 20 yrs", "present", 0);
                yield return new schizophrenia2(71, 27, "< 20 yrs", "present", 2);
                yield return new schizophrenia2(115, 27, "< 20 yrs", "absent", 6);
                yield return new schizophrenia2(159, 27, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(203, 27, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(28, 28, "< 20 yrs", "absent", 0);
                yield return new schizophrenia2(72, 28, "< 20 yrs", "absent", 2);
                yield return new schizophrenia2(116, 28, "< 20 yrs", "absent", 6);
                yield return new schizophrenia2(160, 28, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(204, 28, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(29, 29, "> 20 yrs", "present", 0);
                yield return new schizophrenia2(73, 29, "> 20 yrs", "present", 2);
                yield return new schizophrenia2(117, 29, "> 20 yrs", "absent", 6);
                yield return new schizophrenia2(161, 29, "> 20 yrs", "absent", 8);
                yield return new schizophrenia2(205, 29, "> 20 yrs", "absent", 10);
                yield return new schizophrenia2(30, 30, "> 20 yrs", "absent", 0);
                yield return new schizophrenia2(74, 30, "> 20 yrs", "absent", 2);
                yield return new schizophrenia2(118, 30, "> 20 yrs", "absent", 6);
                yield return new schizophrenia2(162, 30, "> 20 yrs", "absent", 8);
                yield return new schizophrenia2(206, 30, "> 20 yrs", "absent", 10);
                yield return new schizophrenia2(31, 31, "< 20 yrs", "absent", 0);
                yield return new schizophrenia2(75, 31, "< 20 yrs", "absent", 2);
                yield return new schizophrenia2(119, 31, "< 20 yrs", "absent", 6);
                yield return new schizophrenia2(163, 31, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(207, 31, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(32, 32, "< 20 yrs", "absent", 0);
                yield return new schizophrenia2(76, 32, "< 20 yrs", "present", 2);
                yield return new schizophrenia2(120, 32, "< 20 yrs", "absent", 6);
                yield return new schizophrenia2(164, 32, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(208, 32, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(33, 33, "< 20 yrs", "present", 0);
                yield return new schizophrenia2(77, 33, "< 20 yrs", "present", 2);
                yield return new schizophrenia2(121, 33, "< 20 yrs", "present", 6);
                yield return new schizophrenia2(165, 33, "< 20 yrs", "present", 8);
                yield return new schizophrenia2(209, 33, "< 20 yrs", "present", 10);
                yield return new schizophrenia2(34, 34, "< 20 yrs", "present", 0);
                yield return new schizophrenia2(78, 34, "< 20 yrs", "present", 2);
                yield return new schizophrenia2(122, 34, "< 20 yrs", "present", 6);
                yield return new schizophrenia2(166, 34, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(210, 34, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(35, 35, "< 20 yrs", "present", 0);
                yield return new schizophrenia2(79, 35, "< 20 yrs", "absent", 2);
                yield return new schizophrenia2(123, 35, "< 20 yrs", "absent", 6);
                yield return new schizophrenia2(167, 35, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(211, 35, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(36, 36, "> 20 yrs", "present", 0);
                yield return new schizophrenia2(80, 36, "> 20 yrs", "absent", 2);
                yield return new schizophrenia2(124, 36, "> 20 yrs", "absent", 6);
                yield return new schizophrenia2(168, 36, "> 20 yrs", null, 8);
                yield return new schizophrenia2(212, 36, "> 20 yrs", null, 10);
                yield return new schizophrenia2(37, 37, "< 20 yrs", "absent", 0);
                yield return new schizophrenia2(81, 37, "< 20 yrs", "present", 2);
                yield return new schizophrenia2(125, 37, "< 20 yrs", null, 6);
                yield return new schizophrenia2(169, 37, "< 20 yrs", null, 8);
                yield return new schizophrenia2(213, 37, "< 20 yrs", null, 10);
                yield return new schizophrenia2(38, 38, "> 20 yrs", "absent", 0);
                yield return new schizophrenia2(82, 38, "> 20 yrs", "absent", 2);
                yield return new schizophrenia2(126, 38, "> 20 yrs", "absent", 6);
                yield return new schizophrenia2(170, 38, "> 20 yrs", "absent", 8);
                yield return new schizophrenia2(214, 38, "> 20 yrs", "absent", 10);
                yield return new schizophrenia2(39, 39, "< 20 yrs", "present", 0);
                yield return new schizophrenia2(83, 39, "< 20 yrs", null, 2);
                yield return new schizophrenia2(127, 39, "< 20 yrs", null, 6);
                yield return new schizophrenia2(171, 39, "< 20 yrs", null, 8);
                yield return new schizophrenia2(215, 39, "< 20 yrs", null, 10);
                yield return new schizophrenia2(40, 40, "< 20 yrs", "present", 0);
                yield return new schizophrenia2(84, 40, "< 20 yrs", "present", 2);
                yield return new schizophrenia2(128, 40, "< 20 yrs", "absent", 6);
                yield return new schizophrenia2(172, 40, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(216, 40, "< 20 yrs", "absent", 10);
                yield return new schizophrenia2(41, 41, "> 20 yrs", "present", 0);
                yield return new schizophrenia2(85, 41, "> 20 yrs", "present", 2);
                yield return new schizophrenia2(129, 41, "> 20 yrs", "present", 6);
                yield return new schizophrenia2(173, 41, "> 20 yrs", "absent", 8);
                yield return new schizophrenia2(217, 41, "> 20 yrs", "absent", 10);
                yield return new schizophrenia2(42, 42, "< 20 yrs", "absent", 0);
                yield return new schizophrenia2(86, 42, "< 20 yrs", "present", 2);
                yield return new schizophrenia2(130, 42, "< 20 yrs", null, 6);
                yield return new schizophrenia2(174, 42, "< 20 yrs", null, 8);
                yield return new schizophrenia2(218, 42, "< 20 yrs", null, 10);
                yield return new schizophrenia2(43, 43, "< 20 yrs", "present", 0);
                yield return new schizophrenia2(87, 43, "< 20 yrs", "absent", 2);
                yield return new schizophrenia2(131, 43, "< 20 yrs", "absent", 6);
                yield return new schizophrenia2(175, 43, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(219, 43, "< 20 yrs", null, 10);
                yield return new schizophrenia2(44, 44, "< 20 yrs", "present", 0);
                yield return new schizophrenia2(88, 44, "< 20 yrs", "present", 2);
                yield return new schizophrenia2(132, 44, "< 20 yrs", "absent", 6);
                yield return new schizophrenia2(176, 44, "< 20 yrs", "absent", 8);
                yield return new schizophrenia2(220, 44, "< 20 yrs", "absent", 10);
            }
        }
    }
}
