// ReSharper disable All

namespace Rdatasets.HSAUR
{
    using System.Collections.Generic;

    /// <summary>
    /// Age of Onset of Schizophrenia Data
    /// </summary>

    public class schizophrenia
    {
        public readonly int age;
        public readonly string gender;

        public schizophrenia(int age, string gender)
        {
            this.age = age;
            this.gender = gender;
        }

        public static IEnumerable<schizophrenia> Data
        {
            get
            {
                yield return new schizophrenia(20, "female");
                yield return new schizophrenia(30, "female");
                yield return new schizophrenia(21, "female");
                yield return new schizophrenia(23, "female");
                yield return new schizophrenia(30, "female");
                yield return new schizophrenia(25, "female");
                yield return new schizophrenia(13, "female");
                yield return new schizophrenia(19, "female");
                yield return new schizophrenia(16, "female");
                yield return new schizophrenia(25, "female");
                yield return new schizophrenia(20, "female");
                yield return new schizophrenia(25, "female");
                yield return new schizophrenia(27, "female");
                yield return new schizophrenia(43, "female");
                yield return new schizophrenia(6, "female");
                yield return new schizophrenia(21, "female");
                yield return new schizophrenia(15, "female");
                yield return new schizophrenia(26, "female");
                yield return new schizophrenia(23, "female");
                yield return new schizophrenia(21, "female");
                yield return new schizophrenia(23, "female");
                yield return new schizophrenia(23, "female");
                yield return new schizophrenia(34, "female");
                yield return new schizophrenia(14, "female");
                yield return new schizophrenia(17, "female");
                yield return new schizophrenia(18, "female");
                yield return new schizophrenia(21, "female");
                yield return new schizophrenia(16, "female");
                yield return new schizophrenia(35, "female");
                yield return new schizophrenia(32, "female");
                yield return new schizophrenia(48, "female");
                yield return new schizophrenia(53, "female");
                yield return new schizophrenia(51, "female");
                yield return new schizophrenia(48, "female");
                yield return new schizophrenia(29, "female");
                yield return new schizophrenia(25, "female");
                yield return new schizophrenia(44, "female");
                yield return new schizophrenia(23, "female");
                yield return new schizophrenia(36, "female");
                yield return new schizophrenia(58, "female");
                yield return new schizophrenia(28, "female");
                yield return new schizophrenia(51, "female");
                yield return new schizophrenia(40, "female");
                yield return new schizophrenia(43, "female");
                yield return new schizophrenia(21, "female");
                yield return new schizophrenia(48, "female");
                yield return new schizophrenia(17, "female");
                yield return new schizophrenia(23, "female");
                yield return new schizophrenia(28, "female");
                yield return new schizophrenia(44, "female");
                yield return new schizophrenia(28, "female");
                yield return new schizophrenia(21, "female");
                yield return new schizophrenia(31, "female");
                yield return new schizophrenia(22, "female");
                yield return new schizophrenia(56, "female");
                yield return new schizophrenia(60, "female");
                yield return new schizophrenia(15, "female");
                yield return new schizophrenia(21, "female");
                yield return new schizophrenia(30, "female");
                yield return new schizophrenia(26, "female");
                yield return new schizophrenia(28, "female");
                yield return new schizophrenia(23, "female");
                yield return new schizophrenia(21, "female");
                yield return new schizophrenia(20, "female");
                yield return new schizophrenia(43, "female");
                yield return new schizophrenia(39, "female");
                yield return new schizophrenia(40, "female");
                yield return new schizophrenia(26, "female");
                yield return new schizophrenia(50, "female");
                yield return new schizophrenia(17, "female");
                yield return new schizophrenia(17, "female");
                yield return new schizophrenia(23, "female");
                yield return new schizophrenia(44, "female");
                yield return new schizophrenia(30, "female");
                yield return new schizophrenia(35, "female");
                yield return new schizophrenia(20, "female");
                yield return new schizophrenia(41, "female");
                yield return new schizophrenia(18, "female");
                yield return new schizophrenia(39, "female");
                yield return new schizophrenia(27, "female");
                yield return new schizophrenia(28, "female");
                yield return new schizophrenia(30, "female");
                yield return new schizophrenia(34, "female");
                yield return new schizophrenia(33, "female");
                yield return new schizophrenia(30, "female");
                yield return new schizophrenia(29, "female");
                yield return new schizophrenia(46, "female");
                yield return new schizophrenia(36, "female");
                yield return new schizophrenia(58, "female");
                yield return new schizophrenia(28, "female");
                yield return new schizophrenia(30, "female");
                yield return new schizophrenia(28, "female");
                yield return new schizophrenia(37, "female");
                yield return new schizophrenia(31, "female");
                yield return new schizophrenia(29, "female");
                yield return new schizophrenia(32, "female");
                yield return new schizophrenia(48, "female");
                yield return new schizophrenia(49, "female");
                yield return new schizophrenia(30, "female");
                yield return new schizophrenia(21, "male");
                yield return new schizophrenia(18, "male");
                yield return new schizophrenia(23, "male");
                yield return new schizophrenia(21, "male");
                yield return new schizophrenia(27, "male");
                yield return new schizophrenia(24, "male");
                yield return new schizophrenia(20, "male");
                yield return new schizophrenia(12, "male");
                yield return new schizophrenia(15, "male");
                yield return new schizophrenia(19, "male");
                yield return new schizophrenia(21, "male");
                yield return new schizophrenia(22, "male");
                yield return new schizophrenia(19, "male");
                yield return new schizophrenia(24, "male");
                yield return new schizophrenia(9, "male");
                yield return new schizophrenia(19, "male");
                yield return new schizophrenia(18, "male");
                yield return new schizophrenia(17, "male");
                yield return new schizophrenia(23, "male");
                yield return new schizophrenia(17, "male");
                yield return new schizophrenia(23, "male");
                yield return new schizophrenia(19, "male");
                yield return new schizophrenia(37, "male");
                yield return new schizophrenia(26, "male");
                yield return new schizophrenia(22, "male");
                yield return new schizophrenia(24, "male");
                yield return new schizophrenia(19, "male");
                yield return new schizophrenia(22, "male");
                yield return new schizophrenia(19, "male");
                yield return new schizophrenia(16, "male");
                yield return new schizophrenia(16, "male");
                yield return new schizophrenia(18, "male");
                yield return new schizophrenia(16, "male");
                yield return new schizophrenia(33, "male");
                yield return new schizophrenia(22, "male");
                yield return new schizophrenia(23, "male");
                yield return new schizophrenia(10, "male");
                yield return new schizophrenia(14, "male");
                yield return new schizophrenia(15, "male");
                yield return new schizophrenia(20, "male");
                yield return new schizophrenia(11, "male");
                yield return new schizophrenia(25, "male");
                yield return new schizophrenia(9, "male");
                yield return new schizophrenia(22, "male");
                yield return new schizophrenia(25, "male");
                yield return new schizophrenia(20, "male");
                yield return new schizophrenia(19, "male");
                yield return new schizophrenia(22, "male");
                yield return new schizophrenia(23, "male");
                yield return new schizophrenia(24, "male");
                yield return new schizophrenia(29, "male");
                yield return new schizophrenia(24, "male");
                yield return new schizophrenia(22, "male");
                yield return new schizophrenia(26, "male");
                yield return new schizophrenia(20, "male");
                yield return new schizophrenia(25, "male");
                yield return new schizophrenia(17, "male");
                yield return new schizophrenia(25, "male");
                yield return new schizophrenia(28, "male");
                yield return new schizophrenia(22, "male");
                yield return new schizophrenia(22, "male");
                yield return new schizophrenia(23, "male");
                yield return new schizophrenia(35, "male");
                yield return new schizophrenia(16, "male");
                yield return new schizophrenia(29, "male");
                yield return new schizophrenia(33, "male");
                yield return new schizophrenia(15, "male");
                yield return new schizophrenia(29, "male");
                yield return new schizophrenia(20, "male");
                yield return new schizophrenia(29, "male");
                yield return new schizophrenia(24, "male");
                yield return new schizophrenia(39, "male");
                yield return new schizophrenia(10, "male");
                yield return new schizophrenia(20, "male");
                yield return new schizophrenia(23, "male");
                yield return new schizophrenia(15, "male");
                yield return new schizophrenia(18, "male");
                yield return new schizophrenia(20, "male");
                yield return new schizophrenia(21, "male");
                yield return new schizophrenia(30, "male");
                yield return new schizophrenia(21, "male");
                yield return new schizophrenia(18, "male");
                yield return new schizophrenia(19, "male");
                yield return new schizophrenia(15, "male");
                yield return new schizophrenia(19, "male");
                yield return new schizophrenia(18, "male");
                yield return new schizophrenia(25, "male");
                yield return new schizophrenia(17, "male");
                yield return new schizophrenia(15, "male");
                yield return new schizophrenia(42, "male");
                yield return new schizophrenia(27, "male");
                yield return new schizophrenia(18, "male");
                yield return new schizophrenia(43, "male");
                yield return new schizophrenia(20, "male");
                yield return new schizophrenia(17, "male");
                yield return new schizophrenia(21, "male");
                yield return new schizophrenia(5, "male");
                yield return new schizophrenia(27, "male");
                yield return new schizophrenia(25, "male");
                yield return new schizophrenia(18, "male");
                yield return new schizophrenia(24, "male");
                yield return new schizophrenia(33, "male");
                yield return new schizophrenia(32, "male");
                yield return new schizophrenia(29, "male");
                yield return new schizophrenia(34, "male");
                yield return new schizophrenia(20, "male");
                yield return new schizophrenia(21, "male");
                yield return new schizophrenia(31, "male");
                yield return new schizophrenia(22, "male");
                yield return new schizophrenia(15, "male");
                yield return new schizophrenia(27, "male");
                yield return new schizophrenia(26, "male");
                yield return new schizophrenia(23, "male");
                yield return new schizophrenia(47, "male");
                yield return new schizophrenia(17, "male");
                yield return new schizophrenia(21, "male");
                yield return new schizophrenia(16, "male");
                yield return new schizophrenia(21, "male");
                yield return new schizophrenia(19, "male");
                yield return new schizophrenia(31, "male");
                yield return new schizophrenia(34, "male");
                yield return new schizophrenia(23, "male");
                yield return new schizophrenia(23, "male");
                yield return new schizophrenia(20, "male");
                yield return new schizophrenia(21, "male");
                yield return new schizophrenia(18, "male");
                yield return new schizophrenia(26, "male");
                yield return new schizophrenia(30, "male");
                yield return new schizophrenia(17, "male");
                yield return new schizophrenia(21, "male");
                yield return new schizophrenia(19, "male");
                yield return new schizophrenia(22, "male");
                yield return new schizophrenia(52, "male");
                yield return new schizophrenia(19, "male");
                yield return new schizophrenia(24, "male");
                yield return new schizophrenia(19, "male");
                yield return new schizophrenia(19, "male");
                yield return new schizophrenia(33, "male");
                yield return new schizophrenia(32, "male");
                yield return new schizophrenia(29, "male");
                yield return new schizophrenia(58, "male");
                yield return new schizophrenia(39, "male");
                yield return new schizophrenia(42, "male");
                yield return new schizophrenia(32, "male");
                yield return new schizophrenia(32, "male");
                yield return new schizophrenia(46, "male");
                yield return new schizophrenia(38, "male");
                yield return new schizophrenia(44, "male");
                yield return new schizophrenia(35, "male");
                yield return new schizophrenia(45, "male");
                yield return new schizophrenia(41, "male");
                yield return new schizophrenia(31, "male");
            }
        }
    }
}
