// ReSharper disable All

namespace Rdatasets.vcd
{
    using System.Collections.Generic;

    /// <summary>
    /// Rochdale Data
    /// </summary>

    public class Rochdale
    {
        public readonly int κ;
        public readonly string EconActive;
        public readonly string Age;
        public readonly string HusbandEmployed;
        public readonly string Child;
        public readonly string Education;
        public readonly string HusbandEducation;
        public readonly string Asian;
        public readonly string HouseholdWorking;
        public readonly int Freq;

        public Rochdale(int κ, string EconActive, string Age, string HusbandEmployed, string Child, string Education, string HusbandEducation, string Asian, string HouseholdWorking, int Freq)
        {
            this.κ = κ;
            this.EconActive = EconActive;
            this.Age = Age;
            this.HusbandEmployed = HusbandEmployed;
            this.Child = Child;
            this.Education = Education;
            this.HusbandEducation = HusbandEducation;
            this.Asian = Asian;
            this.HouseholdWorking = HouseholdWorking;
            this.Freq = Freq;
        }

        public static IEnumerable<Rochdale> Data
        {
            get
            {
                yield return new Rochdale(1, "yes", "<38", "yes", "yes", "yes", "yes", "yes", "yes", 1);
                yield return new Rochdale(2, "no", "<38", "yes", "yes", "yes", "yes", "yes", "yes", 0);
                yield return new Rochdale(3, "yes", ">38", "yes", "yes", "yes", "yes", "yes", "yes", 0);
                yield return new Rochdale(4, "no", ">38", "yes", "yes", "yes", "yes", "yes", "yes", 0);
                yield return new Rochdale(5, "yes", "<38", "no", "yes", "yes", "yes", "yes", "yes", 0);
                yield return new Rochdale(6, "no", "<38", "no", "yes", "yes", "yes", "yes", "yes", 0);
                yield return new Rochdale(7, "yes", ">38", "no", "yes", "yes", "yes", "yes", "yes", 0);
                yield return new Rochdale(8, "no", ">38", "no", "yes", "yes", "yes", "yes", "yes", 0);
                yield return new Rochdale(9, "yes", "<38", "yes", "no", "yes", "yes", "yes", "yes", 0);
                yield return new Rochdale(10, "no", "<38", "yes", "no", "yes", "yes", "yes", "yes", 0);
                yield return new Rochdale(11, "yes", ">38", "yes", "no", "yes", "yes", "yes", "yes", 0);
                yield return new Rochdale(12, "no", ">38", "yes", "no", "yes", "yes", "yes", "yes", 0);
                yield return new Rochdale(13, "yes", "<38", "no", "no", "yes", "yes", "yes", "yes", 0);
                yield return new Rochdale(14, "no", "<38", "no", "no", "yes", "yes", "yes", "yes", 0);
                yield return new Rochdale(15, "yes", ">38", "no", "no", "yes", "yes", "yes", "yes", 0);
                yield return new Rochdale(16, "no", ">38", "no", "no", "yes", "yes", "yes", "yes", 0);
                yield return new Rochdale(17, "yes", "<38", "yes", "yes", "no", "yes", "yes", "yes", 0);
                yield return new Rochdale(18, "no", "<38", "yes", "yes", "no", "yes", "yes", "yes", 0);
                yield return new Rochdale(19, "yes", ">38", "yes", "yes", "no", "yes", "yes", "yes", 0);
                yield return new Rochdale(20, "no", ">38", "yes", "yes", "no", "yes", "yes", "yes", 0);
                yield return new Rochdale(21, "yes", "<38", "no", "yes", "no", "yes", "yes", "yes", 0);
                yield return new Rochdale(22, "no", "<38", "no", "yes", "no", "yes", "yes", "yes", 0);
                yield return new Rochdale(23, "yes", ">38", "no", "yes", "no", "yes", "yes", "yes", 0);
                yield return new Rochdale(24, "no", ">38", "no", "yes", "no", "yes", "yes", "yes", 0);
                yield return new Rochdale(25, "yes", "<38", "yes", "no", "no", "yes", "yes", "yes", 0);
                yield return new Rochdale(26, "no", "<38", "yes", "no", "no", "yes", "yes", "yes", 0);
                yield return new Rochdale(27, "yes", ">38", "yes", "no", "no", "yes", "yes", "yes", 0);
                yield return new Rochdale(28, "no", ">38", "yes", "no", "no", "yes", "yes", "yes", 0);
                yield return new Rochdale(29, "yes", "<38", "no", "no", "no", "yes", "yes", "yes", 0);
                yield return new Rochdale(30, "no", "<38", "no", "no", "no", "yes", "yes", "yes", 0);
                yield return new Rochdale(31, "yes", ">38", "no", "no", "no", "yes", "yes", "yes", 0);
                yield return new Rochdale(32, "no", ">38", "no", "no", "no", "yes", "yes", "yes", 0);
                yield return new Rochdale(33, "yes", "<38", "yes", "yes", "yes", "no", "yes", "yes", 0);
                yield return new Rochdale(34, "no", "<38", "yes", "yes", "yes", "no", "yes", "yes", 0);
                yield return new Rochdale(35, "yes", ">38", "yes", "yes", "yes", "no", "yes", "yes", 0);
                yield return new Rochdale(36, "no", ">38", "yes", "yes", "yes", "no", "yes", "yes", 0);
                yield return new Rochdale(37, "yes", "<38", "no", "yes", "yes", "no", "yes", "yes", 0);
                yield return new Rochdale(38, "no", "<38", "no", "yes", "yes", "no", "yes", "yes", 0);
                yield return new Rochdale(39, "yes", ">38", "no", "yes", "yes", "no", "yes", "yes", 0);
                yield return new Rochdale(40, "no", ">38", "no", "yes", "yes", "no", "yes", "yes", 0);
                yield return new Rochdale(41, "yes", "<38", "yes", "no", "yes", "no", "yes", "yes", 0);
                yield return new Rochdale(42, "no", "<38", "yes", "no", "yes", "no", "yes", "yes", 0);
                yield return new Rochdale(43, "yes", ">38", "yes", "no", "yes", "no", "yes", "yes", 0);
                yield return new Rochdale(44, "no", ">38", "yes", "no", "yes", "no", "yes", "yes", 0);
                yield return new Rochdale(45, "yes", "<38", "no", "no", "yes", "no", "yes", "yes", 0);
                yield return new Rochdale(46, "no", "<38", "no", "no", "yes", "no", "yes", "yes", 0);
                yield return new Rochdale(47, "yes", ">38", "no", "no", "yes", "no", "yes", "yes", 0);
                yield return new Rochdale(48, "no", ">38", "no", "no", "yes", "no", "yes", "yes", 0);
                yield return new Rochdale(49, "yes", "<38", "yes", "yes", "no", "no", "yes", "yes", 0);
                yield return new Rochdale(50, "no", "<38", "yes", "yes", "no", "no", "yes", "yes", 0);
                yield return new Rochdale(51, "yes", ">38", "yes", "yes", "no", "no", "yes", "yes", 0);
                yield return new Rochdale(52, "no", ">38", "yes", "yes", "no", "no", "yes", "yes", 0);
                yield return new Rochdale(53, "yes", "<38", "no", "yes", "no", "no", "yes", "yes", 0);
                yield return new Rochdale(54, "no", "<38", "no", "yes", "no", "no", "yes", "yes", 2);
                yield return new Rochdale(55, "yes", ">38", "no", "yes", "no", "no", "yes", "yes", 0);
                yield return new Rochdale(56, "no", ">38", "no", "yes", "no", "no", "yes", "yes", 0);
                yield return new Rochdale(57, "yes", "<38", "yes", "no", "no", "no", "yes", "yes", 0);
                yield return new Rochdale(58, "no", "<38", "yes", "no", "no", "no", "yes", "yes", 1);
                yield return new Rochdale(59, "yes", ">38", "yes", "no", "no", "no", "yes", "yes", 1);
                yield return new Rochdale(60, "no", ">38", "yes", "no", "no", "no", "yes", "yes", 1);
                yield return new Rochdale(61, "yes", "<38", "no", "no", "no", "no", "yes", "yes", 0);
                yield return new Rochdale(62, "no", "<38", "no", "no", "no", "no", "yes", "yes", 0);
                yield return new Rochdale(63, "yes", ">38", "no", "no", "no", "no", "yes", "yes", 0);
                yield return new Rochdale(64, "no", ">38", "no", "no", "no", "no", "yes", "yes", 1);
                yield return new Rochdale(65, "yes", "<38", "yes", "yes", "yes", "yes", "no", "yes", 2);
                yield return new Rochdale(66, "no", "<38", "yes", "yes", "yes", "yes", "no", "yes", 0);
                yield return new Rochdale(67, "yes", ">38", "yes", "yes", "yes", "yes", "no", "yes", 0);
                yield return new Rochdale(68, "no", ">38", "yes", "yes", "yes", "yes", "no", "yes", 0);
                yield return new Rochdale(69, "yes", "<38", "no", "yes", "yes", "yes", "no", "yes", 0);
                yield return new Rochdale(70, "no", "<38", "no", "yes", "yes", "yes", "no", "yes", 0);
                yield return new Rochdale(71, "yes", ">38", "no", "yes", "yes", "yes", "no", "yes", 0);
                yield return new Rochdale(72, "no", ">38", "no", "yes", "yes", "yes", "no", "yes", 0);
                yield return new Rochdale(73, "yes", "<38", "yes", "no", "yes", "yes", "no", "yes", 3);
                yield return new Rochdale(74, "no", "<38", "yes", "no", "yes", "yes", "no", "yes", 0);
                yield return new Rochdale(75, "yes", ">38", "yes", "no", "yes", "yes", "no", "yes", 22);
                yield return new Rochdale(76, "no", ">38", "yes", "no", "yes", "yes", "no", "yes", 6);
                yield return new Rochdale(77, "yes", "<38", "no", "no", "yes", "yes", "no", "yes", 0);
                yield return new Rochdale(78, "no", "<38", "no", "no", "yes", "yes", "no", "yes", 0);
                yield return new Rochdale(79, "yes", ">38", "no", "no", "yes", "yes", "no", "yes", 1);
                yield return new Rochdale(80, "no", ">38", "no", "no", "yes", "yes", "no", "yes", 0);
                yield return new Rochdale(81, "yes", "<38", "yes", "yes", "no", "yes", "no", "yes", 0);
                yield return new Rochdale(82, "no", "<38", "yes", "yes", "no", "yes", "no", "yes", 0);
                yield return new Rochdale(83, "yes", ">38", "yes", "yes", "no", "yes", "no", "yes", 0);
                yield return new Rochdale(84, "no", ">38", "yes", "yes", "no", "yes", "no", "yes", 0);
                yield return new Rochdale(85, "yes", "<38", "no", "yes", "no", "yes", "no", "yes", 0);
                yield return new Rochdale(86, "no", "<38", "no", "yes", "no", "yes", "no", "yes", 0);
                yield return new Rochdale(87, "yes", ">38", "no", "yes", "no", "yes", "no", "yes", 0);
                yield return new Rochdale(88, "no", ">38", "no", "yes", "no", "yes", "no", "yes", 0);
                yield return new Rochdale(89, "yes", "<38", "yes", "no", "no", "yes", "no", "yes", 4);
                yield return new Rochdale(90, "no", "<38", "yes", "no", "no", "yes", "no", "yes", 1);
                yield return new Rochdale(91, "yes", ">38", "yes", "no", "no", "yes", "no", "yes", 26);
                yield return new Rochdale(92, "no", ">38", "yes", "no", "no", "yes", "no", "yes", 7);
                yield return new Rochdale(93, "yes", "<38", "no", "no", "no", "yes", "no", "yes", 0);
                yield return new Rochdale(94, "no", "<38", "no", "no", "no", "yes", "no", "yes", 0);
                yield return new Rochdale(95, "yes", ">38", "no", "no", "no", "yes", "no", "yes", 1);
                yield return new Rochdale(96, "no", ">38", "no", "no", "no", "yes", "no", "yes", 1);
                yield return new Rochdale(97, "yes", "<38", "yes", "yes", "yes", "no", "no", "yes", 0);
                yield return new Rochdale(98, "no", "<38", "yes", "yes", "yes", "no", "no", "yes", 0);
                yield return new Rochdale(99, "yes", ">38", "yes", "yes", "yes", "no", "no", "yes", 0);
                yield return new Rochdale(100, "no", ">38", "yes", "yes", "yes", "no", "no", "yes", 0);
                yield return new Rochdale(101, "yes", "<38", "no", "yes", "yes", "no", "no", "yes", 0);
                yield return new Rochdale(102, "no", "<38", "no", "yes", "yes", "no", "no", "yes", 0);
                yield return new Rochdale(103, "yes", ">38", "no", "yes", "yes", "no", "no", "yes", 0);
                yield return new Rochdale(104, "no", ">38", "no", "yes", "yes", "no", "no", "yes", 0);
                yield return new Rochdale(105, "yes", "<38", "yes", "no", "yes", "no", "no", "yes", 2);
                yield return new Rochdale(106, "no", "<38", "yes", "no", "yes", "no", "no", "yes", 1);
                yield return new Rochdale(107, "yes", ">38", "yes", "no", "yes", "no", "no", "yes", 10);
                yield return new Rochdale(108, "no", ">38", "yes", "no", "yes", "no", "no", "yes", 2);
                yield return new Rochdale(109, "yes", "<38", "no", "no", "yes", "no", "no", "yes", 0);
                yield return new Rochdale(110, "no", "<38", "no", "no", "yes", "no", "no", "yes", 0);
                yield return new Rochdale(111, "yes", ">38", "no", "no", "yes", "no", "no", "yes", 1);
                yield return new Rochdale(112, "no", ">38", "no", "no", "yes", "no", "no", "yes", 0);
                yield return new Rochdale(113, "yes", "<38", "yes", "yes", "no", "no", "no", "yes", 1);
                yield return new Rochdale(114, "no", "<38", "yes", "yes", "no", "no", "no", "yes", 0);
                yield return new Rochdale(115, "yes", ">38", "yes", "yes", "no", "no", "no", "yes", 0);
                yield return new Rochdale(116, "no", ">38", "yes", "yes", "no", "no", "no", "yes", 0);
                yield return new Rochdale(117, "yes", "<38", "no", "yes", "no", "no", "no", "yes", 1);
                yield return new Rochdale(118, "no", "<38", "no", "yes", "no", "no", "no", "yes", 0);
                yield return new Rochdale(119, "yes", ">38", "no", "yes", "no", "no", "no", "yes", 0);
                yield return new Rochdale(120, "no", ">38", "no", "yes", "no", "no", "no", "yes", 0);
                yield return new Rochdale(121, "yes", "<38", "yes", "no", "no", "no", "no", "yes", 3);
                yield return new Rochdale(122, "no", "<38", "yes", "no", "no", "no", "no", "yes", 0);
                yield return new Rochdale(123, "yes", ">38", "yes", "no", "no", "no", "no", "yes", 25);
                yield return new Rochdale(124, "no", ">38", "yes", "no", "no", "no", "no", "yes", 10);
                yield return new Rochdale(125, "yes", "<38", "no", "no", "no", "no", "no", "yes", 0);
                yield return new Rochdale(126, "no", "<38", "no", "no", "no", "no", "no", "yes", 0);
                yield return new Rochdale(127, "yes", ">38", "no", "no", "no", "no", "no", "yes", 4);
                yield return new Rochdale(128, "no", ">38", "no", "no", "no", "no", "no", "yes", 7);
                yield return new Rochdale(129, "yes", "<38", "yes", "yes", "yes", "yes", "yes", "no", 1);
                yield return new Rochdale(130, "no", "<38", "yes", "yes", "yes", "yes", "yes", "no", 1);
                yield return new Rochdale(131, "yes", ">38", "yes", "yes", "yes", "yes", "yes", "no", 0);
                yield return new Rochdale(132, "no", ">38", "yes", "yes", "yes", "yes", "yes", "no", 0);
                yield return new Rochdale(133, "yes", "<38", "no", "yes", "yes", "yes", "yes", "no", 0);
                yield return new Rochdale(134, "no", "<38", "no", "yes", "yes", "yes", "yes", "no", 1);
                yield return new Rochdale(135, "yes", ">38", "no", "yes", "yes", "yes", "yes", "no", 0);
                yield return new Rochdale(136, "no", ">38", "no", "yes", "yes", "yes", "yes", "no", 0);
                yield return new Rochdale(137, "yes", "<38", "yes", "no", "yes", "yes", "yes", "no", 0);
                yield return new Rochdale(138, "no", "<38", "yes", "no", "yes", "yes", "yes", "no", 2);
                yield return new Rochdale(139, "yes", ">38", "yes", "no", "yes", "yes", "yes", "no", 0);
                yield return new Rochdale(140, "no", ">38", "yes", "no", "yes", "yes", "yes", "no", 0);
                yield return new Rochdale(141, "yes", "<38", "no", "no", "yes", "yes", "yes", "no", 0);
                yield return new Rochdale(142, "no", "<38", "no", "no", "yes", "yes", "yes", "no", 1);
                yield return new Rochdale(143, "yes", ">38", "no", "no", "yes", "yes", "yes", "no", 0);
                yield return new Rochdale(144, "no", ">38", "no", "no", "yes", "yes", "yes", "no", 0);
                yield return new Rochdale(145, "yes", "<38", "yes", "yes", "no", "yes", "yes", "no", 1);
                yield return new Rochdale(146, "no", "<38", "yes", "yes", "no", "yes", "yes", "no", 1);
                yield return new Rochdale(147, "yes", ">38", "yes", "yes", "no", "yes", "yes", "no", 0);
                yield return new Rochdale(148, "no", ">38", "yes", "yes", "no", "yes", "yes", "no", 0);
                yield return new Rochdale(149, "yes", "<38", "no", "yes", "no", "yes", "yes", "no", 0);
                yield return new Rochdale(150, "no", "<38", "no", "yes", "no", "yes", "yes", "no", 1);
                yield return new Rochdale(151, "yes", ">38", "no", "yes", "no", "yes", "yes", "no", 0);
                yield return new Rochdale(152, "no", ">38", "no", "yes", "no", "yes", "yes", "no", 0);
                yield return new Rochdale(153, "yes", "<38", "yes", "no", "no", "yes", "yes", "no", 0);
                yield return new Rochdale(154, "no", "<38", "yes", "no", "no", "yes", "yes", "no", 0);
                yield return new Rochdale(155, "yes", ">38", "yes", "no", "no", "yes", "yes", "no", 0);
                yield return new Rochdale(156, "no", ">38", "yes", "no", "no", "yes", "yes", "no", 0);
                yield return new Rochdale(157, "yes", "<38", "no", "no", "no", "yes", "yes", "no", 0);
                yield return new Rochdale(158, "no", "<38", "no", "no", "no", "yes", "yes", "no", 0);
                yield return new Rochdale(159, "yes", ">38", "no", "no", "no", "yes", "yes", "no", 0);
                yield return new Rochdale(160, "no", ">38", "no", "no", "no", "yes", "yes", "no", 2);
                yield return new Rochdale(161, "yes", "<38", "yes", "yes", "yes", "no", "yes", "no", 0);
                yield return new Rochdale(162, "no", "<38", "yes", "yes", "yes", "no", "yes", "no", 1);
                yield return new Rochdale(163, "yes", ">38", "yes", "yes", "yes", "no", "yes", "no", 0);
                yield return new Rochdale(164, "no", ">38", "yes", "yes", "yes", "no", "yes", "no", 0);
                yield return new Rochdale(165, "yes", "<38", "no", "yes", "yes", "no", "yes", "no", 0);
                yield return new Rochdale(166, "no", "<38", "no", "yes", "yes", "no", "yes", "no", 1);
                yield return new Rochdale(167, "yes", ">38", "no", "yes", "yes", "no", "yes", "no", 0);
                yield return new Rochdale(168, "no", ">38", "no", "yes", "yes", "no", "yes", "no", 0);
                yield return new Rochdale(169, "yes", "<38", "yes", "no", "yes", "no", "yes", "no", 0);
                yield return new Rochdale(170, "no", "<38", "yes", "no", "yes", "no", "yes", "no", 0);
                yield return new Rochdale(171, "yes", ">38", "yes", "no", "yes", "no", "yes", "no", 0);
                yield return new Rochdale(172, "no", ">38", "yes", "no", "yes", "no", "yes", "no", 0);
                yield return new Rochdale(173, "yes", "<38", "no", "no", "yes", "no", "yes", "no", 0);
                yield return new Rochdale(174, "no", "<38", "no", "no", "yes", "no", "yes", "no", 0);
                yield return new Rochdale(175, "yes", ">38", "no", "no", "yes", "no", "yes", "no", 0);
                yield return new Rochdale(176, "no", ">38", "no", "no", "yes", "no", "yes", "no", 0);
                yield return new Rochdale(177, "yes", "<38", "yes", "yes", "no", "no", "yes", "no", 0);
                yield return new Rochdale(178, "no", "<38", "yes", "yes", "no", "no", "yes", "no", 11);
                yield return new Rochdale(179, "yes", ">38", "yes", "yes", "no", "no", "yes", "no", 0);
                yield return new Rochdale(180, "no", ">38", "yes", "yes", "no", "no", "yes", "no", 2);
                yield return new Rochdale(181, "yes", "<38", "no", "yes", "no", "no", "yes", "no", 0);
                yield return new Rochdale(182, "no", "<38", "no", "yes", "no", "no", "yes", "no", 8);
                yield return new Rochdale(183, "yes", ">38", "no", "yes", "no", "no", "yes", "no", 0);
                yield return new Rochdale(184, "no", ">38", "no", "yes", "no", "no", "yes", "no", 3);
                yield return new Rochdale(185, "yes", "<38", "yes", "no", "no", "no", "yes", "no", 2);
                yield return new Rochdale(186, "no", "<38", "yes", "no", "no", "no", "yes", "no", 2);
                yield return new Rochdale(187, "yes", ">38", "yes", "no", "no", "no", "yes", "no", 0);
                yield return new Rochdale(188, "no", ">38", "yes", "no", "no", "no", "yes", "no", 1);
                yield return new Rochdale(189, "yes", "<38", "no", "no", "no", "no", "yes", "no", 0);
                yield return new Rochdale(190, "no", "<38", "no", "no", "no", "no", "yes", "no", 2);
                yield return new Rochdale(191, "yes", ">38", "no", "no", "no", "no", "yes", "no", 0);
                yield return new Rochdale(192, "no", ">38", "no", "no", "no", "no", "yes", "no", 3);
                yield return new Rochdale(193, "yes", "<38", "yes", "yes", "yes", "yes", "no", "no", 29);
                yield return new Rochdale(194, "no", "<38", "yes", "yes", "yes", "yes", "no", "no", 26);
                yield return new Rochdale(195, "yes", ">38", "yes", "yes", "yes", "yes", "no", "no", 3);
                yield return new Rochdale(196, "no", ">38", "yes", "yes", "yes", "yes", "no", "no", 0);
                yield return new Rochdale(197, "yes", "<38", "no", "yes", "yes", "yes", "no", "no", 0);
                yield return new Rochdale(198, "no", "<38", "no", "yes", "yes", "yes", "no", "no", 0);
                yield return new Rochdale(199, "yes", ">38", "no", "yes", "yes", "yes", "no", "no", 0);
                yield return new Rochdale(200, "no", ">38", "no", "yes", "yes", "yes", "no", "no", 0);
                yield return new Rochdale(201, "yes", "<38", "yes", "no", "yes", "yes", "no", "no", 57);
                yield return new Rochdale(202, "no", "<38", "yes", "no", "yes", "yes", "no", "no", 6);
                yield return new Rochdale(203, "yes", ">38", "yes", "no", "yes", "yes", "no", "no", 43);
                yield return new Rochdale(204, "no", ">38", "yes", "no", "yes", "yes", "no", "no", 10);
                yield return new Rochdale(205, "yes", "<38", "no", "no", "yes", "yes", "no", "no", 0);
                yield return new Rochdale(206, "no", "<38", "no", "no", "yes", "yes", "no", "no", 0);
                yield return new Rochdale(207, "yes", ">38", "no", "no", "yes", "yes", "no", "no", 2);
                yield return new Rochdale(208, "no", ">38", "no", "no", "yes", "yes", "no", "no", 1);
                yield return new Rochdale(209, "yes", "<38", "yes", "yes", "no", "yes", "no", "no", 11);
                yield return new Rochdale(210, "no", "<38", "yes", "yes", "no", "yes", "no", "no", 13);
                yield return new Rochdale(211, "yes", ">38", "yes", "yes", "no", "yes", "no", "no", 2);
                yield return new Rochdale(212, "no", ">38", "yes", "yes", "no", "yes", "no", "no", 0);
                yield return new Rochdale(213, "yes", "<38", "no", "yes", "no", "yes", "no", "no", 0);
                yield return new Rochdale(214, "no", "<38", "no", "yes", "no", "yes", "no", "no", 6);
                yield return new Rochdale(215, "yes", ">38", "no", "yes", "no", "yes", "no", "no", 0);
                yield return new Rochdale(216, "no", ">38", "no", "yes", "no", "yes", "no", "no", 0);
                yield return new Rochdale(217, "yes", "<38", "yes", "no", "no", "yes", "no", "no", 23);
                yield return new Rochdale(218, "no", "<38", "yes", "no", "no", "yes", "no", "no", 5);
                yield return new Rochdale(219, "yes", ">38", "yes", "no", "no", "yes", "no", "no", 37);
                yield return new Rochdale(220, "no", ">38", "yes", "no", "no", "yes", "no", "no", 16);
                yield return new Rochdale(221, "yes", "<38", "no", "no", "no", "yes", "no", "no", 4);
                yield return new Rochdale(222, "no", "<38", "no", "no", "no", "yes", "no", "no", 0);
                yield return new Rochdale(223, "yes", ">38", "no", "no", "no", "yes", "no", "no", 2);
                yield return new Rochdale(224, "no", ">38", "no", "no", "no", "yes", "no", "no", 1);
                yield return new Rochdale(225, "yes", "<38", "yes", "yes", "yes", "no", "no", "no", 11);
                yield return new Rochdale(226, "no", "<38", "yes", "yes", "yes", "no", "no", "no", 3);
                yield return new Rochdale(227, "yes", ">38", "yes", "yes", "yes", "no", "no", "no", 0);
                yield return new Rochdale(228, "no", ">38", "yes", "yes", "yes", "no", "no", "no", 1);
                yield return new Rochdale(229, "yes", "<38", "no", "yes", "yes", "no", "no", "no", 0);
                yield return new Rochdale(230, "no", "<38", "no", "yes", "yes", "no", "no", "no", 1);
                yield return new Rochdale(231, "yes", ">38", "no", "yes", "yes", "no", "no", "no", 0);
                yield return new Rochdale(232, "no", ">38", "no", "yes", "yes", "no", "no", "no", 0);
                yield return new Rochdale(233, "yes", "<38", "yes", "no", "yes", "no", "no", "no", 22);
                yield return new Rochdale(234, "no", "<38", "yes", "no", "yes", "no", "no", "no", 4);
                yield return new Rochdale(235, "yes", ">38", "yes", "no", "yes", "no", "no", "no", 15);
                yield return new Rochdale(236, "no", ">38", "yes", "no", "yes", "no", "no", "no", 0);
                yield return new Rochdale(237, "yes", "<38", "no", "no", "yes", "no", "no", "no", 1);
                yield return new Rochdale(238, "no", "<38", "no", "no", "yes", "no", "no", "no", 0);
                yield return new Rochdale(239, "yes", ">38", "no", "no", "yes", "no", "no", "no", 0);
                yield return new Rochdale(240, "no", ">38", "no", "no", "yes", "no", "no", "no", 1);
                yield return new Rochdale(241, "yes", "<38", "yes", "yes", "no", "no", "no", "no", 5);
                yield return new Rochdale(242, "no", "<38", "yes", "yes", "no", "no", "no", "no", 8);
                yield return new Rochdale(243, "yes", ">38", "yes", "yes", "no", "no", "no", "no", 0);
                yield return new Rochdale(244, "no", ">38", "yes", "yes", "no", "no", "no", "no", 1);
                yield return new Rochdale(245, "yes", "<38", "no", "yes", "no", "no", "no", "no", 1);
                yield return new Rochdale(246, "no", "<38", "no", "yes", "no", "no", "no", "no", 4);
                yield return new Rochdale(247, "yes", ">38", "no", "yes", "no", "no", "no", "no", 0);
                yield return new Rochdale(248, "no", ">38", "no", "yes", "no", "no", "no", "no", 0);
                yield return new Rochdale(249, "yes", "<38", "yes", "no", "no", "no", "no", "no", 18);
                yield return new Rochdale(250, "no", "<38", "yes", "no", "no", "no", "no", "no", 5);
                yield return new Rochdale(251, "yes", ">38", "yes", "no", "no", "no", "no", "no", 41);
                yield return new Rochdale(252, "no", ">38", "yes", "no", "no", "no", "no", "no", 17);
                yield return new Rochdale(253, "yes", "<38", "no", "no", "no", "no", "no", "no", 3);
                yield return new Rochdale(254, "no", "<38", "no", "no", "no", "no", "no", "no", 5);
                yield return new Rochdale(255, "yes", ">38", "no", "no", "no", "no", "no", "no", 2);
                yield return new Rochdale(256, "no", ">38", "no", "no", "no", "no", "no", "no", 4);
            }
        }
    }
}
