// ReSharper disable All

namespace Rdatasets.vcd
{
    using System.Collections.Generic;

    /// <summary>
    /// Von Bortkiewicz Horse Kicks Data
    /// </summary>

    public class VonBort
    {
        public readonly int deaths;
        public readonly int year;
        public readonly string corps;
        public readonly string fisher;

        public VonBort(int deaths, int year, string corps, string fisher)
        {
            this.deaths = deaths;
            this.year = year;
            this.corps = corps;
            this.fisher = fisher;
        }

        public static IEnumerable<VonBort> Data
        {
            get
            {
                yield return new VonBort(0, 1875, "G", "no");
                yield return new VonBort(0, 1875, "I", "no");
                yield return new VonBort(0, 1875, "II", "yes");
                yield return new VonBort(0, 1875, "III", "yes");
                yield return new VonBort(0, 1875, "IV", "yes");
                yield return new VonBort(0, 1875, "V", "yes");
                yield return new VonBort(0, 1875, "VI", "no");
                yield return new VonBort(1, 1875, "VII", "yes");
                yield return new VonBort(1, 1875, "VIII", "yes");
                yield return new VonBort(0, 1875, "IX", "yes");
                yield return new VonBort(0, 1875, "X", "yes");
                yield return new VonBort(0, 1875, "XI", "no");
                yield return new VonBort(1, 1875, "XIV", "yes");
                yield return new VonBort(0, 1875, "XV", "yes");
                yield return new VonBort(2, 1876, "G", "no");
                yield return new VonBort(0, 1876, "I", "no");
                yield return new VonBort(0, 1876, "II", "yes");
                yield return new VonBort(0, 1876, "III", "yes");
                yield return new VonBort(1, 1876, "IV", "yes");
                yield return new VonBort(0, 1876, "V", "yes");
                yield return new VonBort(0, 1876, "VI", "no");
                yield return new VonBort(0, 1876, "VII", "yes");
                yield return new VonBort(0, 1876, "VIII", "yes");
                yield return new VonBort(0, 1876, "IX", "yes");
                yield return new VonBort(0, 1876, "X", "yes");
                yield return new VonBort(0, 1876, "XI", "no");
                yield return new VonBort(1, 1876, "XIV", "yes");
                yield return new VonBort(1, 1876, "XV", "yes");
                yield return new VonBort(2, 1877, "G", "no");
                yield return new VonBort(0, 1877, "I", "no");
                yield return new VonBort(0, 1877, "II", "yes");
                yield return new VonBort(0, 1877, "III", "yes");
                yield return new VonBort(0, 1877, "IV", "yes");
                yield return new VonBort(0, 1877, "V", "yes");
                yield return new VonBort(1, 1877, "VI", "no");
                yield return new VonBort(1, 1877, "VII", "yes");
                yield return new VonBort(0, 1877, "VIII", "yes");
                yield return new VonBort(0, 1877, "IX", "yes");
                yield return new VonBort(1, 1877, "X", "yes");
                yield return new VonBort(0, 1877, "XI", "no");
                yield return new VonBort(2, 1877, "XIV", "yes");
                yield return new VonBort(0, 1877, "XV", "yes");
                yield return new VonBort(1, 1878, "G", "no");
                yield return new VonBort(2, 1878, "I", "no");
                yield return new VonBort(2, 1878, "II", "yes");
                yield return new VonBort(1, 1878, "III", "yes");
                yield return new VonBort(1, 1878, "IV", "yes");
                yield return new VonBort(0, 1878, "V", "yes");
                yield return new VonBort(0, 1878, "VI", "no");
                yield return new VonBort(0, 1878, "VII", "yes");
                yield return new VonBort(0, 1878, "VIII", "yes");
                yield return new VonBort(0, 1878, "IX", "yes");
                yield return new VonBort(1, 1878, "X", "yes");
                yield return new VonBort(0, 1878, "XI", "no");
                yield return new VonBort(1, 1878, "XIV", "yes");
                yield return new VonBort(0, 1878, "XV", "yes");
                yield return new VonBort(0, 1879, "G", "no");
                yield return new VonBort(0, 1879, "I", "no");
                yield return new VonBort(0, 1879, "II", "yes");
                yield return new VonBort(1, 1879, "III", "yes");
                yield return new VonBort(1, 1879, "IV", "yes");
                yield return new VonBort(2, 1879, "V", "yes");
                yield return new VonBort(2, 1879, "VI", "no");
                yield return new VonBort(0, 1879, "VII", "yes");
                yield return new VonBort(1, 1879, "VIII", "yes");
                yield return new VonBort(0, 1879, "IX", "yes");
                yield return new VonBort(0, 1879, "X", "yes");
                yield return new VonBort(2, 1879, "XI", "no");
                yield return new VonBort(1, 1879, "XIV", "yes");
                yield return new VonBort(0, 1879, "XV", "yes");
                yield return new VonBort(0, 1880, "G", "no");
                yield return new VonBort(3, 1880, "I", "no");
                yield return new VonBort(2, 1880, "II", "yes");
                yield return new VonBort(1, 1880, "III", "yes");
                yield return new VonBort(1, 1880, "IV", "yes");
                yield return new VonBort(1, 1880, "V", "yes");
                yield return new VonBort(0, 1880, "VI", "no");
                yield return new VonBort(0, 1880, "VII", "yes");
                yield return new VonBort(0, 1880, "VIII", "yes");
                yield return new VonBort(2, 1880, "IX", "yes");
                yield return new VonBort(1, 1880, "X", "yes");
                yield return new VonBort(4, 1880, "XI", "no");
                yield return new VonBort(3, 1880, "XIV", "yes");
                yield return new VonBort(0, 1880, "XV", "yes");
                yield return new VonBort(1, 1881, "G", "no");
                yield return new VonBort(0, 1881, "I", "no");
                yield return new VonBort(0, 1881, "II", "yes");
                yield return new VonBort(2, 1881, "III", "yes");
                yield return new VonBort(1, 1881, "IV", "yes");
                yield return new VonBort(0, 1881, "V", "yes");
                yield return new VonBort(0, 1881, "VI", "no");
                yield return new VonBort(1, 1881, "VII", "yes");
                yield return new VonBort(0, 1881, "VIII", "yes");
                yield return new VonBort(1, 1881, "IX", "yes");
                yield return new VonBort(0, 1881, "X", "yes");
                yield return new VonBort(0, 1881, "XI", "no");
                yield return new VonBort(0, 1881, "XIV", "yes");
                yield return new VonBort(0, 1881, "XV", "yes");
                yield return new VonBort(1, 1882, "G", "no");
                yield return new VonBort(2, 1882, "I", "no");
                yield return new VonBort(0, 1882, "II", "yes");
                yield return new VonBort(0, 1882, "III", "yes");
                yield return new VonBort(0, 1882, "IV", "yes");
                yield return new VonBort(0, 1882, "V", "yes");
                yield return new VonBort(1, 1882, "VI", "no");
                yield return new VonBort(0, 1882, "VII", "yes");
                yield return new VonBort(1, 1882, "VIII", "yes");
                yield return new VonBort(1, 1882, "IX", "yes");
                yield return new VonBort(2, 1882, "X", "yes");
                yield return new VonBort(1, 1882, "XI", "no");
                yield return new VonBort(4, 1882, "XIV", "yes");
                yield return new VonBort(1, 1882, "XV", "yes");
                yield return new VonBort(0, 1883, "G", "no");
                yield return new VonBort(0, 1883, "I", "no");
                yield return new VonBort(1, 1883, "II", "yes");
                yield return new VonBort(2, 1883, "III", "yes");
                yield return new VonBort(0, 1883, "IV", "yes");
                yield return new VonBort(1, 1883, "V", "yes");
                yield return new VonBort(2, 1883, "VI", "no");
                yield return new VonBort(1, 1883, "VII", "yes");
                yield return new VonBort(0, 1883, "VIII", "yes");
                yield return new VonBort(1, 1883, "IX", "yes");
                yield return new VonBort(0, 1883, "X", "yes");
                yield return new VonBort(3, 1883, "XI", "no");
                yield return new VonBort(0, 1883, "XIV", "yes");
                yield return new VonBort(0, 1883, "XV", "yes");
                yield return new VonBort(3, 1884, "G", "no");
                yield return new VonBort(0, 1884, "I", "no");
                yield return new VonBort(1, 1884, "II", "yes");
                yield return new VonBort(0, 1884, "III", "yes");
                yield return new VonBort(0, 1884, "IV", "yes");
                yield return new VonBort(0, 1884, "V", "yes");
                yield return new VonBort(0, 1884, "VI", "no");
                yield return new VonBort(1, 1884, "VII", "yes");
                yield return new VonBort(0, 1884, "VIII", "yes");
                yield return new VonBort(0, 1884, "IX", "yes");
                yield return new VonBort(2, 1884, "X", "yes");
                yield return new VonBort(0, 1884, "XI", "no");
                yield return new VonBort(1, 1884, "XIV", "yes");
                yield return new VonBort(1, 1884, "XV", "yes");
                yield return new VonBort(0, 1885, "G", "no");
                yield return new VonBort(0, 1885, "I", "no");
                yield return new VonBort(0, 1885, "II", "yes");
                yield return new VonBort(0, 1885, "III", "yes");
                yield return new VonBort(0, 1885, "IV", "yes");
                yield return new VonBort(0, 1885, "V", "yes");
                yield return new VonBort(1, 1885, "VI", "no");
                yield return new VonBort(0, 1885, "VII", "yes");
                yield return new VonBort(0, 1885, "VIII", "yes");
                yield return new VonBort(2, 1885, "IX", "yes");
                yield return new VonBort(0, 1885, "X", "yes");
                yield return new VonBort(1, 1885, "XI", "no");
                yield return new VonBort(0, 1885, "XIV", "yes");
                yield return new VonBort(1, 1885, "XV", "yes");
                yield return new VonBort(2, 1886, "G", "no");
                yield return new VonBort(1, 1886, "I", "no");
                yield return new VonBort(0, 1886, "II", "yes");
                yield return new VonBort(0, 1886, "III", "yes");
                yield return new VonBort(1, 1886, "IV", "yes");
                yield return new VonBort(1, 1886, "V", "yes");
                yield return new VonBort(1, 1886, "VI", "no");
                yield return new VonBort(0, 1886, "VII", "yes");
                yield return new VonBort(0, 1886, "VIII", "yes");
                yield return new VonBort(1, 1886, "IX", "yes");
                yield return new VonBort(0, 1886, "X", "yes");
                yield return new VonBort(1, 1886, "XI", "no");
                yield return new VonBort(3, 1886, "XIV", "yes");
                yield return new VonBort(0, 1886, "XV", "yes");
                yield return new VonBort(1, 1887, "G", "no");
                yield return new VonBort(1, 1887, "I", "no");
                yield return new VonBort(2, 1887, "II", "yes");
                yield return new VonBort(1, 1887, "III", "yes");
                yield return new VonBort(0, 1887, "IV", "yes");
                yield return new VonBort(0, 1887, "V", "yes");
                yield return new VonBort(3, 1887, "VI", "no");
                yield return new VonBort(2, 1887, "VII", "yes");
                yield return new VonBort(1, 1887, "VIII", "yes");
                yield return new VonBort(1, 1887, "IX", "yes");
                yield return new VonBort(0, 1887, "X", "yes");
                yield return new VonBort(1, 1887, "XI", "no");
                yield return new VonBort(2, 1887, "XIV", "yes");
                yield return new VonBort(0, 1887, "XV", "yes");
                yield return new VonBort(0, 1888, "G", "no");
                yield return new VonBort(1, 1888, "I", "no");
                yield return new VonBort(1, 1888, "II", "yes");
                yield return new VonBort(0, 1888, "III", "yes");
                yield return new VonBort(0, 1888, "IV", "yes");
                yield return new VonBort(1, 1888, "V", "yes");
                yield return new VonBort(1, 1888, "VI", "no");
                yield return new VonBort(0, 1888, "VII", "yes");
                yield return new VonBort(0, 1888, "VIII", "yes");
                yield return new VonBort(0, 1888, "IX", "yes");
                yield return new VonBort(0, 1888, "X", "yes");
                yield return new VonBort(1, 1888, "XI", "no");
                yield return new VonBort(1, 1888, "XIV", "yes");
                yield return new VonBort(0, 1888, "XV", "yes");
                yield return new VonBort(0, 1889, "G", "no");
                yield return new VonBort(0, 1889, "I", "no");
                yield return new VonBort(1, 1889, "II", "yes");
                yield return new VonBort(1, 1889, "III", "yes");
                yield return new VonBort(0, 1889, "IV", "yes");
                yield return new VonBort(1, 1889, "V", "yes");
                yield return new VonBort(1, 1889, "VI", "no");
                yield return new VonBort(0, 1889, "VII", "yes");
                yield return new VonBort(0, 1889, "VIII", "yes");
                yield return new VonBort(1, 1889, "IX", "yes");
                yield return new VonBort(2, 1889, "X", "yes");
                yield return new VonBort(2, 1889, "XI", "no");
                yield return new VonBort(0, 1889, "XIV", "yes");
                yield return new VonBort(2, 1889, "XV", "yes");
                yield return new VonBort(1, 1890, "G", "no");
                yield return new VonBort(2, 1890, "I", "no");
                yield return new VonBort(0, 1890, "II", "yes");
                yield return new VonBort(2, 1890, "III", "yes");
                yield return new VonBort(0, 1890, "IV", "yes");
                yield return new VonBort(1, 1890, "V", "yes");
                yield return new VonBort(1, 1890, "VI", "no");
                yield return new VonBort(2, 1890, "VII", "yes");
                yield return new VonBort(0, 1890, "VIII", "yes");
                yield return new VonBort(2, 1890, "IX", "yes");
                yield return new VonBort(1, 1890, "X", "yes");
                yield return new VonBort(1, 1890, "XI", "no");
                yield return new VonBort(2, 1890, "XIV", "yes");
                yield return new VonBort(2, 1890, "XV", "yes");
                yield return new VonBort(0, 1891, "G", "no");
                yield return new VonBort(0, 1891, "I", "no");
                yield return new VonBort(0, 1891, "II", "yes");
                yield return new VonBort(1, 1891, "III", "yes");
                yield return new VonBort(1, 1891, "IV", "yes");
                yield return new VonBort(1, 1891, "V", "yes");
                yield return new VonBort(0, 1891, "VI", "no");
                yield return new VonBort(1, 1891, "VII", "yes");
                yield return new VonBort(1, 1891, "VIII", "yes");
                yield return new VonBort(0, 1891, "IX", "yes");
                yield return new VonBort(3, 1891, "X", "yes");
                yield return new VonBort(3, 1891, "XI", "no");
                yield return new VonBort(1, 1891, "XIV", "yes");
                yield return new VonBort(0, 1891, "XV", "yes");
                yield return new VonBort(1, 1892, "G", "no");
                yield return new VonBort(3, 1892, "I", "no");
                yield return new VonBort(2, 1892, "II", "yes");
                yield return new VonBort(0, 1892, "III", "yes");
                yield return new VonBort(1, 1892, "IV", "yes");
                yield return new VonBort(1, 1892, "V", "yes");
                yield return new VonBort(3, 1892, "VI", "no");
                yield return new VonBort(0, 1892, "VII", "yes");
                yield return new VonBort(1, 1892, "VIII", "yes");
                yield return new VonBort(1, 1892, "IX", "yes");
                yield return new VonBort(0, 1892, "X", "yes");
                yield return new VonBort(1, 1892, "XI", "no");
                yield return new VonBort(1, 1892, "XIV", "yes");
                yield return new VonBort(0, 1892, "XV", "yes");
                yield return new VonBort(0, 1893, "G", "no");
                yield return new VonBort(1, 1893, "I", "no");
                yield return new VonBort(0, 1893, "II", "yes");
                yield return new VonBort(0, 1893, "III", "yes");
                yield return new VonBort(0, 1893, "IV", "yes");
                yield return new VonBort(1, 1893, "V", "yes");
                yield return new VonBort(0, 1893, "VI", "no");
                yield return new VonBort(2, 1893, "VII", "yes");
                yield return new VonBort(0, 1893, "VIII", "yes");
                yield return new VonBort(0, 1893, "IX", "yes");
                yield return new VonBort(1, 1893, "X", "yes");
                yield return new VonBort(3, 1893, "XI", "no");
                yield return new VonBort(0, 1893, "XIV", "yes");
                yield return new VonBort(0, 1893, "XV", "yes");
                yield return new VonBort(1, 1894, "G", "no");
                yield return new VonBort(0, 1894, "I", "no");
                yield return new VonBort(0, 1894, "II", "yes");
                yield return new VonBort(0, 1894, "III", "yes");
                yield return new VonBort(0, 1894, "IV", "yes");
                yield return new VonBort(0, 1894, "V", "yes");
                yield return new VonBort(0, 1894, "VI", "no");
                yield return new VonBort(0, 1894, "VII", "yes");
                yield return new VonBort(1, 1894, "VIII", "yes");
                yield return new VonBort(0, 1894, "IX", "yes");
                yield return new VonBort(1, 1894, "X", "yes");
                yield return new VonBort(1, 1894, "XI", "no");
                yield return new VonBort(0, 1894, "XIV", "yes");
                yield return new VonBort(0, 1894, "XV", "yes");
            }
        }
    }
}
