// ReSharper disable All

namespace Rdatasets.Zelig
{
    using System.Collections.Generic;

    /// <summary>
    /// Sample Data on Home Runs Hit By Mark McGwire and Sammy Sosa in 1998.
    /// </summary>

    public class homerun
    {
        public readonly int gameno;
        public readonly string month;
        public readonly int homeruns;
        public readonly int playerstatus;
        public readonly string player;

        public homerun(int gameno, string month, int homeruns, int playerstatus, string player)
        {
            this.gameno = gameno;
            this.month = month;
            this.homeruns = homeruns;
            this.playerstatus = playerstatus;
            this.player = player;
        }

        public static IEnumerable<homerun> Data
        {
            get
            {
                yield return new homerun(1, "March", 1, 0, "McGwire");
                yield return new homerun(2, "April", 1, 0, "McGwire");
                yield return new homerun(3, "April", 1, 0, "McGwire");
                yield return new homerun(4, "April", 1, 0, "McGwire");
                yield return new homerun(5, "April", 0, 0, "McGwire");
                yield return new homerun(6, "April", 0, 0, "McGwire");
                yield return new homerun(7, "April", 0, 0, "McGwire");
                yield return new homerun(8, "April", 0, 0, "McGwire");
                yield return new homerun(9, "April", 0, 0, "McGwire");
                yield return new homerun(10, "April", 0, 0, "McGwire");
                yield return new homerun(11, "April", 0, 0, "McGwire");
                yield return new homerun(12, "April", 0, 0, "McGwire");
                yield return new homerun(13, "April", 3, 0, "McGwire");
                yield return new homerun(14, "April", 0, 0, "McGwire");
                yield return new homerun(16, "April", 1, 0, "McGwire");
                yield return new homerun(17, "April", 0, 0, "McGwire");
                yield return new homerun(18, "April", 0, 0, "McGwire");
                yield return new homerun(19, "April", 1, 0, "McGwire");
                yield return new homerun(20, "April", 0, 0, "McGwire");
                yield return new homerun(22, "April", 0, 0, "McGwire");
                yield return new homerun(23, "April", 1, 0, "McGwire");
                yield return new homerun(24, "April", 0, 0, "McGwire");
                yield return new homerun(25, "April", 0, 0, "McGwire");
                yield return new homerun(26, "April", 0, 0, "McGwire");
                yield return new homerun(27, "April", 1, 0, "McGwire");
                yield return new homerun(28, "May", 1, 0, "McGwire");
                yield return new homerun(29, "May", 0, 0, "McGwire");
                yield return new homerun(30, "May", 0, 0, "McGwire");
                yield return new homerun(31, "May", 0, 0, "McGwire");
                yield return new homerun(32, "May", 0, 0, "McGwire");
                yield return new homerun(33, "May", 0, 0, "McGwire");
                yield return new homerun(34, "May", 1, 0, "McGwire");
                yield return new homerun(35, "May", 0, 0, "McGwire");
                yield return new homerun(36, "May", 1, 0, "McGwire");
                yield return new homerun(37, "May", 0, 0, "McGwire");
                yield return new homerun(38, "May", 1, 0, "McGwire");
                yield return new homerun(39, "May", 0, 0, "McGwire");
                yield return new homerun(40, "May", 1, 0, "McGwire");
                yield return new homerun(41, "May", 0, 0, "McGwire");
                yield return new homerun(42, "May", 1, 0, "McGwire");
                yield return new homerun(43, "May", 3, 0, "McGwire");
                yield return new homerun(45, "May", 0, 0, "McGwire");
                yield return new homerun(46, "May", 1, 0, "McGwire");
                yield return new homerun(47, "May", 2, 0, "McGwire");
                yield return new homerun(48, "May", 1, 0, "McGwire");
                yield return new homerun(49, "May", 1, 0, "McGwire");
                yield return new homerun(50, "May", 0, 0, "McGwire");
                yield return new homerun(51, "May", 0, 0, "McGwire");
                yield return new homerun(52, "May", 1, 0, "McGwire");
                yield return new homerun(53, "May", 1, 0, "McGwire");
                yield return new homerun(54, "May", 0, 0, "McGwire");
                yield return new homerun(55, "June", 0, 0, "McGwire");
                yield return new homerun(59, "June", 1, 0, "McGwire");
                yield return new homerun(60, "June", 0, 0, "McGwire");
                yield return new homerun(61, "June", 0, 0, "McGwire");
                yield return new homerun(62, "June", 1, 0, "McGwire");
                yield return new homerun(63, "June", 0, 0, "McGwire");
                yield return new homerun(64, "June", 1, 0, "McGwire");
                yield return new homerun(65, "June", 1, 0, "McGwire");
                yield return new homerun(66, "June", 0, 0, "McGwire");
                yield return new homerun(67, "June", 0, 0, "McGwire");
                yield return new homerun(68, "June", 0, 0, "McGwire");
                yield return new homerun(69, "June", 1, 0, "McGwire");
                yield return new homerun(70, "June", 1, 0, "McGwire");
                yield return new homerun(71, "June", 0, 0, "McGwire");
                yield return new homerun(72, "June", 0, 0, "McGwire");
                yield return new homerun(73, "June", 0, 0, "McGwire");
                yield return new homerun(74, "June", 0, 0, "McGwire");
                yield return new homerun(75, "June", 0, 0, "McGwire");
                yield return new homerun(76, "June", 1, 0, "McGwire");
                yield return new homerun(77, "June", 1, 0, "McGwire");
                yield return new homerun(78, "June", 0, 0, "McGwire");
                yield return new homerun(79, "June", 1, 0, "McGwire");
                yield return new homerun(80, "June", 0, 0, "McGwire");
                yield return new homerun(81, "June", 1, 0, "McGwire");
                yield return new homerun(82, "July", 0, 0, "McGwire");
                yield return new homerun(83, "July", 0, 0, "McGwire");
                yield return new homerun(84, "July", 0, 0, "McGwire");
                yield return new homerun(85, "July", 0, 0, "McGwire");
                yield return new homerun(86, "July", 0, 0, "McGwire");
                yield return new homerun(87, "July", 0, 0, "McGwire");
                yield return new homerun(88, "July", 0, 0, "McGwire");
                yield return new homerun(89, "July", 1, 0, "McGwire");
                yield return new homerun(90, "July", 2, 0, "McGwire");
                yield return new homerun(91, "July", 0, 0, "McGwire");
                yield return new homerun(92, "July", 0, 0, "McGwire");
                yield return new homerun(93, "July", 0, 0, "McGwire");
                yield return new homerun(94, "July", 0, 0, "McGwire");
                yield return new homerun(95, "July", 2, 0, "McGwire");
                yield return new homerun(96, "July", 0, 0, "McGwire");
                yield return new homerun(97, "July", 0, 0, "McGwire");
                yield return new homerun(98, "July", 1, 0, "McGwire");
                yield return new homerun(99, "July", 0, 0, "McGwire");
                yield return new homerun(100, "July", 0, 0, "McGwire");
                yield return new homerun(101, "July", 0, 0, "McGwire");
                yield return new homerun(102, "July", 0, 0, "McGwire");
                yield return new homerun(103, "July", 0, 0, "McGwire");
                yield return new homerun(104, "July", 1, 0, "McGwire");
                yield return new homerun(105, "July", 1, 0, "McGwire");
                yield return new homerun(106, "July", 0, 0, "McGwire");
                yield return new homerun(107, "July", 0, 0, "McGwire");
                yield return new homerun(108, "July", 0, 0, "McGwire");
                yield return new homerun(109, "August", 0, 0, "McGwire");
                yield return new homerun(110, "August", 0, 0, "McGwire");
                yield return new homerun(111, "August", 0, 0, "McGwire");
                yield return new homerun(112, "August", 0, 0, "McGwire");
                yield return new homerun(114, "August", 0, 0, "McGwire");
                yield return new homerun(115, "August", 1, 0, "McGwire");
                yield return new homerun(116, "August", 0, 0, "McGwire");
                yield return new homerun(117, "August", 0, 0, "McGwire");
                yield return new homerun(118, "August", 1, 0, "McGwire");
                yield return new homerun(119, "August", 0, 0, "McGwire");
                yield return new homerun(120, "August", 0, 0, "McGwire");
                yield return new homerun(121, "August", 0, 0, "McGwire");
                yield return new homerun(122, "August", 0, 0, "McGwire");
                yield return new homerun(123, "August", 0, 0, "McGwire");
                yield return new homerun(124, "August", 2, 0, "McGwire");
                yield return new homerun(125, "August", 1, 0, "McGwire");
                yield return new homerun(126, "August", 1, 0, "McGwire");
                yield return new homerun(127, "August", 0, 0, "McGwire");
                yield return new homerun(128, "August", 0, 0, "McGwire");
                yield return new homerun(129, "August", 1, 0, "McGwire");
                yield return new homerun(130, "August", 1, 0, "McGwire");
                yield return new homerun(132, "August", 0, 0, "McGwire");
                yield return new homerun(133, "August", 1, 0, "McGwire");
                yield return new homerun(134, "August", 0, 0, "McGwire");
                yield return new homerun(135, "August", 0, 0, "McGwire");
                yield return new homerun(136, "August", 0, 0, "McGwire");
                yield return new homerun(137, "August", 1, 0, "McGwire");
                yield return new homerun(138, "August", 0, 0, "McGwire");
                yield return new homerun(139, "September", 2, 0, "McGwire");
                yield return new homerun(140, "September", 2, 0, "McGwire");
                yield return new homerun(141, "September", 0, 0, "McGwire");
                yield return new homerun(142, "September", 1, 0, "McGwire");
                yield return new homerun(143, "September", 0, 0, "McGwire");
                yield return new homerun(144, "September", 1, 0, "McGwire");
                yield return new homerun(145, "September", 1, 0, "McGwire");
                yield return new homerun(146, "September", 0, 0, "McGwire");
                yield return new homerun(147, "September", 0, 0, "McGwire");
                yield return new homerun(148, "September", 0, 0, "McGwire");
                yield return new homerun(149, "September", 0, 0, "McGwire");
                yield return new homerun(150, "September", 0, 0, "McGwire");
                yield return new homerun(151, "September", 0, 0, "McGwire");
                yield return new homerun(152, "September", 1, 0, "McGwire");
                yield return new homerun(153, "September", 0, 0, "McGwire");
                yield return new homerun(154, "September", 0, 0, "McGwire");
                yield return new homerun(155, "September", 1, 0, "McGwire");
                yield return new homerun(156, "September", 0, 0, "McGwire");
                yield return new homerun(157, "September", 1, 0, "McGwire");
                yield return new homerun(158, "September", 0, 0, "McGwire");
                yield return new homerun(159, "September", 0, 0, "McGwire");
                yield return new homerun(160, "September", 0, 0, "McGwire");
                yield return new homerun(161, "September", 1, 0, "McGwire");
                yield return new homerun(162, "September", 2, 0, "McGwire");
                yield return new homerun(163, "September", 2, 0, "McGwire");
                yield return new homerun(1, "March", 0, 0, "Sosa");
                yield return new homerun(2, "April", 0, 0, "Sosa");
                yield return new homerun(3, "April", 0, 0, "Sosa");
                yield return new homerun(4, "April", 0, 0, "Sosa");
                yield return new homerun(5, "April", 1, 0, "Sosa");
                yield return new homerun(6, "April", 0, 0, "Sosa");
                yield return new homerun(7, "April", 0, 0, "Sosa");
                yield return new homerun(8, "April", 0, 0, "Sosa");
                yield return new homerun(9, "April", 0, 0, "Sosa");
                yield return new homerun(10, "April", 0, 0, "Sosa");
                yield return new homerun(11, "April", 1, 0, "Sosa");
                yield return new homerun(12, "April", 0, 0, "Sosa");
                yield return new homerun(13, "April", 0, 0, "Sosa");
                yield return new homerun(14, "April", 1, 0, "Sosa");
                yield return new homerun(15, "April", 0, 0, "Sosa");
                yield return new homerun(16, "April", 0, 0, "Sosa");
                yield return new homerun(17, "April", 0, 0, "Sosa");
                yield return new homerun(18, "April", 0, 0, "Sosa");
                yield return new homerun(19, "April", 0, 0, "Sosa");
                yield return new homerun(20, "April", 0, 0, "Sosa");
                yield return new homerun(21, "April", 1, 0, "Sosa");
                yield return new homerun(22, "April", 1, 0, "Sosa");
                yield return new homerun(23, "April", 0, 0, "Sosa");
                yield return new homerun(24, "April", 0, 0, "Sosa");
                yield return new homerun(25, "April", 1, 0, "Sosa");
                yield return new homerun(26, "April", 0, 0, "Sosa");
                yield return new homerun(27, "April", 0, 0, "Sosa");
                yield return new homerun(28, "May", 0, 0, "Sosa");
                yield return new homerun(29, "May", 0, 0, "Sosa");
                yield return new homerun(30, "May", 1, 0, "Sosa");
                yield return new homerun(31, "May", 0, 0, "Sosa");
                yield return new homerun(32, "May", 0, 0, "Sosa");
                yield return new homerun(33, "May", 0, 0, "Sosa");
                yield return new homerun(34, "May", 0, 0, "Sosa");
                yield return new homerun(35, "May", 0, 0, "Sosa");
                yield return new homerun(36, "May", 0, 0, "Sosa");
                yield return new homerun(37, "May", 0, 0, "Sosa");
                yield return new homerun(38, "May", 0, 0, "Sosa");
                yield return new homerun(39, "May", 0, 0, "Sosa");
                yield return new homerun(40, "May", 0, 0, "Sosa");
                yield return new homerun(41, "May", 0, 0, "Sosa");
                yield return new homerun(42, "May", 1, 0, "Sosa");
                yield return new homerun(43, "May", 0, 0, "Sosa");
                yield return new homerun(44, "May", 0, 0, "Sosa");
                yield return new homerun(45, "May", 0, 0, "Sosa");
                yield return new homerun(46, "May", 0, 0, "Sosa");
                yield return new homerun(47, "May", 1, 0, "Sosa");
                yield return new homerun(48, "May", 0, 0, "Sosa");
                yield return new homerun(49, "May", 0, 0, "Sosa");
                yield return new homerun(50, "May", 2, 0, "Sosa");
                yield return new homerun(51, "May", 2, 0, "Sosa");
                yield return new homerun(52, "May", 0, 0, "Sosa");
                yield return new homerun(56, "June", 2, 0, "Sosa");
                yield return new homerun(57, "June", 0, 0, "Sosa");
                yield return new homerun(58, "June", 1, 0, "Sosa");
                yield return new homerun(59, "June", 1, 0, "Sosa");
                yield return new homerun(60, "June", 1, 0, "Sosa");
                yield return new homerun(61, "June", 1, 0, "Sosa");
                yield return new homerun(62, "June", 1, 0, "Sosa");
                yield return new homerun(63, "June", 0, 0, "Sosa");
                yield return new homerun(64, "June", 0, 0, "Sosa");
                yield return new homerun(65, "June", 0, 0, "Sosa");
                yield return new homerun(66, "June", 1, 0, "Sosa");
                yield return new homerun(67, "June", 0, 0, "Sosa");
                yield return new homerun(68, "June", 3, 0, "Sosa");
                yield return new homerun(69, "June", 0, 0, "Sosa");
                yield return new homerun(70, "June", 1, 0, "Sosa");
                yield return new homerun(71, "June", 0, 0, "Sosa");
                yield return new homerun(72, "June", 2, 0, "Sosa");
                yield return new homerun(73, "June", 2, 0, "Sosa");
                yield return new homerun(74, "June", 1, 0, "Sosa");
                yield return new homerun(75, "June", 0, 0, "Sosa");
                yield return new homerun(76, "June", 0, 0, "Sosa");
                yield return new homerun(77, "June", 1, 0, "Sosa");
                yield return new homerun(78, "June", 1, 0, "Sosa");
                yield return new homerun(79, "June", 0, 0, "Sosa");
                yield return new homerun(80, "June", 0, 0, "Sosa");
                yield return new homerun(81, "June", 0, 0, "Sosa");
                yield return new homerun(82, "June", 1, 0, "Sosa");
                yield return new homerun(83, "July", 0, 0, "Sosa");
                yield return new homerun(84, "July", 0, 0, "Sosa");
                yield return new homerun(85, "July", 0, 0, "Sosa");
                yield return new homerun(86, "July", 0, 0, "Sosa");
                yield return new homerun(88, "July", 1, 0, "Sosa");
                yield return new homerun(89, "July", 1, 0, "Sosa");
                yield return new homerun(90, "July", 0, 0, "Sosa");
                yield return new homerun(91, "July", 0, 0, "Sosa");
                yield return new homerun(92, "July", 0, 0, "Sosa");
                yield return new homerun(93, "July", 0, 0, "Sosa");
                yield return new homerun(94, "July", 0, 0, "Sosa");
                yield return new homerun(95, "July", 1, 0, "Sosa");
                yield return new homerun(96, "July", 0, 0, "Sosa");
                yield return new homerun(97, "July", 0, 0, "Sosa");
                yield return new homerun(98, "July", 0, 0, "Sosa");
                yield return new homerun(99, "July", 0, 0, "Sosa");
                yield return new homerun(100, "July", 1, 0, "Sosa");
                yield return new homerun(101, "July", 0, 0, "Sosa");
                yield return new homerun(102, "July", 0, 0, "Sosa");
                yield return new homerun(103, "July", 0, 0, "Sosa");
                yield return new homerun(104, "July", 0, 0, "Sosa");
                yield return new homerun(105, "July", 1, 0, "Sosa");
                yield return new homerun(106, "July", 2, 0, "Sosa");
                yield return new homerun(107, "July", 1, 0, "Sosa");
                yield return new homerun(108, "July", 0, 0, "Sosa");
                yield return new homerun(109, "July", 0, 0, "Sosa");
                yield return new homerun(110, "July", 1, 0, "Sosa");
                yield return new homerun(111, "August", 0, 0, "Sosa");
                yield return new homerun(112, "August", 0, 0, "Sosa");
                yield return new homerun(113, "August", 0, 0, "Sosa");
                yield return new homerun(114, "August", 0, 0, "Sosa");
                yield return new homerun(115, "August", 1, 0, "Sosa");
                yield return new homerun(116, "August", 0, 0, "Sosa");
                yield return new homerun(117, "August", 1, 0, "Sosa");
                yield return new homerun(118, "August", 0, 0, "Sosa");
                yield return new homerun(119, "August", 2, 0, "Sosa");
                yield return new homerun(120, "August", 0, 0, "Sosa");
                yield return new homerun(121, "August", 0, 0, "Sosa");
                yield return new homerun(122, "August", 0, 0, "Sosa");
                yield return new homerun(123, "August", 0, 0, "Sosa");
                yield return new homerun(124, "August", 1, 0, "Sosa");
                yield return new homerun(125, "August", 0, 0, "Sosa");
                yield return new homerun(126, "August", 1, 0, "Sosa");
                yield return new homerun(127, "August", 0, 0, "Sosa");
                yield return new homerun(128, "August", 1, 0, "Sosa");
                yield return new homerun(129, "August", 0, 0, "Sosa");
                yield return new homerun(130, "August", 2, 0, "Sosa");
                yield return new homerun(131, "August", 0, 0, "Sosa");
                yield return new homerun(132, "August", 0, 0, "Sosa");
                yield return new homerun(133, "August", 1, 0, "Sosa");
                yield return new homerun(134, "August", 0, 0, "Sosa");
                yield return new homerun(135, "August", 1, 0, "Sosa");
                yield return new homerun(136, "August", 0, 0, "Sosa");
                yield return new homerun(137, "August", 1, 0, "Sosa");
                yield return new homerun(138, "August", 1, 0, "Sosa");
                yield return new homerun(139, "September", 0, 0, "Sosa");
                yield return new homerun(140, "September", 1, 0, "Sosa");
                yield return new homerun(141, "September", 1, 0, "Sosa");
                yield return new homerun(142, "September", 1, 0, "Sosa");
                yield return new homerun(143, "September", 0, 0, "Sosa");
                yield return new homerun(144, "September", 0, 0, "Sosa");
                yield return new homerun(145, "September", 0, 0, "Sosa");
                yield return new homerun(146, "September", 0, 0, "Sosa");
                yield return new homerun(147, "September", 0, 0, "Sosa");
                yield return new homerun(148, "September", 1, 0, "Sosa");
                yield return new homerun(149, "September", 1, 0, "Sosa");
                yield return new homerun(150, "September", 2, 0, "Sosa");
                yield return new homerun(151, "September", 0, 0, "Sosa");
                yield return new homerun(152, "September", 0, 0, "Sosa");
                yield return new homerun(153, "September", 1, 0, "Sosa");
                yield return new homerun(154, "September", 0, 0, "Sosa");
                yield return new homerun(155, "September", 0, 0, "Sosa");
                yield return new homerun(156, "September", 0, 0, "Sosa");
                yield return new homerun(157, "September", 0, 0, "Sosa");
                yield return new homerun(158, "September", 0, 0, "Sosa");
                yield return new homerun(159, "September", 2, 0, "Sosa");
                yield return new homerun(160, "September", 1, 0, "Sosa");
                yield return new homerun(161, "September", 0, 0, "Sosa");
                yield return new homerun(162, "September", 0, 0, "Sosa");
                yield return new homerun(163, "September", 0, 0, "Sosa");
            }
        }
    }
}
