// ReSharper disable All

namespace Rdatasets.carData
{
    using System.Collections.Generic;

    /// <summary>
    /// Interlocking Directorates Among Major Canadian Firms
    /// </summary>

    public class Ornstein
    {
        public readonly int assets;
        public readonly string sector;
        public readonly string nation;
        public readonly int interlocks;

        public Ornstein(int assets, string sector, string nation, int interlocks)
        {
            this.assets = assets;
            this.sector = sector;
            this.nation = nation;
            this.interlocks = interlocks;
        }

        public static IEnumerable<Ornstein> Data
        {
            get
            {
                yield return new Ornstein(147670, "BNK", "CAN", 87);
                yield return new Ornstein(133000, "BNK", "CAN", 107);
                yield return new Ornstein(113230, "BNK", "CAN", 94);
                yield return new Ornstein(85418, "BNK", "CAN", 48);
                yield return new Ornstein(75477, "BNK", "CAN", 66);
                yield return new Ornstein(40742, "FIN", "CAN", 69);
                yield return new Ornstein(40140, "TRN", "CAN", 46);
                yield return new Ornstein(26866, "BNK", "CAN", 16);
                yield return new Ornstein(24500, "TRN", "CAN", 77);
                yield return new Ornstein(23700, "MIN", "US", 6);
                yield return new Ornstein(23482, "FIN", "CAN", 18);
                yield return new Ornstein(21512, "FIN", "CAN", 29);
                yield return new Ornstein(20780, "MIN", "US", 36);
                yield return new Ornstein(18688, "FIN", "CAN", 20);
                yield return new Ornstein(18286, "BNK", "CAN", 13);
                yield return new Ornstein(17910, "MIN", "US", 6);
                yield return new Ornstein(17784, "FIN", "CAN", 31);
                yield return new Ornstein(16631, "FIN", "CAN", 27);
                yield return new Ornstein(16458, "FIN", "CAN", 23);
                yield return new Ornstein(15280, "MIN", "US", 13);
                yield return new Ornstein(15140, "FIN", "CAN", 32);
                yield return new Ornstein(14362, "FIN", "CAN", 28);
                yield return new Ornstein(14163, "AGR", "CAN", 4);
                yield return new Ornstein(13820, "HLD", "CAN", 42);
                yield return new Ornstein(13787, "FIN", "CAN", 17);
                yield return new Ornstein(12810, "TRN", "CAN", 40);
                yield return new Ornstein(12080, "MIN", "US", 29);
                yield return new Ornstein(11250, "MIN", "CAN", 29);
                yield return new Ornstein(11090, "MAN", "US", 21);
                yield return new Ornstein(10580, "MIN", "OTH", 3);
                yield return new Ornstein(10570, "MAN", "CAN", 32);
                yield return new Ornstein(10568, "FIN", "CAN", 29);
                yield return new Ornstein(10320, "MIN", "CAN", 40);
                yield return new Ornstein(10110, "TRN", "US", 5);
                yield return new Ornstein(9044, "WOD", "CAN", 33);
                yield return new Ornstein(8395, "FIN", "CAN", 21);
                yield return new Ornstein(8182, "FIN", "US", 18);
                yield return new Ornstein(7994, "TRN", "US", 18);
                yield return new Ornstein(7930, "FIN", "CAN", 13);
                yield return new Ornstein(7877, "MAN", "US", 2);
                yield return new Ornstein(7564, "FIN", "US", 22);
                yield return new Ornstein(7510, "FIN", "US", 13);
                yield return new Ornstein(7287, "FIN", "US", 2);
                yield return new Ornstein(7018, "BNK", "CAN", 0);
                yield return new Ornstein(6629, "MIN", "US", 18);
                yield return new Ornstein(6571, "FIN", "CAN", 9);
                yield return new Ornstein(6498, "TRN", "CAN", 31);
                yield return new Ornstein(6407, "AGR", "CAN", 16);
                yield return new Ornstein(6286, "MIN", "CAN", 28);
                yield return new Ornstein(5932, "FIN", "CAN", 34);
                yield return new Ornstein(5704, "MIN", "CAN", 33);
                yield return new Ornstein(5479, "MER", "CAN", 7);
                yield return new Ornstein(5437, "TRN", "US", 12);
                yield return new Ornstein(5429, "MER", "US", 15);
                yield return new Ornstein(5366, "TRN", "US", 13);
                yield return new Ornstein(5035, "MIN", "US", 16);
                yield return new Ornstein(5021, "MIN", "OTH", 27);
                yield return new Ornstein(4980, "AGR", "CAN", 12);
                yield return new Ornstein(4838, "TRN", "CAN", 11);
                yield return new Ornstein(4634, "MIN", "US", 0);
                yield return new Ornstein(4592, "TRN", "US", 16);
                yield return new Ornstein(4390, "TRN", "CAN", 17);
                yield return new Ornstein(4304, "WOD", "CAN", 55);
                yield return new Ornstein(4298, "AGR", "OTH", 15);
                yield return new Ornstein(4227, "FIN", "CAN", 44);
                yield return new Ornstein(4210, "MIN", "US", 18);
                yield return new Ornstein(4154, "FIN", "OTH", 20);
                yield return new Ornstein(4100, "MAN", "US", 19);
                yield return new Ornstein(4099, "MAN", "US", 9);
                yield return new Ornstein(4088, "FIN", "CAN", 12);
                yield return new Ornstein(3960, "CON", "OTH", 17);
                yield return new Ornstein(3896, "AGR", "CAN", 15);
                yield return new Ornstein(3879, "WOD", "CAN", 27);
                yield return new Ornstein(3673, "MER", "CAN", 30);
                yield return new Ornstein(3654, "MIN", "OTH", 27);
                yield return new Ornstein(3631, "TRN", "US", 12);
                yield return new Ornstein(3606, "MIN", "UK", 11);
                yield return new Ornstein(3570, "MER", "CAN", 28);
                yield return new Ornstein(3561, "MIN", "US", 8);
                yield return new Ornstein(3274, "TRN", "CAN", 12);
                yield return new Ornstein(3152, "MAN", "US", 18);
                yield return new Ornstein(3058, "WOD", "UK", 23);
                yield return new Ornstein(2958, "WOD", "CAN", 51);
                yield return new Ornstein(2927, "MIN", "OTH", 35);
                yield return new Ornstein(2878, "MER", "CAN", 8);
                yield return new Ornstein(2814, "AGR", "CAN", 43);
                yield return new Ornstein(2807, "MIN", "CAN", 4);
                yield return new Ornstein(2801, "WOD", "CAN", 18);
                yield return new Ornstein(2786, "AGR", "OTH", 20);
                yield return new Ornstein(2757, "MIN", "UK", 13);
                yield return new Ornstein(2667, "MIN", "UK", 22);
                yield return new Ornstein(2625, "AGR", "UK", 10);
                yield return new Ornstein(2566, "MER", "US", 1);
                yield return new Ornstein(2549, "HLD", "US", 6);
                yield return new Ornstein(2488, "AGR", "CAN", 30);
                yield return new Ornstein(2285, "MIN", "US", 6);
                yield return new Ornstein(2281, "WOD", "US", 11);
                yield return new Ornstein(2182, "AGR", "US", 20);
                yield return new Ornstein(2165, "MIN", "US", 7);
                yield return new Ornstein(2164, "MIN", "OTH", 13);
                yield return new Ornstein(2141, "MIN", "US", 0);
                yield return new Ornstein(2108, "MAN", "UK", 14);
                yield return new Ornstein(2086, "MIN", "US", 19);
                yield return new Ornstein(2025, "AGR", "CAN", 4);
                yield return new Ornstein(1881, "AGR", "CAN", 2);
                yield return new Ornstein(1876, "MER", "CAN", 2);
                yield return new Ornstein(1841, "WOD", "US", 7);
                yield return new Ornstein(1656, "MIN", "OTH", 25);
                yield return new Ornstein(1655, "MER", "CAN", 29);
                yield return new Ornstein(1612, "MER", "CAN", 5);
                yield return new Ornstein(1603, "MIN", "US", 12);
                yield return new Ornstein(1601, "WOD", "CAN", 25);
                yield return new Ornstein(1591, "AGR", "US", 2);
                yield return new Ornstein(1583, "HLD", "CAN", 25);
                yield return new Ornstein(1561, "MIN", "US", 2);
                yield return new Ornstein(1520, "MAN", "US", 16);
                yield return new Ornstein(1511, "WOD", "US", 3);
                yield return new Ornstein(1487, "MIN", "OTH", 9);
                yield return new Ornstein(1482, "MAN", "US", 1);
                yield return new Ornstein(1477, "MAN", "US", 0);
                yield return new Ornstein(1469, "MIN", "US", 1);
                yield return new Ornstein(1434, "MIN", "US", 1);
                yield return new Ornstein(1427, "HLD", "CAN", 1);
                yield return new Ornstein(1416, "MER", "CAN", 6);
                yield return new Ornstein(1378, "MIN", "US", 12);
                yield return new Ornstein(1372, "MIN", "US", 5);
                yield return new Ornstein(1343, "WOD", "UK", 5);
                yield return new Ornstein(1337, "MIN", "US", 0);
                yield return new Ornstein(1335, "MAN", "CAN", 4);
                yield return new Ornstein(1315, "MIN", "OTH", 5);
                yield return new Ornstein(1235, "MAN", "CAN", 33);
                yield return new Ornstein(1172, "AGR", "CAN", 11);
                yield return new Ornstein(1154, "MAN", "US", 3);
                yield return new Ornstein(1154, "HLD", "CAN", 3);
                yield return new Ornstein(1112, "AGR", "US", 5);
                yield return new Ornstein(1060, "AGR", "CAN", 25);
                yield return new Ornstein(1027, "MIN", "OTH", 14);
                yield return new Ornstein(984, "MER", "US", 1);
                yield return new Ornstein(978, "MAN", "US", 0);
                yield return new Ornstein(953, "MIN", "US", 12);
                yield return new Ornstein(950, "WOD", "CAN", 18);
                yield return new Ornstein(943, "MER", "US", 11);
                yield return new Ornstein(904, "MIN", "CAN", 39);
                yield return new Ornstein(898, "AGR", "UK", 3);
                yield return new Ornstein(888, "WOD", "CAN", 2);
                yield return new Ornstein(848, "WOD", "CAN", 8);
                yield return new Ornstein(844, "MAN", "US", 0);
                yield return new Ornstein(839, "TRN", "CAN", 11);
                yield return new Ornstein(832, "AGR", "CAN", 13);
                yield return new Ornstein(830, "MIN", "UK", 1);
                yield return new Ornstein(816, "MIN", "CAN", 10);
                yield return new Ornstein(809, "MAN", "UK", 0);
                yield return new Ornstein(802, "MAN", "CAN", 0);
                yield return new Ornstein(798, "AGR", "CAN", 11);
                yield return new Ornstein(789, "MIN", "UK", 9);
                yield return new Ornstein(789, "MAN", "US", 6);
                yield return new Ornstein(782, "MER", "CAN", 11);
                yield return new Ornstein(780, "MAN", "US", 1);
                yield return new Ornstein(779, "MER", "CAN", 14);
                yield return new Ornstein(761, "WOD", "US", 1);
                yield return new Ornstein(751, "AGR", "CAN", 8);
                yield return new Ornstein(742, "AGR", "CAN", 7);
                yield return new Ornstein(727, "AGR", "CAN", 1);
                yield return new Ornstein(707, "AGR", "US", 9);
                yield return new Ornstein(704, "HLD", "CAN", 10);
                yield return new Ornstein(702, "MAN", "CAN", 3);
                yield return new Ornstein(690, "WOD", "OTH", 0);
                yield return new Ornstein(677, "MAN", "CAN", 12);
                yield return new Ornstein(638, "MAN", "US", 6);
                yield return new Ornstein(637, "AGR", "US", 1);
                yield return new Ornstein(636, "MIN", "US", 0);
                yield return new Ornstein(614, "CON", "CAN", 2);
                yield return new Ornstein(590, "MAN", "US", 2);
                yield return new Ornstein(589, "MIN", "OTH", 23);
                yield return new Ornstein(586, "TRN", "CAN", 10);
                yield return new Ornstein(575, "AGR", "CAN", 1);
                yield return new Ornstein(566, "AGR", "US", 0);
                yield return new Ornstein(559, "MAN", "US", 7);
                yield return new Ornstein(558, "AGR", "CAN", 14);
                yield return new Ornstein(552, "AGR", "CAN", 7);
                yield return new Ornstein(548, "MIN", "US", 5);
                yield return new Ornstein(540, "MAN", "CAN", 6);
                yield return new Ornstein(539, "AGR", "CAN", 9);
                yield return new Ornstein(533, "TRN", "CAN", 5);
                yield return new Ornstein(523, "MAN", "US", 8);
                yield return new Ornstein(519, "MAN", "US", 8);
                yield return new Ornstein(519, "AGR", "CAN", 0);
                yield return new Ornstein(516, "TRN", "CAN", 5);
                yield return new Ornstein(511, "HLD", "CAN", 0);
                yield return new Ornstein(510, "MAN", "CAN", 11);
                yield return new Ornstein(508, "MAN", "OTH", 1);
                yield return new Ornstein(497, "AGR", "CAN", 4);
                yield return new Ornstein(495, "MAN", "CAN", 0);
                yield return new Ornstein(494, "MER", "CAN", 8);
                yield return new Ornstein(488, "MAN", "CAN", 1);
                yield return new Ornstein(487, "MAN", "CAN", 8);
                yield return new Ornstein(471, "MER", "US", 0);
                yield return new Ornstein(456, "MIN", "US", 5);
                yield return new Ornstein(456, "MAN", "US", 0);
                yield return new Ornstein(444, "AGR", "US", 1);
                yield return new Ornstein(438, "MAN", "UK", 18);
                yield return new Ornstein(432, "MAN", "US", 1);
                yield return new Ornstein(432, "MAN", "CAN", 3);
                yield return new Ornstein(422, "WOD", "US", 11);
                yield return new Ornstein(407, "MIN", "US", 6);
                yield return new Ornstein(402, "MAN", "US", 0);
                yield return new Ornstein(391, "AGR", "CAN", 28);
                yield return new Ornstein(387, "MER", "CAN", 11);
                yield return new Ornstein(386, "CON", "OTH", 2);
                yield return new Ornstein(379, "MAN", "US", 16);
                yield return new Ornstein(376, "MER", "CAN", 5);
                yield return new Ornstein(375, "MAN", "US", 8);
                yield return new Ornstein(372, "AGR", "US", 8);
                yield return new Ornstein(370, "AGR", "UK", 3);
                yield return new Ornstein(364, "TRN", "US", 5);
                yield return new Ornstein(361, "MIN", "US", 2);
                yield return new Ornstein(359, "AGR", "US", 0);
                yield return new Ornstein(358, "AGR", "US", 0);
                yield return new Ornstein(352, "WOD", "CAN", 21);
                yield return new Ornstein(350, "MAN", "US", 1);
                yield return new Ornstein(345, "MER", "US", 8);
                yield return new Ornstein(332, "MAN", "US", 0);
                yield return new Ornstein(326, "AGR", "CAN", 3);
                yield return new Ornstein(326, "AGR", "US", 0);
                yield return new Ornstein(326, "MAN", "CAN", 28);
                yield return new Ornstein(325, "MAN", "OTH", 0);
                yield return new Ornstein(318, "AGR", "CAN", 2);
                yield return new Ornstein(312, "MAN", "US", 2);
                yield return new Ornstein(305, "AGR", "UK", 4);
                yield return new Ornstein(304, "MER", "US", 4);
                yield return new Ornstein(303, "WOD", "UK", 3);
                yield return new Ornstein(297, "CON", "CAN", 2);
                yield return new Ornstein(276, "MIN", "CAN", 9);
                yield return new Ornstein(270, "MAN", "CAN", 4);
                yield return new Ornstein(261, "CON", "UK", 1);
                yield return new Ornstein(256, "MAN", "US", 1);
                yield return new Ornstein(245, "MIN", "CAN", 11);
                yield return new Ornstein(241, "MIN", "US", 3);
                yield return new Ornstein(225, "AGR", "US", 6);
                yield return new Ornstein(225, "MIN", "UK", 8);
                yield return new Ornstein(220, "AGR", "US", 0);
                yield return new Ornstein(201, "AGR", "US", 5);
                yield return new Ornstein(200, "MAN", "US", 0);
                yield return new Ornstein(188, "MAN", "US", 0);
                yield return new Ornstein(160, "AGR", "CAN", 0);
                yield return new Ornstein(158, "AGR", "CAN", 5);
                yield return new Ornstein(119, "AGR", "CAN", 6);
                yield return new Ornstein(62, "MIN", "US", 0);
            }
        }
    }
}
