// ReSharper disable All

namespace Rdatasets.MASS
{
    using System.Collections.Generic;

    /// <summary>
    /// Presence of Bacteria after Drug Treatments
    /// </summary>

    public class bacteria
    {
        public readonly int κ;
        public readonly string y;
        public readonly string ap;
        public readonly string hilo;
        public readonly int week;
        public readonly string ID;
        public readonly string trt;

        public bacteria(int κ, string y, string ap, string hilo, int week, string ID, string trt)
        {
            this.κ = κ;
            this.y = y;
            this.ap = ap;
            this.hilo = hilo;
            this.week = week;
            this.ID = ID;
            this.trt = trt;
        }

        public static IEnumerable<bacteria> Data
        {
            get
            {
                yield return new bacteria(1, "y", "p", "hi", 0, "X01", "placebo");
                yield return new bacteria(2, "y", "p", "hi", 2, "X01", "placebo");
                yield return new bacteria(3, "y", "p", "hi", 4, "X01", "placebo");
                yield return new bacteria(4, "y", "p", "hi", 11, "X01", "placebo");
                yield return new bacteria(5, "y", "a", "hi", 0, "X02", "drug+");
                yield return new bacteria(6, "y", "a", "hi", 2, "X02", "drug+");
                yield return new bacteria(7, "n", "a", "hi", 6, "X02", "drug+");
                yield return new bacteria(8, "y", "a", "hi", 11, "X02", "drug+");
                yield return new bacteria(9, "y", "a", "lo", 0, "X03", "drug");
                yield return new bacteria(10, "y", "a", "lo", 2, "X03", "drug");
                yield return new bacteria(11, "y", "a", "lo", 4, "X03", "drug");
                yield return new bacteria(12, "y", "a", "lo", 6, "X03", "drug");
                yield return new bacteria(13, "y", "a", "lo", 11, "X03", "drug");
                yield return new bacteria(14, "y", "p", "lo", 0, "X04", "placebo");
                yield return new bacteria(15, "y", "p", "lo", 2, "X04", "placebo");
                yield return new bacteria(16, "y", "p", "lo", 4, "X04", "placebo");
                yield return new bacteria(17, "y", "p", "lo", 6, "X04", "placebo");
                yield return new bacteria(18, "y", "p", "lo", 11, "X04", "placebo");
                yield return new bacteria(19, "y", "p", "lo", 0, "X05", "placebo");
                yield return new bacteria(20, "y", "p", "lo", 2, "X05", "placebo");
                yield return new bacteria(21, "y", "p", "lo", 4, "X05", "placebo");
                yield return new bacteria(22, "y", "p", "lo", 6, "X05", "placebo");
                yield return new bacteria(23, "y", "p", "lo", 11, "X05", "placebo");
                yield return new bacteria(24, "y", "a", "lo", 0, "X06", "drug");
                yield return new bacteria(25, "y", "a", "lo", 2, "X06", "drug");
                yield return new bacteria(26, "y", "a", "lo", 4, "X06", "drug");
                yield return new bacteria(27, "y", "a", "lo", 11, "X06", "drug");
                yield return new bacteria(28, "y", "a", "hi", 0, "X07", "drug+");
                yield return new bacteria(29, "n", "a", "hi", 2, "X07", "drug+");
                yield return new bacteria(30, "n", "a", "hi", 4, "X07", "drug+");
                yield return new bacteria(31, "n", "a", "hi", 6, "X07", "drug+");
                yield return new bacteria(32, "y", "a", "hi", 11, "X07", "drug+");
                yield return new bacteria(33, "n", "p", "hi", 0, "X08", "placebo");
                yield return new bacteria(34, "y", "p", "hi", 2, "X08", "placebo");
                yield return new bacteria(35, "y", "p", "hi", 4, "X08", "placebo");
                yield return new bacteria(36, "y", "p", "hi", 6, "X08", "placebo");
                yield return new bacteria(37, "y", "p", "hi", 11, "X08", "placebo");
                yield return new bacteria(38, "y", "p", "lo", 0, "X09", "placebo");
                yield return new bacteria(39, "y", "p", "lo", 2, "X09", "placebo");
                yield return new bacteria(40, "y", "p", "lo", 4, "X09", "placebo");
                yield return new bacteria(41, "y", "p", "lo", 6, "X09", "placebo");
                yield return new bacteria(42, "y", "p", "lo", 11, "X09", "placebo");
                yield return new bacteria(43, "y", "a", "hi", 0, "X10", "drug+");
                yield return new bacteria(44, "y", "a", "hi", 6, "X10", "drug+");
                yield return new bacteria(45, "y", "p", "hi", 0, "X11", "placebo");
                yield return new bacteria(46, "y", "p", "hi", 2, "X11", "placebo");
                yield return new bacteria(47, "y", "p", "hi", 4, "X11", "placebo");
                yield return new bacteria(48, "y", "p", "hi", 6, "X11", "placebo");
                yield return new bacteria(49, "y", "p", "hi", 11, "X11", "placebo");
                yield return new bacteria(50, "y", "a", "lo", 0, "X12", "drug");
                yield return new bacteria(51, "n", "a", "lo", 2, "X12", "drug");
                yield return new bacteria(52, "n", "a", "lo", 4, "X12", "drug");
                yield return new bacteria(53, "y", "a", "lo", 6, "X12", "drug");
                yield return new bacteria(54, "y", "a", "lo", 11, "X12", "drug");
                yield return new bacteria(55, "y", "p", "hi", 0, "X13", "placebo");
                yield return new bacteria(56, "y", "p", "hi", 2, "X13", "placebo");
                yield return new bacteria(57, "y", "p", "hi", 4, "X13", "placebo");
                yield return new bacteria(58, "y", "p", "hi", 6, "X13", "placebo");
                yield return new bacteria(59, "y", "p", "hi", 11, "X13", "placebo");
                yield return new bacteria(60, "y", "p", "lo", 0, "X14", "placebo");
                yield return new bacteria(61, "y", "p", "lo", 2, "X14", "placebo");
                yield return new bacteria(62, "n", "p", "lo", 4, "X14", "placebo");
                yield return new bacteria(63, "y", "a", "lo", 0, "X15", "drug");
                yield return new bacteria(64, "y", "a", "lo", 2, "X15", "drug");
                yield return new bacteria(65, "y", "a", "lo", 4, "X15", "drug");
                yield return new bacteria(66, "y", "a", "lo", 6, "X15", "drug");
                yield return new bacteria(67, "y", "a", "lo", 11, "X15", "drug");
                yield return new bacteria(68, "y", "a", "hi", 0, "X16", "drug+");
                yield return new bacteria(69, "y", "a", "hi", 2, "X16", "drug+");
                yield return new bacteria(70, "n", "a", "hi", 4, "X16", "drug+");
                yield return new bacteria(71, "y", "a", "hi", 6, "X16", "drug+");
                yield return new bacteria(72, "y", "a", "hi", 11, "X16", "drug+");
                yield return new bacteria(73, "y", "p", "hi", 0, "X17", "placebo");
                yield return new bacteria(74, "y", "p", "hi", 2, "X17", "placebo");
                yield return new bacteria(75, "y", "p", "hi", 4, "X17", "placebo");
                yield return new bacteria(76, "n", "p", "hi", 6, "X17", "placebo");
                yield return new bacteria(77, "y", "p", "hi", 11, "X17", "placebo");
                yield return new bacteria(78, "y", "a", "lo", 0, "X18", "drug");
                yield return new bacteria(79, "y", "a", "lo", 2, "X18", "drug");
                yield return new bacteria(80, "n", "a", "lo", 4, "X18", "drug");
                yield return new bacteria(81, "n", "a", "lo", 6, "X18", "drug");
                yield return new bacteria(82, "n", "a", "lo", 11, "X18", "drug");
                yield return new bacteria(83, "y", "p", "lo", 0, "X19", "placebo");
                yield return new bacteria(84, "y", "p", "lo", 2, "X19", "placebo");
                yield return new bacteria(85, "n", "p", "lo", 4, "X19", "placebo");
                yield return new bacteria(86, "y", "p", "lo", 6, "X19", "placebo");
                yield return new bacteria(87, "n", "p", "lo", 11, "X19", "placebo");
                yield return new bacteria(88, "y", "a", "hi", 0, "X20", "drug+");
                yield return new bacteria(89, "y", "a", "hi", 2, "X20", "drug+");
                yield return new bacteria(90, "y", "a", "hi", 4, "X20", "drug+");
                yield return new bacteria(91, "y", "a", "hi", 11, "X20", "drug+");
                yield return new bacteria(92, "y", "p", "hi", 0, "X21", "placebo");
                yield return new bacteria(93, "y", "p", "hi", 2, "X21", "placebo");
                yield return new bacteria(94, "y", "p", "hi", 4, "X21", "placebo");
                yield return new bacteria(95, "y", "p", "hi", 6, "X21", "placebo");
                yield return new bacteria(96, "y", "p", "hi", 11, "X21", "placebo");
                yield return new bacteria(97, "y", "p", "hi", 0, "Y01", "placebo");
                yield return new bacteria(98, "y", "p", "hi", 2, "Y01", "placebo");
                yield return new bacteria(99, "y", "p", "hi", 4, "Y01", "placebo");
                yield return new bacteria(100, "y", "p", "hi", 6, "Y01", "placebo");
                yield return new bacteria(101, "y", "p", "hi", 11, "Y01", "placebo");
                yield return new bacteria(102, "n", "p", "lo", 0, "Y02", "placebo");
                yield return new bacteria(103, "y", "p", "lo", 2, "Y02", "placebo");
                yield return new bacteria(104, "n", "p", "lo", 4, "Y02", "placebo");
                yield return new bacteria(105, "y", "p", "lo", 6, "Y02", "placebo");
                yield return new bacteria(106, "n", "p", "lo", 11, "Y02", "placebo");
                yield return new bacteria(107, "y", "a", "hi", 0, "Y03", "drug+");
                yield return new bacteria(108, "y", "a", "hi", 2, "Y03", "drug+");
                yield return new bacteria(109, "y", "a", "hi", 4, "Y03", "drug+");
                yield return new bacteria(110, "n", "a", "hi", 6, "Y03", "drug+");
                yield return new bacteria(111, "n", "a", "hi", 11, "Y03", "drug+");
                yield return new bacteria(112, "n", "a", "lo", 0, "Y04", "drug");
                yield return new bacteria(113, "y", "a", "lo", 2, "Y04", "drug");
                yield return new bacteria(114, "n", "a", "lo", 4, "Y04", "drug");
                yield return new bacteria(115, "n", "a", "lo", 11, "Y04", "drug");
                yield return new bacteria(116, "y", "p", "hi", 0, "Y05", "placebo");
                yield return new bacteria(117, "n", "p", "hi", 2, "Y05", "placebo");
                yield return new bacteria(118, "n", "p", "hi", 11, "Y05", "placebo");
                yield return new bacteria(119, "y", "p", "lo", 0, "Y06", "placebo");
                yield return new bacteria(120, "y", "p", "lo", 2, "Y06", "placebo");
                yield return new bacteria(121, "y", "p", "lo", 6, "Y06", "placebo");
                yield return new bacteria(122, "y", "p", "lo", 11, "Y06", "placebo");
                yield return new bacteria(123, "y", "a", "lo", 0, "Y07", "drug");
                yield return new bacteria(124, "y", "a", "lo", 2, "Y07", "drug");
                yield return new bacteria(125, "y", "a", "lo", 4, "Y07", "drug");
                yield return new bacteria(126, "n", "a", "lo", 6, "Y07", "drug");
                yield return new bacteria(127, "n", "a", "lo", 11, "Y07", "drug");
                yield return new bacteria(128, "y", "a", "hi", 0, "Y08", "drug+");
                yield return new bacteria(129, "y", "a", "hi", 4, "Y08", "drug+");
                yield return new bacteria(130, "y", "a", "hi", 6, "Y08", "drug+");
                yield return new bacteria(131, "n", "a", "hi", 11, "Y08", "drug+");
                yield return new bacteria(132, "y", "p", "lo", 0, "Y09", "placebo");
                yield return new bacteria(133, "y", "p", "lo", 4, "Y09", "placebo");
                yield return new bacteria(134, "y", "p", "lo", 6, "Y09", "placebo");
                yield return new bacteria(135, "y", "p", "lo", 11, "Y09", "placebo");
                yield return new bacteria(136, "y", "a", "lo", 0, "Y10", "drug");
                yield return new bacteria(137, "y", "a", "lo", 2, "Y10", "drug");
                yield return new bacteria(138, "n", "a", "lo", 4, "Y10", "drug");
                yield return new bacteria(139, "y", "a", "lo", 6, "Y10", "drug");
                yield return new bacteria(140, "y", "a", "lo", 11, "Y10", "drug");
                yield return new bacteria(141, "y", "p", "hi", 0, "Y11", "placebo");
                yield return new bacteria(142, "y", "p", "hi", 2, "Y11", "placebo");
                yield return new bacteria(143, "y", "p", "hi", 4, "Y11", "placebo");
                yield return new bacteria(144, "y", "p", "hi", 6, "Y11", "placebo");
                yield return new bacteria(145, "y", "p", "hi", 11, "Y11", "placebo");
                yield return new bacteria(146, "y", "a", "hi", 0, "Y12", "drug+");
                yield return new bacteria(147, "y", "a", "hi", 4, "Y12", "drug+");
                yield return new bacteria(148, "y", "a", "lo", 0, "Y13", "drug");
                yield return new bacteria(149, "n", "a", "lo", 2, "Y13", "drug");
                yield return new bacteria(150, "n", "a", "lo", 4, "Y13", "drug");
                yield return new bacteria(151, "n", "a", "lo", 6, "Y13", "drug");
                yield return new bacteria(152, "y", "p", "hi", 0, "Y14", "placebo");
                yield return new bacteria(153, "y", "p", "hi", 2, "Y14", "placebo");
                yield return new bacteria(154, "y", "p", "hi", 11, "Y14", "placebo");
                yield return new bacteria(155, "y", "a", "lo", 0, "Z01", "drug");
                yield return new bacteria(156, "y", "a", "lo", 2, "Z01", "drug");
                yield return new bacteria(157, "y", "a", "lo", 11, "Z01", "drug");
                yield return new bacteria(158, "y", "p", "hi", 0, "Z02", "placebo");
                yield return new bacteria(159, "y", "p", "hi", 2, "Z02", "placebo");
                yield return new bacteria(160, "y", "p", "hi", 4, "Z02", "placebo");
                yield return new bacteria(161, "y", "p", "hi", 6, "Z02", "placebo");
                yield return new bacteria(162, "y", "p", "hi", 11, "Z02", "placebo");
                yield return new bacteria(163, "y", "a", "hi", 0, "Z03", "drug+");
                yield return new bacteria(164, "y", "a", "hi", 2, "Z03", "drug+");
                yield return new bacteria(165, "y", "a", "hi", 4, "Z03", "drug+");
                yield return new bacteria(166, "y", "a", "hi", 6, "Z03", "drug+");
                yield return new bacteria(167, "y", "a", "hi", 11, "Z03", "drug+");
                yield return new bacteria(168, "y", "p", "hi", 0, "Z05", "placebo");
                yield return new bacteria(169, "y", "p", "hi", 2, "Z05", "placebo");
                yield return new bacteria(170, "n", "p", "hi", 4, "Z05", "placebo");
                yield return new bacteria(171, "y", "p", "hi", 6, "Z05", "placebo");
                yield return new bacteria(172, "n", "p", "hi", 11, "Z05", "placebo");
                yield return new bacteria(173, "n", "a", "hi", 0, "Z06", "drug+");
                yield return new bacteria(174, "y", "a", "hi", 4, "Z06", "drug+");
                yield return new bacteria(175, "n", "a", "lo", 0, "Z07", "drug");
                yield return new bacteria(176, "y", "a", "lo", 2, "Z07", "drug");
                yield return new bacteria(177, "y", "a", "lo", 4, "Z07", "drug");
                yield return new bacteria(178, "n", "a", "lo", 6, "Z07", "drug");
                yield return new bacteria(179, "y", "a", "lo", 11, "Z07", "drug");
                yield return new bacteria(180, "y", "a", "hi", 0, "Z09", "drug+");
                yield return new bacteria(181, "y", "a", "hi", 2, "Z09", "drug+");
                yield return new bacteria(182, "y", "a", "hi", 6, "Z09", "drug+");
                yield return new bacteria(183, "y", "a", "hi", 11, "Z09", "drug+");
                yield return new bacteria(184, "y", "p", "hi", 0, "Z10", "placebo");
                yield return new bacteria(185, "y", "p", "hi", 2, "Z10", "placebo");
                yield return new bacteria(186, "y", "p", "hi", 4, "Z10", "placebo");
                yield return new bacteria(187, "y", "p", "hi", 6, "Z10", "placebo");
                yield return new bacteria(188, "y", "p", "hi", 11, "Z10", "placebo");
                yield return new bacteria(189, "y", "a", "lo", 0, "Z11", "drug");
                yield return new bacteria(190, "y", "a", "lo", 2, "Z11", "drug");
                yield return new bacteria(191, "y", "a", "lo", 4, "Z11", "drug");
                yield return new bacteria(192, "y", "a", "lo", 6, "Z11", "drug");
                yield return new bacteria(193, "y", "a", "lo", 11, "Z11", "drug");
                yield return new bacteria(194, "y", "a", "hi", 0, "Z14", "drug+");
                yield return new bacteria(195, "y", "a", "hi", 2, "Z14", "drug+");
                yield return new bacteria(196, "y", "a", "hi", 4, "Z14", "drug+");
                yield return new bacteria(197, "y", "a", "hi", 6, "Z14", "drug+");
                yield return new bacteria(198, "n", "a", "hi", 11, "Z14", "drug+");
                yield return new bacteria(199, "y", "a", "lo", 0, "Z15", "drug");
                yield return new bacteria(200, "y", "a", "lo", 4, "Z15", "drug");
                yield return new bacteria(201, "y", "a", "lo", 6, "Z15", "drug");
                yield return new bacteria(202, "y", "a", "hi", 0, "Z19", "drug+");
                yield return new bacteria(203, "y", "a", "hi", 2, "Z19", "drug+");
                yield return new bacteria(204, "y", "a", "hi", 4, "Z19", "drug+");
                yield return new bacteria(205, "y", "a", "hi", 6, "Z19", "drug+");
                yield return new bacteria(206, "y", "a", "hi", 11, "Z19", "drug+");
                yield return new bacteria(207, "y", "a", "lo", 0, "Z20", "drug");
                yield return new bacteria(208, "y", "a", "lo", 2, "Z20", "drug");
                yield return new bacteria(209, "n", "a", "lo", 6, "Z20", "drug");
                yield return new bacteria(210, "n", "a", "lo", 11, "Z20", "drug");
                yield return new bacteria(211, "y", "a", "hi", 0, "Z24", "drug+");
                yield return new bacteria(212, "y", "a", "hi", 2, "Z24", "drug+");
                yield return new bacteria(213, "y", "a", "hi", 4, "Z24", "drug+");
                yield return new bacteria(214, "n", "a", "hi", 6, "Z24", "drug+");
                yield return new bacteria(215, "n", "a", "hi", 11, "Z24", "drug+");
                yield return new bacteria(216, "y", "a", "hi", 0, "Z26", "drug+");
                yield return new bacteria(217, "y", "a", "hi", 2, "Z26", "drug+");
                yield return new bacteria(218, "y", "a", "hi", 4, "Z26", "drug+");
                yield return new bacteria(219, "n", "a", "hi", 6, "Z26", "drug+");
                yield return new bacteria(220, "y", "a", "hi", 11, "Z26", "drug+");
            }
        }
    }
}
