// ReSharper disable All

namespace Rdatasets.MASS
{
    using System.Collections.Generic;

    /// <summary>
    /// Space Shuttle Autolander Problem
    /// </summary>

    public class shuttle
    {
        public readonly int κ;
        public readonly string stability;
        public readonly string error;
        public readonly string sign;
        public readonly string wind;
        public readonly string magn;
        public readonly string vis;
        public readonly string use;

        public shuttle(int κ, string stability, string error, string sign, string wind, string magn, string vis, string use)
        {
            this.κ = κ;
            this.stability = stability;
            this.error = error;
            this.sign = sign;
            this.wind = wind;
            this.magn = magn;
            this.vis = vis;
            this.use = use;
        }

        public static IEnumerable<shuttle> Data
        {
            get
            {
                yield return new shuttle(1, "xstab", "LX", "pp", "head", "Light", "no", "auto");
                yield return new shuttle(2, "xstab", "LX", "pp", "head", "Medium", "no", "auto");
                yield return new shuttle(3, "xstab", "LX", "pp", "head", "Strong", "no", "auto");
                yield return new shuttle(4, "xstab", "LX", "pp", "tail", "Light", "no", "auto");
                yield return new shuttle(5, "xstab", "LX", "pp", "tail", "Medium", "no", "auto");
                yield return new shuttle(6, "xstab", "LX", "pp", "tail", "Strong", "no", "auto");
                yield return new shuttle(7, "xstab", "LX", "nn", "head", "Light", "no", "auto");
                yield return new shuttle(8, "xstab", "LX", "nn", "head", "Medium", "no", "auto");
                yield return new shuttle(9, "xstab", "LX", "nn", "head", "Strong", "no", "auto");
                yield return new shuttle(10, "xstab", "LX", "nn", "tail", "Light", "no", "auto");
                yield return new shuttle(11, "xstab", "LX", "nn", "tail", "Medium", "no", "auto");
                yield return new shuttle(12, "xstab", "LX", "nn", "tail", "Strong", "no", "auto");
                yield return new shuttle(13, "xstab", "XL", "pp", "head", "Light", "no", "auto");
                yield return new shuttle(14, "xstab", "XL", "pp", "head", "Medium", "no", "auto");
                yield return new shuttle(15, "xstab", "XL", "pp", "head", "Strong", "no", "auto");
                yield return new shuttle(16, "xstab", "XL", "pp", "tail", "Light", "no", "auto");
                yield return new shuttle(17, "xstab", "XL", "pp", "tail", "Medium", "no", "auto");
                yield return new shuttle(18, "xstab", "XL", "pp", "tail", "Strong", "no", "auto");
                yield return new shuttle(19, "xstab", "XL", "nn", "head", "Light", "no", "auto");
                yield return new shuttle(20, "xstab", "XL", "nn", "head", "Medium", "no", "auto");
                yield return new shuttle(21, "xstab", "XL", "nn", "head", "Strong", "no", "auto");
                yield return new shuttle(22, "xstab", "XL", "nn", "tail", "Light", "no", "auto");
                yield return new shuttle(23, "xstab", "XL", "nn", "tail", "Medium", "no", "auto");
                yield return new shuttle(24, "xstab", "XL", "nn", "tail", "Strong", "no", "auto");
                yield return new shuttle(25, "xstab", "MM", "pp", "head", "Light", "no", "auto");
                yield return new shuttle(26, "xstab", "MM", "pp", "head", "Medium", "no", "auto");
                yield return new shuttle(27, "xstab", "MM", "pp", "head", "Strong", "no", "auto");
                yield return new shuttle(28, "xstab", "MM", "pp", "tail", "Light", "no", "auto");
                yield return new shuttle(29, "xstab", "MM", "pp", "tail", "Medium", "no", "auto");
                yield return new shuttle(30, "xstab", "MM", "pp", "tail", "Strong", "no", "auto");
                yield return new shuttle(31, "xstab", "MM", "nn", "head", "Light", "no", "auto");
                yield return new shuttle(32, "xstab", "MM", "nn", "head", "Medium", "no", "auto");
                yield return new shuttle(33, "xstab", "MM", "nn", "head", "Strong", "no", "auto");
                yield return new shuttle(34, "xstab", "MM", "nn", "tail", "Light", "no", "auto");
                yield return new shuttle(35, "xstab", "MM", "nn", "tail", "Medium", "no", "auto");
                yield return new shuttle(36, "xstab", "MM", "nn", "tail", "Strong", "no", "auto");
                yield return new shuttle(37, "xstab", "SS", "pp", "head", "Light", "no", "auto");
                yield return new shuttle(38, "xstab", "SS", "pp", "head", "Medium", "no", "auto");
                yield return new shuttle(39, "xstab", "SS", "pp", "head", "Strong", "no", "auto");
                yield return new shuttle(40, "xstab", "SS", "pp", "tail", "Light", "no", "auto");
                yield return new shuttle(41, "xstab", "SS", "pp", "tail", "Medium", "no", "auto");
                yield return new shuttle(42, "xstab", "SS", "pp", "tail", "Strong", "no", "auto");
                yield return new shuttle(43, "xstab", "SS", "nn", "head", "Light", "no", "auto");
                yield return new shuttle(44, "xstab", "SS", "nn", "head", "Medium", "no", "auto");
                yield return new shuttle(45, "xstab", "SS", "nn", "head", "Strong", "no", "auto");
                yield return new shuttle(46, "xstab", "SS", "nn", "tail", "Light", "no", "auto");
                yield return new shuttle(47, "xstab", "SS", "nn", "tail", "Medium", "no", "auto");
                yield return new shuttle(48, "xstab", "SS", "nn", "tail", "Strong", "no", "auto");
                yield return new shuttle(49, "stab", "LX", "pp", "head", "Light", "no", "auto");
                yield return new shuttle(50, "stab", "LX", "pp", "head", "Medium", "no", "auto");
                yield return new shuttle(51, "stab", "LX", "pp", "head", "Strong", "no", "auto");
                yield return new shuttle(52, "stab", "LX", "pp", "tail", "Light", "no", "auto");
                yield return new shuttle(53, "stab", "LX", "pp", "tail", "Medium", "no", "auto");
                yield return new shuttle(54, "stab", "LX", "pp", "tail", "Strong", "no", "auto");
                yield return new shuttle(55, "stab", "LX", "nn", "head", "Light", "no", "auto");
                yield return new shuttle(56, "stab", "LX", "nn", "head", "Medium", "no", "auto");
                yield return new shuttle(57, "stab", "LX", "nn", "head", "Strong", "no", "auto");
                yield return new shuttle(58, "stab", "LX", "nn", "tail", "Light", "no", "auto");
                yield return new shuttle(59, "stab", "LX", "nn", "tail", "Medium", "no", "auto");
                yield return new shuttle(60, "stab", "LX", "nn", "tail", "Strong", "no", "auto");
                yield return new shuttle(61, "stab", "XL", "pp", "head", "Light", "no", "auto");
                yield return new shuttle(62, "stab", "XL", "pp", "head", "Medium", "no", "auto");
                yield return new shuttle(63, "stab", "XL", "pp", "head", "Strong", "no", "auto");
                yield return new shuttle(64, "stab", "XL", "pp", "tail", "Light", "no", "auto");
                yield return new shuttle(65, "stab", "XL", "pp", "tail", "Medium", "no", "auto");
                yield return new shuttle(66, "stab", "XL", "pp", "tail", "Strong", "no", "auto");
                yield return new shuttle(67, "stab", "XL", "nn", "head", "Light", "no", "auto");
                yield return new shuttle(68, "stab", "XL", "nn", "head", "Medium", "no", "auto");
                yield return new shuttle(69, "stab", "XL", "nn", "head", "Strong", "no", "auto");
                yield return new shuttle(70, "stab", "XL", "nn", "tail", "Light", "no", "auto");
                yield return new shuttle(71, "stab", "XL", "nn", "tail", "Medium", "no", "auto");
                yield return new shuttle(72, "stab", "XL", "nn", "tail", "Strong", "no", "auto");
                yield return new shuttle(73, "stab", "MM", "pp", "head", "Light", "no", "auto");
                yield return new shuttle(74, "stab", "MM", "pp", "head", "Medium", "no", "auto");
                yield return new shuttle(75, "stab", "MM", "pp", "head", "Strong", "no", "auto");
                yield return new shuttle(76, "stab", "MM", "pp", "tail", "Light", "no", "auto");
                yield return new shuttle(77, "stab", "MM", "pp", "tail", "Medium", "no", "auto");
                yield return new shuttle(78, "stab", "MM", "pp", "tail", "Strong", "no", "auto");
                yield return new shuttle(79, "stab", "MM", "nn", "head", "Light", "no", "auto");
                yield return new shuttle(80, "stab", "MM", "nn", "head", "Medium", "no", "auto");
                yield return new shuttle(81, "stab", "MM", "nn", "head", "Strong", "no", "auto");
                yield return new shuttle(82, "stab", "MM", "nn", "tail", "Light", "no", "auto");
                yield return new shuttle(83, "stab", "MM", "nn", "tail", "Medium", "no", "auto");
                yield return new shuttle(84, "stab", "MM", "nn", "tail", "Strong", "no", "auto");
                yield return new shuttle(85, "stab", "SS", "pp", "head", "Light", "no", "auto");
                yield return new shuttle(86, "stab", "SS", "pp", "head", "Medium", "no", "auto");
                yield return new shuttle(87, "stab", "SS", "pp", "head", "Strong", "no", "auto");
                yield return new shuttle(88, "stab", "SS", "pp", "tail", "Light", "no", "auto");
                yield return new shuttle(89, "stab", "SS", "pp", "tail", "Medium", "no", "auto");
                yield return new shuttle(90, "stab", "SS", "pp", "tail", "Strong", "no", "auto");
                yield return new shuttle(91, "stab", "SS", "nn", "head", "Light", "no", "auto");
                yield return new shuttle(92, "stab", "SS", "nn", "head", "Medium", "no", "auto");
                yield return new shuttle(93, "stab", "SS", "nn", "head", "Strong", "no", "auto");
                yield return new shuttle(94, "stab", "SS", "nn", "tail", "Light", "no", "auto");
                yield return new shuttle(95, "stab", "SS", "nn", "tail", "Medium", "no", "auto");
                yield return new shuttle(96, "stab", "SS", "nn", "tail", "Strong", "no", "auto");
                yield return new shuttle(97, "xstab", "LX", "pp", "head", "Out", "no", "auto");
                yield return new shuttle(98, "xstab", "LX", "pp", "tail", "Out", "no", "auto");
                yield return new shuttle(99, "xstab", "LX", "nn", "head", "Out", "no", "auto");
                yield return new shuttle(100, "xstab", "LX", "nn", "tail", "Out", "no", "auto");
                yield return new shuttle(101, "xstab", "XL", "pp", "head", "Out", "no", "auto");
                yield return new shuttle(102, "xstab", "XL", "pp", "tail", "Out", "no", "auto");
                yield return new shuttle(103, "xstab", "XL", "nn", "head", "Out", "no", "auto");
                yield return new shuttle(104, "xstab", "XL", "nn", "tail", "Out", "no", "auto");
                yield return new shuttle(105, "xstab", "MM", "pp", "head", "Out", "no", "auto");
                yield return new shuttle(106, "xstab", "MM", "pp", "tail", "Out", "no", "auto");
                yield return new shuttle(107, "xstab", "MM", "nn", "head", "Out", "no", "auto");
                yield return new shuttle(108, "xstab", "MM", "nn", "tail", "Out", "no", "auto");
                yield return new shuttle(109, "xstab", "SS", "pp", "head", "Out", "no", "auto");
                yield return new shuttle(110, "xstab", "SS", "pp", "tail", "Out", "no", "auto");
                yield return new shuttle(111, "xstab", "SS", "nn", "head", "Out", "no", "auto");
                yield return new shuttle(112, "xstab", "SS", "nn", "tail", "Out", "no", "auto");
                yield return new shuttle(113, "stab", "LX", "pp", "head", "Out", "no", "auto");
                yield return new shuttle(114, "stab", "LX", "pp", "tail", "Out", "no", "auto");
                yield return new shuttle(115, "stab", "LX", "nn", "head", "Out", "no", "auto");
                yield return new shuttle(116, "stab", "LX", "nn", "tail", "Out", "no", "auto");
                yield return new shuttle(117, "stab", "XL", "pp", "head", "Out", "no", "auto");
                yield return new shuttle(118, "stab", "XL", "pp", "tail", "Out", "no", "auto");
                yield return new shuttle(119, "stab", "XL", "nn", "head", "Out", "no", "auto");
                yield return new shuttle(120, "stab", "XL", "nn", "tail", "Out", "no", "auto");
                yield return new shuttle(121, "stab", "MM", "pp", "head", "Out", "no", "auto");
                yield return new shuttle(122, "stab", "MM", "pp", "tail", "Out", "no", "auto");
                yield return new shuttle(123, "stab", "MM", "nn", "head", "Out", "no", "auto");
                yield return new shuttle(124, "stab", "MM", "nn", "tail", "Out", "no", "auto");
                yield return new shuttle(125, "stab", "SS", "pp", "head", "Out", "no", "auto");
                yield return new shuttle(126, "stab", "SS", "pp", "tail", "Out", "no", "auto");
                yield return new shuttle(127, "stab", "SS", "nn", "head", "Out", "no", "auto");
                yield return new shuttle(128, "stab", "SS", "nn", "tail", "Out", "no", "auto");
                yield return new shuttle(129, "xstab", "LX", "pp", "head", "Light", "yes", "noauto");
                yield return new shuttle(130, "xstab", "LX", "pp", "head", "Medium", "yes", "noauto");
                yield return new shuttle(131, "xstab", "LX", "pp", "head", "Strong", "yes", "noauto");
                yield return new shuttle(132, "xstab", "LX", "pp", "tail", "Light", "yes", "noauto");
                yield return new shuttle(133, "xstab", "LX", "pp", "tail", "Medium", "yes", "noauto");
                yield return new shuttle(134, "xstab", "LX", "pp", "tail", "Strong", "yes", "noauto");
                yield return new shuttle(135, "xstab", "LX", "nn", "head", "Light", "yes", "noauto");
                yield return new shuttle(136, "xstab", "LX", "nn", "head", "Medium", "yes", "noauto");
                yield return new shuttle(137, "xstab", "LX", "nn", "head", "Strong", "yes", "noauto");
                yield return new shuttle(138, "xstab", "LX", "nn", "tail", "Light", "yes", "noauto");
                yield return new shuttle(139, "xstab", "LX", "nn", "tail", "Medium", "yes", "noauto");
                yield return new shuttle(140, "xstab", "LX", "nn", "tail", "Strong", "yes", "noauto");
                yield return new shuttle(141, "xstab", "XL", "pp", "head", "Light", "yes", "noauto");
                yield return new shuttle(142, "xstab", "XL", "pp", "head", "Medium", "yes", "noauto");
                yield return new shuttle(143, "xstab", "XL", "pp", "head", "Strong", "yes", "noauto");
                yield return new shuttle(144, "xstab", "XL", "pp", "tail", "Light", "yes", "noauto");
                yield return new shuttle(145, "xstab", "XL", "pp", "tail", "Medium", "yes", "noauto");
                yield return new shuttle(146, "xstab", "XL", "pp", "tail", "Strong", "yes", "noauto");
                yield return new shuttle(147, "xstab", "XL", "nn", "head", "Light", "yes", "noauto");
                yield return new shuttle(148, "xstab", "XL", "nn", "head", "Medium", "yes", "noauto");
                yield return new shuttle(149, "xstab", "XL", "nn", "head", "Strong", "yes", "noauto");
                yield return new shuttle(150, "xstab", "XL", "nn", "tail", "Light", "yes", "noauto");
                yield return new shuttle(151, "xstab", "XL", "nn", "tail", "Medium", "yes", "noauto");
                yield return new shuttle(152, "xstab", "XL", "nn", "tail", "Strong", "yes", "noauto");
                yield return new shuttle(153, "xstab", "MM", "pp", "head", "Light", "yes", "noauto");
                yield return new shuttle(154, "xstab", "MM", "pp", "head", "Medium", "yes", "noauto");
                yield return new shuttle(155, "xstab", "MM", "pp", "head", "Strong", "yes", "noauto");
                yield return new shuttle(156, "xstab", "MM", "pp", "tail", "Light", "yes", "noauto");
                yield return new shuttle(157, "xstab", "MM", "pp", "tail", "Medium", "yes", "noauto");
                yield return new shuttle(158, "xstab", "MM", "pp", "tail", "Strong", "yes", "noauto");
                yield return new shuttle(159, "xstab", "MM", "nn", "head", "Light", "yes", "noauto");
                yield return new shuttle(160, "xstab", "MM", "nn", "head", "Medium", "yes", "noauto");
                yield return new shuttle(161, "xstab", "MM", "nn", "head", "Strong", "yes", "noauto");
                yield return new shuttle(162, "xstab", "MM", "nn", "tail", "Light", "yes", "noauto");
                yield return new shuttle(163, "xstab", "MM", "nn", "tail", "Medium", "yes", "noauto");
                yield return new shuttle(164, "xstab", "MM", "nn", "tail", "Strong", "yes", "noauto");
                yield return new shuttle(165, "xstab", "SS", "pp", "head", "Light", "yes", "noauto");
                yield return new shuttle(166, "xstab", "SS", "pp", "head", "Medium", "yes", "noauto");
                yield return new shuttle(167, "xstab", "SS", "pp", "head", "Strong", "yes", "noauto");
                yield return new shuttle(168, "xstab", "SS", "pp", "tail", "Light", "yes", "noauto");
                yield return new shuttle(169, "xstab", "SS", "pp", "tail", "Medium", "yes", "noauto");
                yield return new shuttle(170, "xstab", "SS", "pp", "tail", "Strong", "yes", "noauto");
                yield return new shuttle(171, "xstab", "SS", "nn", "head", "Light", "yes", "noauto");
                yield return new shuttle(172, "xstab", "SS", "nn", "head", "Medium", "yes", "noauto");
                yield return new shuttle(173, "xstab", "SS", "nn", "head", "Strong", "yes", "noauto");
                yield return new shuttle(174, "xstab", "SS", "nn", "tail", "Light", "yes", "noauto");
                yield return new shuttle(175, "xstab", "SS", "nn", "tail", "Medium", "yes", "noauto");
                yield return new shuttle(176, "xstab", "SS", "nn", "tail", "Strong", "yes", "noauto");
                yield return new shuttle(177, "stab", "LX", "pp", "head", "Light", "yes", "noauto");
                yield return new shuttle(178, "stab", "LX", "pp", "head", "Medium", "yes", "noauto");
                yield return new shuttle(179, "stab", "LX", "pp", "head", "Strong", "yes", "noauto");
                yield return new shuttle(180, "stab", "LX", "pp", "tail", "Light", "yes", "noauto");
                yield return new shuttle(181, "stab", "LX", "pp", "tail", "Medium", "yes", "noauto");
                yield return new shuttle(182, "stab", "LX", "pp", "tail", "Strong", "yes", "noauto");
                yield return new shuttle(183, "stab", "LX", "nn", "head", "Light", "yes", "noauto");
                yield return new shuttle(184, "stab", "LX", "nn", "head", "Medium", "yes", "noauto");
                yield return new shuttle(185, "stab", "LX", "nn", "head", "Strong", "yes", "noauto");
                yield return new shuttle(186, "stab", "LX", "nn", "tail", "Light", "yes", "noauto");
                yield return new shuttle(187, "stab", "LX", "nn", "tail", "Medium", "yes", "noauto");
                yield return new shuttle(188, "stab", "LX", "nn", "tail", "Strong", "yes", "noauto");
                yield return new shuttle(189, "stab", "XL", "pp", "head", "Light", "yes", "noauto");
                yield return new shuttle(190, "stab", "XL", "pp", "head", "Medium", "yes", "noauto");
                yield return new shuttle(191, "stab", "XL", "pp", "head", "Strong", "yes", "noauto");
                yield return new shuttle(192, "stab", "XL", "pp", "tail", "Light", "yes", "noauto");
                yield return new shuttle(193, "stab", "XL", "pp", "tail", "Medium", "yes", "noauto");
                yield return new shuttle(194, "stab", "XL", "pp", "tail", "Strong", "yes", "noauto");
                yield return new shuttle(195, "stab", "XL", "nn", "head", "Light", "yes", "noauto");
                yield return new shuttle(196, "stab", "XL", "nn", "head", "Medium", "yes", "noauto");
                yield return new shuttle(197, "stab", "XL", "nn", "head", "Strong", "yes", "noauto");
                yield return new shuttle(198, "stab", "XL", "nn", "tail", "Light", "yes", "noauto");
                yield return new shuttle(199, "stab", "XL", "nn", "tail", "Medium", "yes", "noauto");
                yield return new shuttle(200, "stab", "XL", "nn", "tail", "Strong", "yes", "noauto");
                yield return new shuttle(201, "stab", "MM", "pp", "head", "Light", "yes", "auto");
                yield return new shuttle(202, "stab", "MM", "pp", "head", "Medium", "yes", "auto");
                yield return new shuttle(203, "stab", "MM", "pp", "head", "Strong", "yes", "noauto");
                yield return new shuttle(204, "stab", "MM", "pp", "tail", "Light", "yes", "auto");
                yield return new shuttle(205, "stab", "MM", "pp", "tail", "Medium", "yes", "auto");
                yield return new shuttle(206, "stab", "MM", "pp", "tail", "Strong", "yes", "auto");
                yield return new shuttle(207, "stab", "MM", "nn", "tail", "Light", "yes", "noauto");
                yield return new shuttle(208, "stab", "MM", "nn", "tail", "Medium", "yes", "noauto");
                yield return new shuttle(209, "stab", "MM", "nn", "tail", "Strong", "yes", "noauto");
                yield return new shuttle(210, "stab", "SS", "pp", "head", "Light", "yes", "auto");
                yield return new shuttle(211, "stab", "SS", "pp", "head", "Medium", "yes", "auto");
                yield return new shuttle(212, "stab", "SS", "pp", "head", "Strong", "yes", "auto");
                yield return new shuttle(213, "stab", "SS", "pp", "tail", "Light", "yes", "auto");
                yield return new shuttle(214, "stab", "SS", "pp", "tail", "Medium", "yes", "auto");
                yield return new shuttle(215, "stab", "SS", "pp", "tail", "Strong", "yes", "auto");
                yield return new shuttle(216, "stab", "SS", "nn", "head", "Light", "yes", "auto");
                yield return new shuttle(217, "stab", "SS", "nn", "head", "Medium", "yes", "auto");
                yield return new shuttle(218, "stab", "SS", "nn", "head", "Strong", "yes", "auto");
                yield return new shuttle(219, "stab", "SS", "nn", "tail", "Light", "yes", "auto");
                yield return new shuttle(220, "stab", "SS", "nn", "tail", "Medium", "yes", "auto");
                yield return new shuttle(221, "stab", "SS", "nn", "tail", "Strong", "yes", "auto");
                yield return new shuttle(222, "xstab", "LX", "pp", "head", "Out", "yes", "noauto");
                yield return new shuttle(223, "xstab", "LX", "pp", "tail", "Out", "yes", "noauto");
                yield return new shuttle(224, "xstab", "LX", "nn", "head", "Out", "yes", "noauto");
                yield return new shuttle(225, "xstab", "LX", "nn", "tail", "Out", "yes", "noauto");
                yield return new shuttle(226, "xstab", "XL", "pp", "head", "Out", "yes", "noauto");
                yield return new shuttle(227, "xstab", "XL", "pp", "tail", "Out", "yes", "noauto");
                yield return new shuttle(228, "xstab", "XL", "nn", "head", "Out", "yes", "noauto");
                yield return new shuttle(229, "xstab", "XL", "nn", "tail", "Out", "yes", "noauto");
                yield return new shuttle(230, "xstab", "MM", "pp", "head", "Out", "yes", "noauto");
                yield return new shuttle(231, "xstab", "MM", "pp", "tail", "Out", "yes", "noauto");
                yield return new shuttle(232, "xstab", "MM", "nn", "head", "Out", "yes", "noauto");
                yield return new shuttle(233, "xstab", "MM", "nn", "tail", "Out", "yes", "noauto");
                yield return new shuttle(234, "xstab", "SS", "pp", "head", "Out", "yes", "noauto");
                yield return new shuttle(235, "xstab", "SS", "pp", "tail", "Out", "yes", "noauto");
                yield return new shuttle(236, "xstab", "SS", "nn", "head", "Out", "yes", "noauto");
                yield return new shuttle(237, "xstab", "SS", "nn", "tail", "Out", "yes", "noauto");
                yield return new shuttle(238, "stab", "LX", "pp", "head", "Out", "yes", "noauto");
                yield return new shuttle(239, "stab", "LX", "pp", "tail", "Out", "yes", "noauto");
                yield return new shuttle(240, "stab", "LX", "nn", "head", "Out", "yes", "noauto");
                yield return new shuttle(241, "stab", "LX", "nn", "tail", "Out", "yes", "noauto");
                yield return new shuttle(242, "stab", "XL", "pp", "head", "Out", "yes", "noauto");
                yield return new shuttle(243, "stab", "XL", "pp", "tail", "Out", "yes", "noauto");
                yield return new shuttle(244, "stab", "XL", "nn", "head", "Out", "yes", "noauto");
                yield return new shuttle(245, "stab", "XL", "nn", "tail", "Out", "yes", "noauto");
                yield return new shuttle(246, "stab", "MM", "pp", "head", "Out", "yes", "noauto");
                yield return new shuttle(247, "stab", "MM", "pp", "tail", "Out", "yes", "noauto");
                yield return new shuttle(248, "stab", "MM", "nn", "head", "Out", "yes", "noauto");
                yield return new shuttle(249, "stab", "MM", "nn", "tail", "Out", "yes", "noauto");
                yield return new shuttle(250, "stab", "SS", "pp", "head", "Out", "yes", "noauto");
                yield return new shuttle(251, "stab", "SS", "pp", "tail", "Out", "yes", "noauto");
                yield return new shuttle(252, "stab", "SS", "nn", "head", "Out", "yes", "noauto");
                yield return new shuttle(253, "stab", "SS", "nn", "tail", "Out", "yes", "noauto");
                yield return new shuttle(254, "stab", "MM", "nn", "head", "Light", "yes", "noauto");
                yield return new shuttle(255, "stab", "MM", "nn", "head", "Medium", "yes", "noauto");
                yield return new shuttle(256, "stab", "MM", "nn", "head", "Strong", "yes", "noauto");
            }
        }
    }
}
