// ReSharper disable All

namespace Rdatasets.MASS
{
    using System.Collections.Generic;

    /// <summary>
    /// Space Shuttle Autolander Problem
    /// </summary>

    public class shuttle
    {
        public readonly string stability;
        public readonly string error;
        public readonly string sign;
        public readonly string wind;
        public readonly string magn;
        public readonly string vis;
        public readonly string use;

        public shuttle(string stability, string error, string sign, string wind, string magn, string vis, string use)
        {
            this.stability = stability;
            this.error = error;
            this.sign = sign;
            this.wind = wind;
            this.magn = magn;
            this.vis = vis;
            this.use = use;
        }

        public static IEnumerable<shuttle> Data
        {
            get
            {
                yield return new shuttle("xstab", "LX", "pp", "head", "Light", "no", "auto");
                yield return new shuttle("xstab", "LX", "pp", "head", "Medium", "no", "auto");
                yield return new shuttle("xstab", "LX", "pp", "head", "Strong", "no", "auto");
                yield return new shuttle("xstab", "LX", "pp", "tail", "Light", "no", "auto");
                yield return new shuttle("xstab", "LX", "pp", "tail", "Medium", "no", "auto");
                yield return new shuttle("xstab", "LX", "pp", "tail", "Strong", "no", "auto");
                yield return new shuttle("xstab", "LX", "nn", "head", "Light", "no", "auto");
                yield return new shuttle("xstab", "LX", "nn", "head", "Medium", "no", "auto");
                yield return new shuttle("xstab", "LX", "nn", "head", "Strong", "no", "auto");
                yield return new shuttle("xstab", "LX", "nn", "tail", "Light", "no", "auto");
                yield return new shuttle("xstab", "LX", "nn", "tail", "Medium", "no", "auto");
                yield return new shuttle("xstab", "LX", "nn", "tail", "Strong", "no", "auto");
                yield return new shuttle("xstab", "XL", "pp", "head", "Light", "no", "auto");
                yield return new shuttle("xstab", "XL", "pp", "head", "Medium", "no", "auto");
                yield return new shuttle("xstab", "XL", "pp", "head", "Strong", "no", "auto");
                yield return new shuttle("xstab", "XL", "pp", "tail", "Light", "no", "auto");
                yield return new shuttle("xstab", "XL", "pp", "tail", "Medium", "no", "auto");
                yield return new shuttle("xstab", "XL", "pp", "tail", "Strong", "no", "auto");
                yield return new shuttle("xstab", "XL", "nn", "head", "Light", "no", "auto");
                yield return new shuttle("xstab", "XL", "nn", "head", "Medium", "no", "auto");
                yield return new shuttle("xstab", "XL", "nn", "head", "Strong", "no", "auto");
                yield return new shuttle("xstab", "XL", "nn", "tail", "Light", "no", "auto");
                yield return new shuttle("xstab", "XL", "nn", "tail", "Medium", "no", "auto");
                yield return new shuttle("xstab", "XL", "nn", "tail", "Strong", "no", "auto");
                yield return new shuttle("xstab", "MM", "pp", "head", "Light", "no", "auto");
                yield return new shuttle("xstab", "MM", "pp", "head", "Medium", "no", "auto");
                yield return new shuttle("xstab", "MM", "pp", "head", "Strong", "no", "auto");
                yield return new shuttle("xstab", "MM", "pp", "tail", "Light", "no", "auto");
                yield return new shuttle("xstab", "MM", "pp", "tail", "Medium", "no", "auto");
                yield return new shuttle("xstab", "MM", "pp", "tail", "Strong", "no", "auto");
                yield return new shuttle("xstab", "MM", "nn", "head", "Light", "no", "auto");
                yield return new shuttle("xstab", "MM", "nn", "head", "Medium", "no", "auto");
                yield return new shuttle("xstab", "MM", "nn", "head", "Strong", "no", "auto");
                yield return new shuttle("xstab", "MM", "nn", "tail", "Light", "no", "auto");
                yield return new shuttle("xstab", "MM", "nn", "tail", "Medium", "no", "auto");
                yield return new shuttle("xstab", "MM", "nn", "tail", "Strong", "no", "auto");
                yield return new shuttle("xstab", "SS", "pp", "head", "Light", "no", "auto");
                yield return new shuttle("xstab", "SS", "pp", "head", "Medium", "no", "auto");
                yield return new shuttle("xstab", "SS", "pp", "head", "Strong", "no", "auto");
                yield return new shuttle("xstab", "SS", "pp", "tail", "Light", "no", "auto");
                yield return new shuttle("xstab", "SS", "pp", "tail", "Medium", "no", "auto");
                yield return new shuttle("xstab", "SS", "pp", "tail", "Strong", "no", "auto");
                yield return new shuttle("xstab", "SS", "nn", "head", "Light", "no", "auto");
                yield return new shuttle("xstab", "SS", "nn", "head", "Medium", "no", "auto");
                yield return new shuttle("xstab", "SS", "nn", "head", "Strong", "no", "auto");
                yield return new shuttle("xstab", "SS", "nn", "tail", "Light", "no", "auto");
                yield return new shuttle("xstab", "SS", "nn", "tail", "Medium", "no", "auto");
                yield return new shuttle("xstab", "SS", "nn", "tail", "Strong", "no", "auto");
                yield return new shuttle("stab", "LX", "pp", "head", "Light", "no", "auto");
                yield return new shuttle("stab", "LX", "pp", "head", "Medium", "no", "auto");
                yield return new shuttle("stab", "LX", "pp", "head", "Strong", "no", "auto");
                yield return new shuttle("stab", "LX", "pp", "tail", "Light", "no", "auto");
                yield return new shuttle("stab", "LX", "pp", "tail", "Medium", "no", "auto");
                yield return new shuttle("stab", "LX", "pp", "tail", "Strong", "no", "auto");
                yield return new shuttle("stab", "LX", "nn", "head", "Light", "no", "auto");
                yield return new shuttle("stab", "LX", "nn", "head", "Medium", "no", "auto");
                yield return new shuttle("stab", "LX", "nn", "head", "Strong", "no", "auto");
                yield return new shuttle("stab", "LX", "nn", "tail", "Light", "no", "auto");
                yield return new shuttle("stab", "LX", "nn", "tail", "Medium", "no", "auto");
                yield return new shuttle("stab", "LX", "nn", "tail", "Strong", "no", "auto");
                yield return new shuttle("stab", "XL", "pp", "head", "Light", "no", "auto");
                yield return new shuttle("stab", "XL", "pp", "head", "Medium", "no", "auto");
                yield return new shuttle("stab", "XL", "pp", "head", "Strong", "no", "auto");
                yield return new shuttle("stab", "XL", "pp", "tail", "Light", "no", "auto");
                yield return new shuttle("stab", "XL", "pp", "tail", "Medium", "no", "auto");
                yield return new shuttle("stab", "XL", "pp", "tail", "Strong", "no", "auto");
                yield return new shuttle("stab", "XL", "nn", "head", "Light", "no", "auto");
                yield return new shuttle("stab", "XL", "nn", "head", "Medium", "no", "auto");
                yield return new shuttle("stab", "XL", "nn", "head", "Strong", "no", "auto");
                yield return new shuttle("stab", "XL", "nn", "tail", "Light", "no", "auto");
                yield return new shuttle("stab", "XL", "nn", "tail", "Medium", "no", "auto");
                yield return new shuttle("stab", "XL", "nn", "tail", "Strong", "no", "auto");
                yield return new shuttle("stab", "MM", "pp", "head", "Light", "no", "auto");
                yield return new shuttle("stab", "MM", "pp", "head", "Medium", "no", "auto");
                yield return new shuttle("stab", "MM", "pp", "head", "Strong", "no", "auto");
                yield return new shuttle("stab", "MM", "pp", "tail", "Light", "no", "auto");
                yield return new shuttle("stab", "MM", "pp", "tail", "Medium", "no", "auto");
                yield return new shuttle("stab", "MM", "pp", "tail", "Strong", "no", "auto");
                yield return new shuttle("stab", "MM", "nn", "head", "Light", "no", "auto");
                yield return new shuttle("stab", "MM", "nn", "head", "Medium", "no", "auto");
                yield return new shuttle("stab", "MM", "nn", "head", "Strong", "no", "auto");
                yield return new shuttle("stab", "MM", "nn", "tail", "Light", "no", "auto");
                yield return new shuttle("stab", "MM", "nn", "tail", "Medium", "no", "auto");
                yield return new shuttle("stab", "MM", "nn", "tail", "Strong", "no", "auto");
                yield return new shuttle("stab", "SS", "pp", "head", "Light", "no", "auto");
                yield return new shuttle("stab", "SS", "pp", "head", "Medium", "no", "auto");
                yield return new shuttle("stab", "SS", "pp", "head", "Strong", "no", "auto");
                yield return new shuttle("stab", "SS", "pp", "tail", "Light", "no", "auto");
                yield return new shuttle("stab", "SS", "pp", "tail", "Medium", "no", "auto");
                yield return new shuttle("stab", "SS", "pp", "tail", "Strong", "no", "auto");
                yield return new shuttle("stab", "SS", "nn", "head", "Light", "no", "auto");
                yield return new shuttle("stab", "SS", "nn", "head", "Medium", "no", "auto");
                yield return new shuttle("stab", "SS", "nn", "head", "Strong", "no", "auto");
                yield return new shuttle("stab", "SS", "nn", "tail", "Light", "no", "auto");
                yield return new shuttle("stab", "SS", "nn", "tail", "Medium", "no", "auto");
                yield return new shuttle("stab", "SS", "nn", "tail", "Strong", "no", "auto");
                yield return new shuttle("xstab", "LX", "pp", "head", "Out", "no", "auto");
                yield return new shuttle("xstab", "LX", "pp", "tail", "Out", "no", "auto");
                yield return new shuttle("xstab", "LX", "nn", "head", "Out", "no", "auto");
                yield return new shuttle("xstab", "LX", "nn", "tail", "Out", "no", "auto");
                yield return new shuttle("xstab", "XL", "pp", "head", "Out", "no", "auto");
                yield return new shuttle("xstab", "XL", "pp", "tail", "Out", "no", "auto");
                yield return new shuttle("xstab", "XL", "nn", "head", "Out", "no", "auto");
                yield return new shuttle("xstab", "XL", "nn", "tail", "Out", "no", "auto");
                yield return new shuttle("xstab", "MM", "pp", "head", "Out", "no", "auto");
                yield return new shuttle("xstab", "MM", "pp", "tail", "Out", "no", "auto");
                yield return new shuttle("xstab", "MM", "nn", "head", "Out", "no", "auto");
                yield return new shuttle("xstab", "MM", "nn", "tail", "Out", "no", "auto");
                yield return new shuttle("xstab", "SS", "pp", "head", "Out", "no", "auto");
                yield return new shuttle("xstab", "SS", "pp", "tail", "Out", "no", "auto");
                yield return new shuttle("xstab", "SS", "nn", "head", "Out", "no", "auto");
                yield return new shuttle("xstab", "SS", "nn", "tail", "Out", "no", "auto");
                yield return new shuttle("stab", "LX", "pp", "head", "Out", "no", "auto");
                yield return new shuttle("stab", "LX", "pp", "tail", "Out", "no", "auto");
                yield return new shuttle("stab", "LX", "nn", "head", "Out", "no", "auto");
                yield return new shuttle("stab", "LX", "nn", "tail", "Out", "no", "auto");
                yield return new shuttle("stab", "XL", "pp", "head", "Out", "no", "auto");
                yield return new shuttle("stab", "XL", "pp", "tail", "Out", "no", "auto");
                yield return new shuttle("stab", "XL", "nn", "head", "Out", "no", "auto");
                yield return new shuttle("stab", "XL", "nn", "tail", "Out", "no", "auto");
                yield return new shuttle("stab", "MM", "pp", "head", "Out", "no", "auto");
                yield return new shuttle("stab", "MM", "pp", "tail", "Out", "no", "auto");
                yield return new shuttle("stab", "MM", "nn", "head", "Out", "no", "auto");
                yield return new shuttle("stab", "MM", "nn", "tail", "Out", "no", "auto");
                yield return new shuttle("stab", "SS", "pp", "head", "Out", "no", "auto");
                yield return new shuttle("stab", "SS", "pp", "tail", "Out", "no", "auto");
                yield return new shuttle("stab", "SS", "nn", "head", "Out", "no", "auto");
                yield return new shuttle("stab", "SS", "nn", "tail", "Out", "no", "auto");
                yield return new shuttle("xstab", "LX", "pp", "head", "Light", "yes", "noauto");
                yield return new shuttle("xstab", "LX", "pp", "head", "Medium", "yes", "noauto");
                yield return new shuttle("xstab", "LX", "pp", "head", "Strong", "yes", "noauto");
                yield return new shuttle("xstab", "LX", "pp", "tail", "Light", "yes", "noauto");
                yield return new shuttle("xstab", "LX", "pp", "tail", "Medium", "yes", "noauto");
                yield return new shuttle("xstab", "LX", "pp", "tail", "Strong", "yes", "noauto");
                yield return new shuttle("xstab", "LX", "nn", "head", "Light", "yes", "noauto");
                yield return new shuttle("xstab", "LX", "nn", "head", "Medium", "yes", "noauto");
                yield return new shuttle("xstab", "LX", "nn", "head", "Strong", "yes", "noauto");
                yield return new shuttle("xstab", "LX", "nn", "tail", "Light", "yes", "noauto");
                yield return new shuttle("xstab", "LX", "nn", "tail", "Medium", "yes", "noauto");
                yield return new shuttle("xstab", "LX", "nn", "tail", "Strong", "yes", "noauto");
                yield return new shuttle("xstab", "XL", "pp", "head", "Light", "yes", "noauto");
                yield return new shuttle("xstab", "XL", "pp", "head", "Medium", "yes", "noauto");
                yield return new shuttle("xstab", "XL", "pp", "head", "Strong", "yes", "noauto");
                yield return new shuttle("xstab", "XL", "pp", "tail", "Light", "yes", "noauto");
                yield return new shuttle("xstab", "XL", "pp", "tail", "Medium", "yes", "noauto");
                yield return new shuttle("xstab", "XL", "pp", "tail", "Strong", "yes", "noauto");
                yield return new shuttle("xstab", "XL", "nn", "head", "Light", "yes", "noauto");
                yield return new shuttle("xstab", "XL", "nn", "head", "Medium", "yes", "noauto");
                yield return new shuttle("xstab", "XL", "nn", "head", "Strong", "yes", "noauto");
                yield return new shuttle("xstab", "XL", "nn", "tail", "Light", "yes", "noauto");
                yield return new shuttle("xstab", "XL", "nn", "tail", "Medium", "yes", "noauto");
                yield return new shuttle("xstab", "XL", "nn", "tail", "Strong", "yes", "noauto");
                yield return new shuttle("xstab", "MM", "pp", "head", "Light", "yes", "noauto");
                yield return new shuttle("xstab", "MM", "pp", "head", "Medium", "yes", "noauto");
                yield return new shuttle("xstab", "MM", "pp", "head", "Strong", "yes", "noauto");
                yield return new shuttle("xstab", "MM", "pp", "tail", "Light", "yes", "noauto");
                yield return new shuttle("xstab", "MM", "pp", "tail", "Medium", "yes", "noauto");
                yield return new shuttle("xstab", "MM", "pp", "tail", "Strong", "yes", "noauto");
                yield return new shuttle("xstab", "MM", "nn", "head", "Light", "yes", "noauto");
                yield return new shuttle("xstab", "MM", "nn", "head", "Medium", "yes", "noauto");
                yield return new shuttle("xstab", "MM", "nn", "head", "Strong", "yes", "noauto");
                yield return new shuttle("xstab", "MM", "nn", "tail", "Light", "yes", "noauto");
                yield return new shuttle("xstab", "MM", "nn", "tail", "Medium", "yes", "noauto");
                yield return new shuttle("xstab", "MM", "nn", "tail", "Strong", "yes", "noauto");
                yield return new shuttle("xstab", "SS", "pp", "head", "Light", "yes", "noauto");
                yield return new shuttle("xstab", "SS", "pp", "head", "Medium", "yes", "noauto");
                yield return new shuttle("xstab", "SS", "pp", "head", "Strong", "yes", "noauto");
                yield return new shuttle("xstab", "SS", "pp", "tail", "Light", "yes", "noauto");
                yield return new shuttle("xstab", "SS", "pp", "tail", "Medium", "yes", "noauto");
                yield return new shuttle("xstab", "SS", "pp", "tail", "Strong", "yes", "noauto");
                yield return new shuttle("xstab", "SS", "nn", "head", "Light", "yes", "noauto");
                yield return new shuttle("xstab", "SS", "nn", "head", "Medium", "yes", "noauto");
                yield return new shuttle("xstab", "SS", "nn", "head", "Strong", "yes", "noauto");
                yield return new shuttle("xstab", "SS", "nn", "tail", "Light", "yes", "noauto");
                yield return new shuttle("xstab", "SS", "nn", "tail", "Medium", "yes", "noauto");
                yield return new shuttle("xstab", "SS", "nn", "tail", "Strong", "yes", "noauto");
                yield return new shuttle("stab", "LX", "pp", "head", "Light", "yes", "noauto");
                yield return new shuttle("stab", "LX", "pp", "head", "Medium", "yes", "noauto");
                yield return new shuttle("stab", "LX", "pp", "head", "Strong", "yes", "noauto");
                yield return new shuttle("stab", "LX", "pp", "tail", "Light", "yes", "noauto");
                yield return new shuttle("stab", "LX", "pp", "tail", "Medium", "yes", "noauto");
                yield return new shuttle("stab", "LX", "pp", "tail", "Strong", "yes", "noauto");
                yield return new shuttle("stab", "LX", "nn", "head", "Light", "yes", "noauto");
                yield return new shuttle("stab", "LX", "nn", "head", "Medium", "yes", "noauto");
                yield return new shuttle("stab", "LX", "nn", "head", "Strong", "yes", "noauto");
                yield return new shuttle("stab", "LX", "nn", "tail", "Light", "yes", "noauto");
                yield return new shuttle("stab", "LX", "nn", "tail", "Medium", "yes", "noauto");
                yield return new shuttle("stab", "LX", "nn", "tail", "Strong", "yes", "noauto");
                yield return new shuttle("stab", "XL", "pp", "head", "Light", "yes", "noauto");
                yield return new shuttle("stab", "XL", "pp", "head", "Medium", "yes", "noauto");
                yield return new shuttle("stab", "XL", "pp", "head", "Strong", "yes", "noauto");
                yield return new shuttle("stab", "XL", "pp", "tail", "Light", "yes", "noauto");
                yield return new shuttle("stab", "XL", "pp", "tail", "Medium", "yes", "noauto");
                yield return new shuttle("stab", "XL", "pp", "tail", "Strong", "yes", "noauto");
                yield return new shuttle("stab", "XL", "nn", "head", "Light", "yes", "noauto");
                yield return new shuttle("stab", "XL", "nn", "head", "Medium", "yes", "noauto");
                yield return new shuttle("stab", "XL", "nn", "head", "Strong", "yes", "noauto");
                yield return new shuttle("stab", "XL", "nn", "tail", "Light", "yes", "noauto");
                yield return new shuttle("stab", "XL", "nn", "tail", "Medium", "yes", "noauto");
                yield return new shuttle("stab", "XL", "nn", "tail", "Strong", "yes", "noauto");
                yield return new shuttle("stab", "MM", "pp", "head", "Light", "yes", "auto");
                yield return new shuttle("stab", "MM", "pp", "head", "Medium", "yes", "auto");
                yield return new shuttle("stab", "MM", "pp", "head", "Strong", "yes", "noauto");
                yield return new shuttle("stab", "MM", "pp", "tail", "Light", "yes", "auto");
                yield return new shuttle("stab", "MM", "pp", "tail", "Medium", "yes", "auto");
                yield return new shuttle("stab", "MM", "pp", "tail", "Strong", "yes", "auto");
                yield return new shuttle("stab", "MM", "nn", "tail", "Light", "yes", "noauto");
                yield return new shuttle("stab", "MM", "nn", "tail", "Medium", "yes", "noauto");
                yield return new shuttle("stab", "MM", "nn", "tail", "Strong", "yes", "noauto");
                yield return new shuttle("stab", "SS", "pp", "head", "Light", "yes", "auto");
                yield return new shuttle("stab", "SS", "pp", "head", "Medium", "yes", "auto");
                yield return new shuttle("stab", "SS", "pp", "head", "Strong", "yes", "auto");
                yield return new shuttle("stab", "SS", "pp", "tail", "Light", "yes", "auto");
                yield return new shuttle("stab", "SS", "pp", "tail", "Medium", "yes", "auto");
                yield return new shuttle("stab", "SS", "pp", "tail", "Strong", "yes", "auto");
                yield return new shuttle("stab", "SS", "nn", "head", "Light", "yes", "auto");
                yield return new shuttle("stab", "SS", "nn", "head", "Medium", "yes", "auto");
                yield return new shuttle("stab", "SS", "nn", "head", "Strong", "yes", "auto");
                yield return new shuttle("stab", "SS", "nn", "tail", "Light", "yes", "auto");
                yield return new shuttle("stab", "SS", "nn", "tail", "Medium", "yes", "auto");
                yield return new shuttle("stab", "SS", "nn", "tail", "Strong", "yes", "auto");
                yield return new shuttle("xstab", "LX", "pp", "head", "Out", "yes", "noauto");
                yield return new shuttle("xstab", "LX", "pp", "tail", "Out", "yes", "noauto");
                yield return new shuttle("xstab", "LX", "nn", "head", "Out", "yes", "noauto");
                yield return new shuttle("xstab", "LX", "nn", "tail", "Out", "yes", "noauto");
                yield return new shuttle("xstab", "XL", "pp", "head", "Out", "yes", "noauto");
                yield return new shuttle("xstab", "XL", "pp", "tail", "Out", "yes", "noauto");
                yield return new shuttle("xstab", "XL", "nn", "head", "Out", "yes", "noauto");
                yield return new shuttle("xstab", "XL", "nn", "tail", "Out", "yes", "noauto");
                yield return new shuttle("xstab", "MM", "pp", "head", "Out", "yes", "noauto");
                yield return new shuttle("xstab", "MM", "pp", "tail", "Out", "yes", "noauto");
                yield return new shuttle("xstab", "MM", "nn", "head", "Out", "yes", "noauto");
                yield return new shuttle("xstab", "MM", "nn", "tail", "Out", "yes", "noauto");
                yield return new shuttle("xstab", "SS", "pp", "head", "Out", "yes", "noauto");
                yield return new shuttle("xstab", "SS", "pp", "tail", "Out", "yes", "noauto");
                yield return new shuttle("xstab", "SS", "nn", "head", "Out", "yes", "noauto");
                yield return new shuttle("xstab", "SS", "nn", "tail", "Out", "yes", "noauto");
                yield return new shuttle("stab", "LX", "pp", "head", "Out", "yes", "noauto");
                yield return new shuttle("stab", "LX", "pp", "tail", "Out", "yes", "noauto");
                yield return new shuttle("stab", "LX", "nn", "head", "Out", "yes", "noauto");
                yield return new shuttle("stab", "LX", "nn", "tail", "Out", "yes", "noauto");
                yield return new shuttle("stab", "XL", "pp", "head", "Out", "yes", "noauto");
                yield return new shuttle("stab", "XL", "pp", "tail", "Out", "yes", "noauto");
                yield return new shuttle("stab", "XL", "nn", "head", "Out", "yes", "noauto");
                yield return new shuttle("stab", "XL", "nn", "tail", "Out", "yes", "noauto");
                yield return new shuttle("stab", "MM", "pp", "head", "Out", "yes", "noauto");
                yield return new shuttle("stab", "MM", "pp", "tail", "Out", "yes", "noauto");
                yield return new shuttle("stab", "MM", "nn", "head", "Out", "yes", "noauto");
                yield return new shuttle("stab", "MM", "nn", "tail", "Out", "yes", "noauto");
                yield return new shuttle("stab", "SS", "pp", "head", "Out", "yes", "noauto");
                yield return new shuttle("stab", "SS", "pp", "tail", "Out", "yes", "noauto");
                yield return new shuttle("stab", "SS", "nn", "head", "Out", "yes", "noauto");
                yield return new shuttle("stab", "SS", "nn", "tail", "Out", "yes", "noauto");
                yield return new shuttle("stab", "MM", "nn", "head", "Light", "yes", "noauto");
                yield return new shuttle("stab", "MM", "nn", "head", "Medium", "yes", "noauto");
                yield return new shuttle("stab", "MM", "nn", "head", "Strong", "yes", "noauto");
            }
        }
    }
}
