// ReSharper disable All

namespace Rdatasets.Ecdat
{
    using System.Collections.Generic;

    /// <summary>
    /// Pricing the C's of Diamond Stones
    /// </summary>

    public class Diamond
    {
        public readonly double carat;
        public readonly string colour;
        public readonly string clarity;
        public readonly string certification;
        public readonly int price;

        public Diamond(double carat, string colour, string clarity, string certification, int price)
        {
            this.carat = carat;
            this.colour = colour;
            this.clarity = clarity;
            this.certification = certification;
            this.price = price;
        }

        public static IEnumerable<Diamond> Data
        {
            get
            {
                yield return new Diamond(0.3, "D", "VS2", "GIA", 1302);
                yield return new Diamond(0.3, "E", "VS1", "GIA", 1510);
                yield return new Diamond(0.3, "G", "VVS1", "GIA", 1510);
                yield return new Diamond(0.3, "G", "VS1", "GIA", 1260);
                yield return new Diamond(0.31, "D", "VS1", "GIA", 1641);
                yield return new Diamond(0.31, "E", "VS1", "GIA", 1555);
                yield return new Diamond(0.31, "F", "VS1", "GIA", 1427);
                yield return new Diamond(0.31, "G", "VVS2", "GIA", 1427);
                yield return new Diamond(0.31, "H", "VS2", "GIA", 1126);
                yield return new Diamond(0.31, "I", "VS1", "GIA", 1126);
                yield return new Diamond(0.32, "F", "VS1", "GIA", 1468);
                yield return new Diamond(0.32, "G", "VS2", "GIA", 1202);
                yield return new Diamond(0.33, "E", "VS2", "GIA", 1327);
                yield return new Diamond(0.33, "I", "VS2", "GIA", 1098);
                yield return new Diamond(0.34, "E", "VS1", "GIA", 1693);
                yield return new Diamond(0.34, "F", "VS1", "GIA", 1551);
                yield return new Diamond(0.34, "G", "VS1", "GIA", 1410);
                yield return new Diamond(0.34, "G", "VS2", "GIA", 1269);
                yield return new Diamond(0.34, "H", "VS1", "GIA", 1316);
                yield return new Diamond(0.34, "H", "VS2", "GIA", 1222);
                yield return new Diamond(0.35, "E", "VS1", "GIA", 1738);
                yield return new Diamond(0.35, "F", "VS1", "GIA", 1593);
                yield return new Diamond(0.35, "G", "VS1", "GIA", 1447);
                yield return new Diamond(0.35, "H", "VS2", "GIA", 1255);
                yield return new Diamond(0.36, "F", "VS1", "GIA", 1635);
                yield return new Diamond(0.36, "H", "VVS2", "GIA", 1485);
                yield return new Diamond(0.37, "F", "VS2", "GIA", 1420);
                yield return new Diamond(0.37, "H", "VS1", "GIA", 1420);
                yield return new Diamond(0.4, "F", "VS1", "GIA", 1911);
                yield return new Diamond(0.4, "H", "VS1", "GIA", 1525);
                yield return new Diamond(0.41, "F", "VS1", "GIA", 1956);
                yield return new Diamond(0.43, "H", "VVS2", "GIA", 1747);
                yield return new Diamond(0.45, "I", "VS1", "GIA", 1572);
                yield return new Diamond(0.46, "E", "VVS2", "GIA", 2942);
                yield return new Diamond(0.48, "G", "VVS2", "GIA", 2532);
                yield return new Diamond(0.5, "E", "VS1", "GIA", 3501);
                yield return new Diamond(0.5, "E", "VS1", "GIA", 3501);
                yield return new Diamond(0.5, "F", "VVS2", "GIA", 3501);
                yield return new Diamond(0.5, "F", "VS1", "GIA", 3293);
                yield return new Diamond(0.5, "G", "VS1", "GIA", 3016);
                yield return new Diamond(0.51, "F", "VVS2", "GIA", 3567);
                yield return new Diamond(0.51, "G", "VS1", "GIA", 3205);
                yield return new Diamond(0.52, "D", "VS2", "GIA", 3490);
                yield return new Diamond(0.52, "E", "VS1", "GIA", 3635);
                yield return new Diamond(0.52, "F", "VVS2", "GIA", 3635);
                yield return new Diamond(0.52, "F", "VS1", "GIA", 3418);
                yield return new Diamond(0.53, "D", "VS1", "GIA", 3921);
                yield return new Diamond(0.53, "F", "VVS2", "GIA", 3701);
                yield return new Diamond(0.53, "F", "VS1", "GIA", 3480);
                yield return new Diamond(0.53, "G", "VVS2", "GIA", 3407);
                yield return new Diamond(0.54, "E", "VS1", "GIA", 3767);
                yield return new Diamond(0.54, "F", "VVS1", "GIA", 4066);
                yield return new Diamond(0.55, "E", "VVS2", "GIA", 4138);
                yield return new Diamond(0.55, "F", "VS1", "GIA", 3605);
                yield return new Diamond(0.55, "G", "VVS2", "GIA", 3529);
                yield return new Diamond(0.56, "F", "VS1", "GIA", 3667);
                yield return new Diamond(0.56, "I", "VVS2", "GIA", 2892);
                yield return new Diamond(0.57, "G", "VVS2", "GIA", 3651);
                yield return new Diamond(0.59, "G", "VVS2", "GIA", 3773);
                yield return new Diamond(0.6, "F", "VS1", "GIA", 4291);
                yield return new Diamond(0.62, "E", "VVS1", "GIA", 5845);
                yield return new Diamond(0.63, "G", "VVS2", "GIA", 4401);
                yield return new Diamond(0.64, "G", "VVS1", "GIA", 4759);
                yield return new Diamond(0.66, "H", "VVS1", "GIA", 4300);
                yield return new Diamond(0.7, "F", "VS1", "GIA", 5510);
                yield return new Diamond(0.7, "G", "VS1", "GIA", 5122);
                yield return new Diamond(0.7, "H", "VVS2", "GIA", 5122);
                yield return new Diamond(0.7, "I", "VS2", "GIA", 3861);
                yield return new Diamond(0.71, "F", "VVS2", "GIA", 5881);
                yield return new Diamond(0.71, "F", "VS1", "GIA", 5586);
                yield return new Diamond(0.71, "F", "VS2", "GIA", 5193);
                yield return new Diamond(0.71, "H", "VVS2", "GIA", 5193);
                yield return new Diamond(0.72, "F", "VS2", "GIA", 5263);
                yield return new Diamond(0.8, "I", "VVS2", "GIA", 5441);
                yield return new Diamond(0.82, "I", "VS2", "GIA", 4948);
                yield return new Diamond(0.84, "H", "VS2", "GIA", 5705);
                yield return new Diamond(0.85, "F", "VS2", "GIA", 6805);
                yield return new Diamond(0.86, "H", "VVS2", "GIA", 6882);
                yield return new Diamond(0.89, "H", "VS1", "GIA", 6709);
                yield return new Diamond(0.9, "I", "VVS2", "GIA", 6682);
                yield return new Diamond(0.5, "E", "VS1", "GIA", 3501);
                yield return new Diamond(0.5, "G", "VVS1", "GIA", 3432);
                yield return new Diamond(0.51, "F", "VVS1", "GIA", 3851);
                yield return new Diamond(0.55, "H", "IF", "GIA", 3605);
                yield return new Diamond(0.56, "E", "VS1", "GIA", 3900);
                yield return new Diamond(0.57, "H", "VVS1", "GIA", 3415);
                yield return new Diamond(0.6, "H", "IF", "GIA", 4291);
                yield return new Diamond(0.63, "E", "IF", "GIA", 6512);
                yield return new Diamond(0.7, "E", "VS1", "GIA", 5800);
                yield return new Diamond(0.7, "F", "VVS1", "GIA", 6285);
                yield return new Diamond(0.7, "F", "VS2", "GIA", 5122);
                yield return new Diamond(0.7, "F", "VS2", "GIA", 5122);
                yield return new Diamond(0.7, "G", "VS1", "GIA", 5122);
                yield return new Diamond(0.7, "H", "VVS2", "GIA", 5122);
                yield return new Diamond(0.71, "D", "VS1", "GIA", 6372);
                yield return new Diamond(0.71, "E", "VS1", "GIA", 5881);
                yield return new Diamond(0.71, "H", "VVS2", "GIA", 5193);
                yield return new Diamond(0.72, "E", "VS1", "GIA", 5961);
                yield return new Diamond(0.72, "H", "VVS1", "GIA", 5662);
                yield return new Diamond(0.73, "E", "VS2", "GIA", 5738);
                yield return new Diamond(0.73, "H", "VS1", "GIA", 5030);
                yield return new Diamond(0.73, "H", "VS1", "GIA", 5030);
                yield return new Diamond(0.73, "I", "VVS1", "GIA", 4727);
                yield return new Diamond(0.73, "I", "VS1", "GIA", 4221);
                yield return new Diamond(0.74, "G", "VVS2", "GIA", 5815);
                yield return new Diamond(0.74, "H", "VS2", "GIA", 4585);
                yield return new Diamond(0.75, "D", "VVS2", "GIA", 7368);
                yield return new Diamond(0.75, "I", "VVS2", "GIA", 4667);
                yield return new Diamond(0.75, "I", "VS1", "GIA", 4355);
                yield return new Diamond(0.76, "D", "IF", "GIA", 9885);
                yield return new Diamond(0.77, "F", "VVS1", "GIA", 6919);
                yield return new Diamond(0.78, "H", "VS1", "GIA", 5386);
                yield return new Diamond(0.8, "I", "VS2", "GIA", 4832);
                yield return new Diamond(0.83, "E", "VS2", "GIA", 7156);
                yield return new Diamond(0.9, "F", "VS1", "GIA", 7680);
                yield return new Diamond(1, "D", "VVS1", "GIA", 15582);
                yield return new Diamond(1, "D", "VS1", "GIA", 11419);
                yield return new Diamond(1, "E", "VS1", "GIA", 10588);
                yield return new Diamond(1, "E", "VS2", "GIA", 9757);
                yield return new Diamond(1, "F", "IF", "GIA", 13913);
                yield return new Diamond(1, "F", "VVS2", "GIA", 10588);
                yield return new Diamond(1, "F", "VS1", "GIA", 10713);
                yield return new Diamond(1, "F", "VS2", "GIA", 9480);
                yield return new Diamond(1, "G", "VVS2", "GIA", 9896);
                yield return new Diamond(1, "G", "VS1", "GIA", 9619);
                yield return new Diamond(1, "G", "VS2", "GIA", 9169);
                yield return new Diamond(1, "G", "VS2", "GIA", 9203);
                yield return new Diamond(1, "H", "VS2", "GIA", 8788);
                yield return new Diamond(1, "I", "VS1", "GIA", 8095);
                yield return new Diamond(1, "I", "VS2", "GIA", 7818);
                yield return new Diamond(1.01, "D", "VVS1", "GIA", 16008);
                yield return new Diamond(1.01, "E", "VS1", "GIA", 10692);
                yield return new Diamond(1.01, "E", "VS2", "GIA", 9853);
                yield return new Diamond(1.01, "F", "VS1", "GIA", 10272);
                yield return new Diamond(1.01, "F", "VS2", "GIA", 9573);
                yield return new Diamond(1.01, "H", "VS1", "GIA", 9153);
                yield return new Diamond(1.01, "H", "VS2", "GIA", 8873);
                yield return new Diamond(1.01, "I", "VVS1", "GIA", 8873);
                yield return new Diamond(1.01, "I", "VVS2", "GIA", 8455);
                yield return new Diamond(1.01, "I", "VS2", "GIA", 7895);
                yield return new Diamond(1.02, "F", "VS1", "GIA", 10372);
                yield return new Diamond(1.02, "F", "VS2", "GIA", 9666);
                yield return new Diamond(1.02, "G", "VVS2", "GIA", 10090);
                yield return new Diamond(1.03, "E", "VS1", "GIA", 10900);
                yield return new Diamond(1.04, "F", "VS1", "GIA", 10571);
                yield return new Diamond(1.04, "I", "IF", "GIA", 9563);
                yield return new Diamond(1.05, "I", "VVS2", "GIA", 8781);
                yield return new Diamond(1.06, "G", "VS2", "GIA", 9743);
                yield return new Diamond(1.06, "H", "VS2", "GIA", 9302);
                yield return new Diamond(1.07, "I", "VVS2", "GIA", 8945);
                yield return new Diamond(1.1, "H", "VS2", "GIA", 9646);
                yield return new Diamond(0.18, "F", "VVS1", "IGI", 823);
                yield return new Diamond(0.18, "F", "VVS2", "IGI", 765);
                yield return new Diamond(0.18, "G", "IF", "IGI", 803);
                yield return new Diamond(0.18, "G", "IF", "IGI", 803);
                yield return new Diamond(0.18, "G", "VVS2", "IGI", 705);
                yield return new Diamond(0.18, "H", "IF", "IGI", 725);
                yield return new Diamond(0.19, "D", "VVS2", "IGI", 967);
                yield return new Diamond(0.19, "E", "IF", "IGI", 1050);
                yield return new Diamond(0.19, "F", "IF", "IGI", 967);
                yield return new Diamond(0.19, "F", "VVS1", "IGI", 863);
                yield return new Diamond(0.19, "F", "VVS2", "IGI", 800);
                yield return new Diamond(0.19, "G", "IF", "IGI", 842);
                yield return new Diamond(0.19, "G", "VVS1", "IGI", 800);
                yield return new Diamond(0.19, "H", "IF", "IGI", 758);
                yield return new Diamond(0.2, "D", "VS1", "IGI", 880);
                yield return new Diamond(0.2, "G", "IF", "IGI", 880);
                yield return new Diamond(0.2, "G", "VS1", "IGI", 705);
                yield return new Diamond(0.2, "G", "VS2", "IGI", 638);
                yield return new Diamond(0.21, "D", "VS1", "IGI", 919);
                yield return new Diamond(0.21, "E", "IF", "IGI", 1149);
                yield return new Diamond(0.21, "F", "IF", "IGI", 1057);
                yield return new Diamond(0.21, "G", "IF", "IGI", 919);
                yield return new Diamond(0.22, "E", "IF", "IGI", 1198);
                yield return new Diamond(0.23, "E", "IF", "IGI", 1248);
                yield return new Diamond(0.23, "F", "IF", "IGI", 1147);
                yield return new Diamond(0.23, "G", "IF", "IGI", 995);
                yield return new Diamond(0.24, "H", "IF", "IGI", 1108);
                yield return new Diamond(0.25, "F", "IF", "IGI", 1485);
                yield return new Diamond(0.25, "G", "IF", "IGI", 1283);
                yield return new Diamond(0.25, "H", "IF", "IGI", 1149);
                yield return new Diamond(0.25, "I", "IF", "IGI", 1082);
                yield return new Diamond(0.26, "F", "IF", "IGI", 1539);
                yield return new Diamond(0.26, "F", "VVS1", "IGI", 1365);
                yield return new Diamond(0.26, "F", "VVS2", "IGI", 1260);
                yield return new Diamond(0.26, "I", "IF", "IGI", 1121);
                yield return new Diamond(0.27, "F", "IF", "IGI", 1595);
                yield return new Diamond(0.27, "H", "IF", "IGI", 1233);
                yield return new Diamond(0.28, "I", "IF", "IGI", 1199);
                yield return new Diamond(0.29, "G", "IF", "IGI", 1471);
                yield return new Diamond(0.29, "I", "IF", "IGI", 1238);
                yield return new Diamond(0.3, "E", "VVS2", "IGI", 1580);
                yield return new Diamond(0.3, "F", "VVS2", "IGI", 1459);
                yield return new Diamond(0.3, "G", "VVS1", "IGI", 1459);
                yield return new Diamond(0.3, "H", "VVS2", "IGI", 1218);
                yield return new Diamond(0.3, "I", "IF", "IGI", 1299);
                yield return new Diamond(0.31, "E", "VVS2", "IGI", 1628);
                yield return new Diamond(0.31, "F", "VVS1", "IGI", 1628);
                yield return new Diamond(0.31, "I", "IF", "IGI", 1337);
                yield return new Diamond(0.32, "H", "IF", "IGI", 1462);
                yield return new Diamond(0.33, "H", "IF", "IGI", 1503);
                yield return new Diamond(0.34, "F", "VVS1", "IGI", 1773);
                yield return new Diamond(0.34, "F", "VVS2", "IGI", 1636);
                yield return new Diamond(0.35, "F", "VVS1", "IGI", 1821);
                yield return new Diamond(0.35, "G", "VVS2", "IGI", 1540);
                yield return new Diamond(0.4, "G", "IF", "IGI", 2276);
                yield return new Diamond(0.41, "I", "VVS1", "IGI", 1616);
                yield return new Diamond(0.41, "I", "VVS2", "IGI", 1506);
                yield return new Diamond(0.47, "F", "VVS2", "IGI", 2651);
                yield return new Diamond(0.48, "F", "VS1", "IGI", 2383);
                yield return new Diamond(0.5, "G", "IF", "IGI", 3652);
                yield return new Diamond(0.51, "E", "VVS2", "IGI", 3722);
                yield return new Diamond(0.51, "F", "VVS1", "IGI", 3722);
                yield return new Diamond(0.52, "I", "IF", "IGI", 3095);
                yield return new Diamond(0.55, "F", "VVS2", "IGI", 3706);
                yield return new Diamond(0.56, "E", "VVS2", "IGI", 4070);
                yield return new Diamond(0.56, "G", "VVS2", "IGI", 3470);
                yield return new Diamond(0.58, "E", "VVS1", "IGI", 4831);
                yield return new Diamond(0.58, "F", "VVS1", "IGI", 4209);
                yield return new Diamond(0.58, "G", "VVS1", "IGI", 3821);
                yield return new Diamond(0.7, "G", "VVS1", "IGI", 5607);
                yield return new Diamond(0.7, "G", "VVS2", "IGI", 5326);
                yield return new Diamond(0.71, "D", "VS1", "IGI", 6160);
                yield return new Diamond(0.76, "F", "VVS2", "IGI", 6095);
                yield return new Diamond(0.78, "G", "VVS2", "IGI", 5937);
                yield return new Diamond(1, "H", "VVS2", "IGI", 9342);
                yield return new Diamond(1.01, "G", "VS1", "IGI", 9713);
                yield return new Diamond(1.01, "H", "VS2", "IGI", 8873);
                yield return new Diamond(1.01, "I", "VS1", "IGI", 8175);
                yield return new Diamond(0.5, "F", "VVS1", "HRD", 3778);
                yield return new Diamond(0.5, "G", "VVS1", "HRD", 3432);
                yield return new Diamond(0.51, "F", "VVS1", "HRD", 3851);
                yield return new Diamond(0.52, "E", "VS2", "HRD", 3346);
                yield return new Diamond(0.52, "H", "VVS1", "HRD", 3130);
                yield return new Diamond(0.53, "F", "VVS1", "HRD", 3995);
                yield return new Diamond(0.53, "F", "VVS2", "HRD", 3701);
                yield return new Diamond(0.55, "G", "VVS2", "HRD", 3529);
                yield return new Diamond(0.56, "F", "VS1", "HRD", 3667);
                yield return new Diamond(0.56, "F", "VS2", "HRD", 3202);
                yield return new Diamond(0.57, "F", "VS2", "HRD", 3256);
                yield return new Diamond(0.57, "H", "VVS1", "HRD", 3415);
                yield return new Diamond(0.58, "H", "IF", "HRD", 3792);
                yield return new Diamond(0.6, "G", "VS1", "HRD", 3925);
                yield return new Diamond(0.6, "G", "VS2", "HRD", 3421);
                yield return new Diamond(0.6, "H", "VVS1", "HRD", 3925);
                yield return new Diamond(0.61, "H", "VVS2", "HRD", 3616);
                yield return new Diamond(0.62, "I", "VVS2", "HRD", 3615);
                yield return new Diamond(0.64, "H", "VVS2", "HRD", 3785);
                yield return new Diamond(0.65, "I", "VVS2", "HRD", 3643);
                yield return new Diamond(0.66, "H", "VVS1", "HRD", 4300);
                yield return new Diamond(0.7, "E", "VVS1", "HRD", 6867);
                yield return new Diamond(0.7, "E", "VVS2", "HRD", 6285);
                yield return new Diamond(0.7, "G", "VVS1", "HRD", 5800);
                yield return new Diamond(0.7, "G", "VVS2", "HRD", 5510);
                yield return new Diamond(0.7, "H", "VS2", "HRD", 4346);
                yield return new Diamond(0.71, "G", "IF", "HRD", 6372);
                yield return new Diamond(0.71, "H", "VVS2", "HRD", 5193);
                yield return new Diamond(0.72, "H", "VVS1", "HRD", 5662);
                yield return new Diamond(0.73, "F", "VS2", "HRD", 5333);
                yield return new Diamond(0.73, "G", "VVS1", "HRD", 6041);
                yield return new Diamond(0.74, "H", "VVS1", "HRD", 5815);
                yield return new Diamond(0.8, "F", "IF", "HRD", 8611);
                yield return new Diamond(0.8, "F", "VS1", "HRD", 6905);
                yield return new Diamond(0.8, "G", "VVS2", "HRD", 6905);
                yield return new Diamond(0.8, "H", "VVS2", "HRD", 6416);
                yield return new Diamond(0.8, "H", "VS1", "HRD", 6051);
                yield return new Diamond(0.81, "E", "VVS1", "HRD", 8715);
                yield return new Diamond(0.81, "E", "VS2", "HRD", 6988);
                yield return new Diamond(0.81, "F", "VS1", "HRD", 6988);
                yield return new Diamond(0.81, "G", "VS1", "HRD", 6495);
                yield return new Diamond(0.81, "H", "IF", "HRD", 7358);
                yield return new Diamond(0.82, "F", "VS2", "HRD", 6572);
                yield return new Diamond(0.82, "G", "VVS2", "HRD", 7072);
                yield return new Diamond(0.85, "F", "VVS1", "HRD", 8359);
                yield return new Diamond(0.85, "F", "VS2", "HRD", 6805);
                yield return new Diamond(0.85, "G", "VVS1", "HRD", 7711);
                yield return new Diamond(0.86, "H", "VS2", "HRD", 5835);
                yield return new Diamond(1, "D", "VVS2", "HRD", 13775);
                yield return new Diamond(1, "E", "VVS1", "HRD", 14051);
                yield return new Diamond(1, "E", "VVS2", "HRD", 11419);
                yield return new Diamond(1, "E", "VS1", "HRD", 10588);
                yield return new Diamond(1, "F", "VVS1", "HRD", 11696);
                yield return new Diamond(1, "F", "VVS2", "HRD", 10588);
                yield return new Diamond(1, "G", "VVS1", "HRD", 10450);
                yield return new Diamond(1, "G", "VVS2", "HRD", 9896);
                yield return new Diamond(1, "G", "VS2", "HRD", 9203);
                yield return new Diamond(1, "H", "VVS1", "HRD", 9480);
                yield return new Diamond(1, "H", "VS1", "HRD", 9065);
                yield return new Diamond(1, "H", "VS2", "HRD", 8788);
                yield return new Diamond(1, "I", "VVS1", "HRD", 8788);
                yield return new Diamond(1, "I", "VVS2", "HRD", 8372);
                yield return new Diamond(1, "I", "VS1", "HRD", 8095);
                yield return new Diamond(1, "I", "VS2", "HRD", 7818);
                yield return new Diamond(1.01, "D", "VVS2", "HRD", 13909);
                yield return new Diamond(1.01, "E", "VVS2", "HRD", 11531);
                yield return new Diamond(1.01, "E", "VS1", "HRD", 10692);
                yield return new Diamond(1.01, "F", "VVS1", "HRD", 11811);
                yield return new Diamond(1.01, "F", "VS1", "HRD", 10272);
                yield return new Diamond(1.01, "G", "VVS2", "HRD", 9993);
                yield return new Diamond(1.01, "G", "VS2", "HRD", 9293);
                yield return new Diamond(1.01, "H", "VVS2", "HRD", 9433);
                yield return new Diamond(1.01, "H", "VS1", "HRD", 9153);
                yield return new Diamond(1.01, "I", "VVS1", "HRD", 8873);
                yield return new Diamond(1.01, "I", "VS1", "HRD", 8175);
                yield return new Diamond(1.02, "F", "VVS2", "HRD", 10796);
                yield return new Diamond(1.06, "H", "VVS2", "HRD", 9890);
                yield return new Diamond(1.02, "H", "VS2", "HRD", 8959);
                yield return new Diamond(1.09, "I", "VVS2", "HRD", 9107);
            }
        }
    }
}
