// ReSharper disable All

namespace Rdatasets.Ecdat
{
    using System.Collections.Generic;

    /// <summary>
    /// Data from the Television Game Show Friend Or Foe ?
    /// </summary>

    public class FriendFoe
    {
        public readonly string sex;
        public readonly string white;
        public readonly int age;
        public readonly string play;
        public readonly int round;
        public readonly int season;
        public readonly double cash;
        public readonly string sex1;
        public readonly string white1;
        public readonly int age1;
        public readonly string play1;
        public readonly double win;
        public readonly double win1;

        public FriendFoe(string sex, string white, int age, string play, int round, int season, double cash, string sex1, string white1, int age1, string play1, double win, double win1)
        {
            this.sex = sex;
            this.white = white;
            this.age = age;
            this.play = play;
            this.round = round;
            this.season = season;
            this.cash = cash;
            this.sex1 = sex1;
            this.white1 = white1;
            this.age1 = age1;
            this.play1 = play1;
            this.win = win;
            this.win1 = win1;
        }

        public static IEnumerable<FriendFoe> Data
        {
            get
            {
                yield return new FriendFoe("male", "yes", 20, "foe", 1, 1, 1.2, "male", "yes", 32, "friend", 1.2, 0);
                yield return new FriendFoe("male", "yes", 40, "foe", 3, 1, 7.7, "female", "yes", 31, "foe", 0, 0);
                yield return new FriendFoe("female", "no", 35, "foe", 2, 1, 3.2, "female", "no", 24, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 26, "friend", 1, 1, 1.2, "male", "yes", 40, "friend", 0.6, 0.6);
                yield return new FriendFoe("female", "yes", 40, "friend", 3, 1, 5.7, "male", "yes", 26, "foe", 0, 5.7);
                yield return new FriendFoe("female", "yes", 28, "foe", 2, 1, 3.7, "female", "yes", 23, "friend", 3.7, 0);
                yield return new FriendFoe("female", "yes", 26, "friend", 1, 1, 1.2, "female", "yes", 48, "friend", 0.6, 0.6);
                yield return new FriendFoe("male", "no", 30, "foe", 3, 1, 7.2, "male", "no", 27, "friend", 7.2, 0);
                yield return new FriendFoe("female", "yes", 30, "friend", 2, 1, 3.7, "male", "yes", 22, "foe", 0, 3.7);
                yield return new FriendFoe("female", "yes", 25, "friend", 1, 1, 0.7, "male", "yes", 61, "friend", 0.35, 0.35);
                yield return new FriendFoe("male", "yes", 24, "foe", 2, 1, 2.2, "male", "yes", 32, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 31, "foe", 3, 1, 5.2, "female", "yes", 41, "friend", 5.2, 0);
                yield return new FriendFoe("female", "yes", 55, "foe", 1, 1, 0.7, "male", "yes", 25, "friend", 0.7, 0);
                yield return new FriendFoe("male", "yes", 37, "friend", 3, 1, 5.7, "male", "yes", 19, "foe", 0, 5.7);
                yield return new FriendFoe("female", "yes", 24, "foe", 2, 1, 1.7, "female", "yes", 36, "foe", 0, 0);
                yield return new FriendFoe("female", "no", 31, "foe", 1, 1, 1.2, "male", "no", 37, "friend", 1.2, 0);
                yield return new FriendFoe("male", "yes", 24, "foe", 3, 1, 9.2, "female", "yes", 49, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 27, "foe", 2, 1, 2.7, "male", "yes", 22, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 22, "foe", 1, 1, 0.7, "female", "yes", 21, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 40, "friend", 3, 1, 4.2, "male", "yes", 23, "foe", 0, 4.2);
                yield return new FriendFoe("male", "yes", 26, "friend", 2, 1, 3.2, "male", "yes", 27, "foe", 0, 3.2);
                yield return new FriendFoe("female", "yes", 27, "friend", 3, 1, 5.2, "male", "yes", 26, "foe", 0, 5.2);
                yield return new FriendFoe("female", "yes", 40, "friend", 1, 1, 1.2, "female", "yes", 24, "friend", 0.6, 0.6);
                yield return new FriendFoe("male", "yes", 22, "foe", 2, 1, 2.7, "male", "yes", 31, "friend", 2.7, 0);
                yield return new FriendFoe("female", "yes", 31, "foe", 3, 1, 5.7, "female", "yes", 31, "friend", 5.7, 0);
                yield return new FriendFoe("male", "yes", 20, "foe", 1, 1, 0.7, "female", "yes", 30, "friend", 0.7, 0);
                yield return new FriendFoe("male", "no", 39, "friend", 2, 1, 1.2, "female", "no", 35, "friend", 0.6, 0.6);
                yield return new FriendFoe("female", "no", 30, "friend", 1, 1, 3.2, "male", "no", 36, "foe", 0, 3.2);
                yield return new FriendFoe("female", "yes", 25, "friend", 3, 1, 6.2, "male", "yes", 29, "friend", 3.1, 3.1);
                yield return new FriendFoe("male", "no", 44, "friend", 2, 1, 5.2, "female", "no", 24, "friend", 2.6, 2.6);
                yield return new FriendFoe("female", "yes", 43, "foe", 2, 1, 3.2, "male", "yes", 39, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 31, "foe", 1, 1, 1.2, "male", "yes", 30, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 30, "friend", 3, 1, 8.2, "male", "yes", 46, "friend", 4.1, 4.1);
                yield return new FriendFoe("female", "no", 25, "friend", 3, 1, 3.7, "male", "no", 24, "foe", 0, 3.7);
                yield return new FriendFoe("female", "yes", 29, "friend", 1, 1, 1.2, "female", "yes", 40, "foe", 0, 1.2);
                yield return new FriendFoe("female", "yes", 44, "foe", 1, 1, 1.2, "female", "yes", 26, "friend", 1.2, 0);
                yield return new FriendFoe("male", "yes", 37, "foe", 3, 1, 8.7, "male", "yes", 29, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 24, "friend", 2, 1, 4.2, "male", "yes", 24, "friend", 2.1, 2.1);
                yield return new FriendFoe("female", "yes", 18, "friend", 1, 1, 0.7, "male", "yes", 38, "friend", 0.35, 0.35);
                yield return new FriendFoe("male", "yes", 34, "friend", 3, 1, 16.4, "male", "yes", 26, "foe", 0, 16.4);
                yield return new FriendFoe("female", "yes", 34, "friend", 1, 1, 0.2, "female", "yes", 29, "foe", 0, 0.2);
                yield return new FriendFoe("female", "yes", 33, "friend", 2, 1, 8.2, "male", "yes", 19, "friend", 4.1, 4.1);
                yield return new FriendFoe("male", "yes", 29, "friend", 3, 1, 2.2, "female", "yes", 22, "foe", 0, 2.2);
                yield return new FriendFoe("female", "yes", 42, "foe", 1, 1, 1.2, "male", "yes", 35, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 25, "friend", 1, 1, 1.2, "male", "yes", 26, "friend", 0.6, 0.6);
                yield return new FriendFoe("male", "yes", 32, "foe", 3, 1, 6.7, "male", "yes", 40, "friend", 6.7, 0);
                yield return new FriendFoe("female", "no", 29, "foe", 1, 1, 3.2, "female", "no", 49, "friend", 3.2, 0);
                yield return new FriendFoe("male", "yes", 28, "foe", 2, 2, 5.5, "female", "yes", 23, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 22, "friend", 1, 2, 0.5, "male", "yes", 37, "friend", 0.25, 0.25);
                yield return new FriendFoe("male", "yes", 22, "friend", 2, 2, 2, "female", "yes", 32, "foe", 0, 2);
                yield return new FriendFoe("female", "yes", 24, "friend", 3, 1, 7.2, "male", "yes", 37, "foe", 0, 7.2);
                yield return new FriendFoe("male", "yes", 30, "foe", 3, 1, 2.2, "male", "yes", 27, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 42, "friend", 2, 1, 1.2, "female", "yes", 29, "friend", 0.6, 0.6);
                yield return new FriendFoe("male", "no", 41, "friend", 1, 1, 0.7, "female", "no", 31, "foe", 0, 0.7);
                yield return new FriendFoe("female", "yes", 20, "foe", 2, 1, 3.7, "female", "yes", 36, "friend", 3.7, 0);
                yield return new FriendFoe("male", "yes", 31, "friend", 3, 1, 8.7, "male", "yes", 31, "friend", 4.35, 4.35);
                yield return new FriendFoe("female", "yes", 33, "friend", 1, 1, 2.2, "female", "yes", 28, "friend", 1.1, 1.1);
                yield return new FriendFoe("male", "yes", 37, "friend", 3, 1, 9.2, "male", "yes", 27, "foe", 0, 9.2);
                yield return new FriendFoe("female", "no", 28, "friend", 1, 1, 0.7, "male", "no", 20, "foe", 0, 0.7);
                yield return new FriendFoe("male", "yes", 22, "foe", 1, 1, 0.7, "male", "yes", 34, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 18, "friend", 1, 1, 4.7, "female", "yes", 25, "foe", 0, 4.7);
                yield return new FriendFoe("male", "yes", 57, "friend", 3, 1, 9.2, "female", "yes", 44, "foe", 0, 9.2);
                yield return new FriendFoe("female", "yes", 23, "friend", 2, 1, 6.2, "male", "yes", 28, "foe", 0, 6.2);
                yield return new FriendFoe("male", "yes", 27, "foe", 1, 1, 1.7, "female", "yes", 50, "friend", 1.7, 0);
                yield return new FriendFoe("female", "yes", 32, "foe", 1, 1, 1.7, "male", "yes", 38, "friend", 1.7, 0);
                yield return new FriendFoe("female", "yes", 33, "foe", 3, 2, 6, "male", "yes", 21, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 22, "foe", 2, 2, 0.5, "female", "yes", 22, "foe", 0, 0);
                yield return new FriendFoe("female", "no", 22, "foe", 3, 2, 3, "male", "no", 40, "friend", 3, 0);
                yield return new FriendFoe("female", "no", 19, "foe", 1, 2, 0.2, "female", "no", 21, "friend", 0.2, 0);
                yield return new FriendFoe("male", "yes", 48, "foe", 1, 2, 2.5, "male", "yes", 22, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 25, "friend", 3, 2, 7.5, "female", "yes", 31, "foe", 0, 7.5);
                yield return new FriendFoe("female", "yes", 23, "foe", 2, 2, 4.5, "male", "yes", 25, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 23, "friend", 3, 2, 10, "female", "yes", 31, "foe", 0, 10);
                yield return new FriendFoe("female", "yes", 18, "foe", 1, 2, 1.5, "male", "yes", 37, "friend", 1.5, 0);
                yield return new FriendFoe("male", "yes", 21, "friend", 2, 1, 7.7, "female", "yes", 33, "friend", 3.85, 3.85);
                yield return new FriendFoe("female", "yes", 27, "friend", 1, 1, 0.2, "female", "yes", 50, "foe", 0, 0.2);
                yield return new FriendFoe("female", "yes", 23, "foe", 2, 1, 3.2, "male", "yes", 30, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 47, "friend", 3, 1, 3.7, "male", "yes", 41, "friend", 1.85, 1.85);
                yield return new FriendFoe("male", "no", 21, "foe", 1, 1, 1.2, "female", "no", 20, "foe", 0, 0);
                yield return new FriendFoe("female", "no", 28, "friend", 3, 1, 5.2, "male", "no", 29, "friend", 2.6, 2.6);
                yield return new FriendFoe("female", "yes", 27, "foe", 2, 1, 2.7, "female", "yes", 43, "friend", 2.7, 0);
                yield return new FriendFoe("male", "yes", 23, "friend", 3, 1, 6.2, "male", "yes", 33, "friend", 3.1, 3.1);
                yield return new FriendFoe("female", "yes", 19, "foe", 1, 1, 0.2, "male", "yes", 39, "friend", 0.2, 0);
                yield return new FriendFoe("female", "yes", 32, "foe", 2, 1, 2.7, "female", "yes", 25, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 30, "friend", 1, 1, 0.7, "male", "yes", 28, "foe", 0, 0.7);
                yield return new FriendFoe("female", "yes", 39, "friend", 3, 1, 7.7, "male", "yes", 30, "friend", 3.85, 3.85);
                yield return new FriendFoe("female", "yes", 22, "foe", 2, 1, 3.7, "female", "yes", 33, "friend", 3.7, 0);
                yield return new FriendFoe("male", "yes", 20, "foe", 2, 1, 5.7, "male", "yes", 41, "friend", 5.7, 0);
                yield return new FriendFoe("female", "yes", 41, "friend", 1, 1, 0.2, "female", "yes", 35, "friend", 0.1, 0.1);
                yield return new FriendFoe("male", "yes", 25, "foe", 3, 1, 7.7, "male", "yes", 28, "friend", 7.7, 0);
                yield return new FriendFoe("female", "yes", 20, "foe", 1, 1, 1.2, "female", "yes", 27, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 42, "friend", 3, 1, 4.7, "female", "yes", 20, "foe", 0, 4.7);
                yield return new FriendFoe("female", "yes", 29, "friend", 2, 1, 2.2, "male", "yes", 40, "friend", 1.1, 1.1);
                yield return new FriendFoe("male", "yes", 29, "foe", 1, 1, 1.2, "female", "yes", 43, "foe", 0, 0);
                yield return new FriendFoe("female", "no", 21, "friend", 3, 1, 7.7, "male", "no", 25, "friend", 3.85, 3.85);
                yield return new FriendFoe("female", "yes", 18, "foe", 2, 2, 2.5, "male", "yes", 23, "foe", 0, 0);
                yield return new FriendFoe("male", "no", 23, "friend", 2, 2, 3.5, "female", "no", 23, "foe", 0, 3.5);
                yield return new FriendFoe("female", "yes", 31, "friend", 1, 2, 1, "male", "yes", 50, "friend", 0.5, 0.5);
                yield return new FriendFoe("female", "yes", 30, "friend", 3, 2, 4, "male", "yes", 20, "friend", 2, 2);
                yield return new FriendFoe("female", "yes", 20, "friend", 3, 2, 9, "female", "yes", 24, "foe", 0, 9);
                yield return new FriendFoe("male", "yes", 20, "foe", 1, 2, 0.5, "male", "yes", 41, "foe", 0, 0);
                yield return new FriendFoe("male", "no", 31, "foe", 1, 2, 0.5, "female", "no", 18, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 27, "foe", 2, 2, 3.5, "male", "yes", 23, "friend", 3.5, 0);
                yield return new FriendFoe("male", "yes", 34, "friend", 3, 2, 6, "female", "yes", 21, "foe", 0, 6);
                yield return new FriendFoe("female", "yes", 51, "friend", 1, 2, 0.2, "male", "yes", 22, "foe", 0, 0.2);
                yield return new FriendFoe("female", "yes", 28, "friend", 2, 2, 4, "female", "yes", 20, "friend", 2, 2);
                yield return new FriendFoe("male", "no", 34, "friend", 3, 2, 8, "male", "no", 20, "foe", 0, 8);
                yield return new FriendFoe("male", "yes", 29, "foe", 1, 2, 1, "male", "yes", 34, "friend", 1, 0);
                yield return new FriendFoe("male", "no", 29, "foe", 3, 2, 5, "female", "no", 26, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 26, "friend", 1, 2, 0.2, "male", "yes", 27, "foe", 0, 0.2);
                yield return new FriendFoe("male", "yes", 35, "foe", 2, 2, 0.5, "female", "yes", 19, "foe", 0, 0);
                yield return new FriendFoe("male", "no", 29, "foe", 2, 2, 2.5, "male", "no", 19, "friend", 2.5, 0);
                yield return new FriendFoe("female", "yes", 32, "friend", 3, 2, 6, "female", "yes", 20, "friend", 3, 3);
                yield return new FriendFoe("female", "yes", 29, "foe", 1, 2, 0.5, "female", "yes", 31, "friend", 0.5, 0);
                yield return new FriendFoe("male", "yes", 23, "foe", 3, 2, 7.5, "male", "yes", 26, "friend", 7.5, 0);
                yield return new FriendFoe("male", "yes", 25, "foe", 2, 2, 2, "female", "yes", 44, "friend", 2, 0);
                yield return new FriendFoe("female", "yes", 42, "friend", 1, 2, 0.5, "female", "yes", 19, "foe", 0, 0.5);
                yield return new FriendFoe("male", "yes", 24, "friend", 2, 2, 3.5, "male", "yes", 29, "foe", 0, 3.5);
                yield return new FriendFoe("female", "yes", 24, "foe", 3, 2, 6, "female", "yes", 29, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 32, "friend", 1, 2, 3, "female", "yes", 22, "foe", 0, 3);
                yield return new FriendFoe("female", "yes", 31, "foe", 3, 2, 7.5, "male", "yes", 25, "friend", 7.5, 0);
                yield return new FriendFoe("male", "no", 36, "friend", 1, 2, 0.5, "female", "no", 36, "friend", 0.25, 0.25);
                yield return new FriendFoe("female", "yes", 35, "friend", 2, 2, 3, "female", "yes", 21, "friend", 1.5, 1.5);
                yield return new FriendFoe("male", "yes", 33, "foe", 3, 2, 4, "male", "yes", 21, "foe", 0, 0);
                yield return new FriendFoe("female", "no", 24, "friend", 1, 2, 0.2, "male", "no", 20, "foe", 0, 0.2);
                yield return new FriendFoe("male", "no", 31, "friend", 2, 2, 0.5, "female", "no", 19, "foe", 0, 0.5);
                yield return new FriendFoe("female", "yes", 20, "foe", 2, 2, 3.5, "male", "yes", 42, "friend", 3.5, 0);
                yield return new FriendFoe("male", "yes", 25, "friend", 3, 2, 8, "female", "yes", 23, "friend", 4, 4);
                yield return new FriendFoe("male", "no", 28, "foe", 1, 2, 0.5, "female", "no", 30, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 24, "friend", 3, 2, 3.5, "male", "yes", 26, "friend", 1.75, 1.75);
                yield return new FriendFoe("male", "yes", 29, "friend", 2, 2, 2, "female", "yes", 22, "foe", 0, 2);
                yield return new FriendFoe("female", "yes", 30, "foe", 1, 2, 0.5, "female", "yes", 22, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 24, "friend", 2, 2, 6.5, "male", "yes", 23, "foe", 0, 6.5);
                yield return new FriendFoe("male", "yes", 42, "friend", 1, 2, 3, "female", "yes", 27, "friend", 1.5, 1.5);
                yield return new FriendFoe("female", "yes", 23, "foe", 3, 2, 8, "male", "yes", 19, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 27, "friend", 2, 2, 2, "male", "yes", 38, "friend", 1, 1);
                yield return new FriendFoe("female", "no", 40, "foe", 1, 2, 0.5, "female", "no", 23, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 44, "friend", 3, 2, 7.5, "male", "yes", 22, "foe", 0, 7.5);
                yield return new FriendFoe("female", "yes", 18, "foe", 1, 2, 0.5, "female", "yes", 20, "friend", 0.5, 0);
                yield return new FriendFoe("female", "yes", 18, "friend", 2, 2, 2, "male", "yes", 30, "foe", 0, 2);
                yield return new FriendFoe("male", "yes", 18, "foe", 3, 2, 6, "female", "yes", 29, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 26, "foe", 3, 2, 3, "male", "yes", 29, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 47, "foe", 1, 2, 1, "female", "yes", 36, "foe", 0, 0);
                yield return new FriendFoe("female", "no", 34, "foe", 2, 2, 2, "male", "no", 23, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 29, "friend", 2, 2, 5.5, "female", "yes", 19, "friend", 2.75, 2.75);
                yield return new FriendFoe("male", "yes", 43, "foe", 1, 2, 0.5, "male", "yes", 26, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 27, "foe", 1, 2, 0.5, "female", "yes", 26, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 23, "friend", 2, 2, 6, "male", "yes", 25, "foe", 0, 6);
                yield return new FriendFoe("male", "yes", 20, "friend", 1, 2, 3.5, "female", "yes", 22, "friend", 1.75, 1.75);
                yield return new FriendFoe("male", "yes", 39, "foe", 3, 2, 9, "female", "yes", 33, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 23, "friend", 1, 2, 1, "male", "yes", 20, "friend", 0.5, 0.5);
                yield return new FriendFoe("male", "yes", 31, "foe", 2, 2, 4, "female", "yes", 29, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 30, "friend", 3, 2, 4.5, "male", "yes", 28, "foe", 0, 4.5);
                yield return new FriendFoe("male", "yes", 25, "foe", 2, 2, 1.5, "female", "yes", 40, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 28, "friend", 1, 2, 0.2, "male", "yes", 27, "foe", 0, 0.2);
                yield return new FriendFoe("male", "yes", 21, "foe", 3, 2, 4, "female", "yes", 19, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 23, "friend", 3, 2, 8.5, "male", "yes", 22, "friend", 4.25, 4.25);
                yield return new FriendFoe("male", "yes", 25, "foe", 1, 2, 1.5, "female", "yes", 27, "friend", 1.5, 0);
                yield return new FriendFoe("male", "yes", 18, "friend", 2, 2, 6, "female", "yes", 22, "foe", 0, 6);
                yield return new FriendFoe("female", "yes", 26, "foe", 3, 2, 2.5, "male", "yes", 22, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 34, "friend", 1, 2, 1.5, "female", "yes", 28, "foe", 0, 1.5);
                yield return new FriendFoe("male", "yes", 23, "foe", 1, 2, 1.5, "female", "yes", 20, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 41, "friend", 1, 2, 0.5, "male", "yes", 65, "foe", 0, 0.5);
                yield return new FriendFoe("male", "no", 22, "foe", 2, 2, 5, "female", "no", 27, "foe", 0, 0);
                yield return new FriendFoe("male", "no", 27, "foe", 3, 2, 5, "female", "no", 23, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 22, "friend", 3, 2, 1.5, "male", "yes", 30, "foe", 0, 1.5);
                yield return new FriendFoe("male", "yes", 27, "foe", 1, 2, 1, "female", "yes", 27, "friend", 1, 0);
                yield return new FriendFoe("female", "yes", 31, "foe", 1, 2, 1, "female", "yes", 26, "foe", 0, 0);
                yield return new FriendFoe("male", "no", 21, "foe", 3, 2, 7, "male", "no", 37, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 43, "foe", 1, 2, 0.5, "female", "yes", 22, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 26, "friend", 2, 2, 6, "female", "yes", 20, "friend", 3, 3);
                yield return new FriendFoe("male", "yes", 36, "friend", 1, 2, 0.5, "male", "yes", 24, "friend", 0.25, 0.25);
                yield return new FriendFoe("female", "yes", 32, "foe", 3, 2, 2, "female", "yes", 29, "friend", 2, 0);
                yield return new FriendFoe("male", "yes", 21, "friend", 2, 2, 0.5, "female", "yes", 21, "friend", 0.25, 0.25);
                yield return new FriendFoe("male", "yes", 22, "foe", 3, 2, 6, "male", "yes", 29, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 24, "friend", 1, 2, 1.5, "female", "yes", 19, "foe", 0, 1.5);
                yield return new FriendFoe("male", "yes", 23, "foe", 1, 2, 1.5, "female", "yes", 25, "friend", 1.5, 0);
                yield return new FriendFoe("male", "yes", 32, "friend", 1, 2, 0.5, "male", "yes", 33, "friend", 0.25, 0.25);
                yield return new FriendFoe("female", "no", 39, "foe", 3, 2, 5, "female", "no", 24, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 41, "friend", 2, 2, 3, "female", "yes", 32, "friend", 1.5, 1.5);
                yield return new FriendFoe("male", "yes", 28, "foe", 3, 2, 5.5, "male", "yes", 23, "friend", 5.5, 0);
                yield return new FriendFoe("female", "yes", 24, "foe", 1, 2, 0.2, "male", "yes", 22, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 25, "friend", 1, 2, 0.2, "male", "yes", 23, "friend", 0.1, 0.1);
                yield return new FriendFoe("female", "no", 29, "foe", 3, 2, 6.5, "female", "no", 28, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 30, "friend", 1, 2, 2, "male", "yes", 22, "foe", 0, 2);
                yield return new FriendFoe("female", "yes", 32, "friend", 1, 2, 2, "male", "yes", 35, "friend", 1, 1);
                yield return new FriendFoe("female", "yes", 51, "friend", 1, 2, 0.5, "female", "yes", 29, "friend", 0.25, 0.25);
                yield return new FriendFoe("male", "yes", 19, "friend", 3, 2, 3, "male", "yes", 30, "friend", 1.5, 1.5);
                yield return new FriendFoe("male", "yes", 22, "friend", 1, 2, 0.5, "male", "yes", 22, "foe", 0, 0.5);
                yield return new FriendFoe("female", "no", 32, "foe", 1, 2, 0.5, "female", "no", 24, "friend", 0.5, 0);
                yield return new FriendFoe("female", "yes", 28, "foe", 3, 2, 4, "male", "yes", 30, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 40, "friend", 2, 2, 1.5, "female", "yes", 27, "foe", 0, 1.5);
                yield return new FriendFoe("male", "no", 27, "foe", 2, 2, 5, "male", "no", 27, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 32, "friend", 1, 2, 0.5, "female", "yes", 32, "foe", 0, 0.5);
                yield return new FriendFoe("female", "yes", 24, "foe", 3, 2, 15, "female", "yes", 27, "friend", 15, 0);
                yield return new FriendFoe("male", "yes", 31, "friend", 1, 2, 0.2, "male", "yes", 31, "foe", 0, 0.2);
                yield return new FriendFoe("male", "yes", 23, "foe", 2, 2, 1.5, "female", "yes", 23, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 33, "foe", 3, 2, 8.5, "male", "yes", 28, "foe", 0, 0);
                yield return new FriendFoe("male", "no", 29, "friend", 3, 2, 3.5, "male", "no", 26, "foe", 0, 3.5);
                yield return new FriendFoe("female", "yes", 25, "friend", 1, 2, 1, "female", "yes", 25, "friend", 0.5, 0.5);
                yield return new FriendFoe("male", "yes", 36, "foe", 1, 2, 1, "female", "yes", 32, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 19, "foe", 3, 2, 6, "male", "yes", 19, "friend", 6, 0);
                yield return new FriendFoe("female", "yes", 24, "foe", 1, 2, 2, "female", "yes", 29, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 22, "foe", 1, 2, 2, "male", "yes", 26, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 33, "friend", 1, 2, 0.2, "female", "yes", 23, "friend", 0.1, 0.1);
                yield return new FriendFoe("female", "yes", 23, "friend", 2, 2, 2.5, "male", "yes", 40, "foe", 0, 2.5);
                yield return new FriendFoe("female", "yes", 20, "foe", 1, 2, 0.5, "male", "yes", 23, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 49, "foe", 3, 2, 8, "female", "yes", 31, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 24, "friend", 1, 2, 1, "male", "yes", 19, "foe", 0, 1);
                yield return new FriendFoe("female", "no", 25, "foe", 2, 2, 2, "male", "no", 40, "friend", 2, 0);
                yield return new FriendFoe("male", "yes", 26, "foe", 3, 2, 6, "male", "yes", 26, "friend", 6, 0);
                yield return new FriendFoe("female", "yes", 25, "friend", 1, 2, 0.2, "female", "yes", 29, "friend", 0.1, 0.1);
                yield return new FriendFoe("female", "yes", 46, "friend", 2, 2, 0.5, "male", "yes", 29, "foe", 0, 0.5);
                yield return new FriendFoe("female", "yes", 29, "foe", 3, 2, 2.5, "female", "yes", 24, "friend", 2.5, 0);
                yield return new FriendFoe("male", "yes", 39, "foe", 3, 2, 6.5, "male", "yes", 20, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 28, "friend", 1, 2, 2, "female", "yes", 26, "foe", 0, 2);
                yield return new FriendFoe("female", "yes", 32, "foe", 2, 2, 5.5, "female", "yes", 27, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 34, "foe", 1, 2, 1, "female", "yes", 34, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 36, "friend", 3, 2, 6.5, "male", "yes", 23, "friend", 3.25, 3.25);
                yield return new FriendFoe("male", "no", 37, "foe", 2, 2, 3.5, "female", "no", 49, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 32, "foe", 2, 2, 1, "male", "yes", 19, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 22, "friend", 1, 2, 0.2, "female", "yes", 21, "friend", 0.1, 0.1);
                yield return new FriendFoe("male", "yes", 25, "friend", 3, 2, 2.5, "male", "yes", 28, "foe", 0, 2.5);
                yield return new FriendFoe("male", "no", 25, "foe", 2, 2, 4, "female", "no", 24, "foe", 0, 0);
                yield return new FriendFoe("male", "yes", 43, "friend", 1, 2, 1.5, "female", "yes", 26, "foe", 0, 1.5);
                yield return new FriendFoe("male", "yes", 26, "foe", 3, 2, 5, "male", "yes", 37, "foe", 0, 0);
                yield return new FriendFoe("female", "yes", 34, "foe", 1, 2, 1, "female", "yes", 31, "foe", 0, 0);
            }
        }
    }
}
