// ReSharper disable All

namespace Rdatasets.Ecdat
{
    using System.Collections.Generic;

    /// <summary>
    /// Willingness to Pay for the Preservation of the Alentejo Natural Park
    /// </summary>

    public class NaturalPark
    {
        public readonly int bid1;
        public readonly int bidh;
        public readonly int bidl;
        public readonly string answers;
        public readonly int age;
        public readonly string sex;
        public readonly int income;

        public NaturalPark(int bid1, int bidh, int bidl, string answers, int age, string sex, int income)
        {
            this.bid1 = bid1;
            this.bidh = bidh;
            this.bidl = bidl;
            this.answers = answers;
            this.age = age;
            this.sex = sex;
            this.income = income;
        }

        public static IEnumerable<NaturalPark> Data
        {
            get
            {
                yield return new NaturalPark(6, 18, 3, "yy", 1, "female", 2);
                yield return new NaturalPark(48, 120, 24, "yn", 2, "male", 1);
                yield return new NaturalPark(48, 120, 24, "yn", 2, "female", 3);
                yield return new NaturalPark(24, 48, 12, "nn", 5, "female", 1);
                yield return new NaturalPark(24, 48, 12, "ny", 6, "female", 2);
                yield return new NaturalPark(12, 24, 6, "nn", 4, "male", 2);
                yield return new NaturalPark(6, 18, 3, "yy", 2, "female", 3);
                yield return new NaturalPark(12, 24, 6, "yn", 3, "male", 2);
                yield return new NaturalPark(24, 48, 12, "yn", 2, "female", 2);
                yield return new NaturalPark(6, 18, 3, "yy", 3, "male", 3);
                yield return new NaturalPark(12, 24, 6, "nn", 5, "female", 2);
                yield return new NaturalPark(24, 48, 12, "yn", 3, "female", 1);
                yield return new NaturalPark(12, 24, 6, "yn", 3, "female", 3);
                yield return new NaturalPark(48, 120, 24, "nn", 3, "female", 2);
                yield return new NaturalPark(12, 24, 6, "yy", 1, "male", 1);
                yield return new NaturalPark(6, 18, 3, "nn", 2, "male", 1);
                yield return new NaturalPark(48, 120, 24, "yn", 1, "female", 3);
                yield return new NaturalPark(24, 48, 12, "nn", 1, "female", 2);
                yield return new NaturalPark(12, 24, 6, "yy", 2, "male", 3);
                yield return new NaturalPark(6, 18, 3, "nn", 6, "female", 1);
                yield return new NaturalPark(24, 48, 12, "yn", 2, "male", 4);
                yield return new NaturalPark(12, 24, 6, "yn", 3, "male", 2);
                yield return new NaturalPark(12, 24, 6, "yy", 2, "female", 2);
                yield return new NaturalPark(6, 18, 3, "yn", 3, "male", 1);
                yield return new NaturalPark(6, 18, 3, "nn", 4, "female", 1);
                yield return new NaturalPark(24, 48, 12, "yy", 6, "male", 3);
                yield return new NaturalPark(24, 48, 12, "nn", 2, "female", 2);
                yield return new NaturalPark(48, 120, 24, "yn", 1, "male", 3);
                yield return new NaturalPark(12, 24, 6, "nn", 4, "female", 3);
                yield return new NaturalPark(48, 120, 24, "nn", 6, "male", 3);
                yield return new NaturalPark(24, 48, 12, "yn", 3, "female", 3);
                yield return new NaturalPark(48, 120, 24, "ny", 4, "male", 3);
                yield return new NaturalPark(24, 48, 12, "nn", 3, "female", 2);
                yield return new NaturalPark(12, 24, 6, "nn", 4, "female", 1);
                yield return new NaturalPark(6, 18, 3, "yn", 3, "female", 2);
                yield return new NaturalPark(6, 18, 3, "yy", 5, "female", 2);
                yield return new NaturalPark(48, 120, 24, "yn", 3, "female", 2);
                yield return new NaturalPark(24, 48, 12, "nn", 2, "female", 3);
                yield return new NaturalPark(12, 24, 6, "yy", 4, "female", 2);
                yield return new NaturalPark(48, 120, 24, "nn", 4, "male", 3);
                yield return new NaturalPark(48, 120, 24, "yn", 6, "male", 1);
                yield return new NaturalPark(12, 24, 6, "nn", 3, "male", 2);
                yield return new NaturalPark(24, 48, 12, "yn", 6, "female", 2);
                yield return new NaturalPark(12, 24, 6, "nn", 5, "female", 1);
                yield return new NaturalPark(6, 18, 3, "nn", 5, "female", 2);
                yield return new NaturalPark(24, 48, 12, "nn", 5, "male", 1);
                yield return new NaturalPark(24, 48, 12, "nn", 1, "male", 1);
                yield return new NaturalPark(6, 18, 3, "nn", 1, "female", 3);
                yield return new NaturalPark(12, 24, 6, "nn", 6, "female", 1);
                yield return new NaturalPark(6, 18, 3, "yn", 4, "female", 3);
                yield return new NaturalPark(12, 24, 6, "nn", 1, "male", 2);
                yield return new NaturalPark(48, 120, 24, "ny", 2, "female", 3);
                yield return new NaturalPark(24, 48, 12, "yn", 4, "female", 2);
                yield return new NaturalPark(48, 120, 24, "ny", 3, "male", 2);
                yield return new NaturalPark(6, 18, 3, "yy", 1, "female", 1);
                yield return new NaturalPark(12, 24, 6, "nn", 3, "male", 4);
                yield return new NaturalPark(12, 24, 6, "nn", 6, "female", 1);
                yield return new NaturalPark(6, 18, 3, "yn", 3, "female", 3);
                yield return new NaturalPark(48, 120, 24, "yn", 1, "male", 3);
                yield return new NaturalPark(24, 48, 12, "nn", 3, "male", 3);
                yield return new NaturalPark(48, 120, 24, "yn", 2, "female", 3);
                yield return new NaturalPark(6, 18, 3, "nn", 6, "male", 4);
                yield return new NaturalPark(24, 48, 12, "yn", 2, "female", 4);
                yield return new NaturalPark(12, 24, 6, "nn", 5, "female", 2);
                yield return new NaturalPark(12, 24, 6, "nn", 1, "male", 4);
                yield return new NaturalPark(6, 18, 3, "yn", 1, "female", 6);
                yield return new NaturalPark(48, 120, 24, "yn", 3, "female", 3);
                yield return new NaturalPark(48, 120, 24, "nn", 5, "male", 2);
                yield return new NaturalPark(6, 18, 3, "yy", 1, "male", 5);
                yield return new NaturalPark(12, 24, 6, "nn", 4, "female", 2);
                yield return new NaturalPark(24, 48, 12, "nn", 2, "female", 2);
                yield return new NaturalPark(12, 24, 6, "nn", 2, "male", 5);
                yield return new NaturalPark(24, 48, 12, "yn", 2, "female", 4);
                yield return new NaturalPark(48, 120, 24, "yn", 1, "female", 3);
                yield return new NaturalPark(12, 24, 6, "yy", 2, "female", 5);
                yield return new NaturalPark(6, 18, 3, "yy", 1, "female", 2);
                yield return new NaturalPark(12, 24, 6, "yy", 5, "male", 3);
                yield return new NaturalPark(24, 48, 12, "yn", 1, "male", 2);
                yield return new NaturalPark(48, 120, 24, "nn", 4, "male", 1);
                yield return new NaturalPark(6, 18, 3, "nn", 4, "female", 2);
                yield return new NaturalPark(24, 48, 12, "nn", 3, "female", 1);
                yield return new NaturalPark(12, 24, 6, "yn", 1, "female", 3);
                yield return new NaturalPark(48, 120, 24, "yn", 6, "male", 2);
                yield return new NaturalPark(48, 120, 24, "nn", 5, "male", 1);
                yield return new NaturalPark(6, 18, 3, "yy", 2, "male", 3);
                yield return new NaturalPark(48, 120, 24, "nn", 3, "female", 5);
                yield return new NaturalPark(48, 120, 24, "ny", 3, "female", 4);
                yield return new NaturalPark(12, 24, 6, "nn", 1, "male", 3);
                yield return new NaturalPark(12, 24, 6, "ny", 4, "female", 1);
                yield return new NaturalPark(48, 120, 24, "yn", 4, "male", 1);
                yield return new NaturalPark(12, 24, 6, "nn", 1, "female", 3);
                yield return new NaturalPark(48, 120, 24, "yn", 1, "male", 1);
                yield return new NaturalPark(24, 48, 12, "nn", 4, "male", 1);
                yield return new NaturalPark(24, 48, 12, "yn", 3, "male", 2);
                yield return new NaturalPark(12, 24, 6, "yy", 3, "male", 3);
                yield return new NaturalPark(6, 18, 3, "yn", 3, "female", 2);
                yield return new NaturalPark(48, 120, 24, "yy", 1, "female", 3);
                yield return new NaturalPark(6, 18, 3, "nn", 1, "female", 2);
                yield return new NaturalPark(12, 24, 6, "yn", 1, "male", 3);
                yield return new NaturalPark(24, 48, 12, "yn", 2, "male", 2);
                yield return new NaturalPark(6, 18, 3, "nn", 3, "female", 3);
                yield return new NaturalPark(48, 120, 24, "nn", 2, "male", 2);
                yield return new NaturalPark(12, 24, 6, "yn", 1, "male", 5);
                yield return new NaturalPark(48, 120, 24, "ny", 1, "female", 2);
                yield return new NaturalPark(24, 48, 12, "yn", 3, "female", 4);
                yield return new NaturalPark(24, 48, 12, "nn", 6, "male", 1);
                yield return new NaturalPark(6, 18, 3, "yy", 4, "female", 3);
                yield return new NaturalPark(48, 120, 24, "nn", 4, "female", 2);
                yield return new NaturalPark(48, 120, 24, "yn", 4, "female", 3);
                yield return new NaturalPark(24, 48, 12, "nn", 5, "female", 1);
                yield return new NaturalPark(24, 48, 12, "nn", 4, "female", 4);
                yield return new NaturalPark(12, 24, 6, "nn", 4, "female", 2);
                yield return new NaturalPark(12, 24, 6, "nn", 1, "male", 3);
                yield return new NaturalPark(6, 18, 3, "yy", 2, "male", 3);
                yield return new NaturalPark(12, 24, 6, "yn", 1, "male", 2);
                yield return new NaturalPark(24, 48, 12, "yy", 4, "male", 2);
                yield return new NaturalPark(24, 48, 12, "yn", 2, "female", 1);
                yield return new NaturalPark(48, 120, 24, "nn", 3, "female", 8);
                yield return new NaturalPark(48, 120, 24, "yn", 4, "female", 3);
                yield return new NaturalPark(12, 24, 6, "yn", 5, "female", 2);
                yield return new NaturalPark(12, 24, 6, "yy", 3, "female", 3);
                yield return new NaturalPark(6, 18, 3, "nn", 3, "female", 2);
                yield return new NaturalPark(48, 120, 24, "nn", 6, "female", 3);
                yield return new NaturalPark(24, 48, 12, "yy", 1, "male", 2);
                yield return new NaturalPark(6, 18, 3, "yy", 1, "male", 3);
                yield return new NaturalPark(48, 120, 24, "nn", 3, "female", 4);
                yield return new NaturalPark(48, 120, 24, "yn", 3, "male", 3);
                yield return new NaturalPark(24, 48, 12, "nn", 2, "female", 8);
                yield return new NaturalPark(12, 24, 6, "yn", 4, "male", 3);
                yield return new NaturalPark(12, 24, 6, "yy", 2, "female", 3);
                yield return new NaturalPark(6, 18, 3, "yy", 3, "male", 2);
                yield return new NaturalPark(24, 48, 12, "nn", 2, "female", 2);
                yield return new NaturalPark(48, 120, 24, "yn", 2, "male", 2);
                yield return new NaturalPark(24, 48, 12, "yn", 3, "male", 3);
                yield return new NaturalPark(6, 18, 3, "yy", 1, "female", 2);
                yield return new NaturalPark(6, 18, 3, "yn", 5, "male", 2);
                yield return new NaturalPark(12, 24, 6, "nn", 2, "female", 2);
                yield return new NaturalPark(12, 24, 6, "nn", 1, "male", 2);
                yield return new NaturalPark(12, 24, 6, "yy", 4, "female", 3);
                yield return new NaturalPark(6, 18, 3, "nn", 4, "male", 1);
                yield return new NaturalPark(6, 18, 3, "nn", 4, "male", 3);
                yield return new NaturalPark(6, 18, 3, "yy", 2, "female", 1);
                yield return new NaturalPark(24, 48, 12, "nn", 2, "male", 3);
                yield return new NaturalPark(24, 48, 12, "yn", 1, "male", 3);
                yield return new NaturalPark(48, 120, 24, "nn", 6, "female", 1);
                yield return new NaturalPark(48, 120, 24, "nn", 1, "female", 2);
                yield return new NaturalPark(6, 18, 3, "nn", 6, "female", 1);
                yield return new NaturalPark(6, 18, 3, "nn", 6, "male", 1);
                yield return new NaturalPark(12, 24, 6, "nn", 6, "female", 1);
                yield return new NaturalPark(24, 48, 12, "nn", 2, "female", 1);
                yield return new NaturalPark(48, 120, 24, "nn", 3, "female", 3);
                yield return new NaturalPark(48, 120, 24, "nn", 2, "female", 2);
                yield return new NaturalPark(48, 120, 24, "yn", 1, "female", 2);
                yield return new NaturalPark(48, 120, 24, "yn", 1, "male", 3);
                yield return new NaturalPark(24, 48, 12, "nn", 3, "female", 1);
                yield return new NaturalPark(24, 48, 12, "ny", 5, "male", 1);
                yield return new NaturalPark(12, 24, 6, "yn", 1, "female", 1);
                yield return new NaturalPark(12, 24, 6, "nn", 5, "male", 1);
                yield return new NaturalPark(6, 18, 3, "nn", 4, "female", 1);
                yield return new NaturalPark(6, 18, 3, "yn", 1, "male", 4);
                yield return new NaturalPark(12, 24, 6, "yn", 4, "male", 5);
                yield return new NaturalPark(24, 48, 12, "nn", 1, "male", 7);
                yield return new NaturalPark(48, 120, 24, "nn", 3, "male", 4);
                yield return new NaturalPark(6, 18, 3, "nn", 3, "female", 4);
                yield return new NaturalPark(24, 48, 12, "nn", 6, "male", 1);
                yield return new NaturalPark(48, 120, 24, "nn", 3, "female", 2);
                yield return new NaturalPark(6, 18, 3, "nn", 3, "male", 2);
                yield return new NaturalPark(12, 24, 6, "nn", 5, "female", 1);
                yield return new NaturalPark(48, 120, 24, "nn", 6, "male", 1);
                yield return new NaturalPark(12, 24, 6, "nn", 4, "female", 2);
                yield return new NaturalPark(24, 48, 12, "nn", 5, "female", 1);
                yield return new NaturalPark(6, 18, 3, "nn", 6, "female", 1);
                yield return new NaturalPark(6, 18, 3, "nn", 5, "female", 1);
                yield return new NaturalPark(24, 48, 12, "nn", 4, "male", 2);
                yield return new NaturalPark(12, 24, 6, "nn", 4, "female", 2);
                yield return new NaturalPark(12, 24, 6, "nn", 5, "female", 1);
                yield return new NaturalPark(48, 120, 24, "nn", 4, "female", 2);
                yield return new NaturalPark(24, 48, 12, "yn", 3, "female", 1);
                yield return new NaturalPark(24, 48, 12, "nn", 6, "female", 1);
                yield return new NaturalPark(48, 120, 24, "nn", 5, "female", 1);
                yield return new NaturalPark(24, 48, 12, "nn", 3, "male", 2);
                yield return new NaturalPark(12, 24, 6, "nn", 3, "female", 1);
                yield return new NaturalPark(48, 120, 24, "nn", 1, "female", 1);
                yield return new NaturalPark(6, 18, 3, "nn", 5, "female", 1);
                yield return new NaturalPark(12, 24, 6, "nn", 3, "female", 2);
                yield return new NaturalPark(48, 120, 24, "nn", 5, "female", 2);
                yield return new NaturalPark(48, 120, 24, "nn", 4, "male", 1);
                yield return new NaturalPark(24, 48, 12, "nn", 6, "female", 1);
                yield return new NaturalPark(48, 120, 24, "nn", 6, "female", 1);
                yield return new NaturalPark(24, 48, 12, "nn", 1, "female", 3);
                yield return new NaturalPark(24, 48, 12, "nn", 5, "female", 2);
                yield return new NaturalPark(48, 120, 24, "nn", 1, "female", 4);
                yield return new NaturalPark(6, 18, 3, "nn", 6, "male", 1);
                yield return new NaturalPark(48, 120, 24, "nn", 2, "female", 4);
                yield return new NaturalPark(24, 48, 12, "nn", 1, "male", 2);
                yield return new NaturalPark(24, 48, 12, "nn", 3, "female", 4);
                yield return new NaturalPark(48, 120, 24, "nn", 4, "female", 5);
                yield return new NaturalPark(24, 48, 12, "yn", 4, "female", 6);
                yield return new NaturalPark(48, 120, 24, "nn", 1, "male", 3);
                yield return new NaturalPark(12, 24, 6, "ny", 4, "female", 3);
                yield return new NaturalPark(6, 18, 3, "ny", 2, "male", 2);
                yield return new NaturalPark(6, 18, 3, "yn", 5, "male", 2);
                yield return new NaturalPark(6, 18, 3, "yn", 4, "male", 2);
                yield return new NaturalPark(24, 48, 12, "yn", 1, "male", 2);
                yield return new NaturalPark(12, 24, 6, "yy", 1, "male", 4);
                yield return new NaturalPark(6, 18, 3, "ny", 5, "male", 1);
                yield return new NaturalPark(48, 120, 24, "ny", 3, "female", 4);
                yield return new NaturalPark(24, 48, 12, "nn", 4, "male", 2);
                yield return new NaturalPark(48, 120, 24, "nn", 5, "female", 1);
                yield return new NaturalPark(24, 48, 12, "yn", 3, "male", 3);
                yield return new NaturalPark(24, 48, 12, "yn", 4, "male", 3);
                yield return new NaturalPark(6, 18, 3, "yn", 3, "female", 3);
                yield return new NaturalPark(24, 48, 12, "yy", 1, "male", 7);
                yield return new NaturalPark(6, 18, 3, "nn", 1, "female", 3);
                yield return new NaturalPark(12, 24, 6, "yy", 1, "male", 3);
                yield return new NaturalPark(24, 48, 12, "yn", 4, "female", 4);
                yield return new NaturalPark(12, 24, 6, "yn", 1, "male", 2);
                yield return new NaturalPark(48, 120, 24, "yn", 1, "male", 8);
                yield return new NaturalPark(6, 18, 3, "yn", 3, "female", 2);
                yield return new NaturalPark(12, 24, 6, "ny", 4, "female", 1);
                yield return new NaturalPark(48, 120, 24, "yn", 2, "female", 2);
                yield return new NaturalPark(24, 48, 12, "yn", 1, "male", 2);
                yield return new NaturalPark(24, 48, 12, "nn", 6, "male", 3);
                yield return new NaturalPark(12, 24, 6, "nn", 3, "female", 2);
                yield return new NaturalPark(6, 18, 3, "yn", 4, "male", 3);
                yield return new NaturalPark(6, 18, 3, "yn", 3, "male", 1);
                yield return new NaturalPark(48, 120, 24, "nn", 3, "female", 2);
                yield return new NaturalPark(24, 48, 12, "yn", 1, "male", 4);
                yield return new NaturalPark(6, 18, 3, "yn", 5, "male", 2);
                yield return new NaturalPark(12, 24, 6, "yy", 3, "female", 3);
                yield return new NaturalPark(24, 48, 12, "nn", 4, "male", 2);
                yield return new NaturalPark(12, 24, 6, "yy", 1, "male", 2);
                yield return new NaturalPark(6, 18, 3, "yn", 3, "male", 4);
                yield return new NaturalPark(24, 48, 12, "yn", 4, "female", 2);
                yield return new NaturalPark(6, 18, 3, "yn", 1, "male", 3);
                yield return new NaturalPark(48, 120, 24, "nn", 4, "female", 5);
                yield return new NaturalPark(48, 120, 24, "nn", 3, "female", 4);
                yield return new NaturalPark(12, 24, 6, "yn", 1, "male", 1);
                yield return new NaturalPark(24, 48, 12, "yy", 3, "female", 4);
                yield return new NaturalPark(48, 120, 24, "yn", 2, "female", 3);
                yield return new NaturalPark(48, 120, 24, "yn", 1, "female", 3);
                yield return new NaturalPark(24, 48, 12, "yn", 2, "male", 4);
                yield return new NaturalPark(12, 24, 6, "yn", 2, "female", 2);
                yield return new NaturalPark(48, 120, 24, "yn", 1, "female", 2);
                yield return new NaturalPark(6, 18, 3, "yy", 4, "male", 3);
                yield return new NaturalPark(24, 48, 12, "yn", 3, "male", 2);
                yield return new NaturalPark(24, 48, 12, "ny", 3, "female", 2);
                yield return new NaturalPark(24, 48, 12, "yy", 2, "female", 3);
                yield return new NaturalPark(6, 18, 3, "yy", 2, "female", 2);
                yield return new NaturalPark(24, 48, 12, "nn", 1, "male", 3);
                yield return new NaturalPark(24, 48, 12, "yn", 5, "male", 3);
                yield return new NaturalPark(48, 120, 24, "yn", 3, "male", 2);
                yield return new NaturalPark(12, 24, 6, "yn", 3, "female", 2);
                yield return new NaturalPark(6, 18, 3, "yy", 4, "female", 5);
                yield return new NaturalPark(12, 24, 6, "yy", 6, "male", 2);
                yield return new NaturalPark(12, 24, 6, "yy", 2, "female", 4);
                yield return new NaturalPark(24, 48, 12, "yn", 2, "female", 2);
                yield return new NaturalPark(6, 18, 3, "yy", 2, "female", 2);
                yield return new NaturalPark(48, 120, 24, "yn", 1, "female", 2);
                yield return new NaturalPark(24, 48, 12, "yy", 1, "male", 4);
                yield return new NaturalPark(12, 24, 6, "yy", 3, "male", 2);
                yield return new NaturalPark(6, 18, 3, "yn", 2, "female", 2);
                yield return new NaturalPark(6, 18, 3, "yn", 1, "male", 2);
                yield return new NaturalPark(12, 24, 6, "yn", 2, "male", 3);
                yield return new NaturalPark(6, 18, 3, "yn", 2, "male", 2);
                yield return new NaturalPark(6, 18, 3, "yn", 2, "male", 3);
                yield return new NaturalPark(48, 120, 24, "yn", 2, "female", 3);
                yield return new NaturalPark(6, 18, 3, "yy", 1, "male", 3);
                yield return new NaturalPark(12, 24, 6, "yy", 3, "female", 6);
                yield return new NaturalPark(12, 24, 6, "yy", 4, "male", 8);
                yield return new NaturalPark(6, 18, 3, "yn", 3, "female", 3);
                yield return new NaturalPark(6, 18, 3, "yy", 1, "female", 3);
                yield return new NaturalPark(48, 120, 24, "yy", 5, "male", 2);
                yield return new NaturalPark(6, 18, 3, "nn", 4, "female", 1);
                yield return new NaturalPark(48, 120, 24, "yn", 2, "female", 2);
                yield return new NaturalPark(48, 120, 24, "yy", 3, "female", 2);
                yield return new NaturalPark(6, 18, 3, "yn", 1, "male", 2);
                yield return new NaturalPark(12, 24, 6, "yy", 1, "female", 3);
                yield return new NaturalPark(12, 24, 6, "yn", 3, "female", 2);
                yield return new NaturalPark(24, 48, 12, "ny", 1, "male", 2);
                yield return new NaturalPark(12, 24, 6, "yy", 3, "female", 3);
                yield return new NaturalPark(24, 48, 12, "yn", 2, "female", 3);
                yield return new NaturalPark(6, 18, 3, "yn", 4, "female", 1);
                yield return new NaturalPark(48, 120, 24, "yn", 1, "male", 4);
                yield return new NaturalPark(24, 48, 12, "ny", 4, "female", 1);
                yield return new NaturalPark(12, 24, 6, "yy", 6, "male", 2);
                yield return new NaturalPark(6, 18, 3, "yn", 4, "female", 2);
                yield return new NaturalPark(12, 24, 6, "yy", 1, "male", 3);
                yield return new NaturalPark(6, 18, 3, "yn", 3, "female", 2);
                yield return new NaturalPark(24, 48, 12, "yy", 3, "male", 8);
                yield return new NaturalPark(12, 24, 6, "yn", 5, "male", 3);
                yield return new NaturalPark(12, 24, 6, "nn", 2, "male", 1);
                yield return new NaturalPark(6, 18, 3, "yn", 6, "male", 2);
                yield return new NaturalPark(48, 120, 24, "nn", 2, "female", 2);
                yield return new NaturalPark(12, 24, 6, "yn", 1, "male", 4);
                yield return new NaturalPark(24, 48, 12, "yy", 1, "female", 4);
                yield return new NaturalPark(48, 120, 24, "yn", 2, "male", 1);
                yield return new NaturalPark(6, 18, 3, "yn", 4, "female", 3);
                yield return new NaturalPark(48, 120, 24, "yn", 2, "male", 2);
                yield return new NaturalPark(6, 18, 3, "yy", 4, "male", 2);
                yield return new NaturalPark(12, 24, 6, "nn", 5, "male", 3);
                yield return new NaturalPark(24, 48, 12, "yy", 3, "male", 3);
                yield return new NaturalPark(24, 48, 12, "yn", 4, "female", 2);
                yield return new NaturalPark(48, 120, 24, "yn", 3, "female", 2);
                yield return new NaturalPark(6, 18, 3, "ny", 4, "female", 2);
                yield return new NaturalPark(24, 48, 12, "nn", 2, "female", 3);
                yield return new NaturalPark(24, 48, 12, "yn", 4, "male", 2);
                yield return new NaturalPark(6, 18, 3, "yn", 3, "male", 4);
                yield return new NaturalPark(12, 24, 6, "yy", 3, "female", 3);
                yield return new NaturalPark(48, 120, 24, "yn", 4, "male", 3);
                yield return new NaturalPark(48, 120, 24, "ny", 4, "female", 2);
                yield return new NaturalPark(24, 48, 12, "yn", 4, "female", 4);
            }
        }
    }
}
