// ReSharper disable All

namespace Rdatasets.Ecdat
{
    using System.Collections.Generic;

    /// <summary>
    /// Unemployment Duration
    /// </summary>

    public class Unemployment
    {
        public readonly int κ;
        public readonly int duration;
        public readonly int spell;
        public readonly string race;
        public readonly string sex;
        public readonly string reason;
        public readonly string search;
        public readonly string pubemp;
        public readonly int ftp1;
        public readonly int ftp2;
        public readonly int ftp3;
        public readonly int ftp4;
        public readonly int nobs;

        public Unemployment(int κ, int duration, int spell, string race, string sex, string reason, string search, string pubemp, int ftp1, int ftp2, int ftp3, int ftp4, int nobs)
        {
            this.κ = κ;
            this.duration = duration;
            this.spell = spell;
            this.race = race;
            this.sex = sex;
            this.reason = reason;
            this.search = search;
            this.pubemp = pubemp;
            this.ftp1 = ftp1;
            this.ftp2 = ftp2;
            this.ftp3 = ftp3;
            this.ftp4 = ftp4;
            this.nobs = nobs;
        }

        public static IEnumerable<Unemployment> Data
        {
            get
            {
                yield return new Unemployment(1, 4, 1, "white", "male", "reentr", "yes", "yes", 1, 0, 0, 0, 1);
                yield return new Unemployment(2, 7, 0, "white", "male", "lose", "no", "no", 1, 1, 1, 1, 2);
                yield return new Unemployment(3, 1, 0, "nonwhite", "male", "lose", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(4, 1, 1, "nonwhite", "male", "reentr", "no", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(5, 3, 1, "nonwhite", "female", "reentr", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(6, 1, 1, "white", "female", "reentr", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(7, 65, 0, "white", "male", "lose", "yes", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(8, 4, 0, "white", "female", "reentr", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(9, 113, 0, "white", "female", "reentr", "no", "no", 0, 0, 0, 0, 3);
                yield return new Unemployment(10, 9, 1, "white", "male", "leave", "yes", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(11, 9, 1, "white", "male", "leave", "yes", "no", 1, 1, 0, 0, 2);
                yield return new Unemployment(12, 104, 0, "white", "male", "leave", "yes", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(13, 21, 0, "white", "female", "reentr", "no", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(14, 20, 0, "white", "female", "lose", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(15, 8, 1, "white", "male", "reentr", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(16, 104, 1, "white", "female", "lose", "yes", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(17, 20, 1, "white", "male", "lose", "no", "no", 1, 1, 0, 0, 2);
                yield return new Unemployment(18, 56, 1, "nonwhite", "female", "reentr", "no", "no", 0, 0, 0, 0, 2);
                yield return new Unemployment(19, 61, 0, "white", "female", "lose", "no", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(20, 3, 0, "white", "female", "leave", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(21, 2, 0, "white", "female", "reentr", "yes", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(22, 1, 1, "white", "female", "lose", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(23, 22, 1, "white", "female", "leave", "no", "yes", 1, 1, 1, 0, 3);
                yield return new Unemployment(24, 12, 1, "nonwhite", "male", "reentr", "no", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(25, 7, 1, "nonwhite", "female", "reentr", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(26, 104, 1, "nonwhite", "male", "reentr", "yes", "yes", 0, 1, 0, 0, 1);
                yield return new Unemployment(27, 12, 0, "white", "female", "new", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(28, 17, 0, "white", "female", "lose", "yes", "no", 1, 1, 1, 1, 3);
                yield return new Unemployment(29, 17, 0, "white", "male", "reentr", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(30, 1, 1, "white", "male", "reentr", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(31, 12, 1, "white", "male", "lose", "no", "no", 1, 1, 1, 0, 3);
                yield return new Unemployment(32, 10, 0, "white", "male", "lose", "no", "no", 1, 1, 1, 1, 3);
                yield return new Unemployment(33, 1, 0, "white", "male", "leave", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(34, 10, 1, "nonwhite", "female", "lose", "no", "yes", 1, 1, 1, 0, 3);
                yield return new Unemployment(35, 108, 1, "white", "male", "lose", "no", "no", 1, 1, 0, 1, 2);
                yield return new Unemployment(36, 104, 1, "white", "female", "lose", "yes", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(37, 11, 0, "nonwhite", "female", "new", "no", "no", 0, 0, 0, 0, 3);
                yield return new Unemployment(38, 56, 1, "white", "female", "leave", "yes", "no", 1, 1, 0, 0, 2);
                yield return new Unemployment(39, 65, 0, "white", "male", "reentr", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(40, 7, 1, "white", "male", "reentr", "no", "yes", 1, 0, 1, 0, 1);
                yield return new Unemployment(41, 35, 1, "nonwhite", "female", "lose", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(42, 61, 0, "white", "female", "lose", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(43, 56, 1, "nonwhite", "female", "leave", "no", "no", 1, 1, 0, 0, 2);
                yield return new Unemployment(44, 3, 1, "nonwhite", "male", "reentr", "yes", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(45, 35, 0, "nonwhite", "male", "leave", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(46, 13, 1, "white", "female", "leave", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(47, 2, 1, "nonwhite", "female", "lose", "yes", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(48, 9, 0, "white", "female", "lose", "no", "no", 1, 1, 1, 1, 2);
                yield return new Unemployment(49, 6, 0, "white", "male", "new", "no", "no", 0, 0, 0, 0, 2);
                yield return new Unemployment(50, 3, 0, "white", "female", "lose", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(51, 104, 1, "white", "male", "reentr", "yes", "yes", 1, 0, 0, 0, 1);
                yield return new Unemployment(52, 16, 0, "nonwhite", "female", "lose", "yes", "no", 1, 0, 0, 0, 4);
                yield return new Unemployment(53, 1, 1, "white", "female", "new", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(54, 7, 0, "white", "female", "new", "yes", "yes", 1, 0, 1, 0, 1);
                yield return new Unemployment(55, 65, 0, "white", "male", "reentr", "no", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(56, 9, 1, "white", "female", "reentr", "no", "no", 0, 0, 0, 0, 2);
                yield return new Unemployment(57, 2, 1, "white", "female", "leave", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(58, 5, 0, "white", "male", "lose", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(59, 2, 1, "white", "female", "leave", "yes", "yes", 0, 0, 0, 0, 1);
                yield return new Unemployment(60, 2, 1, "white", "female", "lose", "no", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(61, 8, 1, "white", "female", "lose", "no", "yes", 1, 1, 0, 0, 2);
                yield return new Unemployment(62, 7, 1, "white", "male", "reentr", "no", "no", 0, 0, 0, 0, 2);
                yield return new Unemployment(63, 1, 1, "white", "male", "reentr", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(64, 13, 0, "white", "female", "lose", "no", "no", 1, 1, 1, 1, 2);
                yield return new Unemployment(65, 12, 0, "white", "female", "lose", "yes", "no", 1, 1, 1, 1, 3);
                yield return new Unemployment(66, 8, 0, "white", "male", "lose", "yes", "no", 1, 1, 1, 1, 2);
                yield return new Unemployment(67, 61, 0, "white", "female", "reentr", "yes", "no", 0, 0, 0, 0, 3);
                yield return new Unemployment(68, 17, 0, "white", "female", "reentr", "no", "no", 0, 0, 0, 0, 2);
                yield return new Unemployment(69, 26, 0, "nonwhite", "female", "new", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(70, 16, 1, "nonwhite", "female", "reentr", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(71, 2, 1, "nonwhite", "female", "reentr", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(72, 5, 0, "nonwhite", "female", "reentr", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(73, 3, 0, "nonwhite", "female", "reentr", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(74, 16, 1, "white", "female", "reentr", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(75, 26, 0, "white", "female", "reentr", "yes", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(76, 4, 0, "white", "male", "lose", "yes", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(77, 13, 1, "white", "female", "new", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(78, 58, 0, "white", "male", "lose", "no", "no", 1, 1, 1, 0, 3);
                yield return new Unemployment(79, 14, 1, "white", "male", "lose", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(80, 1, 0, "white", "female", "lose", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(81, 15, 0, "white", "male", "lose", "no", "no", 1, 1, 1, 1, 3);
                yield return new Unemployment(82, 1, 0, "white", "female", "reentr", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(83, 7, 0, "white", "male", "leave", "no", "no", 1, 1, 1, 1, 2);
                yield return new Unemployment(84, 10, 1, "white", "male", "lose", "yes", "yes", 0, 1, 1, 0, 3);
                yield return new Unemployment(85, 18, 1, "white", "female", "reentr", "no", "no", 1, 1, 0, 0, 2);
                yield return new Unemployment(86, 48, 0, "white", "male", "lose", "no", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(87, 21, 1, "white", "male", "lose", "no", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(88, 12, 0, "white", "male", "reentr", "no", "no", 1, 1, 1, 1, 3);
                yield return new Unemployment(89, 3, 1, "white", "female", "lose", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(90, 56, 0, "white", "male", "leave", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(91, 15, 0, "white", "female", "reentr", "no", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(92, 3, 0, "white", "male", "lose", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(93, 2, 1, "white", "female", "reentr", "no", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(94, 3, 1, "white", "male", "lose", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(95, 12, 0, "white", "female", "new", "no", "no", 0, 0, 0, 0, 3);
                yield return new Unemployment(96, 1, 1, "white", "male", "lose", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(97, 3, 1, "white", "male", "lose", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(98, 5, 1, "white", "male", "lose", "no", "yes", 1, 1, 1, 0, 2);
                yield return new Unemployment(99, 2, 1, "white", "female", "lose", "yes", "yes", 1, 0, 1, 0, 1);
                yield return new Unemployment(100, 8, 0, "white", "male", "leave", "no", "no", 0, 0, 0, 0, 2);
                yield return new Unemployment(101, 9, 0, "white", "male", "reentr", "no", "no", 1, 1, 1, 1, 2);
                yield return new Unemployment(102, 26, 1, "white", "female", "reentr", "yes", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(103, 1, 0, "white", "male", "lose", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(104, 7, 1, "white", "female", "reentr", "no", "no", 1, 1, 1, 0, 2);
                yield return new Unemployment(105, 6, 1, "white", "female", "new", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(106, 5, 1, "white", "male", "reentr", "no", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(107, 4, 1, "nonwhite", "female", "lose", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(108, 9, 0, "nonwhite", "male", "reentr", "no", "yes", 0, 0, 0, 0, 1);
                yield return new Unemployment(109, 5, 1, "nonwhite", "male", "new", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(110, 12, 1, "white", "female", "reentr", "no", "no", 1, 1, 1, 0, 3);
                yield return new Unemployment(111, 4, 0, "white", "female", "reentr", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(112, 65, 0, "nonwhite", "female", "leave", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(113, 8, 1, "nonwhite", "female", "reentr", "no", "yes", 1, 1, 0, 0, 2);
                yield return new Unemployment(114, 8, 1, "nonwhite", "female", "new", "no", "no", 1, 1, 0, 0, 2);
                yield return new Unemployment(115, 22, 1, "nonwhite", "female", "reentr", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(116, 19, 0, "nonwhite", "female", "new", "no", "no", 1, 1, 1, 1, 3);
                yield return new Unemployment(117, 38, 1, "nonwhite", "male", "leave", "no", "no", 1, 1, 1, 0, 3);
                yield return new Unemployment(118, 25, 0, "nonwhite", "male", "lose", "no", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(119, 12, 0, "nonwhite", "female", "reentr", "yes", "no", 1, 0, 1, 1, 1);
                yield return new Unemployment(120, 26, 1, "nonwhite", "male", "lose", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(121, 2, 1, "white", "male", "reentr", "yes", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(122, 8, 1, "nonwhite", "female", "lose", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(123, 6, 1, "nonwhite", "female", "new", "no", "no", 0, 0, 0, 1, 1);
                yield return new Unemployment(124, 2, 0, "white", "male", "reentr", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(125, 1, 1, "white", "male", "reentr", "no", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(126, 1, 0, "white", "male", "leave", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(127, 3, 1, "white", "male", "reentr", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(128, 52, 1, "white", "male", "leave", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(129, 1, 1, "white", "male", "lose", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(130, 1, 0, "white", "male", "lose", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(131, 2, 0, "white", "male", "reentr", "yes", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(132, 1, 1, "white", "female", "lose", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(133, 2, 1, "white", "female", "lose", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(134, 20, 1, "white", "female", "reentr", "no", "yes", 1, 1, 1, 0, 3);
                yield return new Unemployment(135, 35, 1, "white", "male", "reentr", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(136, 16, 1, "white", "female", "reentr", "yes", "yes", 1, 0, 1, 1, 1);
                yield return new Unemployment(137, 22, 0, "white", "male", "leave", "yes", "yes", 1, 0, 0, 0, 1);
                yield return new Unemployment(138, 1, 0, "white", "female", "reentr", "yes", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(139, 12, 0, "nonwhite", "female", "reentr", "no", "yes", 1, 1, 0, 0, 2);
                yield return new Unemployment(140, 11, 0, "nonwhite", "male", "leave", "no", "yes", 1, 1, 1, 1, 3);
                yield return new Unemployment(141, 12, 0, "nonwhite", "male", "leave", "no", "yes", 1, 1, 1, 1, 3);
                yield return new Unemployment(142, 7, 1, "nonwhite", "male", "leave", "yes", "yes", 1, 0, 1, 0, 1);
                yield return new Unemployment(143, 21, 1, "white", "male", "lose", "no", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(144, 27, 0, "white", "male", "leave", "yes", "no", 1, 1, 1, 1, 2);
                yield return new Unemployment(145, 23, 0, "white", "male", "reentr", "yes", "no", 1, 1, 1, 1, 3);
                yield return new Unemployment(146, 3, 1, "white", "female", "lose", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(147, 22, 1, "nonwhite", "male", "new", "yes", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(148, 4, 1, "white", "female", "leave", "no", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(149, 39, 1, "white", "male", "lose", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(150, 26, 0, "white", "female", "lose", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(151, 19, 0, "white", "female", "new", "no", "no", 0, 0, 0, 0, 4);
                yield return new Unemployment(152, 16, 1, "nonwhite", "male", "new", "no", "no", 0, 0, 0, 0, 2);
                yield return new Unemployment(153, 11, 0, "white", "female", "reentr", "yes", "no", 1, 1, 1, 1, 3);
                yield return new Unemployment(154, 17, 0, "white", "male", "leave", "no", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(155, 10, 0, "white", "female", "lose", "no", "no", 0, 0, 0, 0, 3);
                yield return new Unemployment(156, 8, 0, "white", "female", "new", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(157, 25, 0, "nonwhite", "female", "lose", "yes", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(158, 48, 0, "white", "male", "leave", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(159, 2, 1, "white", "male", "leave", "yes", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(160, 21, 0, "white", "male", "lose", "yes", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(161, 7, 1, "nonwhite", "male", "new", "no", "no", 0, 0, 0, 1, 2);
                yield return new Unemployment(162, 23, 0, "white", "male", "lose", "no", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(163, 6, 1, "white", "male", "lose", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(164, 1, 1, "nonwhite", "female", "reentr", "yes", "yes", 0, 0, 0, 0, 1);
                yield return new Unemployment(165, 43, 1, "nonwhite", "male", "lose", "yes", "no", 1, 1, 0, 0, 2);
                yield return new Unemployment(166, 3, 1, "white", "female", "reentr", "yes", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(167, 26, 1, "white", "female", "leave", "no", "yes", 1, 1, 1, 0, 3);
                yield return new Unemployment(168, 0, 1, "white", "female", "new", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(169, 3, 0, "white", "female", "leave", "yes", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(170, 78, 1, "white", "male", "lose", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(171, 13, 1, "white", "male", "reentr", "no", "no", 0, 0, 0, 0, 2);
                yield return new Unemployment(172, 13, 1, "white", "female", "lose", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(173, 52, 1, "white", "female", "new", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(174, 52, 0, "white", "male", "lose", "no", "no", 1, 1, 0, 0, 2);
                yield return new Unemployment(175, 2, 0, "white", "female", "reentr", "yes", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(176, 104, 1, "white", "female", "leave", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(177, 7, 1, "white", "female", "leave", "no", "yes", 1, 1, 0, 0, 2);
                yield return new Unemployment(178, 4, 1, "white", "male", "reentr", "yes", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(179, 16, 1, "white", "female", "reentr", "yes", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(180, 35, 1, "nonwhite", "female", "reentr", "no", "no", 1, 0, 1, 1, 1);
                yield return new Unemployment(181, 6, 1, "white", "male", "leave", "no", "no", 0, 0, 0, 0, 2);
                yield return new Unemployment(182, 17, 0, "white", "male", "leave", "no", "no", 0, 0, 0, 0, 4);
                yield return new Unemployment(183, 4, 0, "nonwhite", "female", "lose", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(184, 5, 1, "white", "male", "lose", "no", "no", 1, 1, 1, 0, 2);
                yield return new Unemployment(185, 38, 1, "white", "male", "lose", "yes", "no", 1, 1, 1, 0, 3);
                yield return new Unemployment(186, 4, 0, "white", "female", "reentr", "yes", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(187, 12, 1, "white", "female", "leave", "yes", "yes", 1, 1, 1, 0, 3);
                yield return new Unemployment(188, 30, 1, "white", "male", "reentr", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(189, 4, 0, "white", "female", "reentr", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(190, 1, 0, "nonwhite", "female", "reentr", "no", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(191, 6, 1, "white", "male", "new", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(192, 2, 1, "white", "male", "leave", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(193, 25, 0, "white", "male", "reentr", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(194, 9, 0, "white", "male", "lose", "no", "no", 1, 1, 1, 1, 2);
                yield return new Unemployment(195, 4, 1, "white", "female", "reentr", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(196, 61, 0, "white", "male", "reentr", "no", "yes", 1, 1, 1, 1, 3);
                yield return new Unemployment(197, 3, 1, "white", "female", "new", "yes", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(198, 22, 1, "white", "male", "reentr", "no", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(199, 11, 1, "white", "male", "lose", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(200, 2, 1, "white", "male", "lose", "no", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(201, 48, 0, "white", "male", "lose", "no", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(202, 1, 1, "white", "male", "lose", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(203, 16, 1, "white", "female", "reentr", "no", "yes", 1, 1, 0, 1, 2);
                yield return new Unemployment(204, 15, 0, "white", "male", "lose", "yes", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(205, 26, 0, "white", "male", "lose", "no", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(206, 16, 0, "white", "male", "lose", "no", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(207, 8, 1, "white", "female", "reentr", "no", "no", 1, 1, 1, 0, 2);
                yield return new Unemployment(208, 8, 0, "white", "male", "leave", "yes", "yes", 1, 1, 1, 1, 2);
                yield return new Unemployment(209, 1, 1, "white", "female", "reentr", "no", "yes", 0, 0, 0, 0, 1);
                yield return new Unemployment(210, 7, 0, "white", "male", "leave", "no", "yes", 1, 1, 1, 1, 2);
                yield return new Unemployment(211, 7, 0, "white", "female", "lose", "no", "yes", 1, 1, 1, 1, 2);
                yield return new Unemployment(212, 43, 0, "white", "female", "lose", "no", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(213, 4, 1, "white", "female", "leave", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(214, 61, 0, "white", "male", "lose", "no", "no", 1, 1, 1, 1, 3);
                yield return new Unemployment(215, 39, 0, "white", "male", "leave", "no", "yes", 1, 1, 0, 0, 2);
                yield return new Unemployment(216, 4, 1, "nonwhite", "female", "reentr", "no", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(217, 1, 1, "nonwhite", "female", "leave", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(218, 2, 0, "white", "male", "lose", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(219, 39, 1, "white", "male", "leave", "yes", "yes", 1, 0, 0, 0, 1);
                yield return new Unemployment(220, 12, 1, "white", "male", "lose", "yes", "yes", 1, 0, 0, 0, 1);
                yield return new Unemployment(221, 4, 0, "white", "male", "leave", "yes", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(222, 8, 1, "white", "female", "reentr", "no", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(223, 10, 0, "white", "male", "lose", "no", "no", 0, 0, 0, 0, 3);
                yield return new Unemployment(224, 7, 1, "nonwhite", "male", "leave", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(225, 4, 0, "white", "female", "lose", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(226, 1, 1, "white", "male", "lose", "no", "no", 0, 0, 1, 1, 1);
                yield return new Unemployment(227, 7, 1, "nonwhite", "female", "reentr", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(228, 3, 1, "nonwhite", "male", "reentr", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(229, 12, 0, "white", "female", "leave", "no", "yes", 1, 1, 1, 0, 3);
                yield return new Unemployment(230, 3, 1, "white", "female", "leave", "yes", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(231, 4, 0, "white", "male", "leave", "yes", "yes", 1, 0, 0, 1, 1);
                yield return new Unemployment(232, 117, 0, "white", "male", "lose", "no", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(233, 35, 0, "nonwhite", "female", "reentr", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(234, 6, 0, "white", "male", "leave", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(235, 9, 0, "nonwhite", "female", "new", "no", "no", 0, 0, 0, 0, 2);
                yield return new Unemployment(236, 100, 0, "white", "male", "lose", "no", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(237, 26, 1, "white", "female", "new", "yes", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(238, 8, 1, "white", "male", "reentr", "no", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(239, 9, 0, "white", "male", "lose", "no", "no", 1, 1, 1, 1, 2);
                yield return new Unemployment(240, 2, 1, "white", "male", "leave", "yes", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(241, 16, 1, "white", "female", "new", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(242, 8, 1, "nonwhite", "male", "lose", "no", "no", 1, 1, 0, 0, 2);
                yield return new Unemployment(243, 4, 1, "white", "male", "lose", "yes", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(244, 109, 0, "nonwhite", "female", "lose", "no", "yes", 1, 1, 1, 1, 2);
                yield return new Unemployment(245, 49, 0, "nonwhite", "male", "reentr", "no", "yes", 1, 1, 1, 1, 3);
                yield return new Unemployment(246, 1, 0, "nonwhite", "male", "reentr", "yes", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(247, 12, 1, "nonwhite", "female", "reentr", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(248, 61, 0, "nonwhite", "male", "lose", "no", "yes", 1, 1, 1, 1, 3);
                yield return new Unemployment(249, 2, 1, "nonwhite", "male", "lose", "no", "no", 1, 0, 1, 1, 1);
                yield return new Unemployment(250, 17, 0, "nonwhite", "female", "lose", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(251, 60, 1, "white", "female", "lose", "no", "no", 1, 1, 1, 0, 3);
                yield return new Unemployment(252, 112, 1, "white", "female", "reentr", "no", "no", 1, 1, 1, 0, 3);
                yield return new Unemployment(253, 52, 1, "white", "female", "lose", "no", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(254, 17, 0, "white", "male", "lose", "yes", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(255, 8, 0, "nonwhite", "male", "new", "no", "no", 1, 1, 0, 0, 2);
                yield return new Unemployment(256, 104, 1, "nonwhite", "female", "new", "yes", "yes", 1, 0, 0, 0, 1);
                yield return new Unemployment(257, 65, 0, "nonwhite", "male", "lose", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(258, 6, 1, "white", "female", "lose", "no", "yes", 1, 1, 0, 0, 2);
                yield return new Unemployment(259, 29, 0, "white", "male", "lose", "no", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(260, 8, 1, "nonwhite", "male", "lose", "yes", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(261, 26, 1, "white", "male", "leave", "yes", "no", 1, 1, 0, 0, 2);
                yield return new Unemployment(262, 1, 1, "white", "male", "leave", "yes", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(263, 16, 1, "white", "male", "reentr", "no", "yes", 1, 1, 0, 0, 2);
                yield return new Unemployment(264, 6, 1, "white", "male", "lose", "yes", "yes", 0, 1, 0, 0, 1);
                yield return new Unemployment(265, 30, 0, "white", "male", "lose", "no", "no", 1, 1, 1, 0, 3);
                yield return new Unemployment(266, 3, 1, "white", "female", "leave", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(267, 12, 1, "white", "female", "lose", "no", "no", 0, 0, 0, 0, 3);
                yield return new Unemployment(268, 12, 1, "white", "male", "leave", "no", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(269, 8, 1, "white", "male", "leave", "no", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(270, 13, 1, "white", "female", "new", "yes", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(271, 16, 1, "white", "male", "lose", "yes", "no", 1, 1, 0, 0, 2);
                yield return new Unemployment(272, 6, 1, "white", "male", "lose", "yes", "no", 1, 1, 0, 1, 1);
                yield return new Unemployment(273, 43, 0, "white", "male", "leave", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(274, 52, 0, "white", "female", "reentr", "yes", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(275, 12, 0, "white", "female", "new", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(276, 6, 0, "white", "female", "reentr", "no", "no", 0, 0, 0, 0, 2);
                yield return new Unemployment(277, 1, 0, "white", "male", "reentr", "yes", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(278, 13, 0, "white", "female", "lose", "no", "no", 1, 1, 1, 1, 3);
                yield return new Unemployment(279, 47, 0, "nonwhite", "male", "lose", "no", "no", 1, 1, 1, 0, 2);
                yield return new Unemployment(280, 4, 1, "white", "male", "reentr", "yes", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(281, 4, 0, "white", "male", "leave", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(282, 3, 1, "white", "male", "lose", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(283, 12, 1, "white", "male", "reentr", "no", "yes", 0, 1, 0, 0, 1);
                yield return new Unemployment(284, 12, 1, "white", "female", "leave", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(285, 3, 1, "white", "male", "leave", "no", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(286, 23, 0, "white", "female", "reentr", "no", "no", 0, 0, 0, 0, 4);
                yield return new Unemployment(287, 2, 0, "nonwhite", "female", "leave", "yes", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(288, 39, 0, "white", "male", "lose", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(289, 39, 0, "white", "male", "lose", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(290, 2, 1, "white", "male", "new", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(291, 24, 0, "white", "female", "reentr", "no", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(292, 43, 1, "white", "male", "lose", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(293, 6, 0, "nonwhite", "female", "reentr", "yes", "no", 1, 1, 0, 0, 2);
                yield return new Unemployment(294, 7, 1, "nonwhite", "female", "reentr", "yes", "no", 0, 0, 0, 0, 2);
                yield return new Unemployment(295, 4, 1, "nonwhite", "male", "reentr", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(296, 2, 1, "white", "female", "leave", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(297, 1, 1, "white", "female", "reentr", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(298, 1, 1, "nonwhite", "female", "lose", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(299, 17, 0, "nonwhite", "female", "reentr", "no", "no", 0, 0, 0, 0, 2);
                yield return new Unemployment(300, 104, 0, "nonwhite", "female", "reentr", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(301, 1, 1, "white", "female", "lose", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(302, 4, 1, "white", "male", "new", "no", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(303, 8, 1, "white", "female", "reentr", "yes", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(304, 35, 0, "white", "male", "lose", "yes", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(305, 1, 1, "white", "female", "reentr", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(306, 16, 1, "nonwhite", "female", "leave", "yes", "yes", 1, 0, 1, 1, 1);
                yield return new Unemployment(307, 15, 0, "white", "female", "lose", "no", "no", 1, 1, 1, 1, 2);
                yield return new Unemployment(308, 15, 0, "white", "female", "reentr", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(309, 11, 0, "white", "female", "reentr", "no", "no", 1, 1, 1, 1, 3);
                yield return new Unemployment(310, 1, 1, "white", "female", "reentr", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(311, 2, 0, "white", "female", "new", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(312, 61, 0, "white", "male", "leave", "yes", "no", 1, 1, 1, 1, 3);
                yield return new Unemployment(313, 39, 1, "nonwhite", "male", "lose", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(314, 11, 0, "nonwhite", "male", "lose", "no", "no", 1, 1, 1, 0, 3);
                yield return new Unemployment(315, 4, 0, "white", "male", "leave", "yes", "yes", 1, 0, 1, 0, 1);
                yield return new Unemployment(316, 13, 0, "white", "female", "reentr", "yes", "no", 1, 1, 1, 1, 2);
                yield return new Unemployment(317, 20, 1, "white", "male", "leave", "no", "no", 1, 1, 1, 0, 3);
                yield return new Unemployment(318, 15, 0, "nonwhite", "male", "leave", "no", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(319, 69, 1, "white", "male", "lose", "yes", "yes", 1, 1, 0, 0, 2);
                yield return new Unemployment(320, 20, 1, "white", "female", "reentr", "no", "no", 0, 0, 0, 0, 2);
                yield return new Unemployment(321, 4, 0, "white", "male", "lose", "yes", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(322, 43, 1, "white", "male", "lose", "no", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(323, 20, 1, "white", "female", "reentr", "no", "no", 0, 0, 0, 0, 3);
                yield return new Unemployment(324, 11, 1, "white", "male", "lose", "yes", "yes", 1, 0, 1, 0, 1);
                yield return new Unemployment(325, 3, 1, "white", "female", "new", "yes", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(326, 4, 1, "white", "male", "reentr", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(327, 10, 1, "white", "male", "lose", "yes", "yes", 1, 1, 0, 0, 2);
                yield return new Unemployment(328, 8, 0, "white", "female", "reentr", "yes", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(329, 1, 1, "white", "female", "reentr", "yes", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(330, 8, 1, "nonwhite", "female", "lose", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(331, 35, 0, "white", "male", "lose", "yes", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(332, 12, 1, "white", "male", "reentr", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(333, 52, 0, "nonwhite", "female", "reentr", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(334, 25, 0, "nonwhite", "female", "reentr", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(335, 26, 0, "nonwhite", "male", "new", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(336, 18, 0, "nonwhite", "female", "leave", "no", "no", 1, 1, 1, 1, 2);
                yield return new Unemployment(337, 2, 1, "nonwhite", "male", "lose", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(338, 28, 0, "nonwhite", "female", "lose", "yes", "no", 1, 1, 1, 1, 3);
                yield return new Unemployment(339, 2, 1, "white", "male", "lose", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(340, 11, 1, "white", "male", "lose", "no", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(341, 1, 1, "nonwhite", "female", "reentr", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(342, 2, 1, "nonwhite", "male", "lose", "no", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(343, 17, 1, "white", "male", "lose", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(344, 6, 1, "white", "male", "lose", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(345, 2, 1, "white", "female", "lose", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(346, 1, 1, "white", "female", "reentr", "yes", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(347, 8, 1, "white", "female", "reentr", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(348, 7, 0, "white", "male", "lose", "no", "no", 1, 1, 1, 1, 2);
                yield return new Unemployment(349, 14, 1, "nonwhite", "female", "leave", "no", "yes", 1, 1, 1, 0, 3);
                yield return new Unemployment(350, 9, 0, "nonwhite", "female", "leave", "yes", "yes", 0, 1, 0, 0, 1);
                yield return new Unemployment(351, 1, 1, "white", "male", "lose", "yes", "yes", 1, 0, 1, 0, 1);
                yield return new Unemployment(352, 1, 0, "white", "female", "lose", "yes", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(353, 17, 1, "nonwhite", "female", "reentr", "yes", "no", 1, 1, 0, 0, 2);
                yield return new Unemployment(354, 29, 0, "nonwhite", "male", "lose", "no", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(355, 4, 1, "white", "male", "new", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(356, 9, 0, "nonwhite", "male", "leave", "yes", "no", 0, 0, 0, 0, 2);
                yield return new Unemployment(357, 26, 1, "white", "male", "leave", "no", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(358, 39, 0, "white", "female", "leave", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(359, 3, 0, "nonwhite", "male", "lose", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(360, 17, 0, "white", "male", "leave", "no", "no", 1, 1, 1, 1, 2);
                yield return new Unemployment(361, 19, 0, "nonwhite", "male", "lose", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(362, 29, 0, "nonwhite", "male", "lose", "no", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(363, 2, 1, "white", "female", "lose", "no", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(364, 13, 0, "nonwhite", "male", "lose", "yes", "yes", 1, 0, 0, 1, 1);
                yield return new Unemployment(365, 30, 1, "nonwhite", "male", "reentr", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(366, 4, 1, "nonwhite", "male", "new", "yes", "yes", 0, 0, 0, 0, 1);
                yield return new Unemployment(367, 1, 0, "white", "female", "lose", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(368, 5, 0, "nonwhite", "male", "lose", "no", "no", 1, 1, 1, 0, 2);
                yield return new Unemployment(369, 6, 0, "nonwhite", "male", "reentr", "yes", "yes", 0, 1, 0, 0, 1);
                yield return new Unemployment(370, 1, 1, "white", "female", "lose", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(371, 4, 1, "white", "male", "reentr", "yes", "yes", 1, 0, 0, 0, 1);
                yield return new Unemployment(372, 15, 1, "white", "male", "leave", "no", "no", 1, 1, 0, 0, 2);
                yield return new Unemployment(373, 2, 1, "white", "male", "leave", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(374, 6, 1, "white", "female", "lose", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(375, 2, 0, "white", "male", "leave", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(376, 29, 0, "white", "male", "lose", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(377, 1, 1, "white", "male", "reentr", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(378, 2, 1, "white", "female", "reentr", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(379, 12, 1, "white", "female", "lose", "no", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(380, 35, 1, "white", "male", "reentr", "no", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(381, 13, 1, "white", "male", "lose", "no", "yes", 1, 1, 0, 0, 2);
                yield return new Unemployment(382, 17, 0, "white", "male", "lose", "yes", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(383, 2, 1, "white", "female", "reentr", "yes", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(384, 0, 1, "white", "male", "leave", "no", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(385, 1, 1, "white", "male", "lose", "no", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(386, 10, 1, "white", "female", "lose", "yes", "yes", 0, 1, 0, 0, 1);
                yield return new Unemployment(387, 13, 1, "nonwhite", "male", "reentr", "yes", "yes", 1, 0, 0, 0, 1);
                yield return new Unemployment(388, 6, 1, "white", "female", "reentr", "yes", "yes", 1, 0, 0, 0, 1);
                yield return new Unemployment(389, 1, 1, "white", "female", "lose", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(390, 6, 1, "white", "male", "new", "no", "no", 1, 1, 0, 0, 2);
                yield return new Unemployment(391, 52, 1, "white", "male", "lose", "yes", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(392, 8, 1, "white", "male", "new", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(393, 12, 0, "white", "female", "new", "no", "no", 1, 1, 0, 0, 2);
                yield return new Unemployment(394, 26, 1, "nonwhite", "male", "leave", "no", "yes", 1, 1, 0, 0, 2);
                yield return new Unemployment(395, 52, 1, "white", "female", "reentr", "no", "yes", 1, 0, 0, 0, 1);
                yield return new Unemployment(396, 9, 1, "nonwhite", "male", "lose", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(397, 12, 0, "white", "male", "lose", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(398, 22, 0, "white", "female", "lose", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(399, 16, 1, "white", "female", "reentr", "yes", "no", 1, 1, 1, 0, 3);
                yield return new Unemployment(400, 2, 1, "white", "female", "reentr", "no", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(401, 61, 0, "white", "female", "reentr", "no", "no", 0, 0, 0, 0, 3);
                yield return new Unemployment(402, 2, 1, "nonwhite", "male", "leave", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(403, 52, 0, "white", "female", "reentr", "no", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(404, 9, 1, "nonwhite", "female", "new", "no", "no", 1, 1, 0, 0, 2);
                yield return new Unemployment(405, 39, 1, "white", "male", "leave", "no", "no", 1, 1, 1, 0, 2);
                yield return new Unemployment(406, 26, 1, "white", "male", "lose", "no", "yes", 1, 1, 1, 0, 2);
                yield return new Unemployment(407, 8, 1, "white", "male", "leave", "no", "no", 1, 0, 0, 0, 2);
                yield return new Unemployment(408, 3, 1, "white", "male", "lose", "no", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(409, 5, 1, "white", "female", "lose", "no", "no", 1, 1, 0, 0, 2);
                yield return new Unemployment(410, 6, 0, "nonwhite", "male", "reentr", "yes", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(411, 52, 1, "nonwhite", "male", "reentr", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(412, 3, 0, "nonwhite", "female", "reentr", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(413, 4, 1, "nonwhite", "male", "reentr", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(414, 20, 1, "nonwhite", "female", "leave", "no", "no", 1, 1, 1, 0, 3);
                yield return new Unemployment(415, 2, 1, "nonwhite", "male", "reentr", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(416, 3, 0, "nonwhite", "male", "lose", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(417, 52, 1, "white", "male", "lose", "yes", "yes", 1, 0, 0, 0, 1);
                yield return new Unemployment(418, 21, 0, "white", "male", "reentr", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(419, 65, 0, "white", "male", "leave", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(420, 4, 0, "white", "female", "new", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(421, 3, 1, "white", "male", "reentr", "yes", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(422, 4, 1, "white", "male", "leave", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(423, 52, 0, "white", "female", "lose", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(424, 16, 0, "white", "female", "reentr", "yes", "yes", 1, 1, 0, 0, 2);
                yield return new Unemployment(425, 86, 1, "white", "male", "lose", "no", "yes", 1, 1, 1, 0, 3);
                yield return new Unemployment(426, 12, 1, "white", "male", "lose", "yes", "yes", 1, 0, 0, 0, 1);
                yield return new Unemployment(427, 1, 1, "white", "male", "leave", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(428, 17, 0, "white", "female", "leave", "no", "no", 1, 1, 1, 1, 4);
                yield return new Unemployment(429, 4, 1, "white", "male", "leave", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(430, 34, 0, "white", "male", "lose", "no", "no", 1, 1, 1, 0, 3);
                yield return new Unemployment(431, 1, 1, "white", "female", "reentr", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(432, 38, 0, "white", "male", "lose", "yes", "no", 1, 1, 1, 0, 3);
                yield return new Unemployment(433, 21, 0, "white", "male", "leave", "no", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(434, 60, 1, "white", "female", "lose", "no", "no", 0, 0, 0, 0, 3);
                yield return new Unemployment(435, 2, 1, "white", "male", "lose", "yes", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(436, 14, 0, "white", "male", "lose", "no", "yes", 1, 1, 1, 1, 4);
                yield return new Unemployment(437, 1, 1, "white", "male", "lose", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(438, 8, 1, "nonwhite", "female", "leave", "no", "no", 1, 1, 0, 0, 2);
                yield return new Unemployment(439, 1, 0, "white", "female", "reentr", "yes", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(440, 4, 0, "white", "male", "lose", "no", "no", 1, 0, 0, 1, 1);
                yield return new Unemployment(441, 3, 1, "nonwhite", "male", "leave", "no", "no", 0, 1, 0, 0, 1);
                yield return new Unemployment(442, 2, 0, "white", "male", "reentr", "no", "no", 0, 0, 0, 0, 1);
                yield return new Unemployment(443, 4, 1, "white", "female", "lose", "no", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(444, 30, 1, "white", "female", "reentr", "yes", "no", 1, 0, 0, 0, 1);
                yield return new Unemployment(445, 6, 0, "white", "male", "reentr", "no", "no", 0, 0, 0, 0, 2);
                yield return new Unemployment(446, 7, 1, "white", "male", "leave", "no", "no", 1, 1, 1, 0, 2);
                yield return new Unemployment(447, 6, 1, "white", "female", "leave", "no", "no", 1, 1, 0, 0, 2);
                yield return new Unemployment(448, 43, 0, "nonwhite", "female", "lose", "no", "no", 1, 1, 1, 0, 2);
                yield return new Unemployment(449, 12, 1, "nonwhite", "female", "reentr", "no", "no", 1, 1, 1, 0, 2);
                yield return new Unemployment(450, 52, 1, "white", "female", "leave", "no", "no", 1, 0, 1, 0, 1);
                yield return new Unemployment(451, 12, 1, "nonwhite", "female", "reentr", "no", "no", 1, 1, 1, 0, 3);
                yield return new Unemployment(452, 21, 0, "white", "male", "reentr", "no", "no", 0, 0, 0, 0, 3);
            }
        }
    }
}
